"""Gate's deliberately small, source-led edition. No length or question quotas.

Each chapter has an independent discovery, a published image the reader actively
uses, and authored reasoning/transfer questions. Retired content is not imported.
"""
from copy import deepcopy
from researched_media import MEDIA, M, PD

M('bible', 'https://commons.wikimedia.org/wiki/File:Gutenberg_bible_Old_Testament_Epistle_of_St_Jerome.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Gutenberg_bible_Old_Testament_Epistle_of_St_Jerome.jpg/960px-Gutenberg_bible_Old_Testament_Epistle_of_St_Jerome.jpg',
  'Johannes Gutenberg und Werkstatt · 1454/55 · Exemplar des Harry Ransom Center', PD,
  'Die erste Seite des ersten Bandes: Hieronymus’ Vorrede. Schwarzer Druck und von Hand ergänzte farbige Ausstattung treffen aufeinander. Diese Seite hat 40 Zeilen je Spalte; der verbreitete Name «42-zeilige Bibel» beschreibt nicht jede Seite.',
  'Zwei dichte schwarze Textspalten mit roten Ergänzungen, einer grossen farbigen Initiale und Ranken am Seitenrand.')
MEDIA['frequencies']['caption'] = 'Abbildung 1 aus Binder et al. (2021): dasselbe medizinische Lehrbeispiel als Wahrscheinlichkeitsbaum und als Häufigkeitsbaum. Die Modellzahlen beschreiben keine heutige persönliche Erkrankungswahrscheinlichkeit. Unten führen zwei Äste zu positiven Ergebnissen: 80 echte Treffer und 950 Fehlalarme.'
MEDIA['cash']['caption'] = 'Der veröffentlichte Geldkreislauf: Cash = Geld, Inventory = Vorräte, Accounts receivable = Forderungen. Folge dem Weg bis zum Zahlungseingang. Das Schema zeigt keine Messdaten und enthält nicht die Zahlen unserer Beispielwerkstatt.'

S = {
 'press': ('Jost Amman · Druckwerkstatt im Ständebuch, 1568', MEDIA['press']['sourceURL']),
 'bible': ('Harry Ransom Center · The Gutenberg Bible', 'https://www.hrc.utexas.edu/gutenberg-bible/'),
 'lithography': ('ASML · Six crucial steps in semiconductor manufacturing', 'https://www.asml.com/en/company/stories/2021/semiconductor-manufacturing-process-steps'),
 'overlay': ('ASML · Overachieving with overlay control', 'https://www.asml.com/en/company/stories/2023/novel-lens-manipulator'),
 'cleanroom': ('ASML · How microchips are made', 'https://www.asml.com/en/technology/all-about-microchips/how-microchips-are-made'),
 'sleep': ('NIH / NHLBI · Your Sleep/Wake Cycle', 'https://www.nhlbi.nih.gov/health/sleep/sleep-wake-cycle'),
 'memory': ('Murre & Dros · Replication and Analysis of Ebbinghaus’ Forgetting Curve, 2015', 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0120644'),
 'rates': ('Binder et al. · Natural frequency trees improve diagnostic efficiency in Bayesian reasoning, 2021', 'https://link.springer.com/article/10.1007/s10459-020-10025-8'),
 'cash': ('OpenStax · Principles of Finance: What Is Working Capital?', 'https://openstax.org/books/principles-finance/pages/19-1-what-is-working-capital'),
 'stoic': ('Epiktet · Enchiridion, Abschnitte 1, 4 und 5 · englische Übersetzung von Elizabeth Carter', 'https://classics.mit.edu/Epictetus/epicench.html'),
 'socrates': ('The Metropolitan Museum of Art · The Death of Socrates', 'https://www.metmuseum.org/art/collection/search/436105'),
 'charts': ('Smallman12q · Vergleich korrekt und irreführend skalierter Bilddiagramme', MEDIA['charts']['sourceURL']),
 'survivors': ('Martin Grandjean / McGeddon · Hypothetisches Schema zum Survivorship Bias', MEDIA['survivors']['sourceURL']),
 'heat': ('UCAR · The Greenhouse Effect', 'https://scied.ucar.edu/learning-zone/how-climate-works/greenhouse-effect'),
 'phishing': ('NCSC · How to spot a scam email, text message or call', 'https://www.ncsc.gov.uk/collection/phishing-scams/spot-scams'),
}
PATHS = [
 ('history','Bücher verändern die Welt','Geschichte an Originalen lesen.','Mensch & Gesellschaft','history'),
 ('industries','Unsichtbare Technik','Wie die Dinge in deinem Handy entstehen.','Natur & Technik','science'),
 ('health','Dein Körper','Mechanismen hinter alltäglichen Erfahrungen.','Alltag & Entwicklung','health'),
 ('learn','Wie Wissen bleibt','Experimente statt Lernmythen.','Denken & Wissen','learning'),
 ('data','Zahlen verstehen','Die richtige Frage vor der Rechnung.','Denken & Wissen','learning'),
 ('business','Unternehmen verstehen','Was zwischen Auftrag und Kontostand passiert.','Geld & Wirtschaft','money'),
 ('philosophy','Gedanken ausprobieren','Alte Texte an konkreten Situationen prüfen.','Mensch & Gesellschaft','philosophy'),
 ('think','Bilder hinterfragen','Beobachten, deuten und Belege unterscheiden.','Denken & Wissen','learning'),
 ('earth','Unser Planet','Unsichtbare Vorgänge sichtbar machen.','Natur & Technik','science'),
 ('digital','Digitaler Alltag','Vertrauen und Sicherheit verstehen.','Alltag & Entwicklung','digital'),
]
TOPICS = [
 ('case.press','history','Das gedruckte Buch war noch nicht fertig','Warum Gutenbergs Technik Handarbeit nicht einfach ersetzte – eine Spurensuche in einer Werkstatt und einer echten Bibelseite.','Historische Spurensuche'),
 ('case.chip','industries','Wie Licht einen Chip baut','Eine Schablone, viele Schichten und ein orangefarbener Raum: Verfolge drei Probleme, die dein Handy erst möglich machen.','Blick in die Herstellung'),
 ('case.sleep','health','Müde – und trotzdem hellwach?','Warum Schlafdruck und innere Uhr verschiedene Dinge sind, und was Kaffee an diesem Zusammenspiel verändert.','Ein Körperrätsel'),
 ('case.recall','learn','Vergessen ist nicht gleich gelöscht','Was die berühmte Vergessenskurve tatsächlich misst – und warum erfolgloses Erinnern nicht bedeutet, dass nichts geblieben ist.','Ein Experiment lesen'),
 ('case.rates','data','Ein Alarm ist noch kein Befund','An einem veröffentlichten Baumdiagramm erkennen, warum viele Warnungen falsch sein können, obwohl ein Test echte Fälle entdeckt.','Ein statistisches Rätsel'),
 ('case.cash','business','Gewinn gemacht. Geld fehlt.','Eine Werkstatt bekommt ihren grössten Auftrag – und kann gerade deswegen die nächste Rechnung nicht bezahlen.','Ein Unternehmensfall'),
 ('case.stoic','philosophy','Epiktet im überfüllten Bad','Die stoische Idee an ihrer eigenen Alltagsszene prüfen: Was liegt bei dir, wenn andere dich anrempeln?','Ein philosophischer Versuch'),
 ('case.images','think','Drei Bilder, drei Denkfallen','Ein unmöglicher Augenzeuge, übergrosse Symbole und ein beschädigtes Flugzeug: Was zeigen Bilder, und was lassen sie weg?','Visuelle Detektivarbeit'),
 ('case.heat','earth','Warum kommt Licht hinein, Wärme aber schwerer hinaus?','Verfolge die Strahlungswege durch die Atmosphäre und finde heraus, wo die Decken-Metapher für den Treibhauseffekt endet.','Ein Naturmechanismus'),
 ('case.phishing','digital','Die überzeugende falsche Bank','Lerne an einer veröffentlichten Beispielmail, warum gutes Design und eine verschlüsselte Verbindung die falsche Seite nicht echt machen.','Eine Nachricht untersuchen'),
]
LESSONS=[]
REVIEW=[]
def q(prompt, correct, wrong1, wrong2, explanation):
 return dict(prompt=prompt,options=[correct,wrong1,wrong2],correctIndex=0,explanation=explanation)
def multi(prompt, options, indices, explanation):
 return dict(prompt=prompt,options=options,correctIndex=indices[0],correctIndices=indices,format='multipleChoice',explanation=explanation)
def order(prompt, options, explanation):
 return dict(prompt=prompt,options=options,correctIndex=0,correctOrder=list(range(len(options))),format='ordering',explanation=explanation)
def L(id, topic, title, goal, source, media, parts, questions, takeaway, reflection):
 meta=next(t for t in TOPICS if t[0]==topic)
 for i,item in enumerate(questions,1):item['id']=id+f'.v6.q{i}'
 cards=[dict(title=t,text=text,kind='scene' if i==0 else 'evidence') for i,(t,text) in enumerate(parts)]
 cards[1]['media']=deepcopy(MEDIA[media])
 cards.append(dict(title='Jetzt anwenden',text='Die folgende Aufgabe zählt zum Ergebnis. Du kannst die Abbildung nochmals öffnen und die Erklärung nochmals lesen.',kind='decision',probe=deepcopy(questions[0])))
 LESSONS.append(dict(id=id,pathID=meta[1],order=1+sum(l['pathID']==meta[1] for l in LESSONS),
  topicID=topic,topicOrder=1+sum(l['topicID']==topic for l in LESSONS),title=title,objective=goal,
  cards=cards,questions=questions,takeaway=takeaway,reflection=reflection,source=dict(zip(['title','url'],S[source]))))
 REVIEW.append(dict(lessonID=id,discovery=goal,visualTask=parts[1][1],mediaKey=media,sourceKey=source,
  misconception=questions[0]['explanation'],questionPurposes=[x['prompt'] for x in questions]))

L('case.press.1','case.press','Die Presse ist nur ein Teil der Erfindung',
 'Erkenne, weshalb ein wiederverwendbarer Satz etwas anderes leistet als schnelleres Abschreiben.', 'press','press',[
 ('Eine Werkstatt voller Hände','Stell dir vor, du brauchst hundert Exemplare derselben Seite. Hundertmal abschreiben? Einen ganzen Holzblock für jede Seite schnitzen? Oder einzelne Buchstaben so zusammensetzen, dass du sie nach dem Druck wieder auseinandernehmen kannst?\n\nDer entscheidende Unterschied steckt im letzten Schritt: Aus denselben Teilen lässt sich morgen ein anderer Text bauen.'),
 ('Suche drei verschiedene Tätigkeiten','Im Holzschnitt von Jost Amman steht links vorne ein Arbeiter an der Presse. Rechts wird die Druckform eingefärbt; hinten setzen weitere Arbeiter den Text. Folge dem Weg von den einzelnen Buchstaben bis zum bedruckten Blatt.\n\nDas Bild stammt von 1568, also aus einer späteren Druckwerkstatt. Es zeigt, weshalb «die Presse druckt Bücher» eine Abkürzung ist: Vor jedem Druck muss eine brauchbare Form entstehen.'),
 ('Ein Fehler reist mit','Für unsere gedachte Auflage ist der Satz die gemeinsame Vorlage. Steckt darin ein falscher Buchstabe, kann derselbe Fehler in jedem unveränderten Abdruck auftauchen. Die grosse Stärke – wiederholbare Kopien – vervielfältigt also auch Fehler.\n\nDarum lohnt sich eine Kontrolle besonders, bevor die Serie beginnt. Wiederverwendbare Teile sparen Arbeit; sie entscheiden nicht, ob der Text wahr oder richtig geschrieben ist.')], [
 q('Die ersten Abzüge haben alle denselben falschen Buchstaben. Wo suchst du zuerst?', 'In der gemeinsam benutzten gesetzten Druckform.','Zuerst im Druck, den die Presse auf die Buchstaben ausübt.','Zuerst in der Farbmenge, die auf die unveränderte Form aufgetragen wird.','Wiederholbare Abdrücke teilen eine Vorlage. Ein systematisch wiederkehrender Buchstabenfehler spricht zuerst für den Satz, nicht für einen zufälligen Fehler auf jedem Blatt.'),
 q('Was ermöglicht beweglicher Satz zusätzlich zu einer geschnitzten ganzen Seite?','Die Buchstaben nach dem Druck für einen anderen Text neu zusammenzustellen.','Die gesetzte Seite dauerhaft unverändert aufzubewahren, um das Material zu schonen.','Jede Seite nur einmal zu drucken und für weitere Kopien neu abzuschreiben.','Beweglich bedeutet neu kombinierbar. Das senkt die Bindung des Materials an eine einzige Seite; Setzen und Prüfen bleiben Arbeit.')],
 'Wer eine Vorlage vervielfältigt, vervielfältigt auch ihre Fehler. Wiederverwendbare Teile und gute Kontrolle gehören zusammen.',
 'Wo arbeitest du mit einer Vorlage, deren Fehler sich oft weiterverbreiten könnten?')

L('case.press.2','case.press','Warum diese Druckseite von Hand weiterbearbeitet wurde',
 'Unterscheide am Original gedruckte Wiederholung und individuelle Ausstattung.', 'bible','bible',[
 ('Sieht so eine technische Revolution aus?','Dichte Schrift, rote Zeichen, eine grosse farbige Initiale und Ranken: Auf den ersten Blick könnte diese Seite zu einem handgeschriebenen Buch gehören. Tatsächlich stammt sie aus einer Gutenberg-Bibel der 1450er-Jahre.\n\nDie Überraschung ist kein Trick: Druck und Handarbeit stecken im selben Objekt.'),
 ('Schau auf den Unterschied zwischen Schrift und Schmuck','Vergrössern lohnt sich hier. Vergleiche die schwarzen Textspalten mit der farbigen Ausstattung am Rand. Das Harry Ransom Center beschreibt sein Exemplar ausdrücklich als gedruckt und von Hand ergänzt. Die abgebildete Seite ist Hieronymus’ Vorrede, nicht der Beginn der Schöpfungsgeschichte.\n\nDie Maschine lieferte also keinen vollständig ausgestatteten Einheitsgegenstand. Ein gedruckter Text konnte danach noch individuell gestaltet werden.'),
 ('Was ein Exemplar beweisen kann','Aus diesem Buch lässt sich erkennen, dass beide Verfahren nebeneinander vorkamen. Nicht ableiten lässt sich daraus, dass jedes Exemplar denselben Schmuck hatte oder mit der Presse sämtliche Handschriften verschwanden.\n\nDenk an heutige Serienprodukte, die erst durch spätere Arbeit persönlich werden: Gemeinsame Herstellung und unterschiedliche Endprodukte schliessen sich nicht aus. Eine neue Technik verändert Arbeit oft Schritt für Schritt.')], [
 q('Zwei Gutenberg-Bibeln zeigen denselben gedruckten Text, aber unterschiedlichen Farbschmuck. Welche Erklärung passt zum gezeigten Exemplar?','Der gedruckte Text konnte nachträglich von Hand unterschiedlich ausgestattet werden.','Der unterschiedliche Schmuck beweist, dass keines der Bücher gedruckt wurde.','Alle sichtbaren Farben müssen zusammen mit dem schwarzen Text gedruckt worden sein.','Gedruckter Text und spätere Handarbeit können im selben Buch vorkommen. Unterschiedliche Ausstattung widerlegt den gemeinsamen Druck nicht.'),
 multi('Was kannst du aus der gezeigten Seite und ihrer Museumsbeschreibung begründet ableiten?', ['Druck und Handarbeit wurden hier kombiniert.','Jedes Gutenberg-Exemplar sah genau gleich aus.','Das einzelne Exemplar belegt nicht das Ende aller Handschriften.','Der sichtbare Farbschmuck muss ebenfalls mit beweglichen Lettern gedruckt worden sein.'],[0,2],'Das Buch belegt die Kombination von Verfahren. Ein einzelnes Exemplar belegt weder völlige Gleichheit aller Kopien noch das Verschwinden einer älteren Technik.')],
 'Eine technische Neuerung muss alte Arbeit nicht auf einen Schlag ersetzen. Schau am Gegenstand nach, welche Schritte sich tatsächlich verändert haben.',
 'Welches Produkt um dich herum verbindet Serienfertigung und individuelle Handarbeit?')

L('case.chip.1','case.chip','Eine Schablone aus Licht',
 'Verstehe den Weg vom Lichtmuster zur bearbeiteten Materialschicht.', 'lithography','lithography',[
 ('Wie zeichnet man Dinge, für die kein Stift klein genug ist?','Auf einem Chip müssen winzige Strukturen immer wieder entstehen. Eine Nadel müsste jede davon einzeln nachfahren. Bei der Fotolithografie wird dagegen ein Muster mit Licht auf eine lichtempfindliche Schicht übertragen.\n\nDer Name des Materials verrät die Idee: Fotolack. Das Licht verändert zunächst den Lack – es legt nicht unmittelbar einen fertigen Draht auf den Chip.'),
 ('Lies die Schnittbilder von oben nach unten','Die veröffentlichte Zeichnung zeigt einen vereinfachten Ablauf. Ein Wafer trägt eine Materialschicht und darüber Fotolack. Belichtung und Entwicklung machen daraus eine gemusterte Schutzschicht. Durch ihre Öffnungen kann die darunterliegende Schicht gezielt geätzt werden. Am Ende wird der restliche Lack entfernt.\n\nAchte darauf, welche Schicht jeweils verschwindet. Entwickeln und Ätzen sind verschiedene Schritte: erst die Maske formen, dann das darunterliegende Material bearbeiten.'),
 ('Wo die Vereinfachung endet','Es gibt unterschiedliche Lacke und Herstellungsverfahren. Das Schema zeigt deshalb ein Prinzip, keine vollständige Bauanleitung für einen modernen Prozessor. Ein realer Chip braucht viele weitere Schritte und Schichten.\n\nDie übertragbare Idee ist überraschend einfach: Du bearbeitest nicht alles einzeln. Du erzeugst zuerst eine selektive Schutzschicht, die festlegt, wo der nächste Prozess wirken darf.')], [
 q('Nach der Entwicklung ist der Lack gemustert. Die darunterliegende Schicht ist noch unverändert. Ist das ein Widerspruch?','Nein. Erst das anschliessende Ätzen überträgt in diesem Verfahren das Muster auf diese Schicht.','Ja. Licht müsste die untere Schicht bereits vollständig wegschneiden.','Nein. Der Lack bleibt in diesem Verfahren als endgültige Materialschicht bestehen.','Die Lackmaske bestimmt, wo geätzt werden kann. Das Herstellen der Maske und die Bearbeitung des Materials sind zwei verschiedene Vorgänge.'),
 order('Ordne die Schritte dieses vereinfachten Verfahrens.', ['Fotolack auftragen','Muster belichten und entwickeln','Freigelegte Materialbereiche ätzen','Übrigen Fotolack entfernen'],'Erst entsteht eine lichtempfindliche Schicht, dann die selektive Maske. Sie schützt während des Ätzens und wird erst danach entfernt.')],
 'Licht formt eine Maske. Die Maske steuert die Bearbeitung. Diese Trennung macht feinste wiederholbare Muster möglich.',
 'Welche andere Technik benutzt eine Maske oder Schablone, um viele Details zugleich zu übertragen?')

L('case.chip.2','case.chip','Zwei perfekte Muster können zusammen falsch sein',
 'Unterscheide die Schärfe einer Struktur von ihrer Lage zur nächsten Schicht.', 'overlay','overlay',[
 ('Das Loch sitzt neben dem Anschluss','Stell dir zwei durchsichtige Folien vor: Auf der unteren liegt ein Anschluss, auf der oberen die Öffnung, die ihn erreichen soll. Beide sind sauber gezeichnet. Verschiebst du eine Folie, trifft die Öffnung trotzdem daneben.\n\nGenau diese Art von Problem entsteht, wenn die vielen Musterschichten eines Chips zusammenpassen müssen. Scharf ist noch nicht richtig ausgerichtet.'),
 ('Verschoben oder verdreht?','Im Diagramm werden verschiedene Überlagerungsfehler verglichen. Suche zuerst ein Musterpaar, dessen Teile gegeneinander versetzt sind, und danach eines mit einer Drehung. Die Einzellinien können in beiden Fällen klar erkennbar bleiben.\n\nDieses Zusammenpassen nennt man Overlay. Es beschreibt die Lage von Schichten zueinander. Eine Aufnahme nur einer Schicht kann daher hervorragend aussehen und den entscheidenden Fehler verbergen.'),
 ('Messen gehört zur Herstellung','ASML beschreibt Systeme, die winzige Abweichungen erfassen und mit optischen Korrekturen ausgleichen. Dabei geht es nicht bloss darum, eine Maschine «schärfer zu stellen»: Position, Drehung und Verformung beeinflussen, wie Muster übereinanderliegen.\n\nFür unsere Folien wäre die passende Kontrolle eine überlagerte Ansicht. An dieser Stelle entscheidet die Beziehung zwischen zwei Teilen, nicht die Qualität jedes Teils für sich.')], [
 q('Jede Schicht sieht einzeln scharf aus, aber Verbindungen treffen ihre Kontakte nicht. Welche Prüfung ist am hilfreichsten?','Die Ausrichtung der Schichten zueinander prüfen.','Nur die Schärfe einer einzelnen Schicht noch einmal bestätigen.','Nur nach einzelnen Kratzern suchen und die Lage der Schichten ausblenden.','Der beschriebene Fehler liegt in der Lagebeziehung. Eine weitere Schärfemessung allein prüft nicht, ob Kontakte übereinanderliegen.'),
 q('Welche Beobachtung unterscheidet einen Drehfehler von einer reinen Verschiebung?','Die Lageabweichung verändert ihre Richtung und Grösse über die Fläche.','Alle Punkte sind um denselben Betrag in dieselbe Richtung verschoben.','Die Linien müssen bei einem Drehfehler unscharf werden.','Eine reine Verschiebung versetzt das ganze Muster gleich. Eine Drehung verändert die Lage abhängig vom Abstand zum Drehpunkt; Unschärfe ist dafür nicht nötig.')],
 'Gute Einzelteile garantieren keine funktionierende Verbindung. Bei Schichten muss auch ihre Lage zueinander stimmen.',
 'Wo scheitert etwas trotz guter Einzelteile daran, dass die Teile nicht zusammenpassen?')

L('case.chip.3','case.chip','Warum dieser Raum orange leuchtet',
 'Erkläre zwei verschiedene Schutzmassnahmen im echten Lithografielabor.', 'cleanroom','cleanroom',[
 ('Der Raum verrät etwas über das Material','Auf dem Foto arbeitet eine Person in Schutzkleidung unter orangefarbenem Licht. Das ist kein Science-Fiction-Set, sondern ein Lithografielabor am London Centre for Nanotechnology.\n\nErinnere dich an den Fotolack: Wenn Licht seine Eigenschaften verändert, muss man auch das Licht beachten, das gar nicht zum eigentlichen Belichten gedacht ist.'),
 ('Zwei Schutzmassnahmen, zwei Ursachen','Schau getrennt auf Beleuchtung und Kleidung. Das orange Licht reduziert ungeeignete Lichtanteile, die den empfindlichen Lack unbeabsichtigt beeinflussen könnten. Die Reinraumkleidung hilft dagegen, Partikel aus der Umgebung der Herstellung fernzuhalten.\n\nBei winzigen Strukturen kann ein Staubteilchen einen relevanten Bereich stören. Die Herstellung schützt daher sowohl vor unbeabsichtigter Belichtung als auch vor Verunreinigung. Dass beide Massnahmen im selben Raum sichtbar sind, macht sie noch nicht austauschbar.'),
 ('Was das Foto nicht zeigt','Du siehst die Umgebung, aber nicht den späteren Ertrag an funktionierenden Chips. Ein ordentlich aussehendes Labor ist kein Nachweis für fehlerfreie Produktion. Dazu braucht es Messungen und Prüfungen.\n\nDie drei Kapitel gehören zusammen: Licht erzeugt ein Muster, Ausrichtung verbindet mehrere Muster, und kontrollierte Bedingungen helfen, diese Arbeit nicht zu beschädigen.')], [
 multi('Welche Zuordnungen passen zu den beiden sichtbaren Massnahmen?', ['Orange Beleuchtung: unbeabsichtigte Wirkung auf Fotolack begrenzen.','Reinraumkleidung: Partikelverunreinigung begrenzen.','Orange Beleuchtung: bereits vorhandenen Staub automatisch entfernen.','Reinraumkleidung: die Ausrichtung aller Schichten messen.'],[0,1],'Lichtschutz und Partikelschutz richten sich gegen verschiedene Fehlerquellen. Kleidung ersetzt keine Ausrichtungsprüfung; farbiges Licht reinigt keinen Wafer.'),
 q('Ein Labor ersetzt seine gefilterte Beleuchtung durch helle normale Lampen. Die Luft bleibt sauber. Welches Problem ist dadurch nicht automatisch gelöst?','Der empfindliche Lack könnte ungewollt belichtet werden.','Der Lack ist durch saubere Luft zugleich vor ungeeigneten Lichtanteilen geschützt.','Der Lack reagiert ausschliesslich auf Licht in der eigentlichen Belichtungsmaschine.','Saubere Luft schützt nicht gegen jede Lichtwirkung. Die Art des Schutzes muss zur jeweiligen Fehlerquelle passen.')],
 'Der Arbeitsraum ist Teil des Herstellungsprozesses. Verschiedene Fehlerquellen brauchen verschiedene Kontrollen.',
 'Welche zwei Kontrollen in deinem Alltag schützen vor unterschiedlichen Fehlern, obwohl sie ähnlich wirken?')

L('case.sleep.1','case.sleep','Schlafdruck ist keine Uhr',
 'Erkläre, weshalb lange Wachzeit und passende Schlafzeit nicht dasselbe sind.', 'sleep','clock',[
 ('Müde im Zug, wach im Bett','Du hast wenig geschlafen und bist tagsüber schwerfällig. Am Abend wirst du plötzlich wieder wacher. Die Erklärung muss nicht sein, dass dein Schlafbedarf verschwunden ist. Im Körper arbeiten verschiedene Systeme zusammen.\n\nFür dieses Rätsel trennen wir zwei davon: den zunehmenden Schlafdruck während des Wachseins und den Tagesrhythmus deiner inneren Uhr.'),
 ('Das Auge stellt die Uhr mit','Folge im NIH-Schema dem Weg des Lichts vom Auge ins Gehirn. Dieses Signal hilft der inneren Uhr, sich am Tag-Nacht-Wechsel auszurichten. Es misst nicht einfach, wie viele Stunden Schlaf dir fehlen.\n\nDaneben steigt während langer Wachzeit der Schlafdruck. Adenosin ist an diesem System beteiligt. Koffein kann Adenosinwirkungen blockieren; dadurch kann sich Wachheit verändern, ohne dass die vorherige Wachzeit rückgängig gemacht wird.'),
 ('Zwei Fragen statt eines Müdigkeitswerts','Im gedachten Fall verschiebt ein heller später Abend zeitgebende Signale, während lange Wachzeit den Schlafbedarf nicht aufhebt. Das erklärt, weshalb «Ich fühle mich gerade wach» keine sichere Antwort auf «Habe ich genug geschlafen?» ist.\n\nMenschen unterscheiden sich zudem in ihrem Tagesrhythmus. Das Modell erklärt Zusammenhänge; aus dieser Zeichnung lässt sich keine exakte persönliche Bettzeit ablesen.')], [
 q('Nach Kaffee fühlst du dich wacher. Was folgt daraus für den vorher aufgebauten Schlafbedarf?','Das Wachheitsgefühl allein beweist nicht, dass der Schlafbedarf abgebaut wurde.','Der Kaffee hat die ausgelassenen Schlafstunden ersetzt.','Die innere Uhr muss dadurch auf die richtige Zeitzone gestellt sein.','Koffein kann ein Müdigkeitssignal beeinflussen. Ein verändertes Signal ist kein Beleg dafür, dass Schlaf stattgefunden hat.'),
 q('Was zeigt der Lichtweg in der Abbildung vor allem?','Wie ein Umweltsignal zur zeitlichen Abstimmung der inneren Uhr beiträgt.','Wie das Auge den angesammelten Schlafdruck unmittelbar abbaut.','Warum die innere Uhr ausschliesslich von der bisherigen Wachzeit abhängt.','Licht liefert Zeitinformation. Schlafdruck und innere Uhr wirken zusammen, erfüllen aber unterschiedliche Aufgaben.')],
 'Ein Wachheitssignal ist kein Ersatz für Schlaf. Frage getrennt nach Schlafdruck und innerer Uhr.',
 'Wann hast du schon erlebt, dass Müdigkeit und Uhrzeit scheinbar nicht zusammenpassen?')

L('case.recall.1','case.recall','Die Kurve misst nicht, wie viel von dir gelöscht ist',
 'Lies die Vergessenskurve als Messung der Wiederlern-Ersparnis statt als persönlichen Countdown.', 'memory','forgetting',[
 ('Du weisst es nicht mehr – aber lernst es schneller','Ein Lied fällt dir nicht ein. Sobald du die ersten Töne hörst, ist es wieder da. Oder du brauchst beim erneuten Lernen einer alten Vokabelliste weniger Versuche als beim ersten Mal.\n\nDas wirft eine bessere Frage auf als «erinnert oder gelöscht?»: Kann frühere Erfahrung noch wirken, obwohl du gerade nichts frei abrufen kannst?'),
 ('Erst die Achse, dann die Geschichte','Die veröffentlichte Ebbinghaus-Kurve zeigt Ersparnis beim Wiederlernen über die Zeit. Das Prinzip: Vergleiche den Aufwand für das erste Lernen mit dem Aufwand, denselben Stoff später erneut bis zum Lernkriterium zu beherrschen.\n\nEin gedachtes Beispiel ohne Prozentrechnung: Anfangs brauchst du zehn Durchgänge, später sechs. Du konntest die Liste zwischendurch nicht aufsagen, lernst sie aber mit weniger Aufwand wieder. Die Ersparnis ist ein Hinweis auf eine verbliebene Wirkung des früheren Lernens.'),
 ('Warum kein persönlicher Fahrplan daraus wird','Murre und Dros untersuchten 2015 in einer Replikation einen Teilnehmer über viele Stunden mit Silbenlisten. Das ist eine eng definierte Aufgabe, kein Test aller Menschen mit jedem Wissensgebiet.\n\nDie Kurve macht ein Messprinzip sichtbar. Sie sagt nicht, dass du nach einer festen Stundenanzahl einen festen Anteil jedes beliebigen Inhalts verloren hast. Entscheidend ist auch, was «behalten» im Experiment überhaupt bedeutet.')], [
 q('Du kannst eine Liste nicht frei aufsagen, lernst sie aber deutlich schneller neu. Welche Deutung passt zur Messidee?','Früheres Lernen kann noch wirken, obwohl der freie Abruf misslingt.','Ohne freien Abruf darf es keinerlei Wiederlern-Ersparnis geben.','Das beweist, dass jedes Detail dauerhaft perfekt gespeichert ist.','Freier Abruf und Wiederlernaufwand sind verschiedene Beobachtungen. Schnellere Wiederaneignung belegt weder völliges Vergessen noch perfekte dauerhafte Verfügbarkeit.'),
 q('Eine Lern-App behauptet: «Diese Kurve sagt genau voraus, was du morgen vergessen hast.» Was fehlt für diese Schlussfolgerung?','Ein Beleg, dass die Messung bei dieser Person, diesem Inhalt und dieser Abrufaufgabe so übertragbar ist.','Nur die Bestätigung, dass die Kurve im ursprünglichen Experiment korrekt gezeichnet wurde.','Nur die Information, dass der neue Lernstoff ebenfalls aus Wörtern besteht.','Ein Experiment mit bestimmtem Material und Messkriterium wird durch ein präzises Diagramm nicht automatisch zu einer individuellen Vorhersage.')],
 'Nicht abrufbar ist nicht dasselbe wie spurlos verschwunden. Prüfe bei jeder Gedächtniskurve, was tatsächlich gemessen wurde.',
 'Was ging dir beim zweiten Lernen überraschend leichter von der Hand?')

L('case.rates.1','case.rates','Welche Menschen gehören in die Vergleichsgruppe?',
 'Unterscheide echte Treffer unter allen Erkrankten von Erkrankten unter allen positiven Ergebnissen.', 'rates','frequencies',[
 ('Ein Ergebnis, zwei völlig verschiedene Fragen','«Der Test erkennt viele echte Fälle.» Klingt beruhigend. Doch die Frage nach einem positiven Ergebnis lautet anders: Wie viele der positiven Ergebnisse sind tatsächlich echte Fälle?\n\nDie Abbildung stammt aus einer Studie zum medizinischen Denken. Ihre Zahlen sind ein Lehrmodell, keine persönliche Diagnose. Wir benutzen sie, um die Gruppen zu sehen. Du musst keinen Prozentwert ausrechnen.'),
 ('Folge beiden positiven Ästen','Unten im Baum gibt es 80 echte Treffer und 950 Fehlalarme. Beide Gruppen haben ein positives Ergebnis. Für die Frage «Was bedeutet positiv?» gehören deshalb beide zusammen in die Vergleichsgruppe.\n\nWer nur den Ast der bereits Erkrankten betrachtet, beantwortet die andere Frage: Wie oft findet der Test die Erkrankung, wenn sie tatsächlich vorliegt? Das kann eine nützliche Eigenschaft des Tests sein, ist aber nicht dieselbe Aussage.'),
 ('Die Seltenheit arbeitet im Hintergrund','In diesem Beispiel kommen sehr viele Personen ohne Erkrankung vor. Selbst wenn nur ein Teil von ihnen einen Fehlalarm erhält, können diese Fehlalarme die echten Treffer zahlenmässig übersteigen.\n\nDie gleiche Denkstruktur begegnet dir bei Spamfiltern oder Betrugswarnungen. Ein Alarm liefert einen Hinweis. Wie aussagekräftig er ist, hängt auch davon ab, wie häufig das gesuchte Ereignis vorher vorkommt.')], [
 q('Du willst im Modell wissen, was ein positives Ergebnis bedeutet. Welche Gruppe musst du betrachten?','Alle positiven Ergebnisse: echte Treffer und Fehlalarme zusammen.','Nur die Personen, von denen bereits bekannt ist, dass sie erkrankt sind.','Nur Personen mit negativem Ergebnis.','Gesucht ist eine Aussage innerhalb der positiven Ergebnisse. Wer auf bereits Erkrankte einschränkt, vertauscht die Richtung der Bedingung.'),
 q('Warum können im gezeigten Modell mehr Fehlalarme als echte Treffer entstehen?','Die viel grössere Gruppe ohne Erkrankung liefert ebenfalls positive Ergebnisse.','Die Fehlalarmrate wird ausschliesslich innerhalb der bereits Erkrankten berechnet.','Die Erkennungsrate allein legt fest, welcher Anteil aller positiven Ergebnisse echt ist.','Ein Anteil einer grossen Ausgangsgruppe kann mehr Fälle ergeben als ein hoher Anteil einer kleinen. Das macht Alarme nicht bedeutungslos.'),
 q('Zwei gleich arbeitende Spamfilter werden auf sehr unterschiedliche Postfächer angewendet. Wo kann derselbe Alarm leichter eine echte Spamnachricht treffen?','Im Postfach, in dem Spam vorab häufiger vorkommt.','In beiden muss der Anteil echter Spamnachrichten unter den Alarmen immer identisch sein.','Die Ausgangshäufigkeit kann nur negative Ergebnisse beeinflussen, keine Alarme.','Bei gleichen Erkennungs- und Fehlalarmraten verändert die Ausgangshäufigkeit die Zusammensetzung der Alarme. Darum braucht eine Aussage über einen Alarm auch Kontext.')],
 'Vor jeder Rechnung steht die Vergleichsgruppe. «Positiv bei Erkrankung» und «Erkrankung bei positiv» sind verschiedene Fragen.',
 'Bei welcher Warnung wäre es hilfreich zu wissen, wie oft sie falschen Alarm auslöst?')

L('case.cash.1','case.cash','Der Auftrag, der die Werkstatt in Bedrängnis bringt',
 'Erkenne die Finanzierungslücke zwischen einer gewinnbringenden Lieferung und ihrer Bezahlung.', 'cash','cash',[
 ('Der beste Auftrag des Monats','Eine gedachte Werkstatt liefert einen Auftrag für 8’000 Franken. Material und Arbeit kosten insgesamt 5’000 Franken. Der Kunde zahlt aber erst später. Morgen sind 3’000 Franken an den Lieferanten fällig; auf dem Konto liegen nur 1’000.\n\nDer Auftrag kann wirtschaftlich lohnend sein und trotzdem ein unmittelbares Zahlungsproblem auslösen. Das Problem ist der Zeitpunkt – nicht eine versteckte Prozentrechnung.'),
 ('Folge dem Geld durch den Kreislauf','Im Schema wird aus Geld zunächst Material beziehungsweise Vorrat. Nach dem Verkauf kann daraus eine Forderung werden: Der Kunde schuldet Geld, hat es aber noch nicht überwiesen. Erst der tatsächliche Zahlungseingang schliesst den Weg zurück zum verfügbaren Geld.\n\nUnsere Werkstatt steckt vor diesem letzten Schritt. Die offene Rechnung ist ein Anspruch, aber mit diesem Anspruch allein ist die morgen fällige Zahlung noch nicht geleistet.'),
 ('Mehr Erfolg kann die Lücke vergrössern','Stell dir einen zweiten gleichartigen Auftrag vor: Wieder muss die Werkstatt vorleisten, wieder zahlt der Kunde später. Mehr Verkäufe können vorübergehend mehr Geld binden.\n\nIm Modell könnten vereinbarte Anzahlungen, früherer Kundenzahlungseingang oder später fällige Lieferantenrechnungen den zeitlichen Engpass verändern. Welche Möglichkeit tatsächlich verfügbar und sinnvoll ist, hängt von den Verträgen und dem Betrieb ab. Ein Gewinnbericht beantwortet diese Zeitfrage nicht.')], [
 q('Welche Information erklärt das unmittelbare Problem der Werkstatt am besten?','Die eigene Zahlung wird fällig, bevor genügend Kundengeld eingeht.','Der ausgewiesene Gewinn muss bereits als frei verfügbares Kontoguthaben vorliegen.','Die offene Kundenrechnung steht für die morgige Zahlung bereits wie Bargeld bereit.','Ertrag und verfügbarer Geldbestand fallen zeitlich auseinander. Für die nächste Zahlung zählt, wann Geld tatsächlich verfügbar ist.'),
 order('Ordne den im Beispiel beschriebenen Weg bis zum Zahlungseingang.', ['Material beschaffen und Arbeit vorfinanzieren','Auftrag liefern und dem Kunden berechnen','Kunde überweist','Geld steht wieder auf dem Konto zur Verfügung'],'Der Verkauf kann vor dem Zahlungseingang liegen. Zwischen Lieferung und Überweisung besteht eine Forderung.'),
 q('Ein zweiter Kunde bestellt unter denselben Bedingungen. Warum ist «mehr Umsatz löst das sofort» keine sichere Antwort?','Auch der zweite Auftrag kann weitere Vorleistungen verlangen, bevor er bezahlt wird.','Der zweite Verkauf verändert den Finanzierungsbedarf erst, wenn der Kunde bezahlt hat.','Jede zusätzliche Forderung erhöht sofort das verfügbare Bankguthaben.','Wachstum kann den Vorfinanzierungsbedarf erhöhen. Mehr verkaufte Leistung ist nicht automatisch früher verfügbares Geld.')],
 'Gewinn beschreibt nicht den Kontostand. Für Zahlungsfähigkeit zählen Betrag und Zeitpunkt der tatsächlichen Geldflüsse.',
 'Wo musst du selbst etwas vorfinanzieren, obwohl später Geld zurückkommt?')

L('case.stoic.1','case.stoic','Epiktet rechnet mit unhöflichen Badegästen',
 'Prüfe Epiktets Unterscheidung zwischen eigener Handlung und fremdem Verhalten an seinem Badehaus-Beispiel.', 'stoic','epictetus',[
 ('Kein Sonnenuntergang, sondern ein Gedränge','In Abschnitt 4 des Enchiridion geht es erstaunlich gewöhnlich zu: Wer ins Bad geht, soll damit rechnen, dass andere spritzen, drängeln, schimpfen oder stehlen. Die philosophische Übung beginnt also nicht erst in einer perfekten ruhigen Welt.\n\nEpiktets Vorschlag: Nimm dir nicht nur vor zu baden, sondern auch, unter solchen Bedingungen vernünftig zu handeln. Die folgende Erklärung ist eine heutige Paraphrase seiner Überlegung.'),
 ('Ein Gesicht ist noch kein Argument','Die spätere Darstellung von Epiktet gibt der historischen Person ein Gesicht; sie ist kein zeitgenössisches Porträt. Seine Idee prüfen wir deshalb am Text und am Fall, nicht daran, wie gelassen er gezeichnet ist.\n\nAbschnitt 1 unterscheidet eigenes Urteilen und Handeln von äusseren Dingen, die nicht einfach dem eigenen Willen gehorchen. Im Bad kannst du nicht beschliessen, dass sämtliche anderen Gäste höflich sein werden. Du kannst aber überlegen, wie du auf Gedränge reagierst.'),
 ('Wäre Weggehen ein Scheitern?','Nein, aus der Unterscheidung folgt nicht, dass du alles dulden musst. In unserer Anwendung kannst du Abstand nehmen, eine Grenze aussprechen oder den Ort verlassen. Das sind eigene Handlungen. Garantieren, wie die anderen darauf reagieren, kannst du damit nicht.\n\nHier liegt auch eine Grenze der Idee: Wir lesen einen philosophischen Vorschlag, keine Behauptung, dass Gefühle auf Knopfdruck verschwinden oder Menschen für jedes erlittene Unrecht selbst verantwortlich seien.')], [
 q('Ein Badegast rempelt dich an. Welche Absicht passt zu der hier erklärten Unterscheidung?', 'Eine eigene Reaktion wählen, ohne den Erfolg von der Einsicht des anderen abhängig zu machen.','Sich vornehmen, dass der andere ab sofort zwingend höflich sein wird.','Jede Grenze aufgeben, weil fremdes Verhalten nicht kontrollierbar ist.','Eigene Handlung und fremdes Ergebnis sind zu trennen. Einfluss ist möglich; ein garantiertes Verhalten anderer lässt sich daraus nicht machen.'),
 q('Du sprichst eine Grenze aus, der andere bleibt unhöflich. Widerlegt das bereits deine gewählte Vorgehensweise?','Nicht allein. Fremde Zustimmung war kein garantiertes Ergebnis deiner Handlung.','Ja. Eine vernünftige Handlung muss immer sofort höfliche Antworten erzeugen.','Nein, denn nach dieser Idee darf man sein eigenes Verhalten nie überprüfen.','Die Wirkung gehört zur Beurteilung, liegt aber nicht vollständig in deiner Verfügung. Die eigene Handlung kann weiter geprüft werden, ohne fremde Zustimmung zum einzigen Massstab zu machen.')],
 'Bestimme deine Handlung möglichst bewusst. Verwechsle sie nicht mit einer Garantie darüber, wie die Welt antwortet.',
 'Welche eigene Handlung könntest du in einer schwierigen Situation wählen, auch wenn jemand anders sich nicht ändert?')

L('history.photos','case.images','Der Augenzeuge, der gar nicht da war',
 'Entdecke, weshalb ein historisches Gemälde zugleich aufschlussreich und kein Augenzeugenbeleg sein kann.', 'socrates','socrates',[
 ('Der Mann am Fussende','Schau auf den Mann, der am Fussende des Bettes sitzt. In Davids «Tod des Sokrates» stellt er Platon dar. Er wirkt wie ein Teilnehmer der Szene. Doch das Metropolitan Museum erklärt: David fügte ihn als Verweis auf den Autor hinzu, dessen Text die Geschichte überliefert. Platon war bei Sokrates’ Tod nicht anwesend.\n\nDas Bild malt also auch seine eigene Quelle mit ins Bild.'),
 ('Was tun die Hände?','Vergrössern: Sokrates hebt einen Finger und greift zugleich zum Becher. Andere Figuren zeigen Trauer oder wenden sich ab. Die Anordnung lässt ihn als entschlossenen Lehrer erscheinen.\n\nDavid malte das Werk 1787, lange nach dem Ereignis. Dass Kleidung und Möbel sorgfältig gestaltet sind, verwandelt die Szene nicht in eine unmittelbare Aufzeichnung. Historische Detailarbeit und eine erfundene Anwesenheit können im selben Gemälde vorkommen.'),
 ('Die bessere Frage an ein Bild','«Ist alles echt oder alles falsch?» ist zu grob. Für die Frage, wer bei dem Ereignis im Raum war, ist dieses Werk kein direkter Augenzeugenbericht. Für die Frage, wie David Sokrates darstellen wollte, sind Gesten und Anordnung sehr aussagekräftig.\n\nDieselbe Unterscheidung hilft bei nachgestellten Dokumentarszenen: Eine eindrucksvolle Darstellung kann eine Deutung vermitteln, ohne die dargestellte Situation direkt zu dokumentieren.')], [
 q('Was belegt Platons sichtbare Anwesenheit in diesem Gemälde am unmittelbarsten?','Dass David ihn in seine Darstellung aufgenommen hat.','Dass Platon beim historischen Ereignis sicher im Raum sass.','Dass David eine antike Augenzeugenskizze unverändert kopiert hat.','Das Gemälde belegt zuerst seine eigene Gestaltung. Laut Museumsbeschreibung verweist Platon hier auf den überliefernden Autor, nicht auf einen anwesenden Augenzeugen.'),
 q('Für welche Frage ist die Bildgestaltung eine besonders passende Quelle?','Wie David Sokrates als Figur erscheinen lassen wollte.','Welche exakten Worte alle Anwesenden damals sagten.','Wie das Licht im historischen Raum im selben Moment tatsächlich fiel.','Für Davids Darstellung sind sichtbare Gesten, Kontraste und Anordnung direkte Anhaltspunkte. Für ein Ereignis viele Jahrhunderte früher braucht es andere Belege.')],
 'Frage nicht nur, ob ein Bild überzeugt. Frage, für welche Aussage es überhaupt ein Beleg sein kann.',
 'Bei welcher Doku oder Darstellung hast du einmal Nachstellung und Aufzeichnung verwechselt?')

L('data.charts','case.images','Wenn doppelt plötzlich vierfach aussieht',
 'Erkenne, wie die gleichzeitige Vergrösserung von Höhe und Breite einen Vergleich verzerrt.', 'charts','charts',[
 ('Die Zahl bleibt gleich, das Gefühl wird grösser','Zwei Symbole sollen unterschiedliche Mengen darstellen. Ein Designer vergrössert das zweite Symbol in Höhe und Breite. Das wirkt ordentlich: Es bleibt dieselbe Form. Trotzdem kann der Eindruck stark übertreiben.\n\nDer Grund liegt nicht im Text unter dem Bild, sondern in der Fläche, die dein Auge sieht.'),
 ('Vergleiche die beiden Darstellungsarten','Die veröffentlichte Gegenüberstellung zeigt angemessene und unangemessene Skalierung von Bildsymbolen. Achte darauf, ob nur eine Ausdehnung oder das ganze Symbol wächst.\n\nEin einfacher Kontrollgedanke: Ein Rechteck, das doppelt so hoch und doppelt so breit wird, besteht aus vier ursprünglichen Rechtecken. Seine Fläche ist also vierfach. Wenn diese Veränderung nur eine Verdopplung der Menge illustrieren soll, erzählt die sichtbare Fläche eine andere Geschichte als die Zahl.'),
 ('Wie du den Vergleich reparierst','Eine Möglichkeit sind gleich grosse Symbole: Für doppelt so viel zeigst du zwei statt eines. Eine andere ist ein Balken mit unveränderter Breite und passender Längenskala.\n\nDas bedeutet nicht, dass jedes Bilddiagramm unbrauchbar ist. Entscheidend ist, welche visuelle Grösse die Menge codiert und ob diese Grösse proportional mitwächst. Die Zahlen allein machen eine Darstellung noch nicht fair.')], [
 q('Ein Symbol soll doppelt so viel zeigen und wird zugleich doppelt so hoch und breit. Was ist das Problem?','Die sichtbare Fläche wächst stärker als die dargestellte Menge.','Die Fläche bleibt proportional, solange das Symbol seine ursprüngliche Form behält.','Die unveränderten Zahlen machen jede Flächenskalierung automatisch angemessen.','Zwei veränderte Dimensionen multiplizieren sich in der Fläche. Für eine Verdopplung der Menge wirkt das ganze Symbol dadurch übergross.'),
 q('Welche Darstellung zeigt eine Verdopplung mit gleich grossen Bildsymbolen nachvollziehbar?','Zwei gleiche Symbole statt eines.','Ein Symbol mit doppelter Höhe und doppelter Breite.','Ein einzelnes gleich grosses Symbol, das nur etwas dunkler eingefärbt wird.','Gleich grosse Einheiten halten die visuelle Menge vergleichbar. Die Verdopplung entsteht durch die Anzahl, nicht durch zusätzliche Flächenvergrösserung.')],
 'Prüfe, welche Bildgrösse eine Menge darstellt. Höhe und Breite zugleich zu vergrössern verändert die Fläche besonders stark.',
 'Welche Infografik würdest du nach diesem Kapitel gern noch einmal anschauen?')

L('think.survivors','case.images','Die Einschusslöcher zeigen nur die Rückkehrer',
 'Entdecke eine fehlende Gruppe, bevor du aus sichtbaren Schäden eine Empfehlung ableitest.', 'survivors','survivors',[
 ('Wo würdest du verstärken?','Ein Flugzeugumriss mit roten Punkten: Die Punkte sollen Schäden an zurückgekehrten Flugzeugen darstellen. Der erste Impuls ist verständlich: Dort, wo viele Treffer sind, muss mehr Schutz hin.\n\nHalte den Gedanken kurz fest. Die entscheidende Information steckt in einem Wort: zurückgekehrt.'),
 ('Suche, was die Zeichnung gar nicht enthalten kann','Die Abbildung ist ein modernes hypothetisches Schema, keine originale Trefferstatistik. Sie macht eine Auswahl sichtbar. Flugzeuge, die nicht zurückgekehrt sind, können in der Menge der untersuchten Rückkehrer nicht auftauchen.\n\nViele sichtbare Treffer können deshalb auch Stellen markieren, an denen ein Flugzeug einen Treffer überleben konnte. Wenige sichtbare Treffer beweisen umgekehrt nicht automatisch, dass dieser Bereich ungefährdet war.'),
 ('Vom Flugzeug zum Erfolgsratgeber','Stell dir ein Buch vor, das nur erfolgreiche Gründer befragt. Alle sagen, dass sie viel riskiert haben. Daraus folgt noch nicht, dass viel Risiko allgemein zum Erfolg führt: Gescheiterte Gründer mit ähnlichem Verhalten könnten fehlen.\n\nIn beiden Fällen brauchst du die Auswahlregel. Aus dem Flugzeugschema allein folgt noch keine fertige Bauempfehlung; es zeigt zunächst, weshalb die fehlende Gruppe für eine solche Empfehlung entscheidend sein kann.')], [
 q('Ein Bereich hat auf den Rückkehrern kaum Treffer. Was ist daraus allein NICHT gesichert?','Dass Treffer dort harmlos sind.','Dass dieser Bereich in der Rückkehrer-Zeichnung wenig markiert ist.','Dass die dargestellte Gruppe nur Rückkehrer umfasst.','Ein leerer Bereich kann Sicherheit oder fehlende Überlebende widerspiegeln. Ohne die ausgeschlossenen Fälle ist die harmlose Wirkung nicht belegt.'),
 q('Ein Erfolgsratgeber befragt nur erfolgreiche Firmen. Welche Ergänzung hilft gegen denselben Auswahlfehler?','Auch vergleichbare gescheiterte Firmen und ihr Vorgehen untersuchen.','Noch mehr erfolgreiche Firmen befragen, weiterhin ohne gescheiterte Vergleichsfälle.','Die Erfolgreichen genauer nach den gemeinsamen Eigenschaften ihrer Erfolge fragen.','Du musst wissen, ob das gelobte Verhalten auch bei Misserfolgen vorkam. Mehr Details derselben ausgewählten Gruppe beseitigen die Auswahl nicht.')],
 'Die Auswahl der sichtbaren Fälle gehört zur Aussage. Frage: Wer fehlt, und könnte genau das Fehlen mit dem Ergebnis zusammenhängen?',
 'Welche Erfolgsgeschichte kennst du, bei der die nicht erfolgreichen Vergleichsfälle fehlen?')

L('earth.greenhouse','case.heat','Licht hinein, Wärmestrahlung hinaus',
 'Verfolge unterschiedliche Strahlungswege und erkläre die Rolle der Atmosphäre.', 'heat','greenhouse',[
 ('Die Erde braucht keinen Deckel, um warm zu bleiben','Sonnenlicht erreicht den Boden. Der erwärmte Boden sendet wiederum Energie ab, vor allem als infrarote Wärmestrahlung. Die einfallende und die ausgehende Strahlung sind also nicht einfach dasselbe Licht auf dem Rückweg.\n\nDiese Unterscheidung erklärt, warum eine Atmosphäre für das eine relativ durchlässig sein und mit dem anderen stärker wechselwirken kann.'),
 ('Folge zwei verschiedenen Pfeilwegen','Das veröffentlichte Schema von 2009 zeigt Sonnenstrahlung, reflektierte Strahlung und Wärmestrahlung. Seine Zahlen sind keine aktuellen Messwerte für dieses Jahr; hier interessieren uns die Wege.\n\nEin Teil der Wärmestrahlung wird von Treibhausgasen aufgenommen und Energie wird wieder als Strahlung abgegeben – in verschiedene Richtungen, auch zurück zur Oberfläche. «Alles geht ungehindert hinaus» passt deshalb ebenso wenig wie «Nichts kann die Erde verlassen».'),
 ('Warum die Decken-Metapher nur halb hilft','Eine Decke erinnert daran, dass Abkühlung erschwert werden kann. Sie ist aber keine genaue Beschreibung der Strahlungsphysik. Die Atmosphäre erzeugt dabei keine kostenlose zusätzliche Sonnenenergie.\n\nWird bei zunächst gleicher Temperatur weniger Energie ins All abgegeben, während weiterhin Energie ankommt, gerät die Bilanz ins Ungleichgewicht. Die Erde erwärmt sich, bis Ein- und Ausfluss wieder zusammenpassen. Entscheidend sind Energieflüsse, nicht eine undurchdringliche Hülle.')], [
 q('Welche Beschreibung passt zu den unterschiedlichen Strahlungswegen?','Die Erde gibt Energie als Wärmestrahlung ab, mit der Treibhausgase wechselwirken.','Sonnenlicht wird vom Boden unverändert und vollständig zurückgespiegelt.','Die Atmosphäre verhindert grundsätzlich jeden Energieverlust ins All.','Einfallende Sonnenstrahlung und ausgehende Wärmestrahlung unterscheiden sich. Ein Teil der Energie gelangt weiterhin ins All; die Atmosphäre verändert den Weg dorthin.'),
 q('Bei zunächst gleicher Temperatur kommt mehr Energie an, als die Erde ins All abgibt. Was bedeutet das für die Bilanz?','Energie sammelt sich an; das System erwärmt sich.','Die Temperatur bleibt allein deshalb gleich, weil die einfallende Sonnenenergie unverändert ist.','Das Ungleichgewicht kann nur durch eine stärkere Sonnenstrahlung entstanden sein.','Ein Überschuss im Energiezufluss erhöht den Energieinhalt. Eine veränderte Abgabe setzt keine gleichzeitige Veränderung der Sonne voraus.')],
 'Die Atmosphäre ist kein versiegelter Deckel. Sie verändert die Strahlungswege und damit die Energiebilanz.',
 'Welche Alltagsmetapher hilft dir bei einem Naturphänomen – und wo hört sie auf zu passen?')

L('digital.phishing','case.phishing','Das Logo ist kein Herkunftsnachweis',
 'Trenne überzeugende Aufmachung von unabhängig überprüfbarer Herkunft.', 'phishing','phishing',[
 ('Eine Mail will dich in Bewegung bringen','Das abgebildete veröffentlichte Beispiel gibt sich als Nachricht einer Bank aus. Ein vertrauter Name, ein offizieller Ton und ein Link machen daraus eine Aufforderung: Hier handeln.\n\nDie zentrale Frage ist nicht, ob die Mail professionell aussieht. Es ist, ob du dem behaupteten Absender und dem Ziel deiner nächsten Handlung vertrauen kannst.'),
 ('Untersuche den Weg, nicht nur die Oberfläche','Schau auf Aufforderung und Link. Das Beispiel ist eine fiktive Nachbildung, keine Nachricht deiner Bank. Das Layout kann kopiert werden. Auch eine bekannte Marke im Text macht eine verlinkte Seite nicht zur echten Bank.\n\nEin unabhängiger Weg ist stärker: die bekannte App selbst öffnen oder eine bereits verifizierte Adresse benutzen. Dabei kommt das Ziel nicht aus derselben Nachricht, die gerade überprüft werden soll.'),
 ('Drei vermeintliche Beweise','«Kein Rechtschreibfehler» beweist keine Echtheit. «Ein Schloss im Browser» bedeutet eine geschützte Verbindung zu dieser Seite, nicht automatisch zur behaupteten Organisation. Und «Die Nachricht ist dringend» liefert einen Grund zu prüfen, keine neue Vertrauensgarantie.\n\nDu musst auf eine mögliche echte Mitteilung nicht mit blindem Ignorieren reagieren. Überprüfe sie über einen getrennten bekannten Kanal. So bleibt die eigentliche Aufgabe – etwa ein Kontoproblem klären – möglich.')], [
 q('Eine plausible Bankmail fordert eine sofortige Anmeldung. Was überprüft ihr Anliegen unabhängig vom Link in der Mail?','Die bekannte Bank-App selbst öffnen und dort nachsehen oder über einen bekannten Kontakt nachfragen.','Den Link öffnen, weil das Logo genau passt.','Auf die Mail antworten und vom selben Absender eine Bestätigung anfordern.','Eine unabhängige Prüfung nutzt ein bereits bekanntes Ziel. Ein Absender, der sich selbst bestätigt, liefert keinen unabhängigen Herkunftsnachweis.'),
 q('Ein verdächtiger Link führt zu einer verschlüsselten Website. Was bestätigt das Schlosssymbol allein?', 'Eine geschützte Verbindung zu dieser Website, nicht ihre Zugehörigkeit zur behaupteten Bank.','Dass die angezeigte Domain zur im Mailtext behaupteten Bank gehört.','Dass der Link in der ursprünglichen Mail von der Bank geprüft wurde.','Verbindungsverschlüsselung und Identität der behaupteten Organisation sind verschiedene Fragen. Auch eine betrügerische Seite kann eine verschlüsselte Verbindung anbieten.')],
 'Verifiziere das Ziel über einen unabhängigen bekannten Weg. Eine überzeugende Oberfläche kann kopiert werden.',
 'Über welchen bereits bekannten Kanal würdest du eine dringende Nachricht deiner Bank überprüfen?')

LESSONS[-1]['additionalSources'] = [dict(title='Mozilla · How do I tell if my connection to a website is secure?', url='https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure')]

def catalog():
 return dict(version=6, paths=[dict(id=p[0],title=p[1],subtitle=p[2],category=p[3],artwork=p[4],number=f'{i:02d}') for i,p in enumerate(PATHS,1)],
  topics=[dict(id=t[0],pathID=t[1],title=t[2],hook=t[3],format=t[4]) for t in TOPICS],lessons=LESSONS)
