from deep_authoring import course, unit, choice as c, number as n, matching as m

COURSE = course('business', 'cash', 'Warum Gewinn nicht auf dem Konto liegt',
    'Du führst eine kleine Werkstatt. Ein guter Auftrag kann sie zahlungsunfähig machen. Verfolge, wo das Geld bleibt.',
    ('OpenStax · Working Capital', 'https://openstax.org/books/principles-finance/pages/19-1-what-is-working-capital'), [
unit('Ein Auftrag, zwei verschiedene Rechnungen', 'Gewinn und verfügbares Geld auseinanderhalten.', [
('Der volle Kalender täuscht', 'Eine Werkstatt hat 4’000 Franken auf dem Konto. Sie liefert einen Auftrag für 10’000 Franken aus. Das dafür verbrauchte Material und die Arbeit kosten zusammen 6’000 Franken und werden sofort bezahlt. Der Kunde zahlt erst in 30 Tagen. Wir blenden Steuern und andere Geschäfte aus.\n\nAuf dem Auftrag steht ein Gewinn von 4’000 Franken: 10’000 Erlös minus 6’000 Aufwand. Trotzdem fehlen heute 2’000 Franken, um die Ausgaben zu bezahlen. Der Gewinn beantwortet, ob sich das Geschäft wirtschaftlich lohnt. Der Kontostand beantwortet, ob heute gezahlt werden kann. Beide Rechnungen können gleichzeitig richtig sein.'),
('Eine Forderung kann keine Rechnung bezahlen', 'Mit der Lieferung entsteht in diesem vereinfachten Beispiel der Erlös. Weil der Kunde noch nicht überwiesen hat, besitzt die Werkstatt eine Forderung: einen Anspruch auf spätere Zahlung. Eine Forderung ist ein Vermögenswert, aber kein verfügbares Bankguthaben.\n\nTrenne bei jedem Geschäft drei Zeitpunkte: Leistung erbringen, Rechnung stellen, Geld erhalten. Sie können auseinanderliegen. Bei einem sofort bezahlten Verkauf fallen sie fast zusammen; bei einem Geschäftskunden mit Zahlungsfrist nicht. Eine hohe Summe offener Rechnungen ist deshalb weder automatisch schlecht noch ein Beweis für finanzielle Sicherheit. Entscheidend ist, wann und wie zuverlässig sie zu Geld wird.')],
'Eine Agentur startet mit 3’000 Franken. Ein bereits gelieferter Auftrag bringt 8’000 Franken Erlös; die zugehörigen 5’000 Franken Kosten werden heute bezahlt. Der Kunde zahlt später. Wie gross sind Gewinn und heutige Finanzierungslücke?',
'Gewinn: 8’000 − 5’000 = 3’000 Franken. Heute fehlen 5’000 − 3’000 = 2’000 Franken. Die offene Kundenrechnung verbessert den heutigen Kontostand noch nicht.', [
[n('Startguthaben 5’000 CHF, heute fällige Kosten 7’000 CHF, Kundenzahlung morgen. Wie viel Geld fehlt heute?',2000,'CHF','7’000 müssen heute bezahlt werden; verfügbar sind nur 5’000.'), n('Startguthaben 2’500 CHF, heute fällige Kosten 4’000 CHF. Die Kundenrechnung ist noch offen. Wie viel fehlt?',1500,'CHF','Die Lücke beträgt 4’000 − 2’500 = 1’500 CHF.')],
[c('Ein gelieferter Auftrag: Erlös 12’000, Aufwand 9’000, Zahlung nächsten Monat. Was beschreibt die 3’000 am besten?','Gewinn des Auftrags','Heutiger Geldzufluss','Höhe der Kundenforderung','12’000 − 9’000 ist Gewinn. Der Zufluss fehlt noch; die Forderung beträgt 12’000.'),c('Ein Kunde bezahlt heute eine bereits verbuchte Rechnung. Ohne neue Leistung oder Kosten steigt dadurch unmittelbar …','das Bankguthaben.','der Erlös ein zweites Mal.','der Gewinn um den Rechnungsbetrag.','Der Zahlungseingang tauscht Forderung gegen Bankguthaben; er ist kein zweiter Verkauf.')],
[m('Ordne die drei Fragen ihrer Rechnung zu.', [('Lohnt sich der Auftrag?','Erlös minus Aufwand'),('Kann heute bezahlt werden?','Verfügbares Geld gegen fällige Zahlungen'),('Was schuldet der Kunde noch?','Offene Forderung')], 'Ergebnis, Zahlungsfähigkeit und Forderung messen verschiedene Dinge.'),m('Welche Position entsteht im vereinfachten Fall?', [('Geliefert, noch nicht bezahlt','Forderung an den Kunden'),('Kunde überweist','Geldzufluss auf dem Konto'),('Erlös übersteigt Aufwand','Positives Auftragsergebnis')], 'Eine Leistung, ihre Bezahlung und ihr Ergebnis sind getrennte Vorgänge.')]],
dict(kind='flow',title='Drei Zeitpunkte',labels=['Liefern: Erlös','Warten: Forderung','Zahlung: Bankguthaben'],caption='Vereinfachter Verkauf auf Rechnung; der Gewinn ist nicht mit einem dieser Geldbestände identisch.')),
unit('Der tiefste Kontostand entscheidet', 'Eine Zahlungslücke auf einer Zeitachse erkennen.', [
('Am Monatsende ist alles gut. Am Dienstag nicht.', 'Du hast 6’000 Franken. Am Montag werden 4’000 für Material fällig, am Dienstag 3’000 für Löhne. Am Freitag zahlt ein Kunde 9’000. Am Ende der Woche bleiben 8’000 Franken. Wer nur diesen Endwert anschaut, übersieht den Dienstag: Nach dem Material bleiben 2’000, nach den Löhnen wären es minus 1’000.\n\nOhne Kredit oder andere Finanzierung kann der zweite Zahlungsschritt so nicht stattfinden. Für Zahlungsfähigkeit zählt deshalb nicht allein die Summe des Monats, sondern die Reihenfolge der Ein- und Auszahlungen. Ein positiver Endsaldo macht eine frühere Zahlungslücke nicht rückwirkend ungeschehen.'),
('Ein Plan mit Datum statt Hoffnung', 'Schreibe für jeden Fälligkeitstag auf: Anfangsguthaben plus erwartete Eingänge minus fällige Ausgänge ergibt Endguthaben. Dieses Endguthaben wird zum Anfang des nächsten Tages. Suche danach den kleinsten Wert. Liegt er unter null, zeigt sein Abstand zu null die rechnerische Mindestfinanzierung. Ein zusätzlicher Puffer kann für Unsicherheit nötig sein.\n\nDie Planung ist nur so belastbar wie ihre Termine. «Der Kunde zahlt bald» gehört nicht als sicherer Geldeingang hinein. Unterscheide eine bestätigte Zahlung von einer Hoffnung. Auch ein verschobener Lieferantenbetrag hilft nur, wenn die neue Frist wirklich vereinbart ist.')],
'Start: 4’000. Tag 1: minus 2’000. Tag 2: minus 3’000. Tag 3: plus 7’000. Wo liegt der Engpass, und wie gross ist er?',
'Die Salden sind 2’000, −1’000 und 6’000. Es fehlen am zweiten Tag mindestens 1’000 Franken. Der Eingang am dritten Tag kommt für die zweite Fälligkeit zu spät.', [
[n('Start 8’000 CHF. Montag −5’000, Dienstag −4’000, Mittwoch +10’000. Wie hoch ist die grösste Lücke?',1000,'CHF','Nach Montag bleiben 3’000; Dienstag fehlen 1’000.'),n('Start 3’000 CHF. Tag 1 −2’000, Tag 2 +1’000, Tag 3 −4’000. Wie hoch ist die grösste Lücke?',2000,'CHF','Die Salden lauten 1’000, 2’000 und −2’000.')],
[c('Ein Betrieb endet jeden Monat positiv, gerät aber am 20. in Rückstand. Welche Auswertung hilft zuerst?','Zahlungen nach Fälligkeitstag','Umsatz nach Produktgruppe','Jahresgewinn nach Geschäftsbereich','Der Engpass ist zeitlich; eine Tagesplanung zeigt ihn direkter als Ergebniskennzahlen.'),c('Eine Rechnung ist am Dienstag fällig. Der erwartete Kundeneingang kommt Mittwoch. Welche Änderung schliesst die Lücke unmittelbar?','Verbindlich vereinbarte Zahlung am Montag','Höherer Auftragspreis mit Zahlung Mittwoch','Buchung des Erlöses bereits am Freitag','Nur ein verfügbarer Eingang vor der Fälligkeit verschiebt hier den Kontostand rechtzeitig.')],
[m('Ordne die Aussagen ein.', [('Zahlung schriftlich für Montag bestätigt','Planbarer Eingang mit verbleibendem Ausfallrisiko'),('Kunde sagt: irgendwann nächste Woche','Unsicherer Zahlungstermin'),('Monatsendguthaben positiv','Kein Beweis für jeden einzelnen Tag')], 'Auch gute Planwerte ersetzen keine Prüfung der zeitlichen Abfolge.'),m('Was liest du aus dem Plan?', [('Niedrigster Saldo −700 CHF','Rechnerische Mindestlücke 700 CHF'),('Endsaldo +5’000 CHF','Geld am Ende des Zeitraums'),('Zusätzliche Reserve 1’000 CHF','Puffer über den errechneten Bedarf hinaus')], 'Mindestlücke, Endsaldo und Reserve haben verschiedene Aufgaben.')]]),
unit('Wer finanziert die Wartezeit?', 'Den Geldkreislauf eines Auftrags verkürzen.', [
('Geld steckt auch im Lager', 'Eine Werkstatt kauft Material an Tag 0. Die Ware bleibt zehn Tage liegen, die Fertigung und Lieferung dauern weitere fünf Tage. Der Kunde zahlt 30 Tage nach Lieferung. Das Geld kommt also erst an Tag 45 zurück. Bezahlt die Werkstatt den Lieferanten sofort, finanziert sie die ganze Wartezeit. Darf sie erst an Tag 20 zahlen, beginnt ihre Vorfinanzierung entsprechend später.\n\nDiese Betrachtung erklärt, weshalb «mehr Umsatz» nicht die einzige Stellschraube ist. Eine Anzahlung, weniger Lagerzeit oder ein verlässlicher kürzerer Zahlungslauf können den gleichen Auftrag leichter finanzierbar machen, ohne den Verkaufspreis zu ändern.'),
('Drei Hebel, verschiedene Nebenwirkungen', 'Eine Kundenanzahlung verschiebt einen Teil des Eingangs nach vorn. Ein Lieferantenziel verschiebt einen Ausgang nach hinten. Eine schnellere Lieferung verkürzt die Zeit, in der Material gebunden bleibt. Keiner dieser Hebel ist kostenlos garantiert: Kunden können eine Gegenleistung verlangen, Lieferanten höhere Preise, ein sehr knappes Lager kann Lieferfähigkeit gefährden.\n\nPrüfe deshalb den konkreten Engpass. Wenn nächste Woche Geld fehlt, hilft die Anzahlung vor dem Materialkauf direkter als eine allgemeine Marketingkampagne. Wir behandeln hier die Zahlungsmechanik eines Beispielbetriebs, nicht rechtliche Regeln für Anzahlungen oder eine Empfehlung für jedes Unternehmen.')],
'Ein Auftrag verursacht sofort 6’000 Franken Ausgaben. Der Kunde zahlt 10’000 bei Lieferung. Welche Vorfinanzierung bleibt ohne Startreserve, wenn 40 Prozent des Preises vorab bezahlt werden?',
'Die Anzahlung beträgt 4’000 Franken. Von den 6’000 sofortigen Ausgaben bleiben 2’000 zu finanzieren. Die Anzahlung verändert den Zahlungszeitpunkt; sie erhöht nicht von selbst den Gesamtgewinn.', [
[n('Sofortige Ausgaben 9’000 CHF, Preis 15’000 CHF, Anzahlung 40 %. Welche Lücke bleibt ohne eigenes Guthaben?',3000,'CHF','Die Anzahlung beträgt 6’000; 9’000 − 6’000 bleiben offen.'),n('Sofortige Ausgaben 5’000 CHF, Preis 8’000 CHF, Anzahlung 25 %. Welche Lücke bleibt?',3000,'CHF','25 % von 8’000 sind 2’000. Der verbleibende Bedarf ist 3’000.')],
[c('Material wird Tag 0 bezahlt, der Kunde zahlt Tag 40. Welche Änderung verkürzt die Vorfinanzierung auf 25 Tage?','Lieferant wird erst an Tag 15 bezahlt.','Kunde bezahlt erst an Tag 55.','Die Rechnung wird an Tag 15 geschrieben, bezahlt aber an Tag 40.','Zwischen Ausgang Tag 15 und Eingang Tag 40 liegen 25 Tage; das Rechnungsdatum allein bewegt kein Geld.'),c('Ein Betrieb reduziert seine Lagerzeit, liefert aber weiterhin zum gleichen festen Termin. Die Kundenzahlung bleibt gleich. Was muss für einen früheren Geldrückfluss zusätzlich passieren?','Der zahlungsrelevante Liefer- oder Zahlungstermin muss vorgezogen werden.','Die Materialkosten müssen im Ergebnis früher erfasst werden.','Der Auftrag muss vor der Zahlung als Umsatz gebucht werden.','Weniger Lagerzeit wirkt auf den Rückfluss nur, wenn sie den Zahlungsablauf tatsächlich verändert.')],
[c('Welche Massnahme verbessert hier Liquidität, ohne den Auftragserlös zu erhöhen?','Der Kunde bezahlt 30 % vor Materialbestellung.','Der Preis steigt um 30 %, zahlbar nach Lieferung.','Eine zweite offene Rechnung wird gestellt.','Eine Anzahlung verändert den frühen Geldfluss, nicht den vereinbarten Gesamterlös.'),c('Ein Lieferant bietet 20 Tage länger Zahlungsfrist gegen höheren Preis. Welche Gegenüberstellung ist sinnvoll?','Zusatzkosten gegen vermiedenen Finanzierungsbedarf','Zusatzkosten gegen bereits erzielten Vorjahresgewinn','Zusatzkosten gegen den gesamten offenen Kundenumsatz','Die Frist kann eine Lücke überbrücken, muss aber wirtschaftlich gegen ihre Kosten geprüft werden.')]]),
unit('Warum schnelles Wachstum Geld frisst', 'Vorfinanzierung bei mehreren gleichzeitigen Aufträgen berechnen.', [
('Eine gute Rechnung mal zehn', 'Jeder Auftrag bringt 10’000 Franken und kostet 6’000. Die Ausgaben fallen sofort an, bezahlt wird nach einem Monat. Mit 6’000 Reserve kann ein Betrieb genau einen solchen Auftrag vorfinanzieren. Zehn gleichzeitig angenommene Aufträge benötigen zunächst 60’000 – auch wenn sie später insgesamt 40’000 Gewinn bringen sollen.\n\nDas Problem ist nicht ein schlechter Einzelauftrag, sondern die Überlagerung guter Aufträge. Wachstum kann deshalb zuerst das Bankguthaben senken. Ein Geschäft kann profitabel und trotzdem durch das Tempo seiner Expansion überfordert sein. Die Frage lautet: Wie viele Aufträge befinden sich gleichzeitig in der unbezahlten Phase?'),
('Durchsatz und gebundenes Geld', 'Vergleiche zwei Abläufe. Bei Ablauf A zahlt jeder Kunde nach 30 Tagen; bei B nach zehn Tagen. Bei gleicher Zahl neuer Aufträge kann in B früher wieder Geld für den nächsten Auftrag verfügbar werden. Das verringert typischerweise die Bindung, beseitigt aber weder Kosten noch das Risiko eines Zahlungsausfalls.\n\nWachstumsplanung braucht deshalb eine gemeinsame Sicht auf Auftragseingang, verfügbare Kapazität und Zahlungsplan. Der errechnete Bedarf darf nicht mit schon offenen Forderungen verrechnet werden, solange deren Eingang zu spät kommt. Ein kreditwürdiger Kunde ist nicht dasselbe wie ein heute zahlender Kunde.')],
'Vier neue Aufträge brauchen je 3’000 Franken sofort. 7’000 sind frei verfügbar. Alle Kunden zahlen später. Wie viel fehlt für den gleichzeitigen Start?',
'Vier mal 3’000 ergibt 12’000. Gegenüber 7’000 verfügbarem Geld fehlen 5’000. Der spätere Gewinn erklärt die Attraktivität der Aufträge, nicht ihre heutige Finanzierbarkeit.', [
[n('Sechs parallele Aufträge benötigen je 2’000 CHF vorab. Verfügbar sind 9’000 CHF. Wie gross ist die Lücke?',3000,'CHF','6 × 2’000 − 9’000 = 3’000 CHF.'),n('Fünf parallele Aufträge benötigen je 4’000 CHF vorab. Verfügbar sind 14’000 CHF. Wie gross ist die Lücke?',6000,'CHF','5 × 4’000 − 14’000 = 6’000 CHF.')],
[c('Bei gleichem Preis und Gewinn sinkt die Kundenzahlungsfrist von 30 auf 10 Tage. Was verbessert sich zuerst?','Der Zeitpunkt des Geldrückflusses','Der Gewinn je ausgeführtem Auftrag','Der Erlös je verkauftem Auftrag','Eine Friständerung wirkt unmittelbar auf die Geldbindung, nicht auf Preis minus Kosten.'),c('Umsatz und Gewinn steigen, der Kontostand sinkt. Welche Zusatzinformation prüft die Wachstumserklärung am direktesten?','Zeitlicher Anstieg vorfinanzierter Aufträge','Veränderung des Umsatzes je ausgestellter Rechnung','Veränderung des Gewinns je abgeschlossenem Auftrag','Mehr gleichzeitig unbezahlte Arbeit kann trotz positiver Margen Geld binden.')],
[c('Ein Betrieb kann nur drei Aufträge vorfinanzieren. Welcher Plan begrenzt den heutigen Spitzenbedarf?','Starts staffeln, sobald gesicherte Zahlungen eintreffen.','Alle starten und Rechnungen schneller verbuchen.','Alle starten und Gewinne später neu kalkulieren.','Staffelung verändert die gleichzeitig fälligen Ausgaben; Umbuchungen finanzieren sie nicht.'),c('Eine Forderung über 20’000 kommt in sechs Wochen. Morgen fehlen 5’000. Was fehlt für eine gesicherte Überbrückung?','Eine tatsächlich verfügbare Finanzierung vor morgen','Eine höhere Bewertung der Forderung in der Übersicht','Ein zusätzlicher erwarteter Gewinn in sechs Wochen','Eine Forderung kann Finanzierung unterstützen, stellt diese aber nicht selbst bereit.')]]),
unit('Entscheiden unter Unsicherheit', 'Einen Auftrag mit Basis- und Verzögerungsfall beurteilen.', [
('Nicht jeder Planwert ist ein Versprechen', 'Ein Betrieb hat 8’000 Franken. Für einen Auftrag zahlt er morgen 5’000, eine Woche später 4’000. Ein Kunde soll dazwischen 6’000 überweisen. Im Basisfall bleibt der Betrieb zahlungsfähig: 3’000, dann 9’000, dann 5’000. Zahlt der Kunde erst nach der zweiten Ausgabe, entsteht zwischendurch eine Lücke von 1’000.\n\nBeide Pläne verwenden denselben Auftrag und denselben erwarteten Gewinn. Nur eine Annahme verändert sich: der Zahlungstermin. Ein sinnvoller Stresstest nennt diese Annahme ausdrücklich. Er behauptet weder, die Verzögerung werde eintreten, noch berechnet er aus einem einzigen Fall ihre Wahrscheinlichkeit.'),
('Eine Entscheidung mit drei Antworten', 'Bevor du zusagst, beantworte drei getrennte Fragen: Ist der Auftrag wirtschaftlich sinnvoll? Passt er zu deiner Kapazität? Ist er auch im plausiblen Verzögerungsfall finanzierbar? Ein guter Wert in einer Spalte beantwortet die anderen nicht.\n\nEine mögliche Lösung wäre eine verbindliche Anzahlung, eine vereinbarte Fristverschiebung oder verfügbare Reserve. Schreibe neben jede Lösung, wer zustimmen muss und bis wann. Eine noch nicht bewilligte Kreditlinie zählt nicht wie Geld auf dem Konto. Diese Disziplin macht aus einer optimistischen Tabelle einen Entscheidungsplan: Annahmen, Engpass und konkrete Absicherung stehen nebeneinander.')],
'Start 5’000; morgen 4’000 Ausgaben; erwartete 7’000 Einnahmen am Mittwoch; Donnerstag 3’000 Ausgaben. Welche Reserve fehlt, wenn der Eingang erst Freitag kommt?',
'Ohne rechtzeitigen Eingang bleiben nach der ersten Ausgabe 1’000. Die zweite Ausgabe würde den Saldo auf −2’000 drücken. Der Verzögerungsfall braucht mindestens 2’000 zusätzliche verfügbare Mittel.', [
[n('Start 7’000 CHF; zuerst 5’000, danach 4’000 Ausgaben. Der erwartete Eingang verspätet sich bis nach beiden. Wie viel fehlt mindestens?',2000,'CHF','7’000 − 5’000 − 4’000 = −2’000 CHF.'),n('Start 9’000 CHF; vor dem verspäteten Eingang werden 6’000 und 5’000 fällig. Wie viel fehlt mindestens?',2000,'CHF','9’000 − 6’000 − 5’000 = −2’000 CHF.')],
[c('Ein Stresstest nimmt zwei Wochen Zahlungsverzug an. Was darfst du aus dem Ergebnis schliessen?','Welche Lücke unter genau dieser Annahme entstünde.','Mit welcher Wahrscheinlichkeit der Kunde ausfällt.','Welcher Umsatz im nächsten Jahr sicher erreicht wird.','Der Stresstest rechnet Folgen einer Annahme durch; ihre Eintrittswahrscheinlichkeit braucht andere Belege.'),c('Welche Position darf als gesicherte Überbrückung eingeplant werden?','Eine bereits nutzbare, zugesagte Kreditlinie','Ein erst beantragter Kredit gleicher Höhe','Ein erwarteter Folgeauftrag gleicher Höhe','Verfügbarkeit vor der Fälligkeit ist entscheidend; Antrag und Erwartung sind noch keine Mittel.')],
[m('Ordne die Prüfung der richtigen Frage zu.', [('Preis deckt Kosten mit Überschuss','Wirtschaftlichkeit'),('Team kann rechtzeitig liefern','Kapazität'),('Fällige Rechnungen können bezahlt werden','Liquidität')], 'Eine Zusage braucht mehr als einen positiven Gewinn.'),m('Was ist im Plan jeweils beschrieben?', [('Kundenzahlung sieben Tage später','Geänderte Annahme'),('Tiefster Saldo minus 2’000','Folge im Stresstest'),('Anzahlung vor Arbeitsbeginn verbindlich vereinbart','Mögliche Absicherung')], 'Annahme, berechnete Folge und Gegenmassnahme dürfen nicht verwechselt werden.')]])
])
