from deep_authoring import course, unit, choice as c, matching as m, ordering as o, number as n

COURSE=course('industries','chip','Wie ein Chip Schicht für Schicht entsteht',
 'Ein Chip wird nicht aus einem kleinen Block gefräst. Du verfolgst Muster, Materialien und Fehler durch seine Herstellung.',
 ('ASML · Six crucial steps in semiconductor manufacturing', 'https://www.asml.com/en/company/stories/2021/semiconductor-manufacturing-process-steps'),[
unit('Licht zeichnet zunächst nur eine Vorlage', 'Belichtung und fertige elektrische Struktur unterscheiden.',[
('Keine winzige Fräsmaschine', 'Ein Chip besteht aus sehr kleinen Strukturen in und auf einem Halbleitermaterial. Um bestimmte Bereiche gezielt zu bearbeiten, braucht die Herstellung zunächst ein Muster. Bei der Fotolithografie wird eine lichtempfindliche Schicht, der Fotolack, aufgebracht. Licht verändert ausgewählte Bereiche dieses Lacks. Nach dem Entwickeln bleibt ein Muster übrig.\n\nDas ist noch nicht der fertige Prozessor. Der strukturierte Lack kann als vorübergehende Maske für folgende Bearbeitungsschritte dienen. Er legt fest, wo ein Material entfernt oder ein Bereich anderweitig verändert werden soll. Das Licht steuert die Strukturierung, es baut nicht in einem einzigen Schritt alle Transistoren.'),
('Eine Schablone ist nicht das Bauteil', 'Denke an eine Schablone beim Streichen: Sie bestimmt, wo die nächste Arbeit wirkt, ist aber nicht mit dem fertigen Anstrich identisch. Die Analogie erklärt die Rolle der Maske. Sie beschreibt nicht die genauen chemischen oder optischen Vorgänge in einer Chipfabrik.\n\nIm vereinfachten Ablauf folgen Beschichten, Belichten, Entwickeln und eine passende Materialbearbeitung aufeinander. Verschiedene Lackarten reagieren unterschiedlich; du musst hier nicht behaupten, dass belichtete Stellen bei jedem Verfahren genau gleich entfernt werden. Wichtig ist die Funktion: ein kontrolliertes Muster erzeugen und es in weitere Herstellungsschritte übertragen.')],
'Nach der Entwicklung liegt ein gemusterter Fotolack auf dem Wafer. Warum wäre «Der Chip ist fertig, weil das Muster sichtbar ist» ein zu weiter Schluss?',
'Der Lack dient zunächst als Bearbeitungsmaske. Die funktionalen Materialien, elektrischen Strukturen und ihre Verbindungen entstehen erst durch weitere, oft wiederholte Schritte.',[
[o('Ordne den vereinfachten Beginn der Strukturierung.', ['Fotolack aufbringen','Ausgewählte Bereiche belichten','Lack entwickeln und Muster erhalten'],'Der lichtempfindliche Lack muss vor der Belichtung vorhanden sein.'),o('Ordne den Zweckablauf.', ['Muster im Lack erzeugen','Muster bei der Materialbearbeitung nutzen','Funktionale Struktur prüfen'],'Das vorübergehende Lackmuster und die spätere funktionale Struktur sind nicht gleichzusetzen.')],
[c('Was ist die unmittelbare Rolle des Fotolackmusters?','Ausgewählte Bereiche für weitere Bearbeitung festlegen','Alle elektrischen Verbindungen des fertigen Chips ersetzen','Das endgültige Gehäuse des Chips ausformen','Das Muster steuert folgende Schritte; es ist nicht selbst die gesamte Schaltung.'),c('Wo endet die Schablonen-Analogie aus dem Kapitel?','Sie erklärt die Auswahl von Bereichen, nicht die vollständige Herstellungsphysik.','Sie erklärt bereits, wie aus dem Lackmuster die elektrische Funktion entsteht.','Sie zeigt, dass jede belichtete Stelle bei allen Lackarten entfernt werden muss.','Eine Analogie bildet eine Funktion ab; sie ersetzt keine Erklärung von Material und Verfahren.')],
[m('Ordne die Funktion zu.', [('Fotolack','Lichtempfindliche vorübergehende Schicht'),('Belichtung','Gezielte Veränderung des Lacks'),('Entwicklung','Sichtbares beziehungsweise nutzbares Lackmuster erzeugen')],'Die Schritte bereiten die kontrollierte Weiterbearbeitung vor.'),m('Was ist jeweils gemeint?', [('Wafer','Träger der wiederholten Herstellungsschritte'),('Lackmuster','Maske für ausgewählte Bereiche'),('Fertige Schaltung','Ergebnis vieler Material- und Verbindungsschritte')],'Ein Muster auf dem Träger ist noch nicht die fertige Schaltung.')]]),
unit('Material hinzufügen ist nicht Material entfernen', 'Die Aufgaben der Fertigungsschritte unterscheiden.',[
('Das Muster muss in Material übergehen', 'Nach einer Strukturierung können unterschiedliche Arbeiten folgen. Beim Abscheiden wird eine Materialschicht hinzugefügt. Beim Ätzen wird Material in ausgewählten Bereichen entfernt. Beim Dotieren wird die Zusammensetzung bestimmter Halbleiterbereiche gezielt verändert, um ihre elektrischen Eigenschaften einzustellen.\n\nDiese Begriffe stehen nicht für drei austauschbare Arten des Zeichnens. Sie verändern jeweils etwas anderes. Eine Maske kann dabei festlegen, welche Bereiche betroffen sind. Die konkrete Reihenfolge und die genauen Verfahren hängen von der herzustellenden Struktur ab; ein einzelner universeller Ablauf würde die Vielfalt der Fertigung verschweigen.'),
('Die Schaltung ist ein Materialsystem', 'Warum so viele Schritte? Ein Transistor braucht Bereiche mit bestimmten elektrischen Eigenschaften. Isolierende Schichten trennen andere Bereiche. Leitende Verbindungen verbinden die gewünschten Punkte. Die Funktion entsteht aus Material, Form und Lage gemeinsam.\n\nStelle dir drei Fehler vor: Eine Schicht fehlt; ein Bereich wurde zu weit entfernt; eine gewünschte Eigenschaft wurde nicht richtig eingestellt. Das spätere Muster kann auf den ersten Blick ähnlich aussehen und trotzdem elektrisch anders arbeiten. Gute Fertigung kontrolliert deshalb nicht nur, ob ein Bild scharf ist. Sie muss prüfen, ob das richtige Material in der richtigen Form am richtigen Ort liegt.')],
'Eine Verbindung ist vorgesehen, aber an der Stelle fehlt leitendes Material. Ein zweiter Bereich enthält Material, das eigentlich entfernt werden sollte. Welcher grundlegende Prozess passt jeweils zur gewünschten Änderung?',
'Im ersten Fall muss passendes Material hinzugefügt beziehungsweise die Verbindungsstruktur hergestellt werden; im zweiten muss Material gezielt entfernt werden. Abscheiden und Ätzen haben entgegengesetzte Grundfunktionen.',[
[m('Ordne den Prozess seinem Grundzweck zu.', [('Abscheiden','Material hinzufügen'),('Ätzen','Material gezielt entfernen'),('Dotieren','Halbleitereigenschaften durch Zusätze verändern')],'Die drei Prozesse verändern Menge, Form beziehungsweise Zusammensetzung auf verschiedene Weise.'),m('Welche Frage gehört zum Prozess?', [('Welche neue Schicht wird aufgebracht?','Abscheiden'),('Welche Bereiche werden abgetragen?','Ätzen'),('Welche elektrischen Eigenschaften werden eingestellt?','Dotieren')],'Eine optische Vorlage allein beantwortet diese Materialfragen nicht.')],
[c('Warum reicht ein scharfes Lackmuster nicht als Nachweis eines funktionierenden Chips?','Materialeigenschaften und spätere Verbindungen müssen ebenfalls stimmen.','Die Schärfe des Musters legt alle späteren Materialeigenschaften bereits fest.','Ein scharfes Muster macht jede spätere Prüfung derselben Struktur überflüssig.','Die Funktion hängt nicht nur von der optischen Darstellung ab.'),c('Zwei Strukturen sehen ähnlich aus, besitzen aber andere elektrische Eigenschaften. Welche Erklärung passt?','Die Zusammensetzung oder das Material kann unterschiedlich sein.','Gleiche sichtbare Umrisse schliessen Materialunterschiede aus.','Die Form allein bestimmt unabhängig vom Material jede elektrische Eigenschaft.','Geometrie ist nur ein Teil der funktionalen Struktur.')],
[o('Ordne einen vereinfachten maskengesteuerten Ätzschritt.', ['Zu schützende Bereiche mit passender Maske abdecken','Freie Bereiche gezielt ätzen','Ergebnis nach der Bearbeitung prüfen'],'Dies ist ein Lehrablauf, kein vollständiges Rezept für einen Fertigungsprozess.'),o('Ordne die Prüfung eines Materialschritts.', ['Gewünschte Materialänderung festlegen','Passenden Prozess ausführen','Material und Struktur mit dem Ziel vergleichen'],'Das Ziel bestimmt den Prozess und die anschliessende Prüfung.')]]),
unit('Zwei scharfe Muster können schlecht zusammenpassen', 'Auflösung und Schichtausrichtung auseinanderhalten.',[
('Das Loch neben dem Anschluss', 'Stelle dir zwei übereinanderliegende Schichten vor. In der unteren liegt eine Leiterbahn, in der oberen eine Öffnung, durch die eine Verbindung zur Leiterbahn entstehen soll. Beide Muster können für sich sehr scharf sein. Ist die Öffnung seitlich verschoben, trifft sie trotzdem nicht den vorgesehenen Punkt.\n\nAuflösung beschreibt hier vereinfacht, wie fein Strukturen voneinander unterschieden und erzeugt werden können. Ausrichtung beschreibt, wie gut die Muster verschiedener Schritte relativ zueinander liegen. In der Halbleiterfertigung spricht man für diese Überlagerungsgenauigkeit häufig von Overlay. Ein guter Wert bei der einen Eigenschaft garantiert keinen guten Wert bei der anderen.'),
('Viele Schichten brauchen gemeinsame Bezugspunkte', 'Weil Herstellungsschritte wiederholt werden, muss jedes neue Muster zur vorhandenen Struktur passen. Messung, Ausrichtung und Korrektur gehören deshalb zur Herstellung, nicht nur zur nachträglichen Fehlersuche.\n\nDie Landkarten-Analogie hilft: Zwei detailreiche Karten lassen sich falsch übereinanderlegen, wenn ihre Bezugspunkte nicht stimmen. Mehr Details lösen dieses Verschiebungsproblem nicht automatisch. Ebenso kann eine kleinere Strukturgrösse die Anforderungen an die Ausrichtung sogar anspruchsvoller machen. Die Qualität eines Chips lässt sich daher nicht aus einem einzigen Schlagwort wie «kleiner» oder «schärfer» ableiten.')],
'Zwei Kreise sind gleich scharf gezeichnet. Der obere ist drei Millimeter seitlich versetzt. Ist vor allem die Unterscheidbarkeit ihrer Konturen oder ihre relative Lage das Problem?',
'Ihre relative Lage. Das Modell macht ein Ausrichtungsproblem sichtbar. Schärfere Konturen würden die Verschiebung nicht von selbst korrigieren.',[
[m('Ordne die Qualitätsfrage zu.', [('Wie fein sind benachbarte Linien unterscheidbar?','Auflösung'),('Trifft die obere Öffnung die untere Leiterbahn?','Ausrichtung / Overlay'),('Besteht die Bahn aus dem richtigen Material?','Materialeigenschaft')],'Drei getrennte Eigenschaften müssen für die Funktion zusammenpassen.'),m('Welcher Fehler liegt im Modell vor?', [('Scharfe Muster seitlich versetzt','Ausrichtungsfehler'),('Nahe Linien nicht mehr getrennt erkennbar','Auflösungsproblem'),('Gute Form, falscher leitender Stoff','Materialproblem')],'Eine Verbesserung muss zur Art des Fehlers passen.')],
[c('Welche Massnahme adressiert zwei scharfe, aber gegeneinander verschobene Schichten am direktesten?','Ihre relative Position genauer ausrichten','Nur die Linien in jeder Schicht weiter verkleinern','Nur die fertigen Muster stärker vergrössert anzeigen','Ein Positionsfehler verlangt eine passende Ausrichtung, nicht bloss mehr Detail.'),c('Warum erhöhen kleinere Strukturen oft auch die Anforderungen an die Fertigung?','Ein gleich grosser Lagefehler kann relativ zur Struktur stärker ins Gewicht fallen.','Kleinere Strukturen beseitigen die Notwendigkeit gemeinsamer Bezugspunkte.','Eine feinere Auflösung legt automatisch die Lage aller späteren Schichten fest.','Auflösung und Ausrichtung sind verbunden, aber keine austauschbaren Grössen.')],
[n('Lehrzeichnung: Ein Anschluss ist 10 Einheiten breit, die seitliche Verschiebung beträgt 2. Wie gross ist die Verschiebung relativ zur Breite?',20,'%','2 / 10 = 20 %. Das ist eine Zeichnungsrechnung, keine Chip-Spezifikation.'),n('Lehrzeichnung: Breite 20 Einheiten, Verschiebung 1. Welchem Anteil der Breite entspricht die Verschiebung?',5,'%','1 / 20 = 5 %. Relative Lagefehler hängen auch von der Strukturgrösse ab.')]]),
unit('Nicht jeder hergestellte Chip wird verkauft', 'Ausbeute von der blossen Stückzahl unterscheiden.',[
('Hundert Kandidaten, achtzig brauchbare Teile', 'Auf einem Wafer werden viele einzelne Chipflächen hergestellt. Nach der Fertigung wird geprüft, welche davon die Anforderungen erfüllen. Wenn von 100 Kandidaten 80 nutzbar sind, beträgt die Ausbeute in unserem einfachen Beispiel 80 Prozent.\n\nDie Zahl hergestellter Strukturen und die Zahl brauchbarer Produkte sind also verschieden. Fehler können unter anderem durch Material, Verunreinigung, Bearbeitung oder Ausrichtung entstehen. Die tatsächliche Ausbeute hängt von konkreter Technik und Produkt ab; unsere runden Zahlen sind keine Behauptung über einen Hersteller.'),
('Der Ausschuss verteilt die Kosten neu', 'Nehmen wir 1’000 Kosteneinheiten für eine Charge. Bei 100 brauchbaren Chips entfielen rechnerisch zehn pro brauchbarem Chip darauf. Bei nur 50 wären es 20. Gleiche Chargenkosten können also sehr unterschiedliche Kosten je nutzbarem Produkt ergeben.\n\nDie Rechnung lässt zusätzliche Prüf-, Verpackungs- und Vertriebskosten weg. Sie zeigt nur den Einfluss der Ausbeute. Wenn jemand allein mit «mehr Chips pro Wafer» wirbt, frage deshalb nach der Zahl guter Chips, nicht nur nach möglichen Chipflächen. Eine höhere theoretische Dichte und eine gute reale Ausbeute müssen gemeinsam betrachtet werden.')],
'Eine Charge kostet 600 Einheiten und enthält 100 Kandidaten. 75 bestehen die Prüfung. Wie hoch sind Ausbeute und rechnerische Chargenkosten je gutem Teil?',
'Die Ausbeute ist 75 %. 600 geteilt durch 75 ergibt acht Kosteneinheiten pro gutem Teil. 600 durch 100 würde die ausgeschiedenen Kandidaten mitrechnen.',[
[n('120 Kandidaten, 90 brauchbare Chips. Wie hoch ist die Ausbeute?',75,'%','90 / 120 = 75 %.'),n('200 Kandidaten, 160 brauchbare Chips. Wie hoch ist die Ausbeute?',80,'%','160 / 200 = 80 %.')],
[c('Mehr Kandidaten passen auf den Wafer, aber deutlich weniger bestehen die Prüfung. Welche Zahl ist für verkaufbare Menge entscheidend?','Die Zahl tatsächlich brauchbarer Chips','Die Zahl theoretisch angeordneter Kandidaten','Die Zahl wiederholter Belichtungsschritte allein','Theoretische Dichte muss sich in gute Produkte übersetzen.'),c('Warum können sinkende Fehlerzahlen die Kosten je brauchbarem Chip senken?','Die Chargenkosten verteilen sich auf mehr gute Teile.','Die ursprünglichen Chargenkosten werden nachträglich vollständig gelöscht.','Jede zusätzliche Prüfung ersetzt bereits alle Materialkosten.','Die Rechnung verändert den Nenner brauchbarer Produkte, nicht rückwirkend sämtliche Kosten.')],
[n('Charge: 900 Kosteneinheiten, 60 gute Chips. Wie viel entfällt rechnerisch pro gutem Chip?',15,'Einheiten','900 / 60 = 15; zusätzliche Kosten sind im Modell ausgeblendet.'),n('Charge: 1’200 Kosteneinheiten, 80 gute Chips. Wie hoch ist der rechnerische Betrag je gutem Chip?',15,'Einheiten','1’200 / 80 = 15.')]]),
unit('Eine Fabrik ist eine abgestimmte Kette', 'Den Engpass im Gesamtablauf statt nur eine schnelle Maschine betrachten.',[
('Eine Spitzenmaschine wartet auf den Rest', 'Ein Fertigungsschritt kann besonders beeindruckend sein und dennoch nicht den Ausstoss der gesamten Fabrik bestimmen. Angenommen, drei notwendige Stationen schaffen nachhaltig 60, 40 und 55 Einheiten pro Stunde. Ohne andere Begrenzungen und ohne Vorratseffekte kann die Kette langfristig höchstens 40 fertige Einheiten pro Stunde liefern.\n\nDie zweite Station ist im Lehrmodell der Engpass. Wird nur die erste auf 90 beschleunigt, steigt der Enddurchsatz dadurch nicht auf 90. Vor dem Engpass kann stattdessen mehr unfertige Arbeit warten. Die reale Chipfertigung enthält viele Rückläufe und komplexere Abhängigkeiten; das einfache Modell isoliert das Grundprinzip.'),
('Präzision, Ausbeute und Kapazität zusammen denken', 'Du kannst den gesamten Weg nun nachvollziehen: Licht strukturiert zunächst eine Maske. Materialschritte formen funktionale Bereiche. Wiederholte Schichten müssen genau passen. Prüfungen trennen gute von fehlerhaften Teilen. Die ganze Kette muss mit ausreichender Kapazität zusammenarbeiten.\n\nDeshalb ist «Wir kaufen eine bessere Maschine» noch kein vollständiger Industrieplan. Welche Stufe verbessert sie? Passt das zu einem tatsächlichen Engpass? Bleiben Ausbeute und andere notwendige Schritte erhalten? Ein technischer Vorteil kann gross sein; sein Nutzen im System muss trotzdem konkret begründet werden. So wird aus einem Schlagwort eine nachvollziehbare Produktionsentscheidung.')],
'Stationen A, B, C schaffen 50, 30 und 45 Einheiten pro Stunde. B wird auf 40 verbessert, alle anderen bleiben gleich. Wie verändert sich der theoretische dauerhafte Enddurchsatz?',
'Er steigt von 30 auf 40 pro Stunde. B bleibt mit 40 weiterhin unter A und C. Die Rechnung setzt vergleichbare Einheiten und einen einfachen notwendigen Durchlauf voraus.',[
[n('Drei notwendige Stationen: 70, 45 und 60 Einheiten/Stunde. Maximaler langfristiger Enddurchsatz im einfachen Modell?',45,'Einheiten/Stunde','Die langsamste notwendige Station begrenzt auf 45.'),n('Stationen: 80, 50 und 65. Die zweite wird auf 70 verbessert. Neuer maximaler Enddurchsatz?',65,'Einheiten/Stunde','Jetzt ist die dritte Station mit 65 der Engpass.')],
[c('Eine schnelle Maschine wird schneller, während die langsamere Folgestufe unverändert bleibt. Was kann im einfachen Modell wachsen?','Der Bestand unfertiger Teile vor der Folgestufe','Der dauerhafte Enddurchsatz automatisch im gleichen Verhältnis','Die Ausbeute aller späteren Schritte allein durch die Geschwindigkeit','Lokale Geschwindigkeit und Gesamtergebnis sind nicht identisch.'),c('Welche Frage verbindet eine neue Anlage am besten mit dem Fabriknutzen?','Welche bestehende Begrenzung wird unter Erhalt der nötigen Qualität verbessert?','Welche Anlage hat unabhängig vom Ablauf die grösste Einzelgeschwindigkeit?','Welche Anlage besitzt allein die kleinste angegebene Strukturzahl?','Der Nutzen hängt von Engpass, Qualität und Zusammenwirken ab.')],
[m('Ordne die Kennzahl ihrer Frage zu.', [('Auflösung','Wie fein können Strukturen dargestellt werden?'),('Ausbeute','Wie viele Kandidaten werden brauchbare Produkte?'),('Enddurchsatz','Wie viele fertige Einheiten liefert die ganze Kette pro Zeit?')],'Feinheit, Anteil guter Teile und Ausstoss pro Zeit sind unterschiedliche Grössen.'),m('Welche Verbesserung passt zum Problem?', [('Schichten gegeneinander versetzt','Ausrichtung verbessern'),('Viele Kandidaten fehlerhaft','Ursachen der Ausbeuteverluste beheben'),('Warteschlange vor langsamster Station','Engpasskapazität prüfen')],'Der passende Eingriff folgt aus der Diagnose des Systems.')]])
])
