from deep_authoring import course, unit, choice as c, number as n, matching as m

COURSE = course('data','rates','Was ein Treffer wirklich bedeutet',
 'Ein Alarm meldet einen Fehler. Wie wahrscheinlich ist der Fehler tatsächlich? Du lernst es an gezählten Fällen statt an Formelnebel.',
 ('Binder et al. · Natural frequency trees and Bayesian reasoning', 'https://link.springer.com/article/10.1007/s10459-020-10025-8'),[
unit('Die Gruppe hinter der Prozentzahl', 'Den Nenner einer Quote benennen.',[
('90 Prozent von wem?', 'Eine Fabrik prüft Bauteile. Von 100 tatsächlich defekten Teilen erkennt der Alarm 90. Der Satz «Der Alarm erkennt 90 Prozent der Defekte» beschreibt diese Gruppe: die wirklich defekten Teile. Er sagt noch nicht, dass 90 Prozent der alarmierten Teile defekt sind.\n\nDie Wörter ähneln sich, aber die Gruppen sind verschieden. Im ersten Fall beginnen wir bei allen Defekten und fragen nach Alarmen. Im zweiten beginnen wir bei allen Alarmen und fragen nach Defekten. Wer die Richtung vertauscht, kann aus einer guten Erkennungsleistung eine viel zu sichere Diagnose machen.'),
('Eine Kreuztabelle ohne Zauberei', 'Jedes Teil hat zwei Eigenschaften: Es ist tatsächlich defekt oder intakt; der Alarm löst aus oder bleibt still. Daraus entstehen vier Gruppen. Ein Alarm bei einem Defekt ist ein richtiger Treffer. Ein stiller Alarm bei einem Defekt ist ein übersehener Fehler. Ein Alarm bei einem intakten Teil ist ein Fehlalarm. Ein stiller Alarm bei einem intakten Teil ist eine richtige Entwarnung.\n\nBeginne jede Prozentrechnung mit einem vollständigen Satz: «Von allen … sind …». Erst dann teilst du. Diese Gewohnheit wirkt unspektakulär, verhindert aber den häufigsten Fehler: den richtigen Zähler durch die falsche Gesamtgruppe zu teilen.')],
'Von 50 defekten Teilen erkennt der Alarm 40. Unter allen 100 Alarmen sind diese 40 Defekte. Wie unterscheiden sich Erkennungsquote und Defektanteil unter den Alarmen?',
'Erkennungsquote: 40 von 50 = 80 %. Defektanteil unter Alarmen: 40 von 100 = 40 %. Dieselben 40 Treffer stehen über zwei unterschiedlichen Nennern.',[
[n('Von 80 defekten Teilen werden 60 erkannt. Wie hoch ist die Erkennungsquote?',75,'%','60 / 80 = 0,75; der Nenner sind die Defekte.'),n('Unter 120 Alarmen sind 30 tatsächliche Defekte. Wie hoch ist der Defektanteil unter Alarmen?',25,'%','30 / 120 = 0,25; gefragt ist die Gruppe der Alarme.')],
[c('«80 % der Defekte werden erkannt.» Welche Gruppe bildet den Nenner?','Alle tatsächlich defekten Teile','Alle Teile mit einem Alarm','Alle geprüften Teile','Die Aussage startet bei den Defekten, nicht bei den Alarmen oder bei der Gesamtproduktion.'),c('Welche Frage beginnt bei derselben Gruppe wie «Wie verlässlich ist ein ausgelöster Alarm?»','Wie viele alarmierte Teile sind tatsächlich defekt?','Wie viele defekte Teile lösen einen Alarm aus?','Wie viele intakte Teile bleiben ohne Alarm?','Die gesuchte Gruppe ist die Menge ausgelöster Alarme; die anderen Fragen beginnen anders.')],
[m('Ordne die Kombination zu.',[('Defekt und Alarm','Richtiger Treffer'),('Intakt und Alarm','Fehlalarm'),('Defekt und kein Alarm','Übersehener Fehler')],'Wirklichkeit und Prüfergebnis sind zwei getrennte Merkmale.'),m('Welche Gruppe wird betrachtet?', [('Erkannte Defekte / alle Defekte','Erkennungsquote'),('Defekte mit Alarm / alle Alarme','Trefferanteil eines Alarms'),('Alarme bei intakten Teilen / alle intakten Teile','Fehlalarmquote')],'Die Richtung der Bedingung entscheidet über den Nenner.')]]),
unit('Wenn seltene Fehler viele Fehlalarme bekommen', 'Richtige und falsche Treffer zusammenzählen.',[
('Der Alarm ist gut. Trotzdem liegt er oft daneben.', 'In einer Lieferung von 1’000 Teilen sind 20 defekt und 980 intakt. Der Alarm erkennt 90 Prozent der Defekte: Das sind 18 Treffer. Er alarmiert ausserdem bei zehn Prozent der intakten Teile: Das sind 98 Fehlalarme. Insgesamt gibt es 116 Alarme. Nur 18 davon gehören zu einem Defekt, also ungefähr 15,5 Prozent.\n\nDas ist kein Widerspruch. Die grosse Gruppe intakter Teile erzeugt trotz niedrigerer Alarmrate viele Fehlalarme. Die ursprüngliche Häufigkeit der Defekte nennt man Grundrate. Ohne sie lässt sich der Aussagewert eines Alarms nicht aus seiner Erkennungsquote ableiten.'),
('Erst zählen, dann teilen', 'Der Rechenweg hat vier übersichtliche Schritte. Teile die Gesamtmenge in defekt und intakt. Berechne in jeder Gruppe die Alarmzahl. Addiere beide Alarmzahlen. Teile zuletzt die richtigen Treffer durch alle Alarme.\n\nEin Baumdiagramm zeigt genau diese Verzweigungen. Wichtig ist, dass die Fehlalarmquote auf die intakten Teile angewendet wird, nicht auf alle Teile. Unsere Fabrikzahlen sind erfundene Lehrdaten. Die Methode lässt sich auf Spamfilter oder technische Warnungen übertragen, aber ihre tatsächlichen Kennzahlen müssen separat bekannt sein. Eine überzeugende Prozentzahl ersetzt diese Informationen nicht.')],
'100 Teile: 10 defekt, 90 intakt. Der Alarm findet acht Defekte und meldet neun intakte Teile. Wie viele seiner Alarme sind richtig?',
'Es gibt 8 + 9 = 17 Alarme. Davon sind acht richtig: 8/17, also rund 47 %. Der Wert 80 % beschreibt dagegen die Erkennung innerhalb der zehn Defekte.',[
[n('Eine Prüfung liefert 24 richtige Treffer und 36 Fehlalarme. Wie viel Prozent der Alarme sind richtig?',40,'%','24 / (24 + 36) = 40 %.'),n('15 richtige Treffer und 45 Fehlalarme: Wie viel Prozent der Alarme sind richtig?',25,'%','15 / 60 = 25 %.')],
[c('20 Defekte, 980 intakte Teile; Fehlalarmquote 5 %. Auf welche Zahl wendest du die 5 % an?','980','1’000','20','Fehlalarme sind Alarme in der intakten Gruppe; deshalb ist 980 die Bezugsgrösse.'),c('Welche Information fehlt, wenn nur Erkennungsquote und Fehlalarmquote bekannt sind?','Die Häufigkeit tatsächlicher Fehler in der geprüften Gruppe','Die Reihenfolge der bereits berechneten Prozentwerte','Der Anteil erkannter Fehler unter allen tatsächlichen Fehlern','Für den Anteil echter Treffer unter Alarmen braucht man zusätzlich die Grundrate.')],
[n('200 Teile, davon 10 defekt. Bei 10 % der intakten Teile gibt es Fehlalarm. Wie viele Fehlalarme sind das?',19,'Alarme','190 intakte Teile × 10 % = 19.'),n('500 Teile, davon 50 defekt. Bei 2 % der intakten Teile gibt es Fehlalarm. Wie viele Fehlalarme sind das?',9,'Alarme','450 × 0,02 = 9.')]],
dict(kind='flow',title='100 Teile im Lehrbeispiel',labels=['10 defekt → 8 Alarme','90 intakt → 9 Alarme','8 von 17 Alarmen richtig'],caption='Gezählte Fälle verhindern die Verwechslung der Nenner.')),
unit('Der gleiche Alarm in einer anderen Gruppe', 'Erkennen, warum sich der Aussagewert bei anderer Grundrate ändert.',[
('Zwei Lieferungen, dasselbe Prüfgerät', 'Das Gerät erkennt weiterhin 90 Prozent der Defekte und meldet zehn Prozent der intakten Teile fälschlich. Lieferung A enthält 100 defekte und 900 intakte Teile. Es entstehen 90 richtige und 90 falsche Alarme: Jeder zweite Alarm ist richtig.\n\nLieferung B stammt aus einer vorab verdächtigen Charge und enthält 500 defekte und 500 intakte Teile. Jetzt entstehen 450 richtige und 50 falsche Alarme: Neun von zehn Alarmen sind richtig. Das Gerät hat seine Eigenschaften im Beispiel nicht verändert. Verändert hat sich die Zusammensetzung der geprüften Gruppe.'),
('Vorauswahl ist keine neutrale Kleinigkeit', 'Wenn du einen veröffentlichten Trefferanteil überträgst, frage deshalb: An wem oder woran wurde er gemessen? Eine Prüfung an bereits auffälligen Fällen kann einen anderen Aussagewert haben als dieselbe Prüfung ohne Vorauswahl.\n\nDas heisst nicht, dass höhere Trefferanteile durch Vorauswahl wertlos wären. Es heisst, dass sie eine andere Frage beantworten. In realen Anwendungen können zusätzlich die Eigenschaften des Geräts zwischen Gruppen variieren. Unsere Rechnung hält sie absichtlich konstant, damit du genau einen Einfluss erkennst: die Grundrate. Ein sauberer Vergleich nennt, welche Bedingungen gleich bleiben und welche geändert werden.')],
'In Gruppe A gibt es 20 richtige und 80 falsche Alarme, in Gruppe B 80 richtige und 20 falsche. Wie hoch sind die Trefferanteile, und reicht der Unterschied als Beweis für ein verbessertes Gerät?',
'A: 20 %, B: 80 %. Der Unterschied allein beweist keine Geräteverbesserung. Auch eine andere Zusammensetzung der geprüften Fälle kann ihn verursachen.',[
[n('Eine verdächtige Charge erzeugt 72 richtige und 18 falsche Alarme. Wie hoch ist der Trefferanteil?',80,'%','72 / 90 = 80 %.'),n('Eine breite Kontrollgruppe erzeugt 30 richtige und 120 falsche Alarme. Wie hoch ist der Trefferanteil?',20,'%','30 / 150 = 20 %.')],
[c('Bei unveränderten Prüfquoten steigt der Defektanteil der geprüften Teile. Was erwartest du für den Anteil richtiger Alarme?','Er steigt.','Er bleibt durch die Prüfquoten festgelegt.','Er sinkt wegen der grösseren Defektzahl.','Bei höherer Grundrate gibt es relativ mehr echte Treffer unter den Alarmen.'),c('Eine Studie prüft nur auffällige Teile. Du prüfst die gesamte Produktion. Was begrenzt die Übertragbarkeit des Trefferanteils zuerst?','Die unterschiedliche Grundrate','Die identische Bezeichnung des Geräts','Die gleiche Zahl von Antwortkategorien','Eine identische Technik garantiert bei anderer Fallmischung keinen identischen Trefferanteil.')],
[m('Trenne Gerät und Gruppe.',[('90 % der Defekte werden erkannt','Erkennungsquote des Verfahrens'),('10 % der intakten Teile lösen Alarm aus','Fehlalarmquote des Verfahrens'),('20 % der Lieferung sind defekt','Grundrate der Gruppe')],'Ein Trefferanteil verbindet Verfahrenskennzahlen mit der Zusammensetzung der Gruppe.'),m('Was darfst du daraus ableiten?', [('Andere Grundrate, gleiche Prüfquoten','Trefferanteil kann sich ändern'),('Gleicher Trefferanteil allein','Gleiche Prüfquoten nicht bewiesen'),('Höherer Trefferanteil nach Vorauswahl','Geräteverbesserung nicht bewiesen')],'Gleiche oder bessere Endquoten lassen die zugrunde liegenden Mechanismen offen.')]]),
unit('Ein Alarm ist noch keine Handlung', 'Wahrscheinlichkeit und Folgen einer Entscheidung trennen.',[
('Was kostet der Fehler?', 'Zwei Betriebe verwenden dasselbe Prüfgerät. Ein falscher Alarm bedeutet in Betrieb A eine zweite Kontrolle für zwei Franken. In Betrieb B führt er sofort zur Vernichtung eines Bauteils für 500 Franken. Selbst bei identischen Trefferquoten wäre es nicht überraschend, dass die Betriebe unterschiedlich reagieren.\n\nDie Wahrscheinlichkeit eines Fehlers ist eine Frage. Die angemessene Handlung ist eine zweite. Für sie zählen zusätzlich die Folgen richtiger und falscher Entscheidungen. Eine günstige Folgeprüfung kann sinnvoll sein, wenn die erste Warnung noch unsicher ist. Umgekehrt kann ein übersehener sicherheitskritischer Defekt eine vorsichtige Reaktion rechtfertigen.'),
('Eine bessere Schwelle hat einen Preis', 'Viele Prüfverfahren erlauben eine empfindlichere Einstellung. Sie entdeckt mehr Defekte, löst aber oft auch mehr Fehlalarme aus. Eine strengere Einstellung kann Fehlalarme reduzieren und dafür mehr Defekte übersehen. Diese Abwägung ist nicht durch die Überschrift «genauer» erledigt.\n\nLass dir beide Kennzahlen zeigen. Ein Verfahren, das fast nie Alarm gibt, kann wenige Fehlalarme haben und trotzdem viele Defekte übersehen. Ein Verfahren, das fast immer Alarm gibt, kann viele Defekte finden und dennoch unbrauchbar viele intakte Teile aussortieren. Ob eine Einstellung sinnvoll ist, hängt von den Aufgaben und den Fehlerkosten ab.')],
'Variante A erkennt 95 von 100 Defekten und alarmiert 100 intakte Teile. B erkennt 85 Defekte und alarmiert 20 intakte Teile. Welche Zahl allein entscheidet, welche Variante besser ist?',
'Keine einzelne der genannten Zahlen entscheidet. A übersieht weniger Defekte, B verursacht weniger Fehlalarme. Man muss die Folgen beider Fehlerarten und die Möglichkeit einer Folgeprüfung kennen.',[
[n('Eine Einstellung erkennt 92 von 100 Defekten. Wie viele Defekte werden übersehen?',8,'Defekte','100 − 92 = 8.'),n('Von 200 tatsächlichen Defekten werden 170 erkannt. Wie viele bleiben unerkannt?',30,'Defekte','200 − 170 = 30.')],
[c('A verursacht weniger Fehlalarme, übersieht aber mehr Defekte als B. Was fehlt für eine begründete Wahl?','Die Folgen beider Fehlerarten im Einsatz','Nur die Gesamtzahl der Fehlalarme von A','Nur die Zahl erkannter Defekte von B','Die Entscheidung verlangt die Abwägung, nicht nur eine der beiden Leistungszahlen.'),c('Ein unsicherer Erstalarm lässt sich günstig und unabhängig nachprüfen. Welche Strategie berücksichtigt beide Schritte?','Erstalarm als Anlass zur gezielten Folgeprüfung nutzen.','Erstalarm unmittelbar mit einem bewiesenen Defekt gleichsetzen.','Erstalarm wegen seiner Unsicherheit ohne weitere Prüfung verwerfen.','Eine Folgeprüfung kann Informationen hinzufügen; weder Gewissheit noch Wertlosigkeit folgt aus dem ersten Alarm.')],
[m('Welche Art von Frage ist das?', [('Wie viele Alarme sind echte Defekte?','Aussagewert'),('Was kostet eine unnötige Aussortierung?','Fehlerfolge'),('Ab welchem Messwert wird Alarm ausgelöst?','Entscheidungsschwelle')],'Messung, Folgen und Schwelle hängen zusammen, sind aber verschiedene Grössen.'),m('Welcher Nachteil kann zur Verbesserung gehören?', [('Empfindlichere Einstellung','Mehr Fehlalarme möglich'),('Strengere Alarmschwelle','Mehr übersehene Defekte möglich'),('Zusätzliche Kontrollstufe','Mehr Prüfaufwand möglich')],'Verbesserungen sollten einschliesslich ihrer Kosten und Gegenwirkungen beurteilt werden.')]]),
unit('Der zweite Alarm ist nicht immer ein zweiter Beleg', 'Abhängige Prüfungen und begrenzte Daten erkennen.',[
('Doppelt gelesen ist nicht doppelt gemessen', 'Du prüfst eine verdächtige Nachricht mit zwei Diensten. Beide warnen. Das klingt stärker als eine einzelne Warnung. Wenn beide Dienste aber dieselbe Sperrliste kopieren, stecken hinter den zwei Anzeigen möglicherweise dieselben Informationen.\n\nZwei positive Ergebnisse dürfen deshalb nicht blind wie unabhängige Bestätigungen behandelt werden. Unabhängigkeit bedeutet hier vereinfacht, dass der zweite Befund nicht bloss durch denselben Informationsweg erklärt wird. Auch unterschiedliche Logos garantieren keine unabhängigen Daten. Frage nach dem Prüfweg: Was kann die zweite Kontrolle herausfinden, das die erste noch nicht wusste?'),
('Wie belastbar sind die Kennzahlen selbst?', 'Eine Quote aus zehn beobachteten Fällen ist anfälliger für Zufallsschwankungen als eine Quote aus vielen vergleichbaren Fällen. Acht richtige Alarme von zehn ergeben zwar genau 80 Prozent in dieser Stichprobe. Daraus folgt nicht, dass der wahre zukünftige Anteil exakt 80 Prozent beträgt.\n\nFür eine vernünftige Beurteilung gehören deshalb drei Dinge zusammen: die richtige Bezugsgruppe, die Zahl der beobachteten Fälle und die Herkunft der Belege. Du brauchst dafür nicht sofort komplizierte Statistik. Schon die Fragen «Wie viele?», «Von welchen?» und «Unabhängig wovon?» verhindern viele voreilige Schlüsse. Zahlen werden nicht weniger nützlich, wenn man ihre Grenzen kennt.')],
'Zwei Berichte nennen denselben Defekt. Beide gehen auf die Aussage desselben Mitarbeiters zurück. Was hast du: zwei Veröffentlichungen oder zwei unabhängige Beobachtungen?',
'Zwei Veröffentlichungen, aber nach diesen Angaben nur einen ursprünglichen Informationsweg. Eine zusätzliche unabhängige Prüfung müsste eigene Beobachtungen liefern.',[
[n('Acht von zehn Alarmen waren richtig. Wie hoch ist der beobachtete Anteil in genau dieser Stichprobe?',80,'%','8 / 10 = 80 %. Die Zahl beschreibt die Stichprobe, nicht einen garantiert exakten zukünftigen Anteil.'),n('18 von 30 überprüften Alarmen waren richtig. Wie hoch ist der beobachtete Anteil?',60,'%','18 / 30 = 60 %. Umfang und Auswahl der Stichprobe bleiben für die Übertragung wichtig.')],
[c('Zwei Prüfsysteme verwenden dieselbe Datenbank. Was ist beim gemeinsamen Alarm zu prüfen?','Ob beide Ergebnisse auf derselben fehlerhaften Information beruhen.','Ob die Einzelquoten ohne weitere Annahmen miteinander multipliziert werden dürfen.','Ob gleiche Alarmtexte eine unabhängige Messung belegen.','Die Informationsabhängigkeit kann den Zusatznutzen des zweiten Alarms begrenzen.'),c('Welche zweite Prüfung liefert eher einen zusätzlichen Informationsweg?','Eine eigene technische Messung mit anderem Verfahren','Eine weitere App mit derselben übernommenen Sperrliste','Eine Übersetzung des ersten Prüfberichts','Ein anderes Messverfahren kann zusätzliche Evidenz liefern; Kopien und Übersetzungen tun das nicht.')],
[c('10 von 10 Prüfungen waren richtig. Welche Formulierung ist durch diese Daten gedeckt?','In diesen zehn Fällen trat kein beobachteter Fehler auf.','Die zukünftige Fehlerwahrscheinlichkeit ist damit null.','Die Prüfung ist für jede andere Fallgruppe gleich zuverlässig.','Ein fehlerfreies kleines Sample beweist weder Perfektion noch allgemeine Übertragbarkeit.'),c('Welche Angabe macht eine Quote von 80 % am besten einordbar?','Fallzahl, Auswahl der Fälle und Definition von «richtig»','Nur eine weitere Nachkommastelle derselben Quote','Nur der höchste bisher gemessene Einzelwert','Eine genaue Dezimaldarstellung ersetzt keine Kenntnis der Datenbasis.')]])
])
