from deep_authoring import course, unit, choice as c, matching as m, recall as r, ordering as o

COURSE=course('think','images','Was ein Bild belegt – und was du ergänzt',
 'Ein berühmtes Gemälde zeigt eine antike Sterbeszene. Du untersuchst, wie aus sichtbaren Details scheinbar sichere Geschichten werden.',
 ('The Metropolitan Museum of Art · The Death of Socrates', 'https://www.metmuseum.org/art/collection/search/436105'),[
unit('Der Maler war nicht dabei', 'Zeitpunkt der Darstellung und Zeitpunkt des Ereignisses trennen.',[
('Eine überzeugende Szene, eine grosse Zeitlücke', 'Jacques-Louis David malte «Der Tod des Sokrates» 1787. Das dargestellte Ereignis gehört ins Jahr 399 vor unserer Zeitrechnung. Zwischen Ereignis und Gemälde liegen also mehr als zwei Jahrtausende. Die eindringliche Szene ist keine Augenzeugenaufnahme.\n\nSie kann dennoch eine wertvolle Quelle sein. Nur muss die Frage passen: Was zeigt sie über Davids Darstellung von Sokrates, über seine gestalterischen Entscheidungen oder über die Rezeption der antiken Geschichte? Diese Fragen sind von der Frage zu trennen, wo genau jede Person im historischen Raum gestanden hat.'),
('Quelle wofür?', 'Ein Bild ist nicht einfach entweder «Quelle» oder «keine Quelle». Es kann unmittelbar belegen, wie etwas dargestellt wurde, und zugleich nur mittelbar oder unsicher Auskunft über ein viel früheres Ereignis geben. Diese Unterscheidung schützt vor zwei Fehlern: dem blinden Vertrauen in eine anschauliche Szene und dem vollständigen Verwerfen einer späteren Darstellung.\n\nSchreibe deshalb unter ein Bild gedanklich zwei Daten: das dargestellte Ereignis und die Entstehung der Darstellung. Frage dann, worauf sie beruht: Beobachtung, Textüberlieferung, Erinnerung oder gestalterische Rekonstruktion. Je nach Antwort verändern sich die sinnvollen Schlüsse.')],
'Ein Film von heute zeigt eine Schlacht des Mittelalters. Welche Aussage kann eine einzelne Einstellung direkt belegen: die genaue historische Aufstellung oder die gewählte filmische Darstellung?',
'Direkt belegt die Einstellung die Darstellung im Film. Aussagen über die historische Aufstellung brauchen zusätzliche Quellen und die Prüfung, wie der Film mit ihnen umgeht.',[
[m('Ordne die Zeitangabe ihrer Ebene zu.',[('399 vor unserer Zeitrechnung','Dargestelltes Ereignis'),('1787','Entstehung des Gemäldes'),('Heute betrachtete digitale Abbildung','Aktueller Zugang zur Darstellung')],'Ereignis, Werk und heutige Wiedergabe sind drei zeitliche Ebenen.'),m('Welche Frage beantwortet das Gemälde unmittelbarer?', [('Wie komponiert David die Szene?','Frage an die Darstellung'),('Wo stand jeder Mensch 399 v. u. Z. genau?','Frage an das historische Ereignis'),('Wie wurde Sokrates später gedeutet?','Frage an die Rezeption')],'Eine spätere Darstellung ist besonders direkt als Beleg ihrer eigenen Gestaltung und Deutung lesbar.')],
[c('Was folgt aus der grossen Zeitlücke zwischen Ereignis und Gemälde?','Die Szene kann nicht als unmittelbarer Augenzeugenbericht des Malers gelten.','Das Gemälde enthält deshalb keine historisch untersuchbare Information.','Jedes dargestellte Detail muss deshalb das Gegenteil des Ereignisses zeigen.','Eine fehlende Augenzeugenschaft begrenzt eine bestimmte Verwendung, macht das Werk aber nicht wertlos.'),c('Welche Zusatzinformation ist für die historische Verwendung zuerst hilfreich?','Auf welche Texte oder anderen Vorlagen sich die Darstellung stützt','Wie stark die Darstellung mit heutigen Vorstellungen übereinstimmt','Wie oft die digitale Kopie ohne Quellenangabe geteilt wurde','Vorlagen helfen, die Verbindung zwischen späterer Darstellung und früherem Ereignis zu prüfen.')],
[r('Wer malte das im Kapitel untersuchte Werk? Der Nachname genügt.',['David','Jacques Louis David','Jacques-Louis David'],'Das Werk stammt von Jacques-Louis David, nicht von einem antiken Augenzeugen.'),r('Wie nennt der Kurs die spätere Aufnahme und Deutung eines Stoffes?',['Rezeption'],'Rezeption ist selbst historisch interessant, auch wenn sie kein unmittelbarer Bericht des ursprünglichen Ereignisses ist.')]]),
unit('Was du siehst, ist noch nicht die ganze Behauptung', 'Sichtbares Detail, Identifikation und Interpretation auseinanderhalten.',[
('Ein erhobener Finger', 'In der Szene hebt die zentrale Figur einen Finger. Das ist zunächst eine Beschreibung einer sichtbaren Körperhaltung. «Die Figur ist Sokrates» ist eine Identifikation, gestützt auf Titel und Werkzusammenhang. «Der Finger beweist seine völlige innere Furchtlosigkeit» wäre ein weitergehender psychologischer Schluss.\n\nDiese drei Ebenen können zusammenpassen, sind aber nicht identisch. Ein Bild kann eine Haltung absichtlich als Zeichen von Überzeugung inszenieren. Daraus folgt nicht, dass wir den genauen inneren Zustand einer historischen Person unmittelbar sehen. Die sichtbare Geste und ihre Bedeutung brauchen unterschiedliche Arten von Begründung.'),
('Beschreiben, bevor du die Geschichte schliesst', 'Versuche zunächst eine nüchterne Beschreibung: Wer oder was ist wo zu sehen? Welche Linien, Blicke, Lichtverteilungen oder Gegenstände fallen auf? Trenne dann, welche Namen und Bedeutungen du aus Beschriftung oder Vorwissen ergänzt.\n\nDiese Reihenfolge macht Interpretation nicht überflüssig. Sie macht sie überprüfbarer. Zwei Betrachter können bei der sichtbaren Geste übereinstimmen und ihre Bedeutung dennoch anders deuten. Dann liegt der Streit nicht unbedingt darüber, ob sie richtig hingeschaut haben, sondern darüber, welche zusätzliche Erklärung die Beobachtung trägt. Das gleiche Werkzeug hilft bei Pressefotos und kurzen Videoclips.')],
'«Die Person schaut nach unten; sie bereut ihre Entscheidung.» Welcher Teil ist eine sichtbare Beschreibung, welcher eine Deutung?',
'Die Blickrichtung kann beschrieben werden. Reue ist eine Interpretation des inneren Zustands. Weitere Informationen könnten sie stützen, aber die Blickrichtung allein legt sie nicht eindeutig fest.',[
[m('Ordne die Aussage ihrer Ebene zu.',[('Eine Figur hebt den Finger','Sichtbare Beschreibung'),('Die Figur stellt Sokrates dar','Identifikation'),('Die Figur empfindet keinerlei Angst','Psychologische Interpretation')],'Die Sicherheit der sichtbaren Beschreibung überträgt sich nicht automatisch auf den inneren Zustand.'),m('Welche Information wird verwendet?', [('Der Gegenstand liegt links im Bild','Direkt sichtbare Lage'),('Die Bildunterschrift nennt einen Namen','Angabe aus der Beschriftung'),('Die Haltung steht für Standhaftigkeit','Deutung der Inszenierung')],'Bild, Beschriftung und Interpretation liefern verschiedene Beiträge.')],
[c('Zwei Betrachter sehen dieselbe Geste, deuten sie aber unterschiedlich. Was ist noch zu prüfen?','Welche zusätzliche Begründung die jeweilige Bedeutung stützt','Ob übereinstimmendes Sehen bereits jede Bedeutungsfrage entschieden hat','Ob eine der beiden Personen wegen der Abweichung nichts gesehen haben kann','Eine Beobachtung kann mehrere Deutungen zulassen.'),c('Welche Formulierung wahrt die Grenze zwischen Inszenierung und innerem Zustand?','Die Komposition stellt die Figur als standhaft dar.','Die Komposition misst die tatsächliche Angstfreiheit der historischen Person.','Die Komposition schliesst alle anderen Motive der historischen Person aus.','Die erste Aussage betrifft die Darstellung; die anderen behaupten einen direkten Zugang zum inneren Zustand.')],
[r('Wie nennt der Kurs einen zusätzlichen Schluss über die Bedeutung eines sichtbaren Details?',['Interpretation','Deutung'],'Interpretation geht über die reine Beschreibung hinaus.'),r('Wie heisst die Ebene, auf der einer sichtbaren Figur ein Name zugeordnet wird?',['Identifikation','Identifizierung'],'Die Identifikation kann durch Titel, Beschriftung und weitere Quellen gestützt werden.')]]),
unit('Der Ausschnitt verändert die Geschichte', 'Fehlenden Kontext als Informationslücke erkennen.',[
('Ein Bild ohne seinen Rand', 'Schneide in Gedanken eine Szene so eng zu, dass nur eine erhobene Hand sichtbar bleibt. Ohne die anderen Personen und Gegenstände kann sie wie eine Drohung, ein Gruss oder eine Redegeste wirken. Der Ausschnitt hat die Hand nicht unbedingt verändert. Er hat Informationen entfernt, mit denen wir ihre Bedeutung einordnen.\n\nBei einem kurzen Video wirkt zusätzlich die zeitliche Auswahl. Ein einzelner Moment kann eine Reaktion zeigen, ohne die vorausgehende Handlung zu zeigen. Deshalb ist «Der Ausschnitt ist echt» noch keine vollständige Antwort auf «Trägt er die dazu behauptete Geschichte?» Echtheit und Vollständigkeit sind unterschiedliche Fragen.'),
('Mehr Kontext heisst nicht automatisch die endgültige Wahrheit', 'Eine längere Aufnahme oder das vollständige Bild kann eine Deutung korrigieren. Aber auch die längere Fassung hat einen Blickwinkel, eine Auswahl und mögliche Lücken. Man sollte deshalb nicht von blindem Vertrauen in den Ausschnitt zu blindem Vertrauen in die vermeintlich vollständige Fassung springen.\n\nDie praktische Prüfung lautet: Welche entfernte Information könnte den Schluss verändern? Suche gezielt nach dem ursprünglichen Rahmen, nach vorherigen und nachfolgenden Momenten oder nach einer anderen Perspektive. So wird «Kontext fehlt» zu einer konkreten Untersuchungsfrage statt zu einer pauschalen Ausrede, nichts beurteilen zu können.')],
'Ein Foto zeigt eine Person, die eine andere am Arm hält. Der Ausschnitt lässt den Boden und die Umgebung weg. Welche Art fehlender Information könnte zwischen Angriff und Hilfe unterscheiden?',
'Zum Beispiel eine sichtbare Stolperstelle, eine vorausgehende Bewegung oder die längere Situation. Der Armkontakt allein kann die konkurrierenden Erklärungen noch nicht trennen.',[
[m('Welche Auswahl wirkt hier?',[('Bildränder fehlen','Räumlicher Ausschnitt'),('Die Sekunden davor fehlen','Zeitlicher Ausschnitt'),('Nur eine Kameraseite ist sichtbar','Perspektivische Auswahl')],'Kontext kann räumlich, zeitlich und durch den Blickwinkel begrenzt sein.'),m('Welche Prüfung adressiert die Lücke?', [('Handlung vor dem gezeigten Moment unbekannt','Längeren Ablauf suchen'),('Wichtiger Gegenstand am Rand abgeschnitten','Ursprünglichen Bildausschnitt prüfen'),('Gegenseite der Situation verdeckt','Weitere Perspektive vergleichen')],'Eine passende Kontextsuche richtet sich nach der konkreten Unsicherheit.')],
[c('Was folgt aus «Dieser Bildausschnitt wurde nicht digital manipuliert» allein noch nicht?','Dass die dazu behauptete Geschichte durch den Ausschnitt vollständig gestützt ist.','Dass die sichtbaren Pixel zu einem tatsächlichen Bild gehören können.','Dass ein anderer Bildrand zusätzliche Information enthalten könnte.','Ein echter Ausschnitt kann trotzdem selektiv oder irreführend beschriftet sein.'),c('Welche Zusatzinformation trennt zwei konkurrierende Deutungen am ehesten?','Ein vorheriger Moment, den eine Deutung erwartet und die andere nicht','Eine zweite identische Kopie desselben Ausschnitts','Eine höhere Auflösung desselben unwesentlichen Hintergrundteils','Unterscheidender Kontext hilft mehr als blosse Wiederholung gleicher Information.')],
[o('Ordne eine gezielte Ausschnittprüfung.', ['Behaupteten Schluss benennen','Möglicherweise entscheidende fehlende Information bestimmen','Ursprünglichen oder erweiterten Kontext prüfen'],'Kontextsuche braucht eine konkrete Frage, statt nur mehr Material anzuhäufen.'),o('Ordne einen Vergleich von Kurzclip und längerer Aufnahme.', ['Den gezeigten Moment in der längeren Aufnahme finden','Vorausgehende und folgende Handlungen vergleichen','Prüfen, ob sich die ursprüngliche Deutung noch trägt'],'Die längere Fassung ist zusätzliche Information, kein automatisches Wahrheitszertifikat.')]]),
unit('Zehn Kopien sind nicht zehn Zeugen', 'Herkunft und Unabhängigkeit von Bildbelegen prüfen.',[
('Die scheinbare Bestätigung', 'Du findest dasselbe Foto auf zehn Seiten. Alle nennen denselben Ort und dasselbe Datum. Das kann überzeugend wirken. Wenn jedoch alle voneinander kopiert haben, beruhen die zehn Beschriftungen möglicherweise auf nur einer ursprünglichen Angabe.\n\nUnabhängige Bestätigung bedeutet mehr als unterschiedliche Veröffentlichungsorte. Frage, ob tatsächlich verschiedene Informationswege vorliegen: eine zweite Aufnahme, ein zeitgenössischer Bericht mit eigener Beobachtung oder andere passende Dokumente. Ein häufiger Fehler wird nicht dadurch richtig, dass seine Kopien zahlreich sind.'),
('Eine Herkunftskette statt eines Beliebtheitswerts', 'Suche nach der frühesten auffindbaren Veröffentlichung und ihrem Kontext. Wer hat das Bild erstellt? Wer hat die Beschriftung ergänzt? Wurden Ort, Datum oder Bedeutung später verändert? Die früheste auffindbare Quelle ist dabei nicht zwangsläufig die echte erste Quelle, sondern zunächst nur der Stand deiner Suche.\n\nAuch eine Bildrückwärtssuche kann Hinweise auf ältere Verwendungen liefern. Ihr Ausbleiben beweist jedoch weder Echtheit noch Fälschung. Ein Suchwerkzeug deckt nur einen Teil verfügbarer Inhalte ab. Gute Quellenprüfung benennt deshalb den Befund und seine Grenze: «Ich fand eine frühere Nutzung» ist etwas anderes als «Ich kenne die vollständige Entstehungsgeschichte».')],
'Drei Artikel verwenden dasselbe Agenturfoto samt identischer Beschriftung. Wie viele unabhängige visuelle Beobachtungen sind damit mindestens erkennbar?',
'Mindestens eine: die Aufnahme, von der die Veröffentlichungen ausgehen. Drei Artikel allein belegen nicht drei unabhängig entstandene Aufnahmen oder drei getrennte Prüfungen der Beschriftung.',[
[m('Ordne die Informationswege ein.',[('Drei Seiten kopieren dieselbe Bildunterschrift','Abhängige Wiederholung'),('Zweite Kamera zeigt denselben Vorgang','Möglicher zusätzlicher Beobachtungsweg'),('Frühere Veröffentlichung mit anderem Datum','Hinweis zur Herkunftsprüfung')],'Die Zahl der Veröffentlichungen ist nicht die Zahl unabhängiger Ursprünge.'),m('Wie weit trägt der Suchbefund?', [('Ältere Verwendung gefunden','Früheren Kontext nachgewiesen'),('Keine Treffer gefunden','Keinen Treffer im Suchumfang gefunden'),('Erste auffindbare Quelle','Noch nicht zwingend tatsächlicher Ursprung')],'Ein Suchergebnis muss innerhalb der Grenzen des Werkzeugs interpretiert werden.')],
[c('Was macht eine zweite Veröffentlichung zu einer stärkeren Bestätigung?','Ein eigener, nachvollziehbarer Informationsweg zur strittigen Angabe','Ein neuer Artikel, der die ursprüngliche Meldung ausführlicher wiedergibt','Ein weiterer bekannter Verlag, der dieselbe Meldung übernimmt','Unabhängigkeit betrifft die Herkunft des Wissens, nicht die Verpackung der Kopie.'),c('Eine Rückwärtssuche findet nichts. Welche Aussage ist gerechtfertigt?','In dieser Suche wurde keine passende frühere Verwendung gefunden.','Das Bild wurde sicher gerade erst aufgenommen.','Die behauptete Orts- und Zeitangabe ist damit bestätigt.','Ein negatives Suchergebnis ist auf Suchumfang und Trefferfähigkeit begrenzt.')],
[r('Welcher Begriff bezeichnet im Kapitel Belege, die nicht nur denselben ursprünglichen Informationsweg kopieren?',['unabhängig','unabhaengig','unabhängige Belege','unabhaengige Belege','Unabhängigkeit'],'Mehr Veröffentlichungen erzeugen nicht automatisch Unabhängigkeit.'),r('Wie heisst das Nachverfolgen von Erstellung, Veröffentlichung und späteren Änderungen hier: … prüfen?',['Herkunft','Herkunftskette'],'Die Herkunftskette erklärt, woher Bild und Beschriftung stammen.')]]),
unit('Ein Urteil mit genau passender Sicherheit', 'Eine Bildaussage begründet und begrenzt formulieren.',[
('Nicht sicher ist nicht gleich falsch', 'Nach einer Prüfung steht fest, dass ein Foto älter ist als die aktuelle Behauptung. Das widerlegt die Aussage «Heute aufgenommen». Es beweist nicht automatisch, dass alle übrigen Angaben falsch sind oder das Foto technisch verändert wurde.\n\nUmgekehrt kann eine passende Datierung die historische Verwendung verbessern, ohne jede Interpretation der Gesten zu sichern. Gute Urteile passen ihre Reichweite der Evidenz an. Sie unterscheiden: Was ist belegt? Was ist widerlegt? Was bleibt offen? Diese Dreiteilung verhindert, dass eine entdeckte Ungenauigkeit gleich zum Totalurteil über alles im Bild wird.'),
('Zurück zu Sokrates', 'Bei Davids Gemälde kannst du jetzt mehrere Ebenen benennen. Das Werk ist eine spätere Darstellung eines antiken Ereignisses. Seine sichtbare Komposition lässt sich beschreiben. Titel, Textüberlieferung und kunsthistorische Informationen helfen bei Identifikation und Deutung. Die genaue Szene des historischen Ereignisses folgt nicht unmittelbar aus der Anschaulichkeit des Bildes.\n\nDer Gewinn dieses Kurses ist kein pauschales Misstrauen. Es ist eine präzisere Form von Vertrauen: Du verwendest eine Quelle für das, wofür sie tatsächlich Auskunft geben kann. Eine Darstellung darf eindrucksvoll sein; sie muss deshalb nicht mehr beweisen, als ihre Herkunft und ihre Form hergeben.')],
'Du findest das angeblich heutige Foto in einer Veröffentlichung von vor zwei Jahren. Formuliere einen sicheren Befund und eine bewusst offene Frage.',
'Sicherer Befund: Das Bild existierte bereits vor zwei Jahren; «heute aufgenommen» passt nicht dazu. Offen bleiben beispielsweise der ursprüngliche Ort, die Identität einer Person oder mögliche frühere Bearbeitungen.',[
[m('Ordne die Sicherheit zu.',[('Bild in nachweisbar älterer Veröffentlichung','Aktuelle Aufnahmebehauptung widerlegt'),('Geste mit mehreren möglichen Bedeutungen','Interpretation offen'),('Datiertes Gemälde eines viel früheren Ereignisses','Spätere Darstellung belegt')],'Jeder Befund hat eine begrenzte Reichweite.'),m('Welche Ebene prüfst du?', [('Wer fertigte das Werk wann an?','Herkunft'),('Was ist im Bild sichtbar?','Beschreibung'),('Was soll daraus über ein Ereignis folgen?','Behaupteter Schluss')],'Die Prüfung verbindet Ebenen, ohne sie zusammenzuwerfen.')],
[c('Ein falsches Aufnahmedatum ist nachgewiesen. Was folgt daraus am engsten?','Die konkrete Datumsbehauptung stimmt nicht.','Jede abgebildete Person ist damit falsch identifiziert.','Die Bilddatei muss technisch zusammengesetzt worden sein.','Ein widerlegtes Datum belegt nicht automatisch andere Arten von Fehlern.'),c('Welche Schlussformulierung ist bei begrenzter Evidenz am präzisesten?','Die Aufnahme zeigt den Kontakt; dessen Anlass bleibt mit diesem Ausschnitt offen.','Weil der Anlass offen ist, kann der sichtbare Kontakt nicht stattgefunden haben.','Weil der Kontakt sichtbar ist, ist der behauptete Anlass damit bewiesen.','Beobachtung und Erklärung können unterschiedliche Sicherheitsgrade haben.')],
[o('Ordne die abschliessende Bildprüfung.', ['Konkrete Behauptung festhalten','Herkunft und passenden Kontext prüfen','Belegtes, Widerlegtes und Offenes getrennt formulieren'],'Das Ergebnis ist ein begrenztes Urteil, kein pauschales Wahrheits- oder Fälschungsetikett.'),o('Ordne die Verwendung des Sokrates-Gemäldes als Quelle.', ['Entstehungszeit und Darstellungsart feststellen','Sichtbare Gestaltung und ergänzte Deutung trennen','Den historischen Schluss an weiteren Quellen prüfen'],'Die Anschaulichkeit allein macht das Werk nicht zum Augenzeugenbericht.')]])
])
