from deep_authoring import course, unit, choice as c, matching as m, recall as r, number as n

COURSE=course('health','sleep','Müde – aber warum gerade jetzt?',
 'Schlafdruck und innere Uhr erklären unterschiedliche Dinge. Mit diesem Modell liest du deinen Alltag genauer, ohne aus einem schlechten Abend eine Diagnose zu machen.',
 ('NIH / NHLBI · Your Sleep/Wake Cycle', 'https://www.nhlbi.nih.gov/health/sleep/sleep-wake-cycle'),[
unit('Zwei Prozesse, ein müder Mensch', 'Schlafdruck und Tagesrhythmus auseinanderhalten.',[
('Warum Müdigkeit nicht wie ein Akku funktioniert', 'Nach einer langen Wachphase steigt normalerweise das Bedürfnis zu schlafen. Trotzdem fühlst du dich nicht zwingend jede Stunde gleichmässig schläfriger. Manchmal kommt am Abend nochmals ein wacher Abschnitt. Ein einfaches Modell erklärt diesen Unterschied mit zwei zusammenwirkenden Prozessen.\n\nDer Schlafdruck hängt unter anderem davon ab, wie lange du wach warst, und nimmt im Schlaf ab. Der circadiane Rhythmus ist ein ungefähr tageslanger biologischer Takt. Er beeinflusst, zu welchen Zeiten der Körper Wachsein oder Schlaf begünstigt. Der eine Prozess ist also stärker von der vorausgehenden Wach- und Schlafdauer abhängig, der andere von der inneren zeitlichen Phase.'),
('Zwei Fragen statt einer einzigen Zahl', 'Wenn jemand sagt «Ich war lange wach, also muss ich jetzt sofort einschlafen», betrachtet er nur einen Teil des Modells. Wenn jemand sagt «Es ist meine übliche Bettzeit, also muss ich müde sein», ebenfalls. Beide Prozesse und weitere Einflüsse wirken zusammen.\n\nDas Modell ist eine Orientierung, kein persönliches Messgerät. Es liefert keine genaue Prozentanzeige deines Schlafbedarfs und diagnostiziert keine Schlafstörung. Es hilft, unterschiedliche Erklärungen zu prüfen: Hat sich die Wachzeit verändert? Hat sich der Tagesrhythmus verschoben? Oder spielen andere Faktoren mit? Eine konkrete gesundheitliche Beurteilung braucht mehr als dieses Lehrmodell.')],
'Eine Person schläft lange aus und geht am Abend zur sonst üblichen Zeit ins Bett. Welche der beiden Komponenten könnte im Vergleich zu einem frühen Aufstehen geringer sein?',
'Der seit dem Aufwachen aufgebaute Schlafdruck könnte geringer sein. Daraus folgt noch keine sichere Einschlafzeit; die innere Uhr und weitere Einflüsse bleiben beteiligt.',[
[m('Ordne die Beschreibung dem Prozess zu.',[('Bedürfnis steigt mit längerer Wachzeit','Schlafdruck'),('Ungefähr tageslanger biologischer Takt','Circadianer Rhythmus'),('Schlaf vermindert aufgestauten Schlafbedarf','Abbau von Schlafdruck')],'Wachdauer und innere zeitliche Phase sind verschiedene Einflussgrössen.'),m('Welche Frage prüft welchen Einfluss?', [('Wie lange bin ich seit dem Aufwachen wach?','Vorausgehende Wachdauer'),('Welche Tagesphase signalisiert meine innere Uhr?','Circadiane Phase'),('Wie habe ich vorher geschlafen?','Vorausgehender Schlaf')],'Die subjektive Müdigkeit fasst mehrere Einflüsse zusammen.')],
[c('Lange Wachzeit und ein zeitweiliger wacher Abendabschnitt widersprechen sich im Modell nicht, weil …','Schlafdruck und Tagesrhythmus gleichzeitig wirken.','der wache Abschnitt den gesamten Schlafdruck bereits abgebaut hat.','der Tagesrhythmus ausschliesslich von der letzten Stunde abhängt.','Ein wachmachender zeitlicher Einfluss kann trotz erhöhten Schlafdrucks bestehen.'),c('Nach längerem Ausschlafen ist jemand zur üblichen Bettzeit wenig schläfrig. Welche Erklärung passt zunächst zum Modell?','Seit dem Aufwachen konnte sich weniger Schlafdruck aufbauen.','Die gewohnte Uhrzeit beweist unveränderten Schlafdruck.','Wenig Schläfrigkeit beweist einen dauerhaft geringeren Schlafbedarf.','Die veränderte Wachzeit ist ein möglicher Einfluss; eine einzelne Beobachtung bestimmt keinen dauerhaften Bedarf.')],
[r('Wie heisst im Kapitel das mit längerer Wachzeit zunehmende Schlafbedürfnis?',['Schlafdruck'],'Schlafdruck ist nicht identisch mit der inneren Uhr.'),r('Gesucht ist der Fachbegriff für den ungefähr tageslangen Rhythmus: … Rhythmus.',['circadianer','zirkadianer','circadian','zirkadian'],'Circadian bezeichnet einen ungefähr tageslangen biologischen Takt.')]]),
unit('Licht stellt keine Müdigkeit einfach auf null', 'Zeitgeber von unmittelbar empfundener Wachheit unterscheiden.',[
('Die Uhr braucht Hinweise von draussen', 'Die innere Uhr arbeitet nicht wie eine App, die nur die aufgedruckte Uhrzeit abliest. Lichtsignale über die Augen helfen, den biologischen Takt mit dem Tag-Nacht-Wechsel abzustimmen. Ein solches äusseres Signal nennen wir Zeitgeber. Deshalb kann der Wechsel von hellen und dunklen Phasen für den Rhythmus wichtig sein.\n\nDas bedeutet nicht, dass jeder Lichtreiz zu jeder Uhrzeit denselben Effekt hat. Zeitpunkt, Dauer, Stärke und vorherige Lichtbedingungen spielen mit. Die Aussage «Licht macht wach» ist für ein vollständiges Verständnis zu grob: Eine unmittelbare Wirkung auf Wachheit und eine Verschiebung des zeitlichen Takts sind verschiedene Fragen.'),
('Eine Reise macht den Unterschied sichtbar', 'Nach einer Reise über Zeitzonen zeigen die örtlichen Uhren bereits den neuen Tagesablauf. Dein biologischer Rhythmus kann noch teilweise zur bisherigen Zeit passen. Die Umgebung und die innere Phase stimmen dann vorübergehend nicht gut überein.\n\nDas Beispiel macht verständlich, warum «Es ist doch schon Abend» nicht alle Schwierigkeiten erklärt. Die Uhrzeit auf dem Display, die seit dem Aufwachen vergangene Zeit und die innere Phase sind drei verschiedene Informationen. Dieses Kapitel erklärt den Mechanismus; es gibt bewusst keinen individuell berechneten Licht- oder Behandlungsplan. Für gezielte Eingriffe sind persönliche Umstände und gegebenenfalls fachliche Beratung nötig.')],
'Zwei Menschen sitzen um 22 Uhr am selben Ort. Einer kam gerade aus einer weit entfernten Zeitzone. Beweist dieselbe Ortszeit, dass ihre innere Uhr dieselbe Phase hat?',
'Nein. Die örtliche Uhr ist eine gemeinsame äussere Angabe. Die biologische Phase kann nach unterschiedlichen Tagesabläufen oder Reisen davon abweichen.',[
[m('Ordne die Angaben zu.',[('22 Uhr am Zielort','Örtliche Uhrzeit'),('Seit 14 Stunden wach','Wachdauer'),('Körperrhythmus noch am Herkunftsort orientiert','Abweichende innere Phase')],'Gleiche Uhrzeit bedeutet weder gleiche Wachdauer noch gleiche circadiane Phase.'),m('Welche Rolle hat das Signal?', [('Regelmässiger Hell-Dunkel-Wechsel','Zeitgeber für den Rhythmus'),('Zahl auf der Armbanduhr','Anzeige der vereinbarten Ortszeit'),('Vorherige Schlafphase','Teil der vorausgehenden Schlaf-Wach-Geschichte')],'Biologische Abstimmung und Zeitmessung sind nicht dasselbe.')],
[c('Was fehlt in der Aussage «Eine Stunde Licht hat immer dieselbe Wirkung auf die innere Uhr»?','Der Zeitpunkt relativ zur inneren Phase','Die gesamte Lichtdauer, unabhängig von ihrer Verteilung','Die Wachzeit, ohne die innere Phase zu berücksichtigen','Der zeitliche Zusammenhang ist entscheidend; gleiche Dauer allein definiert die Wirkung nicht.'),c('Warum kann Schlafen direkt nach einem Zeitzonenwechsel trotz passender Ortszeit schwerfallen?','Die innere Phase kann noch vom neuen Tagesablauf abweichen.','Die örtliche Uhr bestimmt den Schlafdruck vollständig.','Eine Reise beseitigt den Bedarf an vorausgehendem Schlaf.','Die äussere Zeitumstellung und die biologische Anpassung sind nicht identisch.')],
[r('Wie nennt das Kapitel ein Umweltsignal, das den inneren Takt mit dem Tagesablauf abstimmt?',['Zeitgeber'],'Licht ist ein wichtiger Zeitgeber; ein Zeitgeber ist keine Messung des Schlafdrucks.'),r('Welches Umweltsignal erreicht über die Augen den für dieses Kapitel wichtigen zeitlichen Regelkreis?',['Licht','Lichtsignal'],'Licht hilft, den biologischen Takt an den Hell-Dunkel-Wechsel anzupassen.')]]),
unit('Koffein: ein Signal dämpfen ist keine Erholung', 'Gefühlte Wachheit von abgebautem Schlafdruck unterscheiden.',[
('Eine Anzeige wird leiser', 'Während längerer Wachzeit spielt der Botenstoff Adenosin eine Rolle beim zunehmenden Schlafbedürfnis. Koffein kann an Adenosinrezeptoren wirken und dadurch einen Teil dieser Signalwirkung blockieren. Vereinfacht: Ein Müdigkeitssignal wird weniger wirksam wahrgenommen.\n\nDas ist nicht dasselbe wie die Erholung durch Schlaf. Wer sich nach einem Kaffee wacher fühlt, hat damit nicht nachgewiesen, dass sein vorausgehender Schlafmangel verschwunden ist. Die Analogie einer leiser gestellten Warnanzeige hilft bei genau dieser Unterscheidung. Sie soll nicht behaupten, der menschliche Körper sei eine einfache Maschine mit nur einer Warnlampe.'),
('Eine Beobachtung, zwei mögliche Schlüsse', 'Beobachtung: Nach Koffein fühlt sich eine Person aufmerksamer. Vorsichtiger Schluss: Koffein könnte die subjektive Wachheit beeinflusst haben. Zu weit gehender Schluss: Die Person ist vollständig erholt und kann in jeder anspruchsvollen Situation zuverlässig leisten.\n\nMenschen unterscheiden sich in ihrer Reaktion und im zeitlichen Abbau. Deshalb rechnen wir hier nicht mit einer universellen Uhrzeit, ab der Koffein für alle verschwunden sei. Für das Lernziel genügt die Mechanik: Ein verändertes Signal ist kein Beleg für beseitigten Bedarf. Das gilt besonders, wenn subjektive Einschätzung als Ersatz für eine objektive Leistungsprüfung dienen soll.')],
'Jemand hat wenig geschlafen, trinkt Kaffee und sagt: «Ich fühle mich wieder normal, also fehlt mir kein Schlaf mehr.» Welche Schlussstufe ist nicht durch das Gefühl allein belegt?',
'Dass der Schlafbedarf beziehungsweise die Folgen zu kurzen Schlafs beseitigt wären. Die veränderte Wachheit kann zur Signalwirkung von Koffein passen, ohne vollständige Erholung zu beweisen.',[
[m('Trenne die Vorgänge.',[('Koffein beeinflusst Adenosinrezeptoren','Veränderte Signalwirkung'),('Person berichtet mehr Wachheit','Subjektive Beobachtung'),('Ausreichender erholsamer Schlaf','Nicht durch das Wachheitsgefühl bewiesen')],'Ein Signal, sein Erleben und die vorausgehende Erholung sind verschiedene Ebenen.'),m('Welche Aussage gehört zu welcher Ebene?', [('Ich fühle mich weniger müde','Erleben'),('Adenosinwirkung wird blockiert','Beschriebener Mechanismus'),('Mein Schlafdefizit ist sicher beseitigt','Nicht daraus ableitbarer Schluss')],'Das Gefühl allein kann die weitergehende Behauptung nicht tragen.')],
[c('Welche Formulierung beschreibt Koffein hier am treffendsten?','Es kann die Wirkung eines Müdigkeitssignals abschwächen.','Es baut durch Rezeptorblockade den gesamten vorausgehenden Schlafbedarf ab.','Es bringt die innere Uhr unmittelbar auf die örtliche Zeit.','Die beschriebene Rezeptorwirkung erklärt veränderte Wachheit, nicht vollständige Erholung oder sichere Zeitumstellung.'),c('Was wäre nötig, um mehr als subjektive Wachheit zu beurteilen?','Zur Fragestellung passende weitere Informationen oder Leistungsmessungen','Die gleiche Gefühlsfrage in einer optimistischeren Formulierung','Die Annahme, jede Signalveränderung bedeute vollständige Erholung','Ein Gefühl kann relevant sein, ersetzt aber keine Prüfung anderer behaupteter Wirkungen.')],
[r('Welcher im Kapitel genannte Stoff ist am zunehmenden Schlafbedürfnis beteiligt?',['Adenosin'],'Koffein wirkt unter anderem an Adenosinrezeptoren.'),r('Gesucht ist der Stoff: Welcher verbreitete Wachmacher beeinflusst im beschriebenen Mechanismus Adenosinrezeptoren?',['Koffein','Coffein','Caffeine'],'Die Wirkung von Koffein ist nicht mit Schlaf gleichzusetzen.')]]),
unit('Zeit im Bett ist nicht vollständig Schlaf', 'Eine einfache Schlafaufzeichnung ohne Selbstdiagnose lesen.',[
('Acht Stunden können verschiedene Nächte enthalten', 'Eine Person liegt von 23 bis 7 Uhr im Bett. Das sind acht Stunden Schlafgelegenheit. Braucht sie 30 Minuten bis zum Einschlafen und ist später insgesamt 30 Minuten wach, hat sie im vereinfachten Protokoll sieben Stunden geschlafen.\n\nDrei Angaben gehören auseinander: Bettzeit, geschätzte Einschlafdauer und geschätzte Wachzeit in der Nacht. Eine einzelne Zahl wie «acht Stunden» ist ohne Definition mehrdeutig. Das erklärt auch, weshalb zwei Menschen mit ähnlichen Bettzeiten ihre Nacht unterschiedlich erleben können. Unsere Rechnung ist ein Lehrbeispiel und keine Messung von Schlafqualität.'),
('Ein Protokoll zeigt Muster, keine sichere Ursache', 'Wenn eine Person ihren Ablauf verstehen will, kann sie über mehrere Tage ähnliche Angaben notieren: Bett- und Aufstehzeit, geschätzte Wachphasen, Tagesmüdigkeit und auffällige Veränderungen. Gleichartig erhobene Notizen sind oft aussagekräftiger als die Erinnerung an den schlechtesten Abend.\n\nTrotzdem bleiben Selbsteinschätzungen ungenau. Auch ein Gerät ersetzt nicht automatisch eine medizinische Beurteilung. Ein Verlauf kann eine Frage sichtbar machen, etwa wiederkehrende starke Tagesmüdigkeit; er beweist nicht allein die Ursache. Bei anhaltenden Beschwerden oder relevanten Auswirkungen gehört die Abklärung in fachliche Hände, statt aus einem Diagramm selbst eine Diagnose abzuleiten.')],
'Bettzeit 7,5 Stunden, Einschlafphase 20 Minuten, spätere Wachzeit 40 Minuten. Wie viel geschätzter Schlaf bleibt in diesem vereinfachten Modell?',
'7,5 Stunden sind 450 Minuten. Nach Abzug von 60 wachen Minuten bleiben 390 Minuten, also 6,5 Stunden. Daraus allein folgt noch keine Aussage über eine konkrete Störung.',[
[n('480 Minuten im Bett, 25 Minuten bis zum Einschlafen, 35 Minuten später wach. Geschätzte Schlafzeit?',420,'Minuten','480 − 25 − 35 = 420 Minuten.'),n('450 Minuten im Bett, 15 Minuten Einschlafphase, 45 Minuten nachts wach. Geschätzte Schlafzeit?',390,'Minuten','450 − 15 − 45 = 390 Minuten.')],
[c('Was erlaubt ein gleichartig geführtes mehrtägiges Schlafprotokoll eher als eine einzelne Erinnerung?','Wiederkehrende zeitliche Muster zu erkennen','Eine konkrete medizinische Ursache sicher festzustellen','Gerätemessungen ohne weitere Prüfung als fehlerfrei zu behandeln','Ein Protokoll kann Muster zeigen, ist aber kein alleiniger Ursachen- oder Diagnosenachweis.'),c('Zwei Menschen berichten acht Stunden «Schlaf». Welche Rückfrage verbessert den Vergleich zuerst?','Meinen beide Schlafzeit oder Zeit im Bett?','Haben beide die gleiche Zeit zum Zubettgehen gewählt?','Liegen beide acht Stunden zwischen Zubettgehen und Aufstehen?','Die Definition der gemessenen Grösse muss übereinstimmen, bevor Zahlen verglichen werden.')],
[m('Welche Grösse wird beschrieben?', [('Von Hinlegen bis Aufstehen','Zeit im Bett'),('Zeit bis zum Einschlafen','Einschlafdauer'),('Mehrere notierte Nächte','Verlauf mit möglichen Mustern')],'Definitionen verhindern, dass verschiedene Grössen unter demselben Namen verglichen werden.'),m('Wie weit trägt die Information?', [('Ein schlechter Abend','Einzelbeobachtung'),('Ähnliches Muster über viele Tage','Wiederkehrender Verlauf'),('Verlauf ohne weitere Untersuchung','Noch kein sicherer Ursachennachweis')],'Eine längere Beobachtung kann Fragen schärfen, ersetzt aber nicht jede weitere Prüfung.')]]),
unit('Ein Abend ist noch kein Experiment', 'Eine plausibel veränderte Gewohnheit vorsichtig beurteilen.',[
('Heute ging es besser – weshalb?', 'Eine Person lässt an einem Tag späten Kaffee weg, trainiert früher, arbeitet weniger und geht früher ins Bett. Sie schläft besser. Es ist verständlich, einen Erfolg sehen zu wollen. Die Beobachtung trennt aber nicht, welche der Änderungen welchen Anteil hatte. Auch normale Schwankung kommt als Erklärung infrage.\n\nEin verständlicher Selbstvergleich beschreibt deshalb zuerst die konkrete Frage. Nicht «War mein Tag gesünder?», sondern beispielsweise «Wie verändert sich meine abendliche Wachheit, wenn ich einen bestimmten gewohnten Ablauf ändere?» Je mehr gleichzeitig umgestellt wird, desto schwieriger wird die Zuordnung des Ergebnisses.'),
('Ein Lernmodell bleibt ein Lernmodell', 'Verknüpfe zum Schluss die Komponenten: Längere Wachzeit kann Schlafdruck erhöhen. Licht und Tagesablauf können mit der inneren Phase zusammenhängen. Koffein kann ein Müdigkeitssignal beeinflussen. Zeit im Bett ist nicht mit tatsächlichem Schlaf identisch. Ein einzelnes subjektives Gefühl bildet diese Vorgänge nicht vollständig ab.\n\nDiese Zusammenhänge geben dir bessere Fragen, keine universelle Optimierungsformel. Wer regelmässig stark beeinträchtigt ist, sollte das nicht mit immer strengeren Selbstexperimenten überdecken. Für den Alltag dieses Kurses genügt eine zurückhaltende Haltung: Begriffe sauber verwenden, Beobachtungen über passende Zeiträume vergleichen und die Grenzen der eigenen Schlussfolgerung benennen.')],
'Du schläfst nach drei gleichzeitigen Änderungen einmal besser. Welche Aussage ist gerechtfertigt, und welche wäre zu stark?',
'Gerechtfertigt: Unter diesen Bedingungen gab es eine bessere Nacht. Zu stark: Eine bestimmte einzelne Änderung sei damit als Ursache bewiesen. Dafür fehlen getrennte Vergleiche und weitere Beobachtungen.',[
[m('Welche Komponente prüfst du?', [('Späteres Aufstehen bei gleicher Bettzeit','Veränderte Wachdauer'),('Wechsel über mehrere Zeitzonen','Veränderte Abstimmung der inneren Phase'),('Wacheres Gefühl nach Kaffee','Mögliche veränderte Signalwirkung')],'Die Situationen betreffen unterschiedliche Teile des Modells.'),m('Ordne Beobachtung und Schluss ein.', [('Eine bessere Nacht nach mehreren Änderungen','Beobachtetes Zusammentreffen'),('Nur die Kaffeeänderung war die Ursache','Noch nicht isolierter Ursachenschluss'),('Weitere vergleichbare Beobachtungen sammeln','Möglicher Weg zur besseren Einordnung')],'Gleichzeitige Änderungen erschweren die kausale Zuordnung.')],
[c('Warum ist ein einzelner erfolgreicher Abend kein starker Beweis für genau eine neue Gewohnheit?','Andere gleichzeitige Veränderungen und Schwankungen bleiben mögliche Erklärungen.','Einzelne Erlebnisse enthalten grundsätzlich keine nutzbare Information.','Ein guter Ausgang beweist die Wirkung jeder gleichzeitig geänderten Gewohnheit.','Die Beobachtung ist Information, aber trennt die konkurrierenden Erklärungen noch nicht.'),c('Welche Frage passt zum Zwei-Prozess-Modell?','Haben sich sowohl Wachdauer als auch innere zeitliche Phase verändert?','Wie viele Prozent Schlaf sind durch gefühlte Wachheit ersetzt worden?','Welche örtliche Uhrzeit legt den Schlafdruck aller Menschen fest?','Das Modell unterscheidet Wachdauer und circadiane Phase, statt sie zu einer universellen Zahl zusammenzuziehen.')],
[r('Welcher Begriff aus dem Kurs beschreibt eine Erklärung dafür, warum zwei Personen bei gleicher Ortszeit biologisch verschieden eingestellt sein können?',['Innere Phase','circadiane Phase','zirkadiane Phase','innere Uhr','circadianer Rhythmus','zirkadianer Rhythmus'],'Die innere Phase kann von der gemeinsamen örtlichen Uhrzeit abweichen.'),r('Welcher Begriff aus dem Kurs steigt typischerweise mit längerer Wachzeit und wird durch Schlaf abgebaut?',['Schlafdruck'],'Das bezeichnet die homeostatische Komponente, nicht die Ortszeit.')]])
])
