from deep_authoring import course, unit, choice as c, number as n, matching as m, recall as r

COURSE = course('earth', 'heat', 'Der Treibhauseffekt ohne Nebel',
    'Warum kann sich die Erde erwärmen, obwohl die Sonne nicht stärker scheint? Du verfolgst Energie statt Schlagwörter.',
    ('UCAR · The Greenhouse Effect', 'https://scied.ucar.edu/learning-zone/how-climate-works/greenhouse-effect'), [
unit('Der entscheidende Wechsel der Strahlung', 'Sonnenlicht, Reflexion und Wärmestrahlung unterscheiden.', [
('Ein Stein nach Sonnenuntergang', 'Ein dunkler Stein liegt am Nachmittag in der Sonne. Nach Sonnenuntergang ist er noch warm. Er hat einen Teil der einfallenden Strahlungsenergie aufgenommen. Jetzt gibt er Energie an seine Umgebung ab, unter anderem als unsichtbare infrarote Strahlung. Er spiegelt nicht einfach das Sonnenlicht des Nachmittags verspätet zurück.\n\nHier liegt der erste Schlüssel zum Treibhauseffekt: Die Sonne und die vergleichsweise kühle Erde senden Energie überwiegend in unterschiedlichen Wellenlängenbereichen aus. Die Atmosphäre kann deshalb einen grossen Teil des Sonnenlichts durchlassen und zugleich mit einem Teil der von der Erde ausgesandten Infrarotstrahlung wechselwirken.'),
('Drei Pfeile statt eines', 'Unterscheide im Schema drei Vorgänge. Reflexion bedeutet: Strahlung wird zurückgeworfen. Absorption bedeutet: Ein Körper nimmt Strahlungsenergie auf. Emission bedeutet: Ein Körper sendet Strahlung aus. Ein erwärmter Boden emittiert Infrarotstrahlung; Treibhausgase absorbieren bestimmte Wellenlängen davon und geben ebenfalls Strahlung ab.\n\nDas veröffentlichte Bild dient hier der Orientierung, nicht als Messung des heutigen Jahres. Folge zuerst den Wegen: Was trifft ein, was wird reflektiert, was wird erst von der Erde ausgesandt? Verwechsle die Farbe eines Diagrammpfeils nicht mit einer für Menschen sichtbaren Lichtfarbe. Infrarot bleibt für unser Auge unsichtbar.')],
'Eine helle Fläche spiegelt Sonnenlicht zurück. Eine dunkle Fläche nimmt Energie auf und gibt später Infrarotstrahlung ab. Welcher Vorgang verändert den Energieinhalt zunächst stärker?',
'Die Absorption erhöht zunächst den Energieinhalt der dunklen Fläche. Die reflektierte Strahlung wurde gerade nicht aufgenommen. Wie warm die Fläche tatsächlich wird, hängt zusätzlich von ihren Energieabgaben ab.', [
[m('Ordne den Vorgang zu.', [('Schnee wirft Sonnenlicht zurück','Reflexion'),('Boden nimmt Strahlungsenergie auf','Absorption'),('Warmer Boden sendet Infrarot aus','Emission')], 'Zurückwerfen, Aufnehmen und Aussenden sind nicht derselbe Vorgang.'),m('Welche Beschreibung passt?', [('Strahlung verlässt einen warmen Stein','Emission'),('Energie gelangt durch Strahlung in den Stein','Absorption'),('Einfallendes Licht wird zurückgeworfen','Reflexion')], 'Entscheidend ist die Richtung des Energieaustauschs am Körper.')],
[c('Warum kann die Atmosphäre Sonnenlicht vergleichsweise gut durchlassen und zugleich die Wärmeabgabe beeinflussen?','Die Strahlung liegt überwiegend in anderen Wellenlängenbereichen.','Die ausgehende Strahlung enthält grundsätzlich weniger einzelne Strahlen.','Die Atmosphäre unterscheidet an der Flugrichtung zwischen Licht und Wärme.','Die Wechselwirkung hängt von Wellenlänge und Stoff ab, nicht davon, ob ein Strahl nach oben zeigt.'),c('Ein Stein strahlt nach Sonnenuntergang weiter. Woher stammt die dabei abgegebene Energie?','Aus seinem vorhandenen Energieinhalt','Aus Sonnenlicht, das er nach Sonnenuntergang noch reflektiert','Aus Energie, die erst beim Ausstrahlen entsteht','Ein warmer Körper gibt gespeicherte Energie ab; dazu braucht er keine laufende direkte Beleuchtung.')],
[r('Wie heisst das Aufnehmen von Strahlungsenergie durch einen Körper? Gesucht ist der im Kapitel verwendete Fachbegriff.',['Absorption'],'Absorption ist Aufnahme; Emission ist Aussenden.'),r('Wie heisst das Aussenden von Strahlung durch einen Körper? Gesucht ist der Fachbegriff aus dem Kapitel.',['Emission'],'Emission bezeichnet das Aussenden, nicht das Zurückwerfen einfallender Strahlung.')]]),
unit('Eine Bilanz an der richtigen Grenze', 'Einen Energieüberschuss für das gesamte Erdsystem berechnen.', [
('Die Grenze liegt oben, nicht am Boden', 'Für die Energiebilanz der ganzen Erde ziehen wir eine gedachte Grenze oberhalb der Atmosphäre. Durch diese Grenze kommt Sonnenenergie herein und geht Energie wieder hinaus. Austausch zwischen Boden und Atmosphäre liegt innerhalb der Grenze. Solche inneren Wege sind wichtig für Temperaturen, aber kein neuer Energiezufluss von ausserhalb.\n\nStell dir stark vereinfachte Recheneinheiten pro Sekunde vor: 100 Einheiten werden vom Erdsystem aufgenommen, 100 verlassen es. Sein gesamter Energieinhalt nimmt dadurch nicht zu. Werden weiter 100 aufgenommen, aber nur 98 abgegeben, bleiben pro Sekunde zwei Einheiten zusätzlich im System.'),
('Fluss ist nicht Vorrat', 'Ein Energiefluss beschreibt Energie pro Zeit. Der Energieinhalt ist ein Vorrat. Die Differenz zwischen Zufluss und Abfluss verändert diesen Vorrat. Die Temperatur ist noch einmal etwas anderes: Wie stark sie auf zusätzliche Energie reagiert, hängt unter anderem vom Material und seiner Wärmekapazität ab.\n\nWenn du eine Bilanz liest, prüfe die Einheiten und die Systemgrenze. Zähle Strahlung von der Atmosphäre zum Boden nicht gleichzeitig als zusätzliche Sonnenenergie. Im Bild kann ein innerer Pfeil gross sein, ohne dass die Erde Energie aus dem Nichts erhält. Unsere 100 und 98 sind Lehrzahlen, keine aktuellen Klimamesswerte.')],
'Ein Modell nimmt jede Sekunde 240 Energieeinheiten auf und gibt 237 ab. Wie verändert sich sein Energieinhalt über zehn Sekunden, solange beide Raten gleich bleiben?',
'Der Überschuss beträgt drei Einheiten pro Sekunde. In zehn Sekunden kommen 30 Einheiten hinzu. Daraus allein lässt sich noch keine Temperaturänderung in Grad berechnen.', [
[n('Ein Lehrmodell nimmt 80 Einheiten pro Sekunde auf und gibt 76 ab. Wie viele Energieeinheiten kommen in fünf Sekunden hinzu?',20,'Einheiten','(80 − 76) × 5 = 20. Die Raten bleiben laut Aufgabe konstant.'),n('Aufnahme 120 Einheiten pro Sekunde, Abgabe 117. Wie viele Einheiten kommen in acht Sekunden hinzu?',24,'Einheiten','(120 − 117) × 8 = 24.')],
[c('Die Atmosphäre strahlt Energie zum Boden. In der Bilanz des gesamten Erdsystems ist das …','ein innerer Austausch.','ein zusätzlicher Zufluss von der Sonne.','ein Abfluss über die äussere Grenze.','Boden und Atmosphäre liegen beide innerhalb der gewählten Systemgrenze.'),c('Aufnahme und Abgabe sind gleich gross. Welche Aussage folgt für diesen Strahlungsbeitrag?','Der gesamte Energieinhalt ändert sich dadurch nicht.','Die Temperatur muss überall auf der Erde gleich sein.','Zwischen Boden und Luft wird keine Energie ausgetauscht.','Eine ausgeglichene äussere Bilanz schliesst innere Flüsse und räumliche Unterschiede nicht aus.')],
[m('Ordne die Grössen ein.', [('Energieeinheiten pro Sekunde','Fluss'),('Gespeicherte Energieeinheiten','Vorrat'),('Grad Celsius','Temperatur')], 'Wer diese Grössen vermischt, kann weder Bilanz noch Erwärmung sauber erklären.'),m('Welche Information liefert die Grösse?', [('Aufnahme minus Abgabe','Änderungsrate des Energieinhalts'),('Wärmekapazität','Zusammenhang zwischen Energie und Temperaturänderung'),('Gedachte äussere Grenze','Welche Flüsse als hinein und hinaus zählen')], 'Eine Bilanz braucht Abgrenzung und Einheiten, nicht nur Pfeile.')]],
dict(kind='balance',title='Lehrmodell pro Sekunde',labels=['Aufgenommen: 100','Ins All: 98','Im System: +2'],values=[100,98,2],caption='Erfundene Energieeinheiten zur Erklärung der Bilanz; keine Messdaten.')),
unit('Warum eine unveränderte Sonne genügt', 'Die Reaktion auf eine zunächst verringerte Energieabgabe erklären.', [
('Zuerst ändert sich die Abgabe', 'Denke an ein System, das anfangs gleich viel Energie aufnimmt wie abgibt. Nun ändern zusätzliche Treibhausgase seine Strahlungseigenschaften. Bei zunächst gleicher Temperatur kann dadurch weniger Energie ins All entweichen. Die Sonne muss für diesen Schritt nicht stärker werden.\n\nIm vereinfachten Modell wird aus 100 hinein und 100 hinaus zunächst 100 hinein und 98 hinaus. Die zwei fehlenden Ausgangseinheiten verschwinden nicht; der Energieinhalt des Systems nimmt zu. Der Treibhauseffekt ist hier eine Veränderung des Energieabflusses und der Temperaturen, kein zusätzlicher Energielieferant.'),
('Die Temperatur reagiert, die Abgabe auch', 'Mit zunehmender Temperatur kann ein Körper mehr Wärmestrahlung abgeben. In einem einfachen Gleichgewichtsbild erwärmt sich das System so weit, bis seine Abgabe wieder zur aufgenommenen Energie passt. In der wirklichen Erde spielen dabei unter anderem Ozeane, Wolken und zeitlich veränderliche Rückkopplungen mit.\n\nZwei Fehler sind besonders verführerisch: «Die Sonne bleibt gleich, also muss die Temperatur gleich bleiben» übersieht die Abgabe. «Treibhausgase verhindern jede Abkühlung» übersieht, dass weiterhin Energie entweicht. Eine bessere Frage lautet: Welche Temperaturverteilung ist unter den veränderten Bedingungen mit der Bilanz vereinbar?')],
'Ein Modell ist im Gleichgewicht. Bei unveränderter Temperatur sinkt die Abgabe von 90 auf 87 Einheiten pro Sekunde; die Aufnahme bleibt 90. Was geschieht zuerst, und was könnte ein neues Gleichgewicht ermöglichen?',
'Zunächst wächst der Energieinhalt um drei Einheiten pro Sekunde. Eine höhere Temperatur kann die Abgabe wieder erhöhen. Das Modell braucht dafür weder eine stärkere Sonne noch eine vollständig undurchlässige Atmosphäre.', [
[n('Aufnahme und bisherige Abgabe: je 200 Einheiten/s. Nach einer Änderung beträgt die Abgabe zunächst 196 Einheiten/s. Wie gross ist der anfängliche Überschuss pro Sekunde?',4,'Einheiten/s','200 − 196 = 4; die Aufnahme wurde nicht verändert.'),n('Aufnahme 150 Einheiten/s, neue Abgabe bei gleicher Temperatur 147 Einheiten/s. Wie gross ist der anfängliche Überschuss pro Sekunde?',3,'Einheiten/s','150 − 147 = 3.')],
[c('Was passt zum neuen Gleichgewicht eines wärmeren Lehrmodells bei unveränderter Aufnahme?','Die Abgabe ist wieder so gross wie die Aufnahme.','Die Abgabe bleibt dauerhaft kleiner als die Aufnahme.','Der Energieinhalt wächst weiterhin pro Sekunde um denselben Betrag.','Ein dauerhaft positiver Überschuss wäre gerade kein energetisches Gleichgewicht.'),c('Welche Beobachtung erklärt Erwärmung bei konstanter Sonneneinstrahlung im beschriebenen Modell?','Die Abgabe sank zunächst bei gleicher Temperatur.','Die Aufnahme und Abgabe blieben jederzeit gleich.','Die Reflexion erhöhte sich bei sonst unveränderten Flüssen.','Ein zuerst verringerter Abfluss erzeugt den Überschuss. Mehr Reflexion würde die Aufnahme eher senken.')],
[m('Ordne die Schritte ihrer Rolle zu.', [('Mehr absorbierende Gase','Veränderte Strahlungseigenschaften'),('Aufnahme übersteigt Abgabe','Anfängliches Ungleichgewicht'),('Höhere Temperatur erhöht die Abgabe','Weg zu einer neuen Bilanz')], 'Ursache, Ungleichgewicht und Reaktion folgen aufeinander.'),m('Welche Aussage beschreibt welchen Zustand?', [('100 hinein, 100 hinaus','Ausgeglichene äussere Bilanz'),('100 hinein, 97 hinaus','Zunehmender Energieinhalt'),('100 hinein, 103 hinaus','Abnehmender Energieinhalt')], 'Die Bilanz folgt der Differenz, nicht allein der Grösse des Zuflusses.')]]),
unit('Rückkopplung ist nicht der erste Auslöser', 'Auslöser und verstärkende Rückwirkung trennen.', [
('Ein Kreis im Ursache-Wirkungs-Denken', 'Eine anfängliche Erwärmung kann Eisflächen verkleinern. Wo vorher helles Eis viel Sonnenlicht reflektierte, kann eine dunklere Oberfläche mehr davon aufnehmen. Diese zusätzliche Aufnahme begünstigt weitere Erwärmung. Ein Teil der Wirkung beeinflusst damit die ursprüngliche Veränderung zurück: Das heisst Rückkopplung.\n\nDie Fähigkeit einer Oberfläche, einfallende Strahlung zu reflektieren, wird hier als Albedo bezeichnet. Hohe Albedo bedeutet starke Reflexion. Das Eisbeispiel zeigt eine verstärkende Rückkopplung, weil die Rückwirkung in dieselbe Richtung wirkt wie die anfängliche Erwärmung. Es erklärt nicht allein, wodurch diese erste Erwärmung ausgelöst wurde.'),
('«Positiv» heisst hier nicht «gut»', 'Eine positive Rückkopplung verstärkt eine Veränderung. Eine negative wirkt ihr entgegen. Diese Wörter bewerten den Mechanismus, nicht seinen Nutzen für Menschen. Die stärkere Wärmestrahlung eines wärmeren Körpers wirkt beispielsweise einer weiteren Energieansammlung entgegen.\n\nUm einen behaupteten Kreislauf zu prüfen, gehe jeden Pfeil einzeln durch: Was verändert sich? Was bewirkt das am nächsten Schritt? Führt die letzte Wirkung zur Verstärkung oder Abschwächung des Anfangs? Eine Geschichte mit vielen Pfeilen ist noch kein Beleg für ihre Stärke. Dafür braucht man Messungen und Modelle. Auch eine verstärkende Rückkopplung bedeutet nicht automatisch grenzenloses Wachstum.')],
'Eine dunkler gewordene Fläche reflektiert von 100 einfallenden Einheiten statt 40 nur noch 25. Wie verändert sich die aufgenommene Energie in diesem vereinfachten Beispiel?',
'Vorher wurden 60, danach 75 Einheiten aufgenommen. Das sind 15 mehr. Die Rechnung hält den Zufluss gleich und betrachtet nur die Änderung der Reflexion.', [
[n('100 Einheiten treffen ein. Die Reflexion sinkt von 35 auf 20. Um wie viele Einheiten steigt die Aufnahme?',15,'Einheiten','Aufnahme vorher 65, danach 80: Zunahme 15.'),n('100 Einheiten treffen ein. Die Reflexion steigt von 20 auf 45. Um wie viele Einheiten sinkt die Aufnahme?',25,'Einheiten','Aufnahme vorher 80, danach 55: Abnahme 25.')],
[c('Erwärmung verringert Eis, dunklerer Untergrund nimmt mehr Energie auf. Was ist der letzte Schritt?','Weitere Erwärmung wird begünstigt.','Die ursprüngliche Erwärmung wird abgeschwächt.','Die Sonneneinstrahlung muss stärker werden.','Die verstärkte Aufnahme wirkt zurück auf die Erwärmung, ohne eine veränderte Sonne vorauszusetzen.'),c('Ein wärmerer Körper gibt mehr Wärmestrahlung ab. Wie wirkt dies auf einen anfänglichen Energieüberschuss?','Es wirkt der weiteren Ansammlung entgegen.','Es vergrössert den Überschuss bei gleicher Aufnahme.','Es lässt die reflektierte Sonnenenergie zwingend sinken.','Mehr Abgabe bei gleichem Zufluss verringert den Überschuss.')],
[r('Welcher Begriff bezeichnet das Reflexionsvermögen einer Oberfläche?',['Albedo'],'Albedo beschreibt Reflexion, nicht gespeicherte Wärme.'),r('Wie nennt man eine Wirkung, die auf den ursprünglichen Vorgang zurückwirkt?',['Rückkopplung','Rueckkopplung','Feedback'],'Eine Rückkopplung kann verstärken oder abschwächen; der Begriff legt die Richtung noch nicht fest.')]]),
unit('Was eine kalte Woche beweisen kann', 'Zeitmassstab, Bilanz und Aussagekraft gemeinsam prüfen.', [
('Ein falscher Beweis kann ein richtiger Messwert sein', 'In einer Stadt ist eine Woche kälter als im Vorjahr. Der Messwert kann völlig korrekt sein. Er beantwortet aber zuerst eine lokale, kurzfristige Frage. Eine Behauptung über die langfristige mittlere Entwicklung des Klimas hat einen anderen Zeit- und Raumbezug. Man muss nicht den kalten Tag leugnen, um den Schluss daraus zurückzuweisen.\n\nUmgekehrt beweist eine einzelne Hitzewoche allein noch keine bestimmte langfristige Ursache. Trenne Beobachtung und Schluss: Wo wurde was über welchen Zeitraum gemessen? Welche Behauptung soll daraus folgen? Die Reichweite der Daten sollte zur Reichweite der Behauptung passen.'),
('Mit dem Mechanismus prüfen statt mit einem Schlagwort', 'Du kannst nun drei Prüfungen verbinden. Erstens: Spricht die Person über Energiefluss, Temperatur oder Wetter? Zweitens: Wo liegt ihre Systemgrenze – ein Ort, die Oberfläche oder die ganze Erde? Drittens: Geht es um einen anfänglichen Überschuss oder einen späteren Zustand?\n\nDie Aussage «Die Atmosphäre strahlt zum Boden, also erzeugt sie Energie» verwechselt einen inneren Austausch mit einem äusseren Zufluss. «Die Sonne ist unverändert, also ist Erwärmung ausgeschlossen» übersieht eine veränderte Abgabe. Nicht jedes falsche Argument braucht eine neue Zahl. Häufig genügt es, die verwendeten Grössen und den fehlenden Zusammenhang präzise zu benennen.')],
'Jemand zeigt eine kalte Messwoche und behauptet: «Damit ist bewiesen, dass zusätzliche Treibhausgase keine Erwärmung verursachen können.» Welche zwei Ebenen werden vermischt?',
'Eine kurzfristige lokale Temperaturbeobachtung wird mit einer Aussage über einen globalen Strahlungsmechanismus vermischt. Zur langfristigen Entwicklung passen räumlich geeignete, über viele Jahre vergleichbare Daten.', [
[m('Welche Daten passen zur Frage?', [('War die Stadt gestern kälter als vorgestern?','Vergleichbare örtliche Tageswerte'),('Wie entwickelt sich das regionale Klima?','Vergleichbare regionale Langzeitreihe'),('Wie arbeitet der beschriebene Mechanismus?','Strahlungswege und Energieflüsse')], 'Eine passende Messung richtet sich nach der Frage, nicht nach dem gewünschten Ergebnis.'),m('Welcher Fehler steckt im Schluss?', [('Rückstrahlung sei neue Sonnenenergie','Innere und äussere Flüsse verwechselt'),('Gleiche Sonne bedeute gleiche Temperatur','Mögliche Änderung der Abgabe übersehen'),('Kalte Woche widerlege langen Trend','Zeit- und Raumbezug vermischt')], 'Die Fehler betreffen unterschiedliche Ebenen der Erklärung.')],
[c('Welche Beobachtung widerspricht für sich allein einem langfristigen Erwärmungstrend am wenigsten?','Eine kalte Woche an einem einzelnen Ort','Eine langjährig unveränderte passende globale Messreihe','Eine langjährig fallende passende globale Messreihe','Lokale kurzfristige Schwankungen können innerhalb eines globalen langfristigen Trends auftreten.'),c('Welche Zusatzinformation ist für einen Vergleich zweier regionaler Temperaturreihen zuerst wichtig?','Ob Zeitraum, Messgebiet und Messweise vergleichbar sind','Ob sich die höchsten Einzelwerte beider Reihen ähneln','Ob beide Reihen am selben besonders warmen Tag beginnen','Vergleichbarkeit verhindert, dass unterschiedliche Ausschnitte als widersprüchliche Trends erscheinen.')],
[n('Ein vereinfachtes System nimmt über zehn Sekunden je 50 Einheiten auf und gibt je 49 ab. Wie viele Einheiten gewinnt es insgesamt?',10,'Einheiten','(50 − 49) × 10 = 10. Diese Bilanz allein beschreibt noch keinen örtlichen Wetterverlauf.'),n('Über sechs Sekunden werden je 70 Einheiten aufgenommen und 72 abgegeben. Wie viele Einheiten verliert das System insgesamt?',12,'Einheiten','(72 − 70) × 6 = 12. Eine Abnahme des Energieinhalts ist nicht dieselbe Grösse wie Grad Celsius.')]])
])
