from deep_authoring import course, unit, choice as c, number as n, matching as m, ordering as o

COURSE=course('history','press','Buchdruck: mehr als eine Presse',
 'Du gehst durch eine frühe Druckwerkstatt und untersuchst, weshalb eine wiederholbare Seite Wissen, Kosten und Fehler verändert.',
 ('Library of Congress · The Gutenberg Bible', 'https://www.loc.gov/exhibits/bibles/the-gutenberg-bible.html'),[
unit('Die Seite wird zum wiederverwendbaren Werkzeug', 'Handschrift, Blockdruck und bewegliche Lettern unterscheiden.',[
('Eine Werkstatt voller Arbeitsschritte', 'Auf dem Werkstattbild von Jost Amman aus dem Jahr 1568 siehst du keine Maschine, die ein fertiges Buch auswirft. Menschen setzen, schwärzen, pressen und bearbeiten Papier. Das Bild stammt deutlich nach Gutenbergs Arbeit im 15. Jahrhundert. Es ist ein historischer Blick auf eine Druckwerkstatt, keine Fotografie ihrer Erfindung.\n\nBei einer Handschrift wird der Text für jedes Exemplar erneut geschrieben. Beim Blockdruck kann eine in einen Block geschnittene Seite wiederholt abgedruckt werden. Bewegliche Lettern teilen diese Form in wiederverwendbare Zeichen. Nach einer Auflage lassen sich die Zeichen auseinandernehmen und zu einem anderen Text zusammensetzen.'),
('Die Kombination macht den Unterschied', 'Der entscheidende Vorteil liegt nicht darin, dass ein einzelner Buchstabe plötzlich schneller zu entwerfen wäre. Die aufwendig gesetzte Druckform kann viele Abdrücke liefern, und ihre Teile können später neu verwendet werden. Dazu müssen Material, Farbe, Papier, Anpressdruck und Arbeitsabläufe zusammenpassen.\n\nDruck und bewegliche Zeichen haben zudem eine Geschichte ausserhalb Europas, die vor Gutenberg beginnt. Die europäische Entwicklung darf deshalb nicht als Erfindung jedes Druckprinzips aus dem Nichts erzählt werden. Unser Kurs untersucht den Mechanismus der europäischen Werkstatt und seiner Verbreitung, nicht einen Wettstreit um einen einzigen allumfassenden Erfinder.')],
'Du willst nach 200 gleichen Flugblättern einen anderen Text drucken. Was kann bei einer Form aus beweglichen Lettern neu zusammengestellt werden, während ein ganzer geschnittener Textblock dies nicht erlaubt?',
'Die einzelnen Zeichen können auseinandergelegt und neu gesetzt werden. Ein vollständiger geschnittener Block lässt sich erneut abdrucken, aber sein Text nicht ebenso frei aus denselben Einzelzeichen umbauen.',[
[m('Ordne den Ablauf zu.',[('Jedes Exemplar neu schreiben','Handschrift'),('Ganze geschnittene Seite mehrfach abdrucken','Blockdruck'),('Einzelzeichen zu neuen Texten zusammensetzen','Bewegliche Lettern')],'Wiederholbarkeit und Wiederverwendbarkeit sind unterschiedliche Eigenschaften.'),m('Was lässt sich hier wiederverwenden?', [('Gesetzte Form für weitere identische Abdrücke','Seitenanordnung'),('Einzellettern nach dem Auseinandernehmen','Zeichen für andere Texte'),('Handschriftliche Textvorlage','Inhalt als Abschreibvorlage')],'Eine Vorlage wiederzuverwenden spart nicht automatisch die erneute Herstellung jedes Exemplars.')],
[c('Worin liegt der besondere Unterschied zwischen beweglichen Lettern und einer ganzen geschnittenen Textseite?','Die Zeichen lassen sich für neue Texte umordnen.','Beide Seiten erzeugen identische Exemplare ohne Vorbereitung.','Nur die geschnittene Seite kann mehrfach abgedruckt werden.','Auch ein Block kann viele Abdrücke liefern; bewegliche Zeichen erlauben zusätzlich neue Zusammensetzungen.'),c('Was kann das Werkstattbild von 1568 unmittelbar zeigen?','Eine zeitgenössische Darstellung damaliger Werkstattarbeit','Eine direkte Aufnahme von Gutenbergs erster Presse','Den exakten Arbeitsablauf sämtlicher Druckereien Europas','Datum und Darstellungsart begrenzen den Schluss; das Bild ist später und keine universelle technische Dokumentation.')],
[o('Ordne den vereinfachten Ablauf für eine neue Druckseite.', ['Zeichen zum Text setzen','Form einfärben','Papier anpressen und Abdruck gewinnen'],'Die Form muss vor dem Einfärben und Abdrucken vorbereitet sein.'),o('Wie wird aus einer fertigen Auflage ein anderer Text mit denselben Lettern?', ['Vorhandene Form auseinandernehmen','Zeichen neu zusammensetzen','Neue Form einfärben und abdrucken'],'Die Wiederverwendung betrifft die einzelnen Zeichen, nicht die unveränderte alte Seitenanordnung.')]]),
unit('Warum die Auflage den Stückpreis verändert', 'Einmalige Vorbereitung und Kosten je Exemplar getrennt rechnen.',[
('Die erste Seite ist die teuerste', 'Eine Druckform zu setzen kostet Zeit, bevor ein einziges Exemplar verkauft wird. Dieser Aufwand kann sich auf viele gleiche Exemplare verteilen. Nehmen wir für ein frei erfundenes Lehrmodell 120 Kosteneinheiten Vorbereitung und zwei Einheiten pro Abdruck. Zehn Exemplare kosten zusammen 140, also 14 pro Stück. Hundert kosten 320, also 3,2 pro Stück.\n\nDer Stückpreis fällt, obwohl jeder zusätzliche Abdruck weiterhin etwas kostet. Der einmalige Aufwand wird auf mehr Exemplare verteilt. Diese Rechnung ist eine Erklärung des Mechanismus, keine Preisangabe für eine historische Druckerei.'),
('Billiger herstellen ist nicht dasselbe wie sicher verkaufen', 'Vergleiche eine Abschrift für zehn Kosteneinheiten pro Exemplar. Für eine sehr kleine Menge kann sie günstiger sein, weil die Druckvorbereitung noch stark ins Gewicht fällt. Bei einer grösseren gleichen Auflage kann der Druckvorteil wachsen.\n\nDas gilt nur unter den Annahmen des Beispiels. Papier, Arbeitszeit, Ausschuss und Vertrieb verändern die Rechnung. Vor allem müssen die Exemplare einen Abnehmer finden. Hundert gedruckte Bücher auf Lager sind nicht hundert verkaufte Bücher. Eine neue Technik verschiebt Kosten und Möglichkeiten; sie hebt Nachfrage und Finanzierung nicht auf. So wird aus dem technischen Vorteil eine wirtschaftliche Frage.')],
'Vorbereitung 80 Einheiten, Abdruck zwei pro Exemplar. Was kostet eine Auflage von 40 insgesamt und im Durchschnitt pro Stück?',
'80 + 40 × 2 = 160 Einheiten insgesamt. Geteilt durch 40 sind das vier pro Exemplar. Die Vorbereitung trägt zwei, der Abdruck weitere zwei zum Stückwert bei.',[
[n('Lehrmodell: 90 Einheiten Vorbereitung, drei je Abdruck, 30 Exemplare. Durchschnittliche Kosten pro Stück?',6,'Einheiten','(90 + 30 × 3) / 30 = 6.'),n('Vorbereitung 100 Einheiten, zwei je Abdruck, 50 Exemplare. Durchschnittliche Kosten pro Stück?',4,'Einheiten','(100 + 50 × 2) / 50 = 4.')],
[c('Warum sinkt im Modell bei höherer Auflage der Durchschnittspreis?','Der einmalige Aufwand verteilt sich auf mehr Exemplare.','Die Vorbereitung wird bei jedem neuen Abdruck erneut bezahlt.','Die Kosten jedes zusätzlichen Abdrucks fallen zwangsläufig auf null.','Der fixe Anteil pro Stück sinkt; der variable Aufwand bleibt im Modell bestehen.'),c('Eine Druckerei verdoppelt ihre Auflage ohne zusätzliche Käufer. Was folgt aus niedrigeren Herstellungskosten pro Stück allein nicht?','Dass der Gesamtgewinn steigt.','Dass der Vorbereitungsanteil pro Stück sinkt.','Dass mehr Exemplare hergestellt wurden.','Unverkaufte Ware und höhere Gesamtausgaben können den Vorteil niedrigerer Stückkosten aufheben.')],
[n('Vorbereitung 60, Abdruck zwei je Stück: Wie hoch sind die Gesamtkosten für 20 Exemplare?',100,'Einheiten','60 + 20 × 2 = 100.'),n('Vorbereitung 50, Abdruck drei je Stück: Wie hoch sind die Gesamtkosten für zehn Exemplare?',80,'Einheiten','50 + 10 × 3 = 80.')]]),
unit('Auch ein Fehler wird vervielfältigt', 'Verlässliche Reproduktion von inhaltlicher Richtigkeit trennen.',[
('Gleichheit kann falsch sein', 'Ein Setzer vertauscht zwei Zeichen. Die Druckform liefert nun hundert gleiche Exemplare mit demselben Fehler. Ihre Übereinstimmung ist kein Beweis, dass die Aussage stimmt. Sie zeigt zuerst, dass dieselbe Vorlage zuverlässig vervielfältigt wurde.\n\nDas unterscheidet sich von einem Abschreibfehler, der bei jedem neuen Exemplar an anderer Stelle entstehen kann. Druck kann bestimmte Unterschiede zwischen Exemplaren verringern und gleichzeitig einen Fehler der Vorlage weit verbreiten. Technische Gleichförmigkeit und inhaltliche Richtigkeit sind deshalb zwei getrennte Qualitätsfragen.'),
('Prüfen, bevor der Fehler teuer wird', 'Ein Probeabdruck erlaubt, Text und Anordnung vor einer grossen Auflage zu prüfen. Wird ein Fehler entdeckt, kann die Form korrigiert werden. Bereits gedruckte Exemplare ändern sich dadurch jedoch nicht. Innerhalb einer Auflage können deshalb unterschiedliche Zustände auftreten: frühe Abdrücke vor der Korrektur und spätere danach.\n\nFür eine historische Untersuchung ist so ein Unterschied eine Spur. Er kann etwas über Herstellung und Korrektur verraten, beweist für sich allein aber noch nicht den ganzen Ablauf. Man muss Exemplare vergleichen, Datierungen prüfen und alternative Erklärungen berücksichtigen. Ein Produktionsfehler wird so manchmal zu einer Quelle über die Produktion selbst.')],
'Eine Form wird nach dem 40. Abdruck korrigiert. Danach entstehen 60 weitere Exemplare. Welche beiden Gruppen erwartest du unter den 100, wenn keine anderen Änderungen erfolgen?',
'40 Exemplare enthalten den ursprünglichen Fehler, 60 die korrigierte Fassung. Ein später gefundenes fehlerfreies Exemplar beweist also nicht, dass nie eine fehlerhafte Fassung existierte.',[
[n('Nach 25 von insgesamt 100 Abdrücken wird ein Fehler korrigiert. Wie viele Exemplare tragen danach die korrigierte Fassung?',75,'Exemplare','100 − 25 = 75, unter den genannten Annahmen.'),n('Eine Form wird nach 60 Abdrücken korrigiert; es entstehen insgesamt 180. Wie viele frühe fehlerhafte Exemplare gibt es?',60,'Exemplare','Die Änderung betrifft erst spätere Abdrücke; die ersten 60 bleiben unverändert.')],
[c('Hundert Bücher enthalten denselben sachlichen Irrtum. Welche Eigenschaft ist dadurch belegt?','Übereinstimmung dieses Inhalts in den verglichenen Exemplaren','Richtigkeit des Inhalts durch viele Bestätigungen','Unabhängige Entstehung der hundert Aussagen','Gemeinsame Reproduktion ist nicht mit hundert unabhängigen Belegen gleichzusetzen.'),c('Zwei Exemplare derselben Auflage unterscheiden sich an einem Zeichen. Welche Erklärung ist mit dem Kapitel vereinbar?','Die Form wurde während der Herstellung korrigiert.','Die Drucktechnik musste für jedes Exemplar vollständig neu erfunden werden.','Die Übereinstimmung aller anderen Zeichen beweist unterschiedliche Autoren.','Eine Korrektur während der Produktion kann unterschiedliche Zustände erzeugen; weitere Prüfung bleibt nötig.')],
[m('Welche Prüfung beantwortet welche Frage?', [('Vergleich zweier Abdrücke','Sind sie an der Stelle gleich?'),('Vergleich der Aussage mit unabhängigen Belegen','Ist der Inhalt sachlich gestützt?'),('Prüfung eines Probeabdrucks','Ist vor der Auflage eine Korrektur nötig?')],'Produktion, Vergleich und inhaltliche Prüfung sind verschiedene Aufgaben.'),m('Ordne die Fehlerquelle zu.', [('Falsches Zeichen in der Druckform','Gemeinsamer Vorlagenfehler'),('Neue Verwechslung beim einzelnen Abschreiben','Individueller Kopierfehler'),('Korrektur nach einem Teil der Auflage','Unterschiedliche Druckzustände')],'Der Ort des Fehlers bestimmt, wie er sich auf Exemplare verteilen kann.')]]),
unit('Warum ein gedrucktes Buch Handarbeit enthält', 'Eine neue Technik als Teil einer Produktionskette verstehen.',[
('Die rote Initiale ist kein Widerspruch', 'Eine frühe gedruckte Seite kann handgemalte Initialen, farbige Überschriften oder andere Ergänzungen enthalten. Daraus folgt nicht, dass sie eigentlich gar nicht gedruckt sei. Der Druck vervielfältigt bestimmte Bestandteile; Gestaltung, Bindung und weitere Arbeiten können daneben von Hand erfolgen.\n\nFrühe Druckwerke orientieren sich zudem an vertrauten Buchformen. Wer eine neue Technik nutzt, muss nicht sofort jede ästhetische Gewohnheit aufgeben. Die Gutenberg-Bibel zeigt, wie technische Neuerung und bestehende Buchkultur verbunden sein können. Die Abbildung ist daher interessant gerade dort, wo sie nicht nach einer modernen standardisierten Ware aussieht.'),
('Der langsamste Schritt bleibt wichtig', 'Stelle dir einen Lehrbetrieb vor: Der Druck schafft 100 Seitenpakete pro Tag, die anschliessende Handbearbeitung nur 40. Auf Dauer können ohne weitere Änderungen nicht täglich 100 vollständig bearbeitete Pakete fertig werden. Zwischen den Arbeitsschritten entsteht ein wachsender Stapel.\n\nEine beschleunigte Teilaufgabe ist also nicht automatisch eine gleich grosse Beschleunigung des Gesamtablaufs. Suche den Engpass: Welche notwendige Stufe hat die geringste nachhaltige Kapazität? Das ist ein allgemeines Denkwerkzeug für Produktionsketten. Die Lehrzahlen beschreiben keine bestimmte historische Werkstatt; sie machen sichtbar, warum ein Buch mehr als der Moment unter der Presse ist.')],
'Druck: 80 Pakete pro Tag. Nachbearbeitung: 30. Anfangs gibt es keinen Vorrat. Wie viele gedruckte, aber noch nicht nachbearbeitete Pakete kommen an einem vollen Arbeitstag hinzu?',
'80 − 30 = 50 Pakete. Bei unveränderten Kapazitäten wächst der Rückstand weiter. Mehr Druckleistung allein löst diesen Engpass nicht.',[
[n('Pro Tag werden 90 Pakete gedruckt und 50 fertig nachbearbeitet. Um wie viele Pakete wächst der Zwischenbestand täglich?',40,'Pakete','90 − 50 = 40, solange beide Stufen so arbeiten.'),n('Druckleistung 70, Bindekapazität 45 Pakete pro Tag. Wie gross ist der maximale dauerhafte tägliche Enddurchsatz ohne Vorratsabbau?',45,'Pakete','Die notwendige langsamere Stufe begrenzt den nachhaltigen Enddurchsatz.')],
[c('Eine gedruckte Seite besitzt handgemalte Initialen. Welche Aussage ist am besten begründet?','Die Herstellung kombinierte verschiedene Arbeitsverfahren.','Die ganze Seite wurde ohne Druck hergestellt.','Die Initialen beweisen eine Herstellung vor der Erfindung des Drucks.','Gedruckter Text und spätere Handgestaltung können zum selben Werk gehören.'),c('Der Druck wird doppelt so schnell, die langsamere Bindung bleibt gleich. Was erwartest du ohne andere Änderungen langfristig?','Mehr Zwischenbestand statt entsprechend mehr fertiger Bücher','Eine Verdopplung der fertigen Bücher durch den schnelleren Druck','Eine Halbierung der notwendigen Bindearbeit pro Buch','Eine unveränderte notwendige Engpassstufe begrenzt den dauerhaften Gesamtdurchsatz.')],
[m('Welche Rolle hat der Arbeitsschritt?', [('Zeichen zur Form setzen','Vorbereitung der Vervielfältigung'),('Text auf Papier drucken','Wiederholter Abdruck'),('Gedruckte Bogen binden','Fertigstellung des Buches')],'Ein Buch entsteht aus einer Kette, nicht aus einem einzelnen Maschinenschritt.'),m('Ordne die Beobachtung ein.', [('Handfarbe auf gedrucktem Text','Kombination von Verfahren'),('Stapel vor langsamer Nachbearbeitung','Zwischenbestand am Engpass'),('Mehr Presseleistung ohne mehr Buchausgabe','Teiloptimierung ohne gleichen Gesamteffekt')],'Die gesamte Kette erklärt Erscheinungsbild und Leistung.')]]),
unit('Eine Möglichkeit ist noch keine gesellschaftliche Wirkung', 'Technik, Verbreitung und Folgen kausal auseinanderhalten.',[
('Warum mehr Exemplare nicht automatisch mehr Leser sind', 'Eine Druckwerkstatt kann einen Text in grösserer Zahl herstellen. Damit er gelesen wird, braucht es jedoch Leser, Finanzierung, Vertrieb und Zugang. Sprache, Preis, Bildung und politische Kontrolle können die Reichweite begrenzen. Die technische Möglichkeit und die tatsächliche Verbreitung sind deshalb zwei verschiedene Stufen.\n\nAuch eine verbreitete Schrift bewirkt nicht bei allen Lesern dasselbe. Menschen wählen aus, verstehen unterschiedlich, widersprechen oder verwenden einen Text für andere Zwecke. «Buchdruck führte zu Wirkung X» ist als Kurzform oft zu grob. Interessanter ist der nachvollziehbare Weg von veränderten Herstellungskosten zu konkreten Formen der Nutzung.'),
('Eine Erklärung mit Zwischenschritten', 'Formuliere die Kette: Wiederholbare Herstellung kann gleiche Exemplare günstiger und zahlreicher machen. Das kann unter passenden Bedingungen ihre Verbreitung erleichtern. Verbreitung ermöglicht bestimmte Formen gemeinsamer Diskussion. Welche Wirkung tatsächlich entsteht, muss an historischen Belegen geprüft werden.\n\nDie vorsichtigen Wörter schwächen die Erklärung nicht, sondern benennen ihre Bedingungen. Sie verhindern, dass man einer Technik allein zuschreibt, was von vielen Menschen, Institutionen und Konflikten mitgestaltet wurde. Das gilt auch beim Vergleich mit digitalen Medien: Eine Ähnlichkeit im Mechanismus ist nützlich, aber kein Beweis für identische historische Folgen.')],
'Ein Flugblatt wird billig gedruckt, aber fast alle Exemplare bleiben im Lager. Welche Stufe der Wirkungskette ist erreicht, welche noch nicht belegt?',
'Die Herstellung wurde erleichtert. Breite Verbreitung und tatsächliche Lektüre sind damit noch nicht belegt. Eine gesellschaftliche Wirkung lässt sich erst recht nicht aus der Auflagenzahl allein ableiten.',[
[m('Ordne die Belege ihrer Ebene zu.', [('Rechnung über 1’000 gedruckte Exemplare','Herstellung'),('Nachweise über Lieferungen in mehrere Städte','Verbreitung'),('Briefe, die sich mit dem Text auseinandersetzen','Dokumentierte Rezeption')],'Ein Beleg für Herstellung ist noch kein unmittelbarer Beleg für Lektüre oder Wirkung.'),m('Welcher Zusatzschritt fehlt?', [('Gedruckt, aber noch nicht ausgeliefert','Zugang zum Publikum'),('Ausgeliefert, aber Lektüre unbekannt','Beleg tatsächlicher Nutzung'),('Gelesen, aber politische Folge behauptet','Begründete Verbindung zur Folge')],'Eine Kausalerklärung muss ihre Zwischenschritte belegen.')],
[c('Welche Formulierung erklärt den Druckmechanismus am präzisesten?','Er veränderte Möglichkeiten der Vervielfältigung; ihre Wirkung hing von weiteren Bedingungen ab.','Er erzeugte aus jeder höheren Auflage unmittelbar dieselbe gesellschaftliche Veränderung.','Er wirkte gesellschaftlich nur dann, wenn alle Leser denselben Schluss zogen.','Technische Möglichkeiten, Verbreitung und Reaktionen sind kausal verbunden, aber nicht identisch.'),c('Welche Beobachtung ergänzt eine reine Auflagenzahl am direktesten um einen Beleg für Nutzung?','Ein zeitgenössischer Brief diskutiert Aussagen des Textes.','Eine Werkstatt bestellt Papier für weitere Exemplare.','Ein Drucker erhöht die Kapazität seiner Presse.','Der Brief dokumentiert Auseinandersetzung; Papierbestellung und Kapazität betreffen zunächst die Produktion.')],
[o('Ordne die vereinfachte Wirkungskette.', ['Text wird vervielfältigt','Exemplare erreichen Leser','Leser setzen sich mit dem Inhalt auseinander'],'Die Kette beschreibt Bedingungen, keine automatisch garantierte Wirkung.'),o('Ordne eine sorgfältige historische Untersuchung.', ['Konkrete behauptete Wirkung benennen','Belege für Verbreitung und Nutzung suchen','Prüfen, ob die Belege den behaupteten Zusammenhang tragen'],'Eine gute Geschichte ersetzt nicht die Prüfung ihrer Verbindungsglieder.')]])
])
