from deep_authoring import course, unit, choice as c, matching as m, recall as r

COURSE=course('philosophy','stoic','Epiktet: handeln, ohne alles zu beherrschen',
 'Ein abgelehnter Vorschlag, ein unhöflicher Mensch, ein missglückter Plan: Was verlangt Gelassenheit tatsächlich von dir?',
 ('Epiktet · Enchiridion, besonders Abschnitte 1, 4, 5 und 17', 'https://classics.mit.edu/Epictetus/epicench.html'),[
unit('Einfluss ist nicht Verfügung', 'Eigenes Handeln und äusseres Ergebnis trennen.',[
('Dein Vorschlag wird abgelehnt', 'Du bereitest eine Präsentation sorgfältig vor. Die Leitung entscheidet sich trotzdem gegen deinen Vorschlag. «Dann war die Vorbereitung sinnlos», sagst du. Epiktets Unterscheidung setzt früher an: Was lag in deiner eigenen Entscheidung, und welches Ergebnis hing auch von anderen ab?\n\nDu konntest prüfen, begründen und auf Rückfragen eingehen. Du konntest die Zustimmung der Leitung beeinflussen, aber nicht allein festlegen. Im Enchiridion trennt Epiktet das eigene Urteilen und Wollen von äusseren Dingen wie Ansehen oder Besitz. Das ist strenger als die heutige Einteilung «Was kann ich irgendwie beeinflussen?» Einfluss kann gross sein, ohne Verfügung zu werden.'),
('Warum diese Trennung Handlung ermöglicht', 'Der Gedanke fordert nicht, auf Ergebnisse zu verzichten. Eine Ärztin behandelt, ein Sportler trainiert, eine Unternehmerin verhandelt. Doch ein Ergebnis, das von vielen Bedingungen abhängt, eignet sich schlecht als einziger Massstab für die Qualität des eigenen Handelns.\n\nPrüfe beides getrennt: War meine Entscheidung angesichts des verfügbaren Wissens vernünftig? Und welche Wirkung trat ein? So kannst du aus einem schlechten Ergebnis lernen, ohne es automatisch als persönliches Versagen zu deuten. Umgekehrt macht ein glücklicher Ausgang einen leichtfertigen Entschluss nicht rückwirkend klug. Das ist eine philosophische Perspektive auf Verantwortung, keine Garantie emotionaler Unberührbarkeit.')],
'Zwei Bewerber bereiten sich gleich sorgfältig vor. Nur einer bekommt die Stelle. Welche Bewertung ihrer Vorbereitung ist aus dem Ergebnis allein möglich?',
'Die unterschiedliche Auswahl beweist nicht, dass nur einer vernünftig gehandelt hat. Das Ergebnis hängt auch von Konkurrenz, Anforderungen und Entscheidung der anderen Seite ab. Die konkrete Vorbereitung muss gesondert beurteilt werden.',[
[m('Ordne nach der im Kapitel beschriebenen Unterscheidung.',[('Eigene Argumente vor dem Gespräch prüfen','Eigener Handlungsschritt'),('Zustimmung des Gegenübers','Äusseres Ergebnis'),('Die eigene Begründung nach Kritik überarbeiten','Eigene Reaktion')],'Beeinflussen zu können bedeutet nicht, allein über die Zustimmung zu verfügen.'),m('Welche Ebene ist beschrieben?', [('Sorgfältige Vorbereitung','Handlungsqualität'),('Erteilte Zusage','Ergebnis'),('Entscheidung der Konkurrenz','Weitere äussere Bedingung')],'Handlung und Ergebnis sind verbunden, aber nicht identisch.')],
[c('Was folgt aus Epiktets Unterscheidung für einen Vortrag?','Die eigene Vorbereitung prüfen, ohne Zustimmung als alleinigen Massstab zu setzen.','Die Zustimmung als Massstab setzen, weil Vorbereitung sie beeinflussen kann.','Den Vortrag vermeiden, sobald die Zustimmung nicht gesichert ist.','Einfluss auf Zustimmung ist noch keine Verfügung darüber; trotzdem bleibt Vorbereitung sinnvoll.'),c('Eine riskante Entscheidung ohne Prüfung geht gut aus. Welche Bewertung passt zum Kapitel?','Das Ergebnis allein belegt keine gute Entscheidungsqualität.','Der gute Ausgang bestätigt die Qualität der ursprünglichen Prüfung.','Der Erfolg zeigt, dass die Entscheidung vollständig in eigener Verfügung lag.','Ein glücklicher Ausgang kann auch bei schlechter Vorbereitung entstehen.')],
[r('Welches Wort fehlt in der Unterscheidung «Einfluss ist nicht …»?',['Verfügung','Verfuegung'],'Ein Ergebnis beeinflussen und es allein festlegen sind verschiedene Möglichkeiten.'),r('Wie nennt das Kapitel die Ebene von Zusage oder Ablehnung im Gegensatz zum eigenen Handlungsschritt?',['Ergebnis','äusseres Ergebnis','aeusseres Ergebnis'],'Die Zusage ist ein Ergebnis, das zusätzlich von anderen Bedingungen abhängt.')]]),
unit('Zwischen Ereignis und Urteil', 'Eine Beobachtung von ihrer zusätzlichen Deutung unterscheiden.',[
('Die unbeantwortete Nachricht', 'Du schickst jemandem einen Entwurf. Zwei Stunden später ist noch keine Antwort da. Die beobachtbare Information lautet zunächst: Es liegt keine Antwort vor. «Mein Entwurf ist ihm egal» ist bereits eine Deutung. Sie kann zutreffen, muss es aber nicht. Vielleicht ist die Person in einer Sitzung oder hat den Entwurf noch nicht geprüft.\n\nEpiktet betont in Abschnitt 5 die Rolle unserer Urteile beim Erleben von Ereignissen. Das bedeutet nicht, dass Verletzungen oder Belastungen unwirklich wären. Es fordert dazu auf, den zusätzlichen Satz zu erkennen, den wir einem Ereignis geben. Gerade dieser Satz kann überprüfbar oder vorschnell sein.'),
('Urteile prüfen statt Gefühle verbieten', 'Eine praktische Unterbrechung besteht aus drei Fragen: Was weiss ich tatsächlich? Welche Deutung füge ich hinzu? Welche andere Erklärung passt ebenfalls zu den vorhandenen Informationen? Anschliessend entscheidest du, welche Nachfrage oder Handlung angebracht ist.\n\nEs wäre selbst ein voreiliges Urteil, jede negative Deutung durch eine positive Gewissheit zu ersetzen: «Er antwortet nicht, also findet er den Entwurf bestimmt grossartig.» Die Alternative zu einem unbelegten negativen Schluss ist zunächst Offenheit, nicht ein unbelegter positiver Schluss. Diese Offenheit kann unangenehm bleiben. Das Kapitel verlangt keine bestimmte Gefühlslage als Beweis philosophischer Reife.')],
'«Im Meeting hat sie meinen Punkt nicht aufgegriffen; sie respektiert mich nicht.» Trenne den berichteten Vorgang und den Schluss. Welche Information könnte den Schluss prüfen?',
'Vorgang: Der Punkt wurde nicht aufgegriffen. Schluss: fehlender Respekt. Eine konkrete Nachfrage nach dem Grund oder weitere vergleichbare Beobachtungen wären aussagekräftiger als der einzelne Vorgang allein.',[
[m('Ordne Beobachtung und zusätzliche Deutung.', [('Seit zwei Stunden keine Antwort','Berichteter Vorgang'),('Mein Anliegen ist unwichtig für ihn','Interpretation'),('Ich frage nach einem passenden Zeitpunkt','Möglicher nächster Schritt')],'Der Schritt zur Interpretation ist der Punkt, an dem die Prüfung ansetzt.'),m('Welche Funktion hat der Satz?', [('Die Besprechung wurde abgesagt','Beobachtung'),('Man will mich ausschliessen','Zusätzliche Deutung'),('Vielleicht kollidieren zwei Termine','Alternative Erklärung')],'Eine Alternative widerlegt die erste Deutung nicht, zeigt aber ihre Unsicherheit.')],
[c('Welche Reaktion prüft das eigene Urteil am saubersten?','Die ausbleibende Antwort feststellen und nach dem Stand fragen.','Die ausbleibende Antwort als Zustimmung bewerten und danach handeln.','Die ausbleibende Antwort als Ablehnung bewerten und danach handeln.','Die Nachfrage beschafft Information, bevor einer ungesicherten Deutung gefolgt wird.'),c('Was ist am Schluss «Keine Kritik bedeutet, dass mein Entwurf hervorragend ist» problematisch?','Auch die positive Deutung geht über die Information hinaus.','Positive Deutungen sind nach Epiktet grundsätzlich unzulässig.','Schweigen gehört vollständig zur eigenen Entscheidung.','Das Problem ist die fehlende Begründung, nicht die positive Stimmung der Aussage.')],
[r('Wie nennt das Kapitel den zusätzlichen Sinn, den wir einem beobachteten Ereignis geben?',['Deutung','Interpretation','Urteil'],'Eine Deutung ist von der zugrunde liegenden Beobachtung zu trennen.'),r('Gesucht ist ein Begriff: Ein zweiter möglicher Grund für dasselbe Ereignis ist eine alternative …',['Erklärung','Erklaerung','Deutung','Interpretation'],'Eine alternative Erklärung verhindert vorschnelle Gewissheit, ohne selbst schon bewiesen zu sein.')]]),
unit('Die Badeanstalt als Vorbereitung auf Störungen', 'Realistische Vorbereitung von Resignation unterscheiden.',[
('Ein erstaunlich alltäglicher antiker Rat', 'In Abschnitt 4 des Enchiridions beschreibt Epiktet den Besuch eines Bades. Dort können Menschen spritzen, drängeln oder sich unhöflich verhalten. Wer nur das Ziel «angenehm baden» mitnimmt, behandelt jede Störung wie einen Bruch des gesamten Plans. Epiktet ergänzt ein zweites Ziel: sich bei solchen Umständen vernünftig zu verhalten.\n\nDie Vorbereitung besteht nicht darin, jeden Mitmenschen für feindselig zu erklären. Sie rechnet mit bekannten Reibungen einer Tätigkeit. Für ein heutiges Meeting könnten das technische Probleme, Einwände oder eine verkürzte Redezeit sein. Diese Übertragung ist unser Gedankenfall, keine Behauptung über antike Besprechungen.'),
('Ein Vorbehalt verändert den Plan', 'Vergleiche zwei Vorsätze. «Ich werde alle überzeugen» hängt stark von anderen ab. «Ich werde meinen Punkt verständlich begründen und bei Einwänden prüfen, was ich übersehen habe» benennt ein eigenes Vorgehen. Das Ergebnis bleibt erwünscht, aber es wird nicht zur zugesicherten Weltordnung.\n\nRealistische Vorbereitung führt zu Handlungsmöglichkeiten: Ersatzunterlagen, eine kurze Kernbotschaft, eine vernünftige Rückfrage. Resignation würde dagegen sagen: Weil es Störungen geben kann, lohnt sich der Versuch nicht. Beide rechnen mit Schwierigkeiten, ziehen aber entgegengesetzte Konsequenzen. Gerade die vorbereitete Person kann unter unperfekten Umständen beweglich bleiben.')],
'Eine Präsentation wird von 20 auf fünf Minuten gekürzt. Welcher vorab formulierte zweite Vorsatz hilft, das ursprüngliche Ziel nicht einfach aufzugeben?',
'Zum Beispiel: «Ich werde die zentrale Entscheidung auch in kurzer Form verständlich machen.» Das Ergebnis bleibt offen, aber eine konkrete eigene Handlung bleibt möglich. Bloss auf garantiert gute Bedingungen zu hoffen wäre keine Vorbereitung.',[
[m('Welche Haltung steckt im Vorsatz?', [('Auch bei Einwänden nachvollziehbar begründen','Vorbereitete eigene Handlung'),('Nur präsentieren, wenn niemand widerspricht','Ergebnisbedingung'),('Bei möglichen Einwänden gar nicht beginnen','Resignation')],'Vorbereitung bewahrt Handlungsspielraum, statt ideale Bedingungen zu verlangen.'),m('Was wird jeweils ergänzt?', [('Ersatzunterlagen bereithalten','Praktische Vorbereitung'),('Mit einer kritischen Frage rechnen','Realistische Erwartung'),('Auf Kritik sachlich eingehen wollen','Eigener Verhaltensvorsatz')],'Die drei Elemente unterstützen sich, ersetzen aber nicht gegenseitig ihre Funktion.')],
[c('Was ist der Kern des Bade-Beispiels?','Die Tätigkeit mit einem Vorsatz für den Umgang mit erwartbaren Störungen verbinden.','Die Tätigkeit nur unter vorher kontrollierten störungsfreien Bedingungen durchführen.','Die störenden Menschen zuerst ändern, damit der eigene Vorsatz funktionieren kann.','Epiktet ergänzt das äussere Ziel um einen eigenen Verhaltensmassstab.'),c('Welcher Satz ist Vorbereitung und nicht Resignation?','Wenn die Technik ausfällt, erkläre ich den Kerngedanken anhand meiner Notizen.','Wenn die Technik ausfallen könnte, lasse ich den Vortrag ganz bleiben.','Wenn die Technik ausfällt, war eine sinnvolle Vorbereitung unmöglich.','Der erste Satz erhält eine konkrete Handlung trotz eines möglichen Hindernisses.')],
[r('Welchen alltäglichen Ort verwendet Epiktet in dem hier besprochenen Abschnitt als Beispiel?',['Bad','Badeanstalt','Badehaus'],'Das Bade-Beispiel verbindet eine Tätigkeit mit der Vorbereitung auf typische Störungen.'),r('Welche Haltung gibt den Versuch wegen möglicher Schwierigkeiten bereits auf?',['Resignation','Resignieren'],'Resignation unterscheidet sich von einer Vorbereitung, die Handlungsmöglichkeiten sucht.')]]),
unit('Akzeptieren heisst nicht zustimmen', 'Eine Tatsache anerkennen und trotzdem begründet widersprechen.',[
('Die Entscheidung steht – was nun?', 'Eine Führungskraft verteilt Aufgaben unfair. «Das liegt ausserhalb deiner Verfügung», sagt ein Kollege. «Also solltest du es hinnehmen.» Der erste Satz begründet den zweiten nicht. Du kannst anerkennen, dass die Verteilung bereits beschlossen wurde, und dennoch Widerspruch einlegen, Belege sammeln oder ein Gespräch suchen.\n\nAkzeptieren bedeutet hier zunächst, die gegenwärtige Tatsache nicht mit dem gewünschten Zustand zu verwechseln. Zustimmung wäre ein zusätzliches Werturteil: die Verteilung sei gerecht. Diese beiden Ebenen auseinanderzuhalten verhindert, dass Gelassenheit als höfliches Wort für Untätigkeit verwendet wird.'),
('Verantwortung bleibt konkret', 'Epiktet denkt auch über Rollen und Pflichten nach. Die moderne Anwendung darf daraus keine Pauschalregel machen, sich jeder Hierarchie zu fügen. Eine Rolle kann gerade verlangen, sorgfältig zu widersprechen oder für andere einzustehen. Welche Pflicht im konkreten Konflikt vorrangig ist, braucht zusätzliche ethische Begründung.\n\nDer hier gelernte Prüfrahmen ist bescheidener: Was ist bereits geschehen? Was bewerte ich daran? Welche begründete Handlung ist jetzt möglich? Er löst nicht jede moralische Streitfrage. Er verhindert aber einen Denkfehler: fehlende Kontrolle über den Ausgang mit fehlender Verantwortung für den eigenen Beitrag zu verwechseln.')],
'Du kannst nicht garantieren, dass eine Beschwerde Erfolg hat. Folgt daraus, dass sie unnötig ist? Begründe mit den drei Ebenen Tatsache, Urteil und Handlung.',
'Nein. Tatsache ist der unsichere Ausgang. Das Urteil kann weiterhin lauten, dass die Situation ungerecht ist. Eine sachlich begründete Beschwerde bleibt eine mögliche verantwortliche Handlung, auch ohne Erfolgsgarantie.',[
[m('Trenne die drei Ebenen.', [('Die Verteilung wurde beschlossen','Tatsache'),('Die Verteilung ist unfair','Bewertung'),('Ich lege begründeten Widerspruch ein','Handlung')],'Anerkennen einer Tatsache ist noch keine Zustimmung zur Bewertung oder Verzicht auf Handlung.'),m('Welche Verwechslung liegt nahe?', [('Ich kontrolliere den Ausgang nicht, also habe ich keine Aufgabe','Verfügung mit Verantwortung verwechselt'),('Es ist geschehen, also ist es gerecht','Tatsache mit Werturteil verwechselt'),('Ich widerspreche, also werde ich gewinnen','Handlung mit Erfolgsgarantie verwechselt')],'Die Unterscheidungen begrenzen drei verschiedene vorschnelle Schlüsse.')],
[c('Welche Folgerung ist mit dem Kapitel vereinbar?','Ich erkenne den Beschluss an und prüfe begründete Möglichkeiten des Widerspruchs.','Ich erkenne den Beschluss an und muss ihn deshalb als gerecht bewerten.','Ich bewerte den Beschluss als ungerecht und kann deshalb seine Änderung garantieren.','Tatsache, moralisches Urteil und eigener Beitrag bleiben getrennt.'),c('Was leistet der gelernte Rahmen bei einem Pflichtenkonflikt?','Er klärt Ebenen, entscheidet aber nicht jede moralische Frage allein.','Er bestimmt aus dem Kontrollierbaren bereits die einzig gerechte Handlung.','Er hebt Pflichten auf, sobald andere über das Ergebnis entscheiden.','Für die Bewertung konkreter Pflichten braucht man weitere ethische Argumente.')],
[r('Wie heisst im Kapitel das positive Werturteil zu einer Entscheidung, das von ihrer blossen Anerkennung getrennt wird?',['Zustimmung'],'Eine Tatsache anzuerkennen heisst nicht, ihr zuzustimmen.'),r('Welcher Begriff bezeichnet die Verpflichtung zum eigenen begründeten Beitrag trotz unsicheren Ausgangs?',['Verantwortung'],'Unsicherheit über den Ausgang beseitigt die Verantwortung für den eigenen Beitrag nicht.')]]),
unit('Das Ergebnis als Lernstoff, nicht als Richter', 'Den ganzen Prüfrahmen an einem neuen Fall anwenden.',[
('Nach einer verlorenen Verhandlung', 'Du hast gründlich recherchiert, respektvoll verhandelt und eine unrealistische Forderung abgelehnt. Der Auftrag geht an jemand anderen. Drei Reaktionen sind möglich. «Ich habe verloren, also war jede Entscheidung falsch.» «Mein Vorgehen war vernünftig, also gibt es nichts zu lernen.» Oder: «Ich trenne die Qualität meiner damaligen Gründe vom Ergebnis und prüfe beides.»\n\nNur die dritte Reaktion hält die Untersuchung offen. Vielleicht war der Preis nicht passend. Vielleicht hatte der Kunde andere Bedürfnisse. Vielleicht war die Ablehnung vernünftig. Der Ausgang ist Information, aber er liefert nicht von allein die vollständige Erklärung.'),
('Eine kurze Prüfung, die sich wiederholen lässt', 'Schreibe nach einem wichtigen Vorgang vier Sätze: Was ist beobachtbar geschehen? Welches Urteil fälle ich darüber? Welche meiner Entscheidungen kann ich mit dem damaligen Wissen begründen? Was werde ich beim nächsten Versuch anders prüfen oder tun?\n\nDarin liegt weder Selbstfreispruch noch Selbstanklage. Du übernimmst Verantwortung für überprüfbare Entscheidungen, statt dich vollständig mit einem Ergebnis gleichzusetzen. Der Massstab ist nicht, nie enttäuscht zu sein. Enttäuschung und vernünftige Prüfung können gleichzeitig vorkommen. Philosophie wird hier zu einer wiederholbaren Denkhandlung, nicht zu einem dekorativen Satz über Gelassenheit.')],
'Eine sorgfältige Entscheidung scheitert wegen einer nicht vorhersehbaren Störung. Eine schlecht geprüfte Entscheidung gelingt durch Glück. Welche Entscheidung war besser begründet, und welche hatte das bessere Ergebnis?',
'Die erste war nach den Angaben besser begründet; die zweite hatte das bessere Ergebnis. Das sind zwei Bewertungen. Künftige Verbesserungen richten sich nach Gründen und überprüfbaren Abläufen, nicht nur nach Sieg oder Niederlage.',[
[m('Welcher Schritt gehört zur Rückschau?', [('Verhandlung endete ohne Auftrag','Beobachtung festhalten'),('Ich deute das als völliges Versagen','Zusätzliches Urteil erkennen'),('Beim nächsten Mal Zahlungsbedingungen früher klären','Eigenen Prozess verbessern')],'Der Rahmen führt von Beobachtung über Urteil zu einer beeinflussbaren Verbesserung.'),m('Welche Bewertung ist jeweils möglich?', [('Gute Gründe, ungünstiger Ausgang','Vernünftige Entscheidung kann scheitern'),('Schlechte Gründe, günstiger Ausgang','Erfolg kann auf Glück beruhen'),('Ungünstiger Ausgang ohne bekannte Gründe','Entscheidungsqualität noch offen')],'Eine reine Ergebnisbetrachtung kann die Qualität der Entscheidung nicht sicher rekonstruieren.')],
[c('Welche Nachfrage passt nach einer verlorenen Verhandlung am besten zum gelernten Rahmen?','Welche Annahme meines Vorgehens wurde durch die Rückmeldung fraglich?','Wie beweise ich aus dem Verlust, dass Vorbereitung generell nicht wirkt?','Wie beweise ich aus meiner Vorbereitung, dass die andere Seite falsch lag?','Die konkrete Annahme ist prüfbar; beide anderen Schlüsse machen aus einem Teilaspekt ein Gesamturteil.'),c('Was ist eine Grenze des stoischen Prüfrahmens?','Er garantiert weder Erfolg noch das Verschwinden unangenehmer Gefühle.','Er verbietet das Interesse am Ergebnis einer Handlung.','Er setzt gute Absichten mit einer guten Sachprüfung gleich.','Der Rahmen ordnet Verantwortung und Urteile; Ergebnisse und Gefühle werden dadurch nicht vollständig verfügbar.')],
[r('Welcher Begriff bezeichnet den nach aussen eingetretenen Ausgang, den du von der Entscheidungsqualität trennst?',['Ergebnis','Ausgang'],'Das Ergebnis ist relevante Information, aber nicht der einzige Massstab.'),r('Welche Ebene ergänzt «Was ist geschehen?» mit einem Sinn wie «Damit bin ich gescheitert»?',['Urteil','Deutung','Interpretation'],'Gerade dieses zusätzliche Urteil kann geprüft und revidiert werden.')]])
])
