from deep_authoring import course, unit, choice as c, matching as m, recall as r, ordering as o

COURSE=course('learn','recall','Wissen, das ohne Vorlage wiederkommt',
 'Warum fühlt sich Lesen oft erfolgreicher an, als es ist? Du lernst, dein Verständnis zu prüfen und Lücken gezielt zu schliessen.',
 ('Roediger & Karpicke · Test-enhanced learning, 2006', 'https://pubmed.ncbi.nlm.nih.gov/16507066/'),[
unit('Die vertraute Seite ist noch keine Antwort', 'Wiedererkennen und freien Abruf unterscheiden.',[
('Das kenne ich doch', 'Du liest eine Erklärung zum Treibhauseffekt zum dritten Mal. Jeder Satz kommt dir bekannt vor. Als jemand fragt, weshalb eine unveränderte Sonne trotzdem zu einer wärmeren Erde passen kann, stockst du. Die Seite war vertraut; der Zusammenhang war ohne sie noch nicht gut abrufbar.\n\nWiedererkennen bedeutet, dass dir etwas mit der passenden Vorlage bekannt vorkommt. Abrufen bedeutet, es aus dem Gedächtnis selbst hervorzubringen. Beides hat seinen Platz. Die Verwechslung entsteht, wenn die Leichtigkeit des Wiedererkennens als Beweis für selbstständiges Erklären gilt.'),
('Eine kleine Veränderung des Lernens', 'Lies zunächst aufmerksam genug, um den Gedankengang zu verstehen. Lege die Erklärung dann kurz weg und versuche, die zentrale Frage ohne Vorlage zu beantworten. Prüfe erst danach, was fehlt. Damit wird die Lücke sichtbar, die wiederholtes Lesen unter Umständen verdeckt.\n\nEin misslungener Abruf ist nicht automatisch verlorene Zeit. Er zeigt genauer, was noch nicht verfügbar ist. Das heisst nicht, dass blindes Raten ohne Grundlage jede Erklärung ersetzt. Gerade am Anfang brauchst du verständlichen Stoff und anschliessend eine Rückmeldung. Die Aufgabe des Tests ist hier nicht, dich zu überführen, sondern deine nächste Lernhandlung präziser zu machen.')],
'Du kannst aus vier Sätzen den vertrauten auswählen, aber den Mechanismus nicht selbst erklären. Welcher Teil deiner Leistung ist gezeigt, welcher noch nicht?',
'Das Wiedererkennen in dieser Auswahl ist gezeigt. Der selbstständige Abruf und die Erklärung des Zusammenhangs sind damit noch nicht bewiesen.',[
[m('Ordne die Tätigkeit zu.',[('Vertrauten Satz unter vier Sätzen erkennen','Wiedererkennen'),('Ohne Vorlage den Mechanismus erklären','Abrufen'),('Eigene Antwort mit der Erklärung vergleichen','Rückmeldung nutzen')],'Die Tätigkeiten erzeugen unterschiedliche Informationen über den Lernstand.'),m('Was ist dadurch unmittelbar gezeigt?', [('Ich finde den bekannten Absatz schnell','Vertrautheit mit der Vorlage'),('Ich erkläre den Zusammenhang ohne Text','Selbstständiger Abruf in dieser Situation'),('Ich entdecke einen fehlenden Zwischenschritt','Sichtbare Wissenslücke')],'Keines dieser Zeichen ist automatisch dasselbe wie die anderen.')],
[c('Welche Prüfung zeigt besser, ob du den Zusammenhang ohne den Text hervorbringen kannst?','Den Mechanismus bei geschlossenem Text erklären','Den Absatz erneut lesen und seine Vertrautheit bewerten','Die Stelle suchen, an der der Fachbegriff steht','Nur die erste Tätigkeit verlangt hier das Hervorbringen ohne sichtbare Vorlage.'),c('Was folgt aus einem misslungenen Abruf nach dem ersten Lesen am ehesten?','Die konkrete Lücke kann als nächster Lernschritt bearbeitet werden.','Die gesamte vorangegangene Erklärung war zwangsläufig nutzlos.','Noch häufigeres Wiedererkennen beweist bereits, dass die Lücke geschlossen ist.','Der Fehler liefert Information, muss aber mit Erklärung und erneuter Prüfung bearbeitet werden.')],
[r('Wie heisst das Hervorbringen einer Antwort aus dem Gedächtnis ohne sichtbare Vorlage?',['Abrufen','Abruf','aktiver Abruf'],'Aktiver Abruf unterscheidet sich vom Erkennen eines angebotenen Satzes.'),r('Wie heisst die Leistung, bei der dir ein angebotener Satz als bereits bekannt erscheint?',['Wiedererkennen','Erkennen'],'Wiedererkennen kann gelingen, obwohl selbstständiges Erklären noch schwerfällt.')]]),
unit('Abrufen ist selbst ein Lernschritt', 'Kurzfristige Leichtigkeit von langfristigem Behalten trennen.',[
('Zwei Arten, dieselben Minuten zu verbringen', 'Eine Person liest einen Text mehrfach. Eine andere verwendet einen Teil derselben Lernzeit darauf, sich bei geschlossenem Text an den Inhalt zu erinnern. In den Experimenten von Roediger und Karpicke war wiederholtes Lesen bei einer sehr kurzfristigen Prüfung im Vorteil; bei späteren Prüfungen zeigte sich dagegen ein Vorteil des vorherigen Abrufens.\n\nDie wichtige Einsicht ist nicht «Lesen ist schlecht». Ohne erste Aufnahme gibt es wenig abzurufen. Es geht darum, nach einer verständlichen Einführung einen Teil der Lernzeit anders zu verwenden: Wissen aus dem Gedächtnis hervorbringen statt nur erneut sehen.'),
('Schwieriger kann nützlicher sein – aber nicht beliebig', 'Eine Tätigkeit, die sich flüssig anfühlt, kann kurzfristig angenehm sein, ohne den späteren Zugriff am besten zu unterstützen. Umgekehrt ist nicht jede schwere Aufgabe lernwirksam. Eine unverständliche Frage oder eine fehlende Erklärung macht Lernen nicht automatisch besser.\n\nPrüfe deshalb zwei Dinge: Fordert die Aufgabe den tatsächlich gelehrten Zusammenhang? Und kannst du einen Fehler anschliessend verstehen und korrigieren? Die produktive Schwierigkeit liegt im Abrufen und Denken, nicht im Entziffern unnötig komplizierter Sätze. Genau deshalb sollten gute Lerntexte klar und gute Prüfungen anspruchsvoll sein, statt beides gleichzeitig zu vernebeln.')],
'Du willst einen Ablauf nächste Woche erklären können. Nach einer Einführung stehen zehn Minuten zur Verfügung. Warum wäre eine Mischung aus eigenem Abruf und anschliessender Kontrolle plausibler als ausschliesslich zehn Minuten Wiederlesen?',
'Der eigene Abruf übt den später benötigten Zugriff und zeigt Lücken. Die Kontrolle verhindert, dass Fehler unbemerkt bleiben. Daraus folgt keine universell optimale Minutenaufteilung für jeden Stoff.',[
[m('Trenne Ziel und Messung.',[('Wie vertraut ist der Absatz jetzt?','Unmittelbares Vertrautheitsgefühl'),('Kann ich es nächste Woche erklären?','Verzögertes Behalten'),('Ist die Frage sprachlich unnötig kompliziert?','Mögliche irrelevante Schwierigkeit')],'Kurzfristige Leichtigkeit ist kein vollständiger Massstab für langfristiges Lernen.'),m('Ordne die Lernfunktion zu.', [('Neue Erklärung aufmerksam lesen','Erste Aufnahme und Verständnis'),('Danach ohne Vorlage antworten','Gedächtnisabruf üben'),('Abweichung von der Erklärung prüfen','Fehler erkennen und korrigieren')],'Diese Schritte ergänzen einander; keiner wird durch die Überschrift «Test» automatisch ersetzt.')],
[c('Welche Folgerung passt zu den im Kapitel beschriebenen Experimenten?','Die beste unmittelbar empfundene Leistung muss nicht das beste spätere Behalten anzeigen.','Abruf ersetzt bei unbekanntem Stoff jede vorausgehende Erklärung.','Jede schwieriger formulierte Frage erzeugt automatisch mehr langfristiges Lernen.','Die zeitliche Perspektive ist entscheidend; unnötige Sprachhürden wurden damit nicht gerechtfertigt.'),c('Was macht eine schwere Aufgabe hier sinnvoll?','Sie fordert den gelehrten Zusammenhang und ermöglicht anschliessende Korrektur.','Sie führt unvorbereitete Begriffe ein, damit jede Antwort länger dauert.','Sie verhindert jede Rückmeldung, damit die Unsicherheit dauerhaft bleibt.','Die Schwierigkeit soll aus der Denkleistung entstehen, nicht aus fehlendem Unterricht oder unlösbarer Unklarheit.')],
[r('Welches Wort bezeichnet hier eine Prüfung, die nicht sofort, sondern erst nach einem Abstand stattfindet: … Prüfung?',['verzögerte','verzoegerte','spätere','spaetere'],'Erst eine spätere Prüfung zeigt, was über den unmittelbaren Eindruck hinaus verfügbar bleibt.'),r('Welche Tätigkeit nach dem Lesen übt das eigenständige Hervorbringen des Wissens?',['Abrufen','Abruf','aktiver Abruf'],'Abruf ist nicht nur eine Messung, sondern kann selbst zum Lernen beitragen.')]]),
unit('Der Fehler muss eine Adresse bekommen', 'Eine Rückmeldung in einen konkreten neuen Lernschritt übersetzen.',[
('Falsch ist noch keine Erklärung', 'Eine Aufgabe fragt, warum Gewinn und Kontostand auseinanderfallen können. Du antwortest: «Weil Ausgaben den Gewinn senken.» Das kann in anderem Zusammenhang stimmen, trifft aber den hier gelehrten Unterschied der Zeitpunkte nicht. Eine rote Markierung allein zeigt dir noch nicht, was du anders verstehen musst.\n\nEine brauchbare Rückmeldung benennt die Lücke: Erlös aus einer gelieferten Leistung und tatsächliche Kundenzahlung können auseinanderliegen. Nun weisst du, welchen Zusammenhang du erneut prüfen sollst. Der Fehler hat eine Adresse im Gedankengang bekommen, statt nur eine schlechte Note zu erzeugen.'),
('Vom Korrigieren zum neuen Abruf', 'Lies die passende Erklärung nochmals und bearbeite danach eine neue Aufgabe mit demselben Prinzip. Andere Zahlen oder ein anderer Fall verhindern, dass du bloss die Position der bisherigen Antwort wiederholst. Entscheidend ist, ob sich deine Erklärung auf den neuen Fall übertragen lässt.\n\nEine gute Fehlerrückmeldung kann auch eine plausible falsche Antwort würdigen: Welchen Teil hat sie richtig erkannt, und wo ging der Schluss zu weit? Das schärft Begriffe. Für den Lernenden lautet die praktische Frage: «Welchen Schritt hatte ich ausgelassen oder verwechselt?» Diese Frage ist genauer als «Bin ich gut oder schlecht in dem Fach?»')],
'Du teilst bei einer Trefferquote durch alle geprüften Teile, obwohl nach dem Anteil richtiger Alarme gefragt ist. Formuliere die Lücke und eine passende nächste Übung.',
'Lücke: Die Bezugsgruppe wurde verwechselt. Nächste Übung: Bei einem neuen Zahlenbeispiel zuerst «Von allen Alarmen …» aussprechen, dann richtige Treffer durch alle Alarme teilen.',[
[m('Welche Rückmeldung leistet was?', [('Falsch','Bewertung ohne erklärte Lücke'),('Du hast alle Teile statt aller Alarme verwendet','Benannte Fehlvorstellung'),('Rechne einen neuen Fall mit richtigem Nenner','Gezielte Anschlussübung')],'Die Rückmeldung wird lernwirksam, wenn sie eine bearbeitbare Unterscheidung zeigt.'),m('Ordne Fehler und Lernschritt zu.', [('Forderung mit Bankguthaben verwechselt','Zahlungszeitpunkt aufzeichnen'),('Alarmquote mit Trefferanteil verwechselt','Bezugsgruppe ausdrücklich nennen'),('Ausgang mit Entscheidungsqualität verwechselt','Gründe und Ergebnis getrennt beurteilen')],'Eine gezielte Übung behandelt den Mechanismus des Fehlers, nicht nur dasselbe Antwortwort.')],
[c('Warum ist ein neuer Fall nach einer Korrektur nützlich?','Er prüft den Zusammenhang, ohne nur die alte Antwortposition zu wiederholen.','Er beseitigt die Notwendigkeit, den ursprünglichen Fehler zu verstehen.','Er beweist schon durch seine Neuheit, dass das Wissen langfristig sitzt.','Ein neuer Fall prüft Übertragung; langfristige Festigung braucht weitere Beobachtung.'),c('Welche Rückmeldung hilft nach einer falschen Rechenantwort am meisten?','Sie zeigt den falschen Nenner und begründet den passenden.','Sie zeigt nur eine rote Zahl ohne Rechenweg.','Sie ersetzt die Aufgabe durch einen nicht verwandten einfacheren Begriff.','Die benannte Ursache erlaubt gezielte Korrektur; blosses Umgehen der Lücke nicht.')],
[o('Ordne den sinnvollen Korrekturablauf.', ['Eigene Antwort mit Begründung vergleichen','Den fehlenden oder falschen Schritt klären','Den Zusammenhang an einem neuen Fall abrufen'],'Erst verstehen, was falsch lief, dann die korrigierte Vorstellung anwenden.'),o('Wie prüfst du eine fragliche Trefferquote?', ['Bezugsgruppe der Frage bestimmen','Zähler und Nenner passend auswählen','Ergebnis am neuen Fall berechnen'],'Die Reihenfolge verhindert, dass zuerst mit einer unklaren Prozentzahl gerechnet wird.')]]),
unit('Abstand macht die Prüfung ehrlicher', 'Wiederholung als erneuten Abruf nach einer Pause planen.',[
('Fünfmal hintereinander ist nicht fünfmal später', 'Du beantwortest dieselbe Karte fünfmal direkt nacheinander richtig. Ein Teil dieser Leichtigkeit kann daran liegen, dass die Antwort gerade noch präsent ist. Die Prüfung am nächsten Tag stellt eine andere Anforderung: Du musst sie nach einem Abstand wieder verfügbar machen.\n\nVerteiltes Wiederholen bedeutet, Lerngelegenheiten über die Zeit zu strecken. Es ist nicht gleichbedeutend mit möglichst langen Pausen oder einem universellen perfekten Kalender. Wie gross ein sinnvoller Abstand ist, hängt unter anderem vom Stoff, dem bisherigen Können und dem gewünschten Behaltezeitraum ab.'),
('Ein anpassbarer Plan', 'Ein praktisches Prinzip lautet: Nach erfolgreichem Abruf kann der nächste Abstand wachsen; nach einem Fehler wird die Lücke früher wieder aufgegriffen. Der Fehler bekommt aber zuerst eine verständliche Korrektur. So verbinden sich Rückmeldung und erneute Prüfung.\n\nEin Plan ist nur ein Hilfsmittel. Wenn du eine Antwort nach langem Abstand noch kannst, ist das stärkere Evidenz für Verfügbarkeit als fünf unmittelbare Wiederholungen. Wenn du sie nicht kannst, ist das eine Information für die nächste Übung und kein Beweis, dass du generell nicht lernen kannst. Die Aufgabe lautet weiterhin: gezielt abrufen, prüfen und anpassen.')],
'Plan A: dieselbe Erklärung fünfmal innerhalb von zwei Minuten lesen. Plan B: nach der Einführung heute, morgen und einige Tage später ohne Vorlage erklären und Fehler prüfen. Welcher Unterschied ist für den späteren Zugriff wesentlich?',
'Plan B verbindet verteilte Gelegenheiten mit aktivem Abruf. Die Zeitpunkte sind ein Beispiel, keine allgemein optimale Vorschrift. Plan A prüft hauptsächlich unmittelbare Vertrautheit.',[
[m('Was zeigt die Situation?', [('Antwort gerade zum fünften Mal gesehen','Hohe unmittelbare Verfügbarkeit möglich'),('Antwort nach mehreren Tagen selbst erklärt','Abruf nach zeitlichem Abstand'),('Beim späteren Abruf einen Schritt vergessen','Gezielt zu bearbeitende Lücke')],'Die zeitliche Entfernung verändert, was eine richtige Antwort über das Behalten aussagt.'),m('Welche Anpassung passt zum beschriebenen Prinzip?', [('Sicherer Abruf nach Abstand','Nächsten Abstand vorsichtig vergrössern'),('Fehler beim Abruf','Korrigieren und früher erneut prüfen'),('Nur wiederholtes Anschauen','Zusätzlich einen Abruf ohne Vorlage einbauen')],'Ein Wiederholungsplan orientiert sich am tatsächlichen Abruf, nicht nur am Öffnen einer Karte.')],
[c('Welche Aussage über Wiederholungsabstände ist angemessen?','Sie können an Können und Behalteziel angepasst werden.','Der längste mögliche Abstand ist für jeden Stoff optimal.','Fünf unmittelbar richtige Antworten beweisen dauerhafte Beherrschung.','Verteilung ist nützlich, aber ein einziger optimaler Kalender lässt sich daraus nicht für alles ableiten.'),c('Eine Antwort gelingt sofort nach dem Nachlesen. Was wäre eine stärkere nächste Prüfung des Behaltens?','Nach einem Abstand ohne Vorlage erneut erklären','Den richtigen Satz sofort nochmals markieren','Die Antwort direkt aus dem gerade sichtbaren Absatz kopieren','Die spätere Prüfung verlangt erneuten Zugriff, statt die unmittelbare Vorlage zu nutzen.')],
[r('Welches Wort beschreibt Lerngelegenheiten, die über verschiedene Zeitpunkte gestreckt werden: … Wiederholung?',['verteilte','verteiltes','verteilte Wiederholung'],'Verteilte Wiederholung unterscheidet sich von unmittelbar massiertem Wiederlesen.'),r('Was soll nach einem Fehler zuerst verstanden werden, bevor der nächste Abstand geplant wird?',['Fehler','Lücke','Luecke','Fehlvorstellung','Begründung','Begruendung'],'Zeitabstand allein korrigiert keine falsche Vorstellung; dafür braucht es eine verständliche Rückmeldung.')]]),
unit('Kannst du es woanders wiedererkennen und anwenden?', 'Den gleichen Mechanismus in einem neuen Fall nutzen.',[
('Andere Geschichte, dieselbe Struktur', 'In der Werkstatt fehlt Geld, obwohl der Auftrag profitabel ist. In einer Agentur sind Rechnungen offen, während Löhne bereits fällig werden. Die Geschichten sehen verschieden aus, teilen aber eine Struktur: Wirtschaftlicher Erfolg und Zahlungszeitpunkt fallen auseinander.\n\nÜbertragung, oft Transfer genannt, bedeutet, relevantes Wissen in einer neuen Situation zu verwenden. Dazu musst du zuerst bemerken, dass ein gelernter Zusammenhang passt. Danach musst du ihn abrufen und richtig anwenden. Das blosse Wiederholen der Werkstattzahlen beweist diese drei Schritte noch nicht.'),
('Eine Grenze gehört zum Verständnis', 'Prüfe auch, wann ein Modell nicht passt. Wenn eine Agentur den Auftrag noch gar nicht geliefert hat, darfst du nicht ohne weitere Annahmen dieselbe Erlösrechnung wie beim bereits gelieferten Werkstattauftrag übernehmen. Die gemeinsame Struktur ersetzt nicht das Lesen der neuen Bedingungen.\n\nEine gute Transferfrage verändert deshalb den Fall, hält aber die nötigen Informationen bereit. Sie verlangt keine ungelehrten Spezialregeln. Dein eigener Abschluss kann lauten: «Das Prinzip ist …; hier passt es, weil …; diese zusätzliche Bedingung müsste ich noch prüfen.» So wird aus einem gemerkten Satz ein begründetes Werkzeug.')],
'Ein Museum verkauft Tickets im Voraus, die Kosten der Veranstaltung fallen erst später an. Welcher Teil des Werkstattbeispiels lässt sich übertragen, und was ist zeitlich anders?',
'Übertragbar ist die Trennung von wirtschaftlicher Leistung und Geldfluss. Anders ist, dass der Kunde vor der Veranstaltung zahlt. Der Zahlungsplan muss deshalb für diesen Ablauf neu gezeichnet werden.',[
[m('Ordne die Transferaufgabe zu.',[('Ähnlichen Zusammenhang im neuen Fall bemerken','Relevanz erkennen'),('Passendes Prinzip ohne Vorlage hervorbringen','Wissen abrufen'),('Neue Bedingungen damit durchdenken','Wissen anwenden')],'Transfer umfasst mehr als dieselbe Antwort in einer anderen Schriftart wiederzuerkennen.'),m('Welche Prüfung braucht die neue Situation?', [('Gleiche Begriffe, andere Zahlungstermine','Zeitlichen Ablauf neu prüfen'),('Anderer Betrieb, gleiche Vorfinanzierung','Gemeinsame Struktur erkennen'),('Nicht gelieferte statt gelieferter Leistung','Zusätzliche Annahme zur Erlösrechnung prüfen')],'Oberfläche und zugrunde liegende Bedingungen können unabhängig voneinander wechseln.')],
[c('Was kennzeichnet eine faire Transferfrage?','Sie verändert den Fall und stellt die nötigen Bedingungen bereit.','Sie verlangt stillschweigend eine bislang ungeklärte Spezialregel.','Sie verändert nur die Reihenfolge identischer Antwortsätze.','Die neue Denkleistung soll im Anwenden liegen, nicht im Erraten fehlender Voraussetzungen.'),c('Warum gehört die Grenze eines Modells zum Lernen?','Damit ein ähnlicher Fall nicht trotz wichtiger Unterschiede falsch behandelt wird.','Damit ein gelerntes Prinzip nur im ursprünglichen Beispiel verwendet wird.','Damit jede neue Aufgabe ohne Prüfung als unvergleichbar abgelehnt wird.','Grenzen helfen bei sinnvoller Übertragung, statt sie zu verbieten oder wahllos zu erlauben.')],
[r('Wie heisst das Anwenden von gelerntem Wissen in einer neuen Situation?',['Transfer','Übertragung','Uebertragung'],'Transfer verlangt, einen relevanten Zusammenhang im neuen Fall zu erkennen und zu nutzen.'),r('Was muss neben der Ähnlichkeit geprüft werden, damit ein Modell nicht auf einen unpassenden Fall übertragen wird? Gesucht ist der Begriff aus «Eine … gehört zum Verständnis».',['Grenze','Modellgrenze'],'Eine Modellgrenze benennt Bedingungen, unter denen die Erklärung nicht ohne Weiteres gilt.')]])
])
