from deep_authoring import course, unit, choice as c, matching as m, recall as r, ordering as o

COURSE=course('digital','phishing','Die Nachricht, die deinen Prüfweg kapert',
 'Nicht jedes Phishing enthält Tippfehler. Du lernst, Adresse, Verbindung und Auftrag getrennt zu prüfen und nach einem Fehlklick geordnet zu handeln.',
 ('NCSC · How to spot a scam email, text message or call', 'https://www.ncsc.gov.uk/collection/phishing-scams/spot-scams'),[
unit('Das Logo beantwortet die falsche Frage', 'Gestaltung von bestätigter Herkunft unterscheiden.',[
('Die Nachricht passt erstaunlich gut', 'Phishing ist eine Täuschung, die dich zu sensiblen Angaben oder riskanten Handlungen bewegen soll. Ein Beispiel: Du erwartest ein Paket. Eine Nachricht nennt eine Zustellung und fordert eine kleine Zusatzgebühr. Logo, Farben und Sprache wirken professionell. Gerade die passende Alltagssituation macht den Vorgang plausibel. Aber ein kopierbares Logo beantwortet nur, wie die Nachricht gestaltet ist, nicht wer den Auftrag tatsächlich erteilt hat.\n\nAuch ein richtiger Name oder ein bekannter Betreff ist für sich allein kein ausreichender Herkunftsnachweis. Solche Angaben können aus früheren Nachrichten, öffentlichen Informationen oder anderen Daten stammen. Die zentrale Frage lautet: Ist die verlangte Handlung über einen unabhängig erreichten, bekannten Kanal bestätigt?'),
('Den Prüfweg selbst wählen', 'Wenn die Nachricht dich auf einen Link führt, kontrolliert ihr Absender zunächst auch diesen vorgeschlagenen Weg. Eine stärkere Prüfung beginnt deshalb anders: Öffne die dir bereits bekannte App oder verwende eine zuvor bekannte Adresse des Dienstes. Prüfe dort, ob der behauptete Vorgang tatsächlich existiert.\n\n«Unabhängig» bedeutet nicht einfach, die Nachricht in einer zweiten App zu lesen. Es bedeutet, nicht nur den vom fraglichen Absender gelieferten Weg zu wiederholen. Auch eine Telefonnummer in derselben Nachricht ist noch kein unabhängiger Kontakt. Die Gestaltung kann einen Anlass zur Aufmerksamkeit liefern; bestätigen muss eine andere Informationsgrundlage.')],
'Eine Nachricht fordert dich auf, einen ungewöhnlichen Auftrag unter der darin angegebenen Telefonnummer zu bestätigen. Warum ist der Rückruf allein noch keine unabhängige Prüfung?',
'Weil die Nummer vom selben fraglichen Absender stammen kann. Ein bereits bekannter, separat beschaffter Kontaktweg trennt die Prüfung eher von der ursprünglichen Nachricht.',[
[m('Ordne die Hinweise ein.',[('Passendes Logo','Kopierbares Gestaltungsmerkmal'),('Bekannte App selbst geöffnet','Separat gewählter Prüfweg'),('Nummer aus derselben Nachricht angerufen','Weiterhin vom Absender gelieferter Weg')],'Die Herkunft der Prüfinformation ist wichtiger als ihre vertraute Gestaltung.'),m('Welche Frage wird beantwortet?', [('Sieht die Nachricht wie die Marke aus?','Gestaltung'),('Gibt es den Vorgang in der bekannten App?','Unabhängige Bestätigung des Vorgangs'),('Nennt sie meinen Namen?','Vorhandensein einer persönlichen Angabe')],'Persönliche oder optische Merkmale sind keine vollständige Authentifizierung.')],
[c('Eine Nachricht enthält deinen richtigen Namen und eine plausible Lieferung. Was folgt daraus?','Sie passt zu deinen Umständen, ihre Herkunft ist damit noch nicht bestätigt.','Die persönliche Angabe ersetzt die Prüfung des verlangten Zahlungsvorgangs.','Die passende Lieferung beweist, dass der mitgesendete Link zum echten Dienst führt.','Passende Informationen erhöhen Plausibilität, bestätigen aber nicht automatisch Absender oder Link.'),c('Welche Bestätigung ist unabhängiger vom verdächtigen Absender?','Den Vorgang in der vorher bekannten App prüfen','Die angehängte Telefonnummer aus derselben Nachricht anrufen','Den mitgesendeten Link in einem zweiten Browser öffnen','Ein anderer Browser ändert nicht die Herkunft des Links; eine bekannte App kann einen getrennten Zugang bieten.')],
[r('Welches Wort beschreibt einen Prüfweg, der nicht nur vom fraglichen Absender übernommen wird?',['unabhängig','unabhaengig','unabhängiger','unabhaengiger'],'Ein unabhängiger Weg trennt die Überprüfung von der ursprünglichen Behauptung.'),r('Wie heisst die Angriffsart, bei der täuschende Nachrichten zu sensiblen Angaben oder riskanten Handlungen verleiten sollen?',['Phishing'],'Phishing nutzt häufig vertraute Gestaltung und plausibel wirkende Anlässe.')]]),
unit('Eine Adresse von rechts verstehen', 'Domain, Unteradresse und Pfad in einfachen Beispielen trennen.',[
('Der Markenname kann am falschen Ort stehen', 'Für diesen Kurs erfinden wir den Dienst mira.example. Das ist eine reservierte Beispieladresse, keine echte Bank. login.mira.example ist eine Unteradresse innerhalb dieser Beispiel-Domain. mira.example.pruefung.test gehört in unseren vereinfachten Beispielen dagegen zur Domain pruefung.test: Der bekannte Name steht nur weiter links.\n\nNach dem ersten Schrägstrich hinter dem Host beginnt der Pfad. Bei pruefung.test/mira.example steht der vertraute Text im Pfad, nicht im Hostnamen. Wer nur irgendwo nach dem Markennamen sucht, verwechselt unterschiedliche Teile einer Adresse.'),
('Die Grenze ist wichtiger als das vertraute Wort', 'Frage zuerst nach dem Host, nicht nach Logo oder Seitentitel. Dann prüfe, ob er wirklich zum erwarteten Dienst gehört. Ein Bindestrich erzeugt keine Unteradresse: mira-hilfe.test ist nicht dasselbe wie hilfe.mira.example.\n\nUnsere Lehradressen sind absichtlich einfach. In der realen Welt gibt es mehrteilige öffentliche Endungen, internationale Zeichen und weitere Besonderheiten. Deshalb ist «Nimm immer genau die letzten zwei Wörter» keine sichere Universalregel. Für eine unerwartete sensible Handlung bleibt der bekannte, selbst geöffnete Dienst der robustere Ausgangspunkt. Das Lesen der Adresse ist eine zusätzliche Prüfung, keine Zusage, jeden Angriff erkennen zu können.')],
'Vergleiche konto.mira.example und mira.example.konto.test. Welche der beiden liegt im vereinfachten Kursmodell unter mira.example?',
'konto.mira.example. Bei mira.example.konto.test ist konto.test der entscheidende rechte Domainteil. Der bekannte Name davor macht die Adresse nicht zum Dienst mira.example.',[
[m('Ordne die drei Lehradressen zu.',[('login.mira.example','Unteradresse des Beispieldienstes'),('mira.example.pruefung.test','Andere Beispiel-Domain'),('pruefung.test/mira.example','Markentext im Pfad')],'Die Position der Bestandteile zählt, nicht das blosse Auftauchen des bekannten Namens.'),m('Welcher Teil ist gemeint?', [('login in login.mira.example','Unteradresse vor der bekannten Domain'),('hilfe in mira.example/hilfe','Pfad nach dem Host'),('mira-hilfe.test','Anderer Host, nicht mira.example')],'Punkt, Bindestrich und Schrägstrich strukturieren eine Adresse unterschiedlich.')],
[c('Welche Adresse liegt im vereinfachten Modell unter mira.example?','service.mira.example','mira.example.service.test','mira-service.test','Nur die erste endet als Host auf der bekannten Beispiel-Domain mit passender Punktgrenze.'),c('Wo steht mira.example in konto.test/mira.example/login?','Im Pfad, nicht im Host','Als gesamte Domain des Hosts','Als Unteradresse vor konto.test','Nach dem ersten Schrägstrich beginnt hier der Pfad.')],
[r('Wie heisst der Teil einer URL nach dem Host und dem folgenden Schrägstrich im Kapitel?',['Pfad','URL Pfad','URL-Pfad'],'Ein Markenname im Pfad bestätigt nicht die Herkunft des Hosts.'),r('Welche bekannte Beispiel-Domain verwenden wir für den fiktiven Dienst? Gib nur die Domain ein.',['mira.example'],'Der Kurs verwendet reservierte Beispieladressen, keine echten Zugangsdaten oder Dienste.')]]),
unit('Verschlüsselt ist nicht gleich vertrauenswürdig', 'Verbindungssicherheit und legitimen Inhalt unterscheiden.',[
('Ein geschützter Weg zum falschen Haus', 'Eine betrügerische Seite kann eine verschlüsselte HTTPS-Verbindung besitzen. Die Verschlüsselung schützt die Übertragung zwischen deinem Browser und dem erreichten Server. Sie beantwortet nicht allein, ob der Betreiber die Organisation ist, die du kontaktieren wolltest, oder ob sein Auftrag berechtigt ist.\n\nDie Haus-Analogie hilft: Ein gut gesicherter Weg kann immer noch zum falschen Haus führen. Zuerst muss deshalb die Zieladresse stimmen. Dann bleibt die Frage, ob die konkrete Handlung zum erwarteten Vorgang passt. Ein sicheres Übertragungsverfahren und eine legitime Geschäftsaufforderung sind verschiedene Eigenschaften.'),
('Drei getrennte Prüfungen', 'Prüfe Adresse, Verbindung und Auftrag getrennt. Adresse: Welchen Host erreiche ich? Verbindung: Gibt es Warnungen, und wird verschlüsselt übertragen? Auftrag: Habe ich diese Anmeldung, Zahlung oder Freigabe wirklich beabsichtigt und unabhängig bestätigt?\n\nEine Warnung vor Verbindungsproblemen sollte nicht einfach übergangen werden. Umgekehrt ist das Fehlen einer Warnung kein vollständiges Gütesiegel für den Inhalt. Auch ein korrekt erreichter echter Dienst kann missverstanden oder für einen ungewollten Vorgang benutzt werden. Sicherheit entsteht hier aus passenden Prüfungen auf mehreren Ebenen, nicht aus einem einzigen Symbol neben der Adresszeile.')],
'Eine Seite unter pruefung.test zeigt ein Schloss und das Logo von mira.example. Welche Aussage stützt HTTPS, welche nicht?',
'HTTPS kann eine geschützte Verbindung zum angezeigten Ziel unterstützen. Es bestätigt nicht allein, dass pruefung.test der beabsichtigte Dienst mira.example ist oder dass die dortige Zahlungsaufforderung legitim ist.',[
[m('Ordne die Sicherheitsfrage ihrer Ebene zu.',[('Mit welchem Host bin ich verbunden?','Zieladresse'),('Ist die Übertragung geschützt?','Verbindung'),('Ist diese Zahlung wirklich beauftragt?','Berechtigung der Handlung')],'Ein positives Ergebnis auf einer Ebene ersetzt die anderen nicht.'),m('Was belegt das Merkmal allein nicht?', [('HTTPS-Verbindung','Legitimität des Seitenbetreibers als gewünschte Organisation'),('Passendes Logo','Bestätigte Domainzugehörigkeit'),('Bekannte Domain','Dass jeder angezeigte Auftrag von dir beabsichtigt ist')],'Gestaltung, Verbindung, Ziel und Handlung müssen getrennt geprüft werden.')],
[c('Eine Phishing-Seite nutzt HTTPS. Warum ist das möglich?','Verschlüsselte Übertragung sagt nicht allein aus, dass der Inhalt legitim ist.','HTTPS bestätigt den Host und damit auch dessen behauptete Unternehmenszugehörigkeit.','Das Zertifikat prüft den Betreiber auch auf die Berechtigung seiner Zahlungsaufforderung.','Die Verschlüsselung schützt einen Transportweg, nicht jede Behauptung des Betreibers.'),c('Welche Aussage zu einer fehlenden Browserwarnung ist angemessen?','Sie ersetzt keine Prüfung von Zieladresse und Auftrag.','Sie bestätigt jeden dort verlangten Zahlungsvorgang.','Sie beweist, dass persönliche Daten nie beim Betreiber ankommen.','Auch ohne Verbindungswarnung bleiben Betreiber und Handlung eigenständige Prüfgegenstände.')],
[r('Welches Protokollkürzel nennt das Kapitel für verschlüsselte Webverbindungen?',['HTTPS'],'HTTPS und die Legitimität einer Aufforderung sind getrennte Fragen.'),r('Welche Ebene prüfst du mit «Welchen Host erreiche ich?»?',['Zieladresse','Adresse','Host','Domain'],'Die Zieladresse wird nicht allein durch ein Schloss oder ein Logo bestätigt.')]]),
unit('Die Freigabe ist der entscheidende Moment', 'Eine unerwartete Bestätigung nicht mit einem eigenen Auftrag verwechseln.',[
('Du sollst nur kurz bestätigen', 'Eine Anmeldung oder Zahlung kann eine zweite Bestätigung auf deinem Gerät auslösen. Das ist nützlich, wenn sie wirklich zu deinem eigenen Vorgang gehört. Ein Angreifer kann jedoch versuchen, dich zur Bestätigung seines Vorgangs zu bewegen – etwa mit einer Geschichte über eine dringende Sicherheitsprüfung.\n\nDie wichtige Frage lautet nicht nur «Kam die Meldung in einer echten App an?», sondern «Welche Handlung bestätige ich gerade?» Eine echte Bestätigungsoberfläche kann für einen ungewollten Vorgang erscheinen. Die Herkunft der Oberfläche und die Absicht hinter der Handlung sind erneut zwei verschiedene Ebenen.'),
('Den Inhalt der Bestätigung lesen', 'Vergleiche angezeigte Details mit dem, was du selbst begonnen hast: Art des Vorgangs, Betrag, Empfänger oder Anmeldung, soweit angezeigt. Ein allgemeiner Satz wie «Bestätigen, damit Ihr Konto geschützt wird» erklärt diese Details nicht.\n\nWenn du den Vorgang nicht selbst ausgelöst hast oder wichtige Angaben nicht passen, bestätige ihn nicht und prüfe über den bekannten Dienst nach. Bestätigungscodes gehören nicht in ein Gespräch mit einer unbekannten Person, die eine Geschichte darüber erzählt. Dieses Kapitel behandelt die defensive Prüfung von Freigaben; es behauptet nicht, dass jede Form zusätzlicher Anmeldung gleich funktioniert oder gegen jeden Angriff schützt.')],
'Du willst dich anmelden. Eine Meldung fordert stattdessen die Bestätigung einer Zahlung an einen unbekannten Empfänger. Warum reicht die echte App als Beruhigung nicht?',
'Weil die angezeigte Handlung nicht zu deinem beabsichtigten Vorgang passt. Die Oberfläche kann echt sein, während du gerade einen fremden oder falsch ausgelösten Auftrag bestätigen würdest.',[
[m('Ordne den Prüfpunkt zu.',[('Habe ich die Anmeldung gestartet?','Eigene Absicht'),('Welcher Betrag und Empfänger stehen dort?','Konkreter Inhalt'),('Meldung erscheint in der bekannten App','Herkunft der Oberfläche')],'Die echte Oberfläche ersetzt die Prüfung von Absicht und Inhalt nicht.'),m('Welche Abweichung ist relevant?', [('Anmeldung erwartet, Zahlung angezeigt','Andere Handlungsart'),('Gewünschter Betrag stimmt nicht','Abweichender Auftragsinhalt'),('Unangeforderte Bestätigung','Fehlender eigener Auslöser')],'Alle drei Abweichungen sind Gründe, den Vorgang vor einer Freigabe zu klären.')],
[c('Eine Person am Telefon verlangt einen Code zur «Sicherheitsprüfung». Welcher Prüfweg ist unabhängig?','Gespräch beenden und den bekannten Dienst selbst kontaktieren.','Den Code nennen, wenn die Person deinen Namen weiss.','Eine Bestätigung über die von derselben Person diktierte Nummer einholen.','Der bekannte selbst gewählte Kontakt löst die Prüfung vom fraglichen Gespräch.'),c('Eine echte App zeigt eine unerwartete Freigabe. Was ist die entscheidende nächste Frage?','Welchen konkreten Vorgang würde ich damit erlauben?','Stammt die Anzeige aus der bereits installierten echten App?','Passt der Zeitpunkt ungefähr zu meiner letzten Anmeldung?','Eine echte Oberfläche kann einen nicht beabsichtigten Vorgang anzeigen; dessen Inhalt muss geprüft werden.')],
[o('Ordne eine bewusste Freigabeprüfung.', ['Eigenen beabsichtigten Vorgang benennen','Angezeigte Details damit vergleichen','Nur bei passender geklärter Handlung bestätigen'],'Ungeklärte oder abweichende Vorgänge werden nicht durch blosse Wiederholung legitim.'),o('Ordne die Reaktion auf eine unangeforderte Bestätigung.', ['Nicht bestätigen','Bekannten Dienst über eigenen Weg öffnen','Den Vorgang dort prüfen beziehungsweise melden'],'Die Prüfung übernimmt nicht einfach den Weg einer verdächtigen Aufforderung.')]]),
unit('Nach einem Fehlklick geordnet reagieren', 'Öffnen, Datenabgabe und bestätigte Handlung unterscheiden.',[
('Nicht jeder Fehler hat dieselbe Reichweite', 'Eine Person öffnet einen verdächtigen Link und schliesst die Seite, ohne etwas einzugeben. Eine zweite gibt ihr Passwort ein. Eine dritte bestätigt zusätzlich eine Zahlung. Diese Situationen verlangen nicht dieselbe Einordnung. Die erste Frage lautet deshalb: Was ist tatsächlich geschehen?\n\nNotiere, ob Daten eingegeben, Dateien geöffnet, Berechtigungen erteilt oder Vorgänge bestätigt wurden. «Ich habe geklickt» kann diese Unterschiede verdecken. Es geht nicht darum, Entwarnung allein aus einer Erinnerung abzuleiten, sondern darum, dem passenden Dienst oder der IT konkrete Informationen geben zu können.'),
('Den nächsten Schritt an der möglichen Folge ausrichten', 'Wenn Zugangsdaten auf einer verdächtigen Seite abgegeben wurden, nutze einen bekannten sicheren Zugang zum echten Dienst, um das Passwort zu ändern und angebotene Sitzungs- oder Kontoprüfungen vorzunehmen. Bei beruflichen Konten oder geöffneten verdächtigen Dateien gehört die zuständige IT früh hinzu. Bei einer verdächtigen Zahlung kontaktiere den betroffenen Zahlungsdienst beziehungsweise die Bank über einen bekannten Weg zeitnah.\n\nBewahre nötige Angaben zur Meldung auf, ohne die verdächtige Handlung zu wiederholen. Eine schnelle, sachliche Meldung ist hilfreicher als Scham oder hektisches Herumprobieren. Die passende Reaktion hängt vom konkreten Vorgang ab; der Kurs ersetzt keine individuelle technische Schadensprüfung.')],
'Zwei Personen sagen «Ich habe auf den Link geklickt». Eine hat nur die Seite gesehen; die andere ihr Passwort eingegeben. Welche Zusatzinformation verändert den nächsten Schritt wesentlich?',
'Die abgegebenen Zugangsdaten. Im zweiten Fall muss das echte Konto über einen bekannten sicheren Weg abgesichert werden. In beiden Fällen helfen konkrete Angaben bei der weiteren Einordnung.',[
[m('Ordne den Vorgang dem vorrangigen Prüfbereich zu.',[('Passwort auf verdächtiger Seite eingegeben','Betroffenes Konto absichern'),('Ungewöhnliche Zahlung bestätigt','Zahlungsdienst über bekannten Weg kontaktieren'),('Verdächtige Datei auf Arbeitsgerät geöffnet','Zuständige IT informieren')],'Die Reaktion richtet sich nach der möglichen Folge, nicht nur nach dem Wort «Klick». '),m('Welche Information präzisiert den Vorfall?', [('Nur Seite geöffnet','Umfang der Interaktion'),('Passwort eingegeben','Mögliche Zugangsdatenabgabe'),('Freigabe mit Betrag bestätigt','Möglicherweise autorisierter Zahlungsvorgang')],'Konkrete Handlungen ermöglichen eine passendere Einordnung.')],
[c('Warum ist eine genaue Beschreibung hilfreicher als «Ich habe etwas Falsches gemacht»?','Sie zeigt, welches Konto, Gerät oder welcher Vorgang betroffen sein könnte.','Sie erlaubt, den Vorfall allein nach der Zahl der Klicks einzustufen.','Sie macht die Gestaltung der Nachricht zum wichtigsten Schadensindikator.','Präzision verbessert die Einordnung, ersetzt aber nicht jede Untersuchung.'),c('Welcher Weg passt nach einer vermuteten Passwortabgabe?','Den echten Dienst über einen bekannten Zugang öffnen und das Konto absichern.','Auf derselben verdächtigen Seite ein neues Passwort hinterlegen.','Den verdächtigen Absender um eine weitere Bestätigung seiner Echtheit bitten.','Die Absicherung darf nicht wieder vom vermuteten Angreifer geführt werden.')],
[o('Ordne eine geordnete Reaktion.', ['Verdächtige Interaktion stoppen','Tatsächlich ausgeführte Schritte festhalten','Betroffenen Dienst oder zuständige Stelle über bekannten Weg kontaktieren'],'Stoppen, konkret einordnen und passend melden ist hilfreicher als wiederholtes Ausprobieren.'),o('Ordne die Prüfung einer unerwarteten sensiblen Nachricht.', ['Verlangte Handlung erkennen','Bekannten Dienst unabhängig öffnen','Vorgang dort prüfen, bevor sensible Daten oder Freigaben folgen'],'Der unabhängig gewählte Prüfweg durchbricht die Führung durch die verdächtige Nachricht.')]])
])
