from story_authoring import *

SUNK=topic('sunk','think','Noch ein Ersatzteil?','Ein altes Velo hat schon viel Geld gekostet. Die nächste Reparatur zwingt dich zu einer Entscheidung über Vergangenheit und Zukunft.','Entscheidung unter Unsicherheit')
RATES=topic('rates','data','Der Alarm irrt erstaunlich oft','Ein Prüfgerät erkennt fast alle beschädigten Pakete. Trotzdem sind die meisten Alarme falsch. Du löst den scheinbaren Widerspruch.','Zahlenkrimi')
RECALL=topic('recall','learn','Das Buch ist zu. Was bleibt?','Du hast einen Absatz verstanden – solange du ihn siehst. In diesem Fall baust du aus diesem Gefühl eine überprüfbare Erinnerung.','Selbstversuch fürs Lernen')
TOPICS=[SUNK,RATES,RECALL]
K=source('OpenStax · Relevant Information for Decision-Making','https://openstax.org/books/principles-managerial-accounting/pages/10-1-identify-relevant-information-for-decision-making')
B=source('OpenStax · Contingency Tables','https://openstax.org/books/introductory-statistics-2e/pages/3-4-contingency-tables')
R=source('IES · Organizing Instruction and Study to Improve Student Learning','https://ies.ed.gov/ncee/wwc/PracticeGuide/1')
LESSONS=[
chapter(SUNK,1,'Die dreihundert Franken im Raum','Du trennst unwiederbringliche frühere Ausgaben von der nächsten Entscheidung.',[
 card('scene','Das Velo steht noch immer auf dem Ständer','Fiktiver Fall: In ein altes Velo sind bereits 300 CHF geflossen, die du nicht zurückbekommst. Eine zusätzliche Reparatur soll 120 CHF kosten. Danach wäre das Velo im vereinfachten Modell sicher 180 CHF wert. Ohne Reparatur sei es in dieser ersten Version wertlos.\n\nDie 300 CHF tun weh. Aber beide jetzigen Möglichkeiten tragen dieselbe Vergangenheit.',image='sunk-workbench',alt='Eine Person prüft ein teilweise repariertes Velo neben Werkzeug und einem neuen Ersatzteil.',caption=FICTION),
 card('evidence','Versunkene Kosten','Unwiederbringliche Kosten sind bereits angefallen und ändern sich durch die aktuelle Wahl nicht mehr. Man nennt sie versunkene Kosten, englisch sunk costs. Für die nächste Entscheidung vergleichst du, was ab jetzt je Alternative hinzukommt oder entfällt.\n\nDie Vergangenheit bleibt für dein gesamtes Ergebnis und fürs Lernen relevant. Sie ist nur kein eigener Zusatznutzen der nächsten Reparatur.'),
 card('decision','Welche Rechnung betrifft die nächste Wahl?','Unter den ausdrücklich sicheren und vereinfachten Annahmen schafft die Reparatur 180 CHF Wert und kostet zusätzlich 120 CHF.',probe=number('Wie gross ist der zusätzliche Vorteil gegenüber Nichtreparieren im Modell?',60,'CHF','180 zusätzlicher Wert minus 120 zusätzliche Kosten = 60 CHF. Die bereits unwiederbringlichen 300 unterscheiden die jetzigen Alternativen nicht.')),
 card('transfer','Der Fehler hat zwei Richtungen','«Ich muss weitermachen, weil schon 300 weg sind» ist unzureichend. Aber auch «Es hat viel gekostet, also muss ich jetzt stoppen» genügt nicht. Ein vernünftiger Vergleich kann zum Weitermachen oder zum Stoppen führen – je nachdem, was ab jetzt zu erwarten ist.')
],[recall('Wie heissen bereits angefallene, unwiederbringliche Kosten?','Versunkene Kosten|Sunk Costs','Sie ändern sich durch die aktuelle Wahl nicht mehr.'),number('Wie gross ist der zusätzliche Vorteil bei 180 neuem Wert und 120 neuen Kosten?',60,'CHF','180 − 120 = 60 CHF.'),sc('Warum werden die früheren 300 nicht als Vorteil der nächsten Reparatur gezählt?','Sie fallen unabhängig von der jetzigen Wahl in der Vergangenheit an','Weil die gesamten früheren 300 vom heutigen Mehrwert der Reparatur abgezogen werden müssen','Weil jede weitere Reparatur die früheren Ausgaben anteilig zurückverdient','Die Entscheidung verändert diese Ausgabe nicht mehr.'),multi('Welche Begründungen sind allein unzureichend?',['Weitermachen nur wegen früherer Ausgaben','Stoppen nur wegen früherer Ausgaben','Künftigen Nutzen und Kosten vergleichen','Die aktuellen Alternativen prüfen'],[0,1],'Beide pauschalen Reaktionen umgehen die Zukunftsrechnung.'),sc('Sind versunkene Kosten für jede Betrachtung unwichtig?','Nein, sie zählen zum Gesamtergebnis und können Lehren liefern','Ja, denn unwiederbringliche Kosten dürfen auch im Gesamtergebnis ausgeblendet werden','Ja, denn frühere Ausgaben liefern auch für spätere ähnliche Vorhaben keine Information','Entscheidungsrelevanz und historische Ergebnisrechnung sind verschieden.')],
'Die frühere Ausgabe erklärt deinen Ärger. Sie bezahlt nicht automatisch die nächste Entscheidung.','Frage bei einem festgefahrenen Vorhaben: Was würde ich ab heute tun, wenn ich die Vergangenheit nicht rechtfertigen müsste?',K),
chapter(SUNK,2,'Der Wert, den du beim Weitermachen aufgibst','Du berücksichtigst eine reale Alternative und vermeidest, alle alten Werte als versunken abzutun.',[
 card('lab','Eine neue Möglichkeit','Ändere genau eine Annahme: Du könntest das unreparierte Velo jetzt für 50 CHF verkaufen. Repariert wäre es weiterhin 180 CHF wert, die neue Reparatur kostet weiterhin 120 CHF.\n\nReparieren führt zu 180 − 120 = 60 CHF verbleibendem Wert. Sofort verkaufen bringt 50 CHF. Der Vorteil des Reparierens gegenüber dieser Alternative beträgt nur noch 10 CHF.'),
 card('decision','Ist der heutige Verkaufserlös versunken?','Du kannst die 50 CHF durch deine jetzige Entscheidung noch erhalten oder darauf verzichten.',probe=sc('Wie ist dieser Betrag einzuordnen?','Als relevante Alternative, auf die du beim Reparieren verzichtest','Als unwiederbringliche frühere Ausgabe','Als bereits bezahlte Reparaturrechnung','Die 50 sind noch entscheidungsabhängig. Sie gehören daher in den Vergleich.')),
 card('evidence','Opportunitätskosten','Der Wert der besten aufgegebenen Alternative heisst Opportunitätskosten. Hier gibst du beim Reparieren die sofortige Verkaufsmöglichkeit auf.\n\nDas Wort «versunken» darf nicht pauschal auf alles angewendet werden, was zu einem alten Projekt gehört. Ein heutiger Verkaufswert, eine kündbare Verpflichtung oder vermeidbare Folgekosten können die nächste Wahl sehr wohl verändern.'),
 card('reveal','Und wenn das neue Teil 170 kostet?','Rechne bei gleicher Alternative von 50 CHF und gleichem repariertem Wert von 180 CHF neu.',reveal='Reparieren lässt 180 − 170 = 10 CHF übrig; sofortiger Verkauf bringt 50. Verkaufen ist in diesem Modell um 40 CHF besser. Die alte Rechnung bleibt alt – aber die neuen Kosten ändern die Entscheidung.')
],[number('Wie gross ist der Vorteil des Reparierens bei 180 Wert, 120 Kosten und 50 sofortigem Verkauf?',10,'CHF','180 − 120 − 50 = 10 CHF.'),recall('Wie heisst der Wert einer aufgegebenen besten Alternative?','Opportunitätskosten|Opportunitaetskosten','Die nicht gewählte Alternative kann einen realen Wert besitzen.'),sc('Warum sind die möglichen 50 CHF Verkaufserlös nicht versunken?','Du kannst sie durch die jetzige Entscheidung noch realisieren','Weil ein Verkaufserlös unabhängig vom Entscheidungszeitpunkt immer relevant ist','Weil der höhere ursprüngliche Kaufpreis den Betrag automatisch entscheidungsrelevant macht','Der Betrag hängt von der heutigen Wahl ab.'),number('Bei 170 Reparaturkosten: Um wie viel ist sofortiger Verkauf zu 50 besser als 180 − 170?',40,'CHF','50 − 10 = 40 CHF.'),multi('Welche Grössen können eine aktuelle Entscheidung verändern?',['Ein heute erzielbarer Verkaufswert','Vermeidbare künftige Ausgaben','Eine für alle Optionen identische unwiederbringliche Ausgabe','Nur das Bedürfnis, frühere Entscheidungen zu verteidigen'],[0,1],'Entscheidungsabhängige künftige Werte sind relevant.')],
'Nicht alles an einem alten Projekt ist versunken. Heutige Alternativen zählen.', 'Benenne bei deinem nächsten Kostenvergleich ausdrücklich die beste Alternative zum Weitermachen.',K),
chapter(SUNK,3,'Die Reparatur kann auch scheitern','Du berechnest einen Erwartungswert und unterscheidest ihn vom garantierten Ergebnis.',[
 card('scene','Der Mechaniker kann es nicht versprechen','Neue Modellvariante: Die Reparatur kostet 120 CHF. Mit angenommenen 60 % Wahrscheinlichkeit ist das Velo danach 300 CHF wert; sonst bleiben 30 CHF Restwert. Sofortiger Verkauf ohne Reparatur würde 50 CHF bringen.\n\nDiese Wahrscheinlichkeiten sind erfundene Übungswerte, keine tatsächliche technische Diagnose.',image='sunk-choice',alt='Eine Person legt in einer Velowerkstatt einen Schraubenschlüssel ab und betrachtet eine andere fahrbereite Option.',caption=FICTION),
 card('lab','Gewichte die möglichen Ausgänge','Erwarteter Wert nach Reparatur: 0.60 × 300 + 0.40 × 30 = 192 CHF. Nach den zusätzlichen 120 Kosten bleiben rechnerisch 72 CHF. Die sichere Alternative bringt 50 CHF. Der erwartete Mehrwert beträgt 22 CHF.\n\nBei einem einzigen Versuch erhältst du nicht automatisch genau 72. Du erlebst einen konkreten Ausgang, der besser oder schlechter sein kann.'),
 card('decision','Welcher Satz ist zu stark?','Der Erwartungswert spricht im vereinfachten Geldmodell für die Reparatur.',probe=sc('Welche Aussage wäre trotzdem falsch?','Die Reparatur garantiert einen höheren Erlös als sofortiger Verkauf','Der Modellvergleich ergibt 22 CHF erwarteten Mehrwert','Die angenommenen Wahrscheinlichkeiten sind entscheidend','Ein positiver Erwartungswert ist keine Garantie für den einzelnen Ausgang.')),
 card('evidence','Was die Zahl nicht entscheidet','Ob du dir den ungünstigen Ausgang leisten kannst, wie verlässlich die Schätzung ist und welchen Nutzen du aus dem Velo ziehst, bleibt offen. Ein Erwartungswert ist eine Denkstütze, keine Pflicht zum Risiko.\n\nFrühere 300 CHF rechtfertigen weiterhin keine beliebige Wette. Neue Informationen über Erfolgschancen können dagegen sehr relevant sein.')
],[number('Wie hoch ist der erwartete Wert vor Reparaturkosten: 0.6 × 300 + 0.4 × 30?',192,'CHF','180 + 12 = 192 CHF.'),number('Wie hoch ist der erwartete Mehrwert gegenüber 50 sofortigem Verkauf nach 120 Kosten?',22,'CHF','192 − 120 − 50 = 22 CHF.'),recall('Wie heisst die nach Wahrscheinlichkeiten gewichtete Grösse?','Erwartungswert','Er ist ein gewichteter Vergleich, kein garantierter Einzelausgang.'),multi('Was bleibt neben dem Erwartungswert wichtig?',['Verlässlichkeit der Wahrscheinlichkeiten','Tragbarkeit des ungünstigen Ausgangs','Die Annahme, 72 CHF seien garantiert','Die Pflicht, jede frühere Ausgabe zu rechtfertigen'],[0,1],'Unsicherheit und Risikotragfähigkeit werden von der Mittelzahl nicht beseitigt.'),sc('Kann eine vernünftige Modellentscheidung im Einzelfall schlecht ausgehen?','Ja, wenn mehrere mögliche Ausgänge bestehen','Nein, dann war jede Rechnung zwingend falsch','Nein, Wahrscheinlichkeit bedeutet Gewissheit','Entscheidungsqualität und zufälliger Einzelausgang sind nicht identisch.')],
'Ein positiver Erwartungswert ersetzt weder verlässliche Annahmen noch die Fähigkeit, einen Verlust zu tragen.','Nenne bei einer unsicheren Entscheidung den schlechten Ausgang ausdrücklich, nicht nur den erhofften.',K),
chapter(SUNK,4,'Eine Grenze vor dem nächsten Kauf','Du formulierst ein vorab prüfbares Fortsetzungskriterium und passt es an echte neue Informationen an.',[
 card('decision','Noch eine kleine Ausgabe','Du kaufst ein weiteres Teil nur mit dem Argument, sonst seien alle früheren Teile umsonst gewesen.',probe=sc('Welche Frage unterbricht diese Begründung?','Welche zusätzlichen Kosten und welchen Nutzen erwarte ich ab jetzt gegenüber meinen Alternativen?','Wie kann ich die Gesamtsumme möglichst wenig ansehen?','Wie kann ich beweisen, dass meine erste Wahl perfekt war?','Der Zukunftsvergleich verhindert, dass die Vergangenheit allein die neue Ausgabe begründet.')),
 card('lab','Schreibe die Regel vor der nächsten Rechnung','Eine mögliche Regel im fiktiven Fall: Erst eine begrenzte Diagnose; danach nur fortsetzen, wenn die verbleibenden Kosten und die begründeten Chancen gegenüber Verkauf vertretbar sind.\n\nDie Grenze muss zu realen Mitteln und Zielen passen. Sie ist kein universeller Frankenbetrag. Lege auch fest, welche neue Information deine Einschätzung ändern dürfte.'),
 card('evidence','Neue Information oder neue Ausrede?','Ein überprüfter Kostenvoranschlag oder ein entdeckter Schaden verändert die Zukunftsrechnung. «Jetzt ist schon noch mehr Geld drin» verändert sie für sich allein nicht.\n\nEine vorab formulierte Regel hilft, diese Fälle auseinanderzuhalten. Sie darf bei echten neuen Informationen angepasst werden, aber nicht nur, um jede beliebige Fortsetzung nachträglich zu rechtfertigen.'),
 card('transfer','Der ehrliche Abschluss','Vielleicht reparierst du. Vielleicht verkaufst du. In beiden Fällen kannst du den früheren Fehler dokumentieren und daraus lernen, ohne ihn mit weiteren Ausgaben verschönern zu müssen.\n\nDie Methode gilt auch für Zeit: Bereits verbrachte Stunden kommen nicht zurück. Verbleibende Verpflichtungen, Lernnutzen und künftiger Aufwand gehören trotzdem sorgfältig in die nächste Entscheidung.',reveal='Die ganze Prüfung lautet: Was ist wirklich unwiederbringlich? Was kann ich noch verändern? Welche Alternative gebe ich auf? Wie unsicher sind die Ausgänge? Danach entscheidest du über den nächsten Schritt, nicht über deinen Stolz.')
],[multi('Welche Informationen können eine Fortsetzungsentscheidung sachlich ändern?',['Ein überprüfter neuer Kostenvoranschlag','Ein neu entdeckter Schaden','Nur die inzwischen höhere versunkene Summe','Nur der Wunsch, nie einen Fehler zuzugeben'],[0,1],'Die ersten beiden verändern mögliche künftige Kosten oder Nutzen.'),order('Ordne den aktuellen Vergleich.',['Unwiederbringliche Vergangenheit erkennen','Verbleibende Alternativen benennen','Künftige Kosten, Nutzen und Unsicherheit prüfen','Nächsten Schritt begründet wählen'],'Die Entscheidung richtet sich auf noch veränderbare Folgen.'),sc('Wann darf eine vorab gewählte Grenze sinnvoll angepasst werden?','Bei relevanten neuen Informationen und nachvollziehbarer Begründung','Bei jeder neuen Ausgabe allein wegen ihrer Existenz','Nur um das Eingestehen eines Fehlers zu vermeiden','Eine Regel soll Denken unterstützen, nicht neue Tatsachen verbieten.'),sc('Sind bereits vergangene Stunden durch Weiterarbeiten rückholbar?','Nein, aber künftiger Lernnutzen und Verpflichtungen können weiter relevant sein','Ja, jede weitere Stunde löscht eine frühere','Ja, wenn man das Projekt nicht abschliesst','Vergangene Zeit bleibt vergangen; zukünftige Folgen müssen trotzdem geprüft werden.'),matching('Ordne die drei Begriffe des Falls.',[('Versunkene Kosten','Unwiederbringliche frühere Ausgaben'),('Opportunitätskosten','Wert der aufgegebenen Alternative'),('Erwartungswert','Nach Wahrscheinlichkeiten gewichteter Wert')],'Die Begriffe trennen Vergangenheit, Alternative und Unsicherheit.')],
'Du musst die Vergangenheit nicht schönrechnen, um die nächste Entscheidung gut zu treffen.','Schreibe für ein laufendes Vorhaben ein überprüfbares Fortsetzungskriterium auf.',K),
chapter(RATES,1,'Ein Gerät, das neun von zehn findet','Du unterscheidest Trefferquote bei vorhandenen Schäden von der Aussagekraft eines Alarms.',[
 card('scene','Der Alarm am Pakettisch','Fiktiver Test: Von 1’000 Paketen sind 10 beschädigt und 990 unbeschädigt. Ein Prüfgerät meldet 9 der 10 beschädigten Pakete. Es schlägt aber auch bei 99 der 990 unbeschädigten an.\n\nDie erste Zahl klingt stark: Neun von zehn Schäden erkannt. Nun liegt ein markiertes Paket vor dir. Wie viel weisst du dadurch?',image='rates-parcels',alt='Ein Mitarbeiter prüft in einem Paketbereich eine markierte Sendung unter einer Lampe.',caption=FICTION),
 card('decision','Worauf beziehen sich die neunzig Prozent?','Die Trefferquote beträgt 9 / 10 = 90 %, wenn wir nur die tatsächlich beschädigten Pakete betrachten.',probe=sc('Bedeutet das automatisch, dass 90 % aller Alarme echte Schäden sind?','Nein, dafür müssen auch die Fehlalarme in den Alarmen berücksichtigt werden','Ja, beide Aussagen verwenden dieselbe Bezugsgruppe','Ja, solange mindestens ein Schaden erkannt wird','Treffer unter beschädigten Paketen und Schäden unter Alarmen sind umgekehrte Fragen.')),
 card('evidence','Der Nenner wechselt','Frage 1: Von den beschädigten Paketen, wie viele lösen Alarm aus? Frage 2: Von den alarmierten Paketen, wie viele sind beschädigt?\n\nFür die erste Frage ist die Bezugsgruppe 10. Für die zweite gehören echte und falsche Alarme zusammen. Das ist der entscheidende Wechsel, nicht ein komplizierter Fachbegriff.'),
 card('reveal','Zähle zuerst die Alarme','Wie viele Pakete liegen insgesamt im markierten Stapel?',reveal='9 echte Alarme plus 99 Fehlalarme ergeben 108 markierte Pakete. Nur 9 davon sind tatsächlich beschädigt. Die Rechnung für die zweite Frage beginnt also mit 9 von 108, nicht mit 9 von 10.')
],[number('Wie viele Pakete sind im beschriebenen Test beschädigt?',10,'Pakete','Die Ausgangsmenge enthält 10 beschädigte und 990 unbeschädigte Pakete.'),number('Wie viele Alarme entstehen insgesamt?',108,'Alarme','9 echte Alarme + 99 Fehlalarme = 108.'),sc('Welche Bezugsgruppe hat die Aussage «90 % der Schäden erkannt»?','Die tatsächlich beschädigten Pakete','Alle alarmierten Pakete','Nur die unbeschädigten Pakete','Die 9 Treffer werden durch 10 beschädigte Pakete geteilt.'),multi('Welche Grössen gehören in die Zahl aller Alarme?',['Richtig alarmierte beschädigte Pakete','Falsch alarmierte unbeschädigte Pakete','Ausschliesslich übersehene Schäden','Ausschliesslich alle Pakete ohne Alarm'],[0,1],'Der Alarmstapel enthält richtige und falsche Meldungen.'),sc('Was ist der logische Fehler beim direkten Umkehren der 90-%-Aussage?','Die Bezugsgruppe wird unbemerkt verändert','Neun kann nicht durch zehn geteilt werden','Jeder Alarm ist grundsätzlich sinnlos','Die beiden bedingten Fragen besitzen unterschiedliche Nenner.')],
'Frage immer: Prozent von welcher Gruppe?','Übersetze einen Prozentwert in einen Satz mit ausdrücklich genannter Bezugsgruppe.',B),
chapter(RATES,2,'Neun unter hundertacht','Du berechnest den Anteil echter Fälle unter den Alarmen anhand natürlicher Häufigkeiten.',[
 card('lab','Lege vier Felder an','Die 1’000 Pakete lassen sich vollständig aufteilen: beschädigt mit Alarm = 9; beschädigt ohne Alarm = 1; unbeschädigt mit Alarm = 99; unbeschädigt ohne Alarm = 891.\n\nPrüfe die Summen: 9 + 1 = 10 beschädigte, 99 + 891 = 990 unbeschädigte. Zusammen bleiben es 1’000. Die Gruppen dürfen weder fehlen noch doppelt gezählt werden.',visual=compare('Vier disjunkte Gruppen',['Beschädigt + Alarm: 9','Beschädigt + kein Alarm: 1','Unbeschädigt + Alarm: 99','Unbeschädigt + kein Alarm: 891'],'Fiktive absolute Häufigkeiten; zusammen 1’000 Pakete.')),
 card('decision','Die gesuchte Quote','Für «Wie viele Alarme sind echte Schäden?» nimmst du die 9 echten Fälle und alle 108 Alarme.',probe=number('Wie viel Prozent sind 9 von 108? Runde auf zwei Dezimalstellen.',8.33,'%','9 / 108 × 100 ≈ 8.33 %. Die hohe Erkennungsquote unter Schäden war eine andere Frage.',0.02)),
 card('evidence','Warum so viele falsche Meldungen?','Die unbeschädigte Ausgangsgruppe ist viel grösser. Schon 10 % Fehlalarme unter 990 unbeschädigten Paketen ergeben 99 Meldungen. Diese überwiegen die 9 echten Treffer.\n\nDas Gerät ist damit nicht automatisch nutzlos. Ein Alarm kann eine weitere Prüfung auslösen. Seine Bedeutung muss nur realistisch verstanden werden.'),
 card('transfer','Eine Darstellung, die sich prüfen lässt','Natürliche Häufigkeiten machen die Gruppen sichtbar: Von 1’000 sind 10 betroffen; davon werden 9 erkannt. Von 990 anderen werden 99 markiert. Du kannst jeden Schritt zählen, statt Prozentwörter im Kopf umzudrehen.',reveal='Wenn du unsicher wirst, beginne wieder mit einer festen Gesamtzahl und teile sie in überschneidungsfreie Gruppen. Erst danach bildest du die Quote für die tatsächlich gestellte Frage.')
],[number('Wie viele unbeschädigte Pakete lösen keinen Alarm aus?',891,'Pakete','990 unbeschädigte minus 99 Fehlalarme = 891.'),number('Wie viele beschädigte Pakete werden übersehen?',1,'Paket','10 beschädigte minus 9 erkannte = 1.'),number('Welcher Prozentanteil der 108 Alarme ist tatsächlich beschädigt?',8.33,'%','9 / 108 × 100 ≈ 8.33 %.',0.02),sc('Warum überwiegen Fehlalarme in diesem Beispiel?','Die unbeschädigte Ausgangsgruppe ist sehr viel grösser','Weil die 9 echten Treffer nicht existieren','Weil 90 % immer kleiner als 10 % sind','Die Häufigkeit des Problems beeinflusst den Alarmstapel.'),matching('Ordne die Meldungen zu.',[('Echter Alarm','Beschädigt und markiert'),('Fehlalarm','Unbeschädigt und markiert'),('Übersehener Schaden','Beschädigt und nicht markiert')],'Die Kombination aus Zustand und Meldung bestimmt die Gruppe.')],
'Zähle die Gruppen, bevor du die Quote bildest.','Stelle den Paketfall als vier Gruppen dar und prüfe, dass ihre Summe 1’000 ergibt.',B),
chapter(RATES,3,'Dasselbe Gerät, ein anderer Eingang','Du erkennst die Wirkung einer veränderten Grundhäufigkeit bei gleichen Modellraten.',[
 card('decision','Die neue Lieferung ist riskanter','Neue fiktive Lieferung: 100 von 1’000 Paketen sind beschädigt, 900 nicht. Das Gerät erkennt weiter 90 % der beschädigten und alarmiert fälschlich bei 10 % der unbeschädigten.',probe=number('Wie viele echte Alarme entstehen jetzt?',90,'Alarme','90 % von 100 beschädigten Paketen = 90 echte Alarme.')),
 card('lab','Rechne beide Seiten neu','Unter 900 unbeschädigten Paketen entstehen nun 90 Fehlalarme. Insgesamt sind es 90 + 90 = 180 Alarme. Davon betreffen 90 einen echten Schaden: 50 %.\n\nDie Modellraten des Geräts sind gleich geblieben. Verändert hat sich, wie häufig Schäden bereits in der eingehenden Lieferung vorkommen.'),
 card('evidence','Die Grundhäufigkeit','Den Anteil tatsächlich beschädigter Pakete vor Kenntnis eines konkreten Alarms nennen wir hier Grundhäufigkeit oder Basisrate. Sie stieg von 1 % auf 10 %.\n\nEin Prüfgerät kann bei gleichen angenommenen Treffer- und Fehlalarmraten in unterschiedlichen Eingangsgruppen sehr verschiedene Anteile echter Alarme erzeugen. Für reale Vergleiche muss zusätzlich geprüft werden, ob die Geräteleistung in der neuen Gruppe wirklich gleich bleibt.'),
 card('reveal','Eine neue Werbezahl','Jemand bewirbt die 50 % echten Alarme, ohne die andere Zusammensetzung der Lieferung zu erwähnen. Welche Frage fehlt?',reveal='Wie häufig war das Problem in der getesteten Gruppe, und entspricht diese Gruppe unserem Einsatz? Eine bessere Alarmquote kann an einem anderen Eingang liegen, nicht unbedingt an einem besseren Gerät.')
],[number('Wie viele Fehlalarme entstehen bei 900 unbeschädigten Paketen und 10 % Fehlalarmrate?',90,'Alarme','900 × 0.10 = 90.'),number('Welcher Anteil von 180 Alarmen mit 90 echten Fällen ist richtig?',50,'%','90 / 180 = 0.5 = 50 %.'),recall('Wie heisst die Ausgangshäufigkeit eines Problems in der betrachteten Gruppe?','Basisrate|Grundhäufigkeit|Grundhaeufigkeit','Die Basisrate wird vor der konkreten Meldung betrachtet.'),sc('Welche Annahme blieb im neuen Modell gleich?','90 % Erkennung und 10 % Fehlalarmrate','Die Zahl beschädigter Pakete','Der Anteil echter Fälle unter Alarmen','Die Testeigenschaften werden im Vergleich konstant gehalten.'),multi('Was solltest du bei einer übertragenen Erfolgszahl prüfen?',['Die Zusammensetzung der getesteten Gruppe','Ob die Leistung in der neuen Gruppe gleich bleibt','Nur die schönste einzelne Quote','Ob der Gerätename beeindruckend klingt'],[0,1],'Eingangsgruppe und tatsächliche Testeigenschaften bestimmen die Aussagekraft.')],
'Die gleiche Meldung kann je nach Ausgangslage eine andere Aussagekraft haben.','Frage bei einer Erfolgsquote, aus welcher Gruppe die untersuchten Fälle stammen.',B),
chapter(RATES,4,'Ein Alarm ist ein Anfang','Du trennst Erkennung, Entscheidung und Folgen verschiedener Fehler.',[
 card('scene','Im markierten Paket liegt ein Pullover','Die nächste Kontrolle zeigt ein unbeschädigtes Kleidungsstück. Der Alarm war ein Fehlalarm. Das macht die zusätzliche Prüfung nicht automatisch unsinnig: Ihr Zweck war gerade, die Meldung genauer einzuordnen.',image='rates-inspection',alt='Ein geöffnetes unauffälliges Paket mit einem gefalteten Pullover liegt neben einem Prüfgerät.',caption=FICTION),
 card('lab','Eine strengere Einstellung','Noch ein klar gekennzeichnetes Testmodell mit 10 beschädigten und 990 unbeschädigten Paketen: Eine andere Einstellung liefert 8 echte Alarme und 9 Fehlalarme. Sie übersieht nun 2 Schäden.\n\nDer Anteil echter Fälle unter den 17 Alarmen steigt auf rund 47.06 %. Gleichzeitig ist die Erkennung unter den Schäden von 9/10 auf 8/10 gefallen. Diese Veränderung ist für den beschriebenen Test gegeben, kein allgemeines Naturgesetz jeder Einstellungsänderung.'),
 card('decision','Welche Einstellung ist besser?','Du kennst die neuen Häufigkeiten, aber noch nicht die Folgen eines übersehenen Schadens oder die Kosten einer zusätzlichen Kontrolle.',probe=sc('Was fehlt für eine verantwortliche Auswahl?','Die Bedeutung und Kosten der verschiedenen Fehler','Nur ein möglichst eindrucksvoller Prozentwert','Die Annahme, jeder Fehlertyp sei gleich folgenlos','Eine Entscheidung verlangt neben Quoten auch eine Bewertung ihrer Folgen.')),
 card('transfer','Die Frage hinter der Technik','Ein Test liefert Hinweise. Eine Entscheidung legt fest, was darauf folgt: nochmals prüfen, markieren oder freigeben. Je nach Einsatz sind übersehene Probleme und unnötige Kontrollen verschieden teuer oder gefährlich.\n\nDu hast jetzt drei getrennte Werkzeuge: Bezugsgruppe nennen, alle Gruppen zählen und die Folgen der Entscheidung prüfen.',reveal='Ein einzelnes «90 %» genügt nicht. Du brauchst Ausgangshäufigkeit, Treffer, Fehlalarme und den Zweck der nachfolgenden Handlung. Erst dann wird aus einer Werbezahl ein brauchbares Urteil.')
],[number('Wie viele Alarme entstehen mit 8 echten und 9 falschen Meldungen?',17,'Alarme','8 + 9 = 17.'),number('Wie hoch ist der Anteil echter Fälle unter diesen 17 Alarmen ungefähr?',47.06,'%','8 / 17 × 100 ≈ 47.06 %.',0.02),number('Wie viele der 10 Schäden werden bei 8 echten Alarmen übersehen?',2,'Schäden','10 − 8 = 2.'),multi('Was gehört zur Entscheidung über die Einstellung?',['Folgen übersehener Schäden','Aufwand zusätzlicher Kontrollen','Nur die höchste Quote unabhängig von der Bezugsgruppe','Die Annahme, jeder Alarm sei ein Beweis'],[0,1],'Die Fehlerfolgen bestimmen mit, welcher Kompromiss vertretbar ist.'),sc('Was ist eine sinnvolle Rolle eines Alarms?','Eine weitere angemessene Prüfung auslösen','Die zusätzliche Prüfung ersetzen, sobald 90 % der vorhandenen Schäden erkannt werden','Den Zustand eines einzelnen Pakets allein aus der Trefferquote sicher bestimmen','Ein Hinweis kann nützlich sein, ohne bereits die endgültige Feststellung zu sein.')],
'Erst die Häufigkeiten verstehen, dann über die Folgen entscheiden.','Frage bei einer automatischen Warnung: Was bedeutet sie genau, und welche Prüfung folgt daraus?',B),
chapter(RECALL,1,'Die geschlossene Seite','Du unterscheidest Wiedererkennen von eigenständigem Abrufen.',[
 card('scene','Im Zug klingt alles vertraut','Du liest einen Absatz über den Buchdruck und nickst bei jedem Satz. Dann schliesst du das Buch und sollst den Mechanismus erklären. Plötzlich fehlt der Anfang.\n\nDas ist eine nützliche Beobachtung: Den sichtbaren Text wiederzuerkennen ist nicht dasselbe, wie die Erklärung ohne Vorlage selbst hervorzubringen.',image='recall-book',alt='Eine lernende Person am Zugtisch schliesst ein Buch und notiert eigene Gedanken.',caption=FICTION),
 card('lab','Versuch vor Kontrolle','Ein kleiner Abrufversuch kann so aussehen: Vorlage schliessen, die Kernidee in zwei eigenen Sätzen erklären, danach mit dem Original vergleichen. Das Wiederaufrufen ist dabei selbst Teil des Lernens. Es ist nicht nur eine Abschlusskontrolle.\n\nDie Aufgabe muss zu deinem Stand passen. Wenn dir die Grundlagen fehlen, brauchst du zunächst eine verständliche Erklärung oder ein ausgearbeitetes Beispiel.'),
 card('decision','Was zeigt eine eigene Erklärung?','Du willst prüfen, ob du einen Zusammenhang selbst rekonstruieren kannst.',probe=sc('Welche Handlung prüft das direkter?','Die Vorlage schliessen und den Zusammenhang aus dem Gedächtnis erklären','Denselben sichtbaren Absatz erneut als vertraut markieren','Nur zählen, wie lange das Buch geöffnet war','Ohne Vorlage musst du die Erklärung selbst abrufen. Vertrautheit und Lesezeit messen etwas anderes.')),
 card('reveal','Erst die Lücke, dann der nächste Schritt','Warum kann sich ein Abrufversuch schwieriger anfühlen und trotzdem nützlich sein?',reveal='Er macht sichtbar, was ohne Vorlage noch fehlt, und fordert das Wiederaufrufen. Schwierigkeit allein ist aber kein Qualitätssiegel: Die Aufgabe muss lösbar werden, und eine falsche Erklärung braucht Korrektur.')
],[recall('Wie heisst das Wiederaufrufen ohne sichtbare Vorlage?','Abrufen|Aktives Abrufen|Retrieval Practice|Active Recall','Du erzeugst die Antwort aus dem Gedächtnis, statt sie nur wiederzuerkennen.'),sc('Was misst blosses vertrautes Lesen nicht zuverlässig?','Ob du die Erklärung ohne Vorlage selbst hervorbringen kannst','Ob die Seite sichtbar ist','Ob du gerade Text ansiehst','Wiedererkennen und eigenständiger Abruf sind unterschiedliche Leistungen.'),order('Ordne einen einfachen Abrufversuch.',['Vorlage schliessen','Kernidee selbst erklären','Mit der Vorlage vergleichen'],'Die Kontrolle folgt auf den eigenen Versuch.'),multi('Was gehört zu einer hilfreichen Abrufübung?',['Eine zum Lernstand passende Aufgabe','Rückmeldung bei Fehlern','Möglichst unlösbare Fragen','Nur die Zahl geöffneter Seiten'],[0,1],'Der Abruf soll lernen helfen, nicht beliebige Überforderung erzeugen.'),sc('Ist jede schwierige Aufgabe automatisch lernwirksam?','Nein, Passung und Korrektur sind wichtig','Ja, Schwierigkeit allein genügt','Ja, auch ohne jede vorherige Erklärung','Schwierigkeit ist nur unter geeigneten Bedingungen hilfreich.')],
'Vertrautheit ist ein Gefühl; eigener Abruf ist ein prüfbarer Versuch.','Schliesse nach dem nächsten kurzen Lerntext die Vorlage und erkläre seine Kernaussage in zwei Sätzen.',R),
chapter(RECALL,2,'Der Fehler braucht eine Erklärung','Du nutzt Feedback, um ein falsches Modell zu korrigieren statt nur eine Antwortposition zu merken.',[
 card('decision','Du hast das Falsche sicher gewusst','Im fiktiven Lernversuch antwortest du: Eine Druckmaschine macht einen Text automatisch wahr. Die Rückmeldung zeigt, dass Kopiergenauigkeit und Wahrheit verschieden sind.',probe=sc('Welcher nächste Schritt verarbeitet die Korrektur am besten?','Den Unterschied in eigenen Worten an einem neuen Satz erklären','Nur merken, dass diesmal Antwort B richtig war','Die Rückmeldung ungelesen überspringen','Eine eigene Anwendung prüft, ob das korrigierte Modell verstanden wurde.')),
 card('evidence','Richtig markieren reicht nicht','Eine Rückmeldung sollte zeigen, warum etwas stimmt und wo die falsche Annahme lag. «Falsch» allein beschreibt das Ergebnis, aber nicht den Reparaturweg.\n\nBei unserem Beispiel kann ein Satz korrekt tausendmal kopiert sein und trotzdem sachlich falsch bleiben. Der Fehler lag in der Gleichsetzung von Verbreitung und Begründung, nicht bloss in einem verwechselten Buchstaben.'),
 card('lab','Eine kleine Gegenprobe','Nimm einen anderen Satz: «Die Maschine kopiert die falsche Jahreszahl exakt.» Ist die Übertragung korrekt? Ja. Ist die Jahreszahl deshalb wahr? Nein.\n\nSo wird aus dem Feedback eine überprüfte Unterscheidung. Danach sollte das Thema später erneut ohne Vorlage auftauchen; unmittelbares Nachsprechen allein belegt noch keine langfristige Erinnerung.'),
 card('reveal','Die gute Fehlermeldung','Welche zwei Informationen sollte eine hilfreiche Erklärung mindestens liefern?',reveal='Was an der richtigen Lösung begründet ist und welche Annahme an der falschen Lösung nicht trägt. Je nach Aufgabe kann ein ausgearbeitetes Beispiel oder ein neuer Anwendungsfall die Reparatur erleichtern.')
],[sc('Warum ist das Merken von Antwort B ein schwacher Lernschritt?','Es kann die Position statt des begrifflichen Unterschieds speichern','Weil wiederholtes Wiedererkennen allein bereits eine spätere eigene Erklärung sicherstellt','Weil dieselbe richtige Antwortposition eine Erklärung des zugrunde liegenden Modells ersetzt','Bei neuer Reihenfolge hilft nur das verstandene Prinzip.'),multi('Was sollte begründetes Feedback leisten?',['Die richtige Lösung nachvollziehbar machen','Die falsche Annahme sichtbar machen','Nur einen roten Punkt zeigen','Nur den Rang anderer Nutzer nennen'],[0,1],'Feedback soll die zugrunde liegende Erklärung verbessern.'),sc('Eine falsche Jahreszahl wird exakt kopiert. Welche Aussage stimmt?','Die Übertragung kann korrekt sein, obwohl der Inhalt falsch ist','Exakte Übertragung macht die Jahreszahl wahr','Falscher Inhalt verhindert technisch jede Kopie','Die Gegenprobe trennt zwei unterschiedliche Qualitätsfragen.'),order('Ordne eine sinnvolle Fehlerbearbeitung.',['Eigene Antwort prüfen','Fehlerannahme verstehen','Korrigiertes Prinzip auf einen neuen Fall anwenden'],'Das neue Beispiel prüft mehr als unmittelbares Nachsprechen.'),sc('Was beweist sofortiges korrektes Nachsprechen noch nicht?','Langfristiges Erinnern ohne Vorlage','Dass der Satz gerade gesehen wurde','Dass eine Rückmeldung existiert','Dauerhafte Erinnerung braucht eine spätere Prüfung.')],
'Ein Fehler ist erst bearbeitet, wenn du erklären kannst, was an deinem Modell nicht stimmte.','Wähle eine falsche Antwort und formuliere die korrigierte Unterscheidung selbst.',R),
chapter(RECALL,3,'Morgen statt nur noch einmal jetzt','Du verstehst, warum zeitlich verteiltes Wiederaufrufen einen anderen Zweck als sofortige Wiederholung erfüllt.',[
 card('scene','Ein neuer Morgen, dieselbe Frage','Du greifst am nächsten Tag erneut zur Frage nach Druckform und Wahrheit. Das Buch bleibt zunächst zu. Gestern konnte die Erklärung noch im unmittelbaren Arbeitskontext liegen; heute musst du sie erneut verfügbar machen.',image='recall-return',alt='An einem ruhigen Tisch wird neben geschlossenem Buch und früheren Notizen eine neue Karte aufgenommen.',caption=FICTION),
 card('evidence','Verteilen statt alles in einen Block packen','Zeitlich verteiltes Lernen und wiederholtes Abrufen unterstützen langfristiges Behalten. Das passende Intervall hängt unter anderem vom Inhalt, dem bisherigen Können und dem gewünschten Zeitraum ab.\n\nGate verwendet 1, 3, 7, 14 und 30 Tage als pragmatische Regel. Das ist keine universell optimale wissenschaftliche Formel. Fehler werden früher erneut aufgegriffen.'),
 card('decision','Heute fünfmal richtig','Du wiederholst dieselbe Antwort fünfmal direkt hintereinander. Das kann beim Verstehen helfen, ersetzt aber nicht fünf über Tage verteilte erfolgreiche Abrufe.',probe=sc('Warum zählt Gate das nicht als fünf langfristige Festigungen?','Weil kaum zeitlicher Abstand dazwischenlag','Weil eine richtige Antwort grundsätzlich wertlos ist','Weil Lernen nur einmal im Leben stattfinden darf','Kurzfristige Verfügbarkeit und spätere Wiederherstellung sind unterschiedliche Prüfbedingungen.')),
 card('transfer','Ein Thema pro Runde bleibt möglich','Verteilte Wiederholung verlangt nicht, dass eine laufende Geschichte plötzlich zu einem anderen Fach springt. Gate kann in einer späteren Runde genau dieses Thema wieder auswählen. Innerhalb der Runde bleibt der Zusammenhang erhalten.\n\nAbwechslung zwischen Lerngelegenheiten und Kohärenz innerhalb einer Lerngelegenheit schliessen sich nicht aus.')
],[sc('Was unterscheidet einen Abruf morgen von fünf sofortigen Wiederholungen?','Der grössere zeitliche Abstand verlangt erneute Verfügbarkeit','Morgen ist jede Erklärung automatisch falsch','Sofortige Wiederholung ist grundsätzlich verboten','Die Erinnerung wird unter anderen zeitlichen Bedingungen geprüft.'),multi('Wovon kann ein passender Wiederholungsabstand abhängen?',['Bisherigem Können','Gewünschtem Behaltezeitraum','Nur der sofortigen Vertrautheit des Texts unmittelbar nach dem Lesen','Einem für alle Inhalte garantierten einzigen Abstand'],[0,1],'Es gibt keine für jeden Inhalt und Menschen identische optimale Regel.'),sc('Wie sind Gates 1/3/7/14/30 Tage einzuordnen?','Als pragmatische Produktregel','Als universelles Naturgesetz','Als Beweis, dass danach nichts mehr vergessen wird','Die Regel ist hilfreich operationalisiert, aber nicht individuell wissenschaftlich optimiert.'),recall('Lernen über getrennte Zeitpunkte zu verteilen nennt man ___ Lernen.','verteiltes|zeitlich verteiltes','Zeitlicher Abstand unterscheidet es von einem einzigen Lernblock.',True),sc('Muss eine Wiederholungsfrage aus einem anderen Fach mitten in dieselbe Geschichte?','Nein, das andere Thema kann eine eigene spätere Runde bekommen','Ja, sonst kann Erinnerung grundsätzlich nicht funktionieren','Ja, unabhängig vom Lernziel','Zeitverteilung und thematisch zusammenhängende Runden lassen sich verbinden.')],
'Heute verstehen und später wieder hervorbringen sind zwei wichtige Teile desselben Lernwegs.','Plane eine spätere kurze Frage zum heutigen Inhalt, bevor du ihn als dauerhaft beherrscht betrachtest.',R),
chapter(RECALL,4,'Erkannt – auch im neuen Gewand?','Du prüfst Wissen an einem neuen Beispiel und benennst die Grenzen der Übertragung.',[
 card('lab','Nicht mehr dieselben Wörter','Du kennst jetzt den Unterschied zwischen Kopiergenauigkeit und Wahrheit. Neuer Fall: Ein Tabellenprogramm übernimmt einen falschen Eingangswert exakt in alle Berichte.\n\nDer gemeinsame Mechanismus ist die zuverlässige Verbreitung einer ungeprüften Vorlage. Das Programm kann korrekt übertragen und die Berichte können trotzdem inhaltlich falsch sein.'),
 card('decision','Was musst du prüfen?','Die Berechnungsformel stimmt, aber der eingegebene Grundwert ist falsch.',probe=sc('Welche Prüfung fehlt?','Die Qualität des Eingangswerts','Nur die Farbe der Tabellenlinien','Eine weitere identische Kopie desselben Berichts','Korrekte Weiterverarbeitung ersetzt keine Prüfung der Ausgangsinformation.')),
 card('evidence','Transfer ist mehr als ein bekanntes Stichwort','Transfer bedeutet hier, einen gelernten Zusammenhang in einer neuen Situation sinnvoll anzuwenden. Dazu musst du erkennen, was gleich ist und was sich unterscheidet. Eine Druckwerkstatt und eine Tabellenkalkulation sind keine identischen Systeme.\n\nIhre gemeinsame Struktur kann die Frage nach der Vorlage tragen. Andere historische oder technische Aussagen darfst du nicht ungeprüft mitübertragen.'),
 card('reveal','Dein fertiger Lernkreislauf','Erkläre in eigenen Worten, wie du aus einem gelesenen Absatz eine belastbarere Erinnerung machst.',reveal='Erst verständlich aufbauen. Dann ohne Vorlage abrufen. Fehler mit Begründung korrigieren. Später erneut abrufen. Schliesslich an einem veränderten Fall prüfen, was wirklich übertragbar ist. Kein Schritt garantiert dauerhaftes Wissen allein; zusammen machen sie den Lernstand sichtbarer.'),
 card('transfer','Ein gutes Ende statt einer weiteren Schleife','Wenn du den Kern erklären und anwenden kannst, darf diese Runde enden. Du musst nicht aus jedem freien Moment eine weitere App-Sitzung machen. Nimm den Gedanken in eine echte Aufgabe mit. Gate soll dir im Leben helfen, nicht möglichst viele Minuten in Gate sammeln.')
],[recall('Wie heisst die sinnvolle Anwendung eines gelernten Zusammenhangs in einer neuen Situation?','Transfer|Lerntransfer','Es geht um die Struktur, nicht bloss um identische Wörter.'),sc('Was verbindet die Druckform und den falschen Tabellen-Eingangswert?','Eine fehlerhafte Vorlage kann zuverlässig weiterverbreitet werden','Beide Systeme sind technisch vollständig identisch','Jede Vervielfältigung garantiert Wahrheit','Übertragbar ist ein bestimmter Mechanismus, nicht jede Eigenschaft.'),multi('Welche Schritte gehören zum beschriebenen Lernkreislauf?',['Ohne Vorlage abrufen','Fehler begründet korrigieren und später erneut prüfen','Nur richtige Antwortpositionen merken','Jede Analogie unbegrenzt ausdehnen'],[0,1],'Abruf und begründete Korrektur unterstützen ein überprüfbares Modell.'),order('Ordne den Lernkreislauf.',['Zusammenhang verstehen','Selbst abrufen','Fehler korrigieren','Später erneut prüfen','Auf einen veränderten Fall anwenden'],'Die Schritte bauen aufeinander auf, können im Alltag wiederkehren und bleiben am Lernziel ausgerichtet.'),sc('Was ist ein sinnvoller Abschluss der Runde?','Den gelernten Gedanken in einer echten Aufgabe anwenden','Möglichst lange ohne Ziel in der App bleiben','Aus jedem Fehler den Wert der Person ableiten','Lernen soll ausserhalb der App nutzbar werden.')],
'Du hast etwas mitgenommen, wenn du den Zusammenhang auch ohne Vorlage in einer passenden neuen Situation erkennst.','Wende heute einen einzigen gelernten Gedanken ausserhalb von Gate an und benenne seine Grenze.',R)
]
