from story_authoring import *

CASH=topic('cash','business','Volle Auftragsbücher. Leeres Konto.','Eine Möbelwerkstatt hat einen guten Auftrag – und kann ihre nächste Rechnung nicht bezahlen. Du musst herausfinden, warum.','Unternehmerisches Planspiel')
COMPOUND=topic('compound','money','Die zweite Verzinsung','Aus 1’000 werden 1’050. Was passiert danach – und welche Annahmen verschwinden in schönen Renditekurven?','Rechenlabor mit Gegenprobe')
CHIP=topic('chip','industries','Warum ein Chip noch lange kein Produkt ist','Du begleitest einen Wafer durch eine vereinfachte Fertigung und suchst den Engpass, der die verkaufbaren Stücke begrenzt.','Blick in die Fertigung')
TOPICS=[CASH,COMPOUND,CHIP]
C=source('OpenStax · Working Capital and Cash Cycle','https://openstax.org/books/principles-finance/pages/19-1-what-is-working-capital')
M=source('Investor.gov · Compound Interest Calculator','https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator')
A=source('ASML · Lithography principles','https://www.asml.com/en/technology/lithography-principles')
LESSONS=[
chapter(CASH,1,'Der Auftrag sieht gut aus','Du unterscheidest das Ergebnis eines Auftrags von der heutigen Zahlungsfähigkeit.',[
 card('scene','Acht Stühle, eine unangenehme Frage','Fiktive Möbelwerkstatt, vereinfachtes Modell: Ein Auftrag bringt 8’000 CHF Umsatz. Die zugehörigen Kosten betragen insgesamt 6’000 CHF. Andere Kosten und Steuern lassen wir ausdrücklich weg. Das rechnerische Auftragsergebnis beträgt also 2’000 CHF.\n\nHeute liegen aber nur 1’000 CHF auf dem Konto. Morgen werden 3’000 CHF für Material fällig. Der Kunde zahlt erst später.',image='cash-workshop',alt='Ein Möbelbauer betrachtet zwischen fertigen Stühlen eine Rechnung.',caption=FICTION),
 card('decision','Kannst du morgen bezahlen?','Die offene Kundenrechnung ist eine Forderung: ein Anspruch auf eine spätere Zahlung. Sie ist noch kein verfügbares Kontoguthaben.',probe=number('Wie viele CHF fehlen morgen für die Materialzahlung?',2000,'CHF','3’000 fällig minus 1’000 vorhanden = 2’000 CHF unmittelbare Lücke.')),
 card('evidence','Zwei Fragen, zwei Antworten','Ergebnisfrage: Was bleibt vom Umsatz nach den berücksichtigten Kosten? Liquiditätsfrage: Ist zum Zahlungstermin genug verfügbares Geld vorhanden?\n\nEin positiver Auftrag kann eine Liquiditätslücke erzeugen, wenn die Ausgaben vor der Kundenzahlung liegen. Das ist kein Rechenwiderspruch, sondern eine Zeitfrage.',visual=bars('Morgen, nicht irgendwann',['Verfügbares Guthaben','Fällige Materialzahlung'],[1000,3000],'CHF im erfundenen Fall; die spätere Forderung ist kein heutiges Guthaben.')),
 card('transfer','Die bessere erste Rückfrage','Wenn jemand sagt, das Geschäft laufe gut, frage zusätzlich: Wann kommt das Geld tatsächlich an und wann müssen wir bezahlen? Eine Umsatzliste allein beantwortet das nicht. Eine bestehende Lücke verlangt rechtzeitig geklärte Finanzierung oder vereinbarte andere Zahlungszeitpunkte, nicht bloss Optimismus.')
],[number('Wie hoch ist das vereinfachte Auftragsergebnis bei 8’000 Umsatz und 6’000 Kosten?',2000,'CHF','8’000 minus 6’000 = 2’000 CHF; weitere Kosten sind im Modell ausgeschlossen.'),number('Wie gross ist die morgige Lücke bei 1’000 Guthaben und 3’000 fälliger Zahlung?',2000,'CHF','3’000 minus 1’000 = 2’000 CHF.'),recall('Wie nennt man die Fähigkeit, fällige Zahlungen leisten zu können?','Liquidität|Zahlungsfähigkeit|Liquiditaet','Liquidität ist nicht mit dem rechnerischen Gewinn gleichzusetzen.'),sc('Warum zählt die offene Rechnung nicht wie Kontoguthaben?','Die Zahlung ist noch nicht eingegangen','Sie ist deshalb zwangsläufig wertlos','Umsatz wird nie bezahlt','Eine Forderung kann wertvoll sein, ohne heute liquide zu sein.'),multi('Welche Daten braucht ein kurzfristiger Zahlungsplan?',['Termine der Auszahlungen','Erwartete Termine der Einzahlungen','Nur die Anzahl der Stühle','Nur den Gesamtumsatz'],[0,1],'Die zeitliche Reihenfolge bestimmt die zwischenzeitliche Lücke.')],
'Ein Auftrag kann sich rechnen und trotzdem vorher Geld benötigen.','Erkläre die Werkstattlücke jemandem, ohne das Wort Gewinn mit Kontostand gleichzusetzen.',C),
chapter(CASH,2,'Der tiefste Punkt im Monat','Du findest die grösste zwischenzeitliche Finanzierungslücke statt nur den Endsaldo.',[
 card('lab','Lege die Zahlungen auf eine Zeitachse','Dasselbe Modell, jetzt vollständig: Startguthaben 1’000 CHF. Tag 1: 3’000 CHF Material. Tag 14: weitere 3’000 CHF für die im Auftrag berücksichtigte Arbeit. Tag 30: 8’000 CHF Kundenzahlung.\n\nOhne zusätzliche Finanzierung ergäbe die Rechnung nach Tag 1 einen Saldo von −2’000, nach Tag 14 von −5’000 und nach Tag 30 von +3’000 CHF. Negative Modellwerte bedeuten einen ungedeckten Bedarf, keine automatische Bankzusage.',visual=chain('Zahlungsfolge',['Start: +1’000 CHF','Tag 1: −3’000 CHF Auszahlung','Tag 14: −3’000 CHF Auszahlung','Tag 30: +8’000 CHF Einzahlung'],'Der tiefste rechnerische Saldo ist −5’000 CHF.')),
 card('reveal','Das Monatsende sieht harmlos aus','Am Monatsende stehen rechnerisch 3’000 CHF da. Weshalb kann die Werkstatt trotzdem schon an Tag 14 scheitern?',reveal='Weil die Zahlung am Tag 30 die frühere Fälligkeit nicht bedient. Bis Tag 14 muss ein Bedarf von insgesamt 5’000 CHF gedeckt sein. Der positive Endsaldo verdeckt die zeitliche Lücke.'),
 card('decision','Welche Zahl gehört ins Gespräch?','Die Werkstatt klärt vorab eine mögliche Überbrückung. Ein Sicherheitszuschlag ist im Modell noch nicht enthalten.',probe=number('Wie gross ist die höchste ungedeckte Lücke ohne Puffer?',5000,'CHF','1’000 Anfangsgeld minus 6’000 frühere Auszahlungen ergibt −5’000 CHF.')),
 card('evidence','Eine Prognose ist keine Zusage','Die Kundenzahlung an Tag 30 ist eine Planannahme. Verspätungen oder zusätzliche Ausgaben können die Lücke vergrössern oder verlängern. Deshalb sind Planwerte, bestätigte Zahlungen und verfügbare Finanzierungszusagen getrennte Informationen.\n\nDer Plan soll Unsicherheit sichtbar machen. Er verwandelt eine Hoffnung nicht in Geld.')
],[number('Wie lautet der rechnerische Endsaldo nach allen Modellzahlungen?',3000,'CHF','1’000 − 3’000 − 3’000 + 8’000 = 3’000.'),number('Wie gross ist die maximale Finanzierungslücke vor der Kundenzahlung?',5000,'CHF','Nach Tag 14 fehlen insgesamt 5’000 CHF.'),sc('Warum genügt ein positiver Monatssaldo nicht?','Frühere fällige Zahlungen können ungedeckt sein','Positive Salden sind immer falsch','Der Umsatz wird dadurch automatisch kleiner','Zahlungsfähigkeit muss zu den jeweiligen Terminen bestehen.'),order('Ordne die Zahlungen chronologisch.',['Materialzahlung an Tag 1','Arbeitszahlung an Tag 14','Kundenzahlung an Tag 30'],'Die Kundenzahlung folgt beiden Auszahlungen.'),multi('Welche Informationen sollten getrennt bleiben?',['Geplante Kundenzahlung','Tatsächlich verfügbare Finanzierung','Eine negative Zahl als automatische Kreditbewilligung','Ein erwarteter Eingang als bereits verbuchte Einzahlung'],[0,1],'Planannahmen und gesicherte Mittel sind nicht identisch.')],
'Liquiditätsplanung sucht den tiefsten Zwischenstand, nicht nur ein schönes Monatsende.','Zeichne für die Werkstatt die drei Zahlungen in Reihenfolge und nenne den grössten Bedarf.',C),
chapter(CASH,3,'Eine Anzahlung löst nicht alles','Du prüfst Zahlungsbedingungen rechnerisch, statt ihre Wirkung zu überschätzen.',[
 card('scene','Bei der Übergabe wird die Vereinbarung konkret','Die Werkstatt bespricht mit dem Kunden eine andere Zahlungsfolge: 50 % des Auftrags, also 4’000 CHF, vor Arbeitsbeginn. Die restlichen 4’000 folgen an Tag 30. Beide Seiten müssen diese Bedingungen tatsächlich vereinbaren; sie gelten nicht durch Wunschdenken.',image='cash-delivery',alt='Möbelbauer und Kundin prüfen bei einem Stuhl eine Auftragsunterlage.',caption=FICTION),
 card('lab','Rechne den Engpass erneut','Start 1’000 plus Anzahlung 4’000 ergibt 5’000 CHF. Nach 3’000 Material verbleiben 2’000. Nach weiteren 3’000 an Tag 14 fehlen immer noch 1’000 CHF.\n\nDie Anzahlung verringert den maximalen Bedarf von 5’000 auf 1’000. Sie beseitigt ihn nicht vollständig. Das Gesamtergebnis des Auftrags bleibt im Modell unverändert; nur die Zahlungszeitpunkte verschieben sich.'),
 card('decision','Die zweite Etappe','Eine Alternative: Die zweite Hälfte wird nach einer vereinbarten Teilabnahme rechtzeitig vor der Auszahlung an Tag 14 fällig und geht tatsächlich ein.',probe=sc('Was verändert dies im Modell?','Die restliche Lücke kann geschlossen werden, ohne den Gesamtpreis zu erhöhen','Das Auftragsergebnis verdoppelt sich automatisch','Die erste Materialzahlung entfällt','Früheres Geld verändert die Liquidität, nicht automatisch den Preis oder die Kosten.')),
 card('transfer','Auch der Kunde trägt ein Risiko','Eine hohe Vorauszahlung verlagert Risiko auf den Kunden. Nachvollziehbare Meilensteine, klare Leistung und verlässliche Abnahme können die Vereinbarung fairer machen. Eine Zahlungsbedingung ist Teil einer beiderseitigen Geschäftsbeziehung, kein Trick, mit dem eine Seite jede Unsicherheit verschwinden lässt.')
],[number('Wie viel sind 50 % von 8’000 CHF?',4000,'CHF','Die Hälfte des Auftragswerts sind 4’000 CHF.'),number('Welche maximale Lücke bleibt mit 4’000 CHF Anzahlung und sonst gleichem Ablauf?',1000,'CHF','1’000 + 4’000 − 3’000 − 3’000 = −1’000 CHF.'),sc('Was ändert die frühere Zahlung bei gleichem Preis und gleichen Kosten unmittelbar?','Die Liquidität im Zeitverlauf','Das Auftragsergebnis von 2’000 auf 4’000 CHF','Die Materialkosten von 3’000 auf null','Ein Zahlungszeitpunkt ist keine zusätzliche Leistung und kein zusätzlicher Umsatz.'),multi('Was macht einen Zahlungsmeilenstein belastbarer?',['Klare vereinbarte Leistung','Ein rechtzeitiger tatsächlicher Zahlungseingang','Nur der Wunsch des Lieferanten','Eine mündlich erhoffte Zahlung ohne Klärung'],[0,1],'Planung braucht Vereinbarung und verfügbare Mittel.'),sc('Welches Risiko kann eine Vorauszahlung beim Kunden erhöhen?','Geld ist bezahlt, bevor die vereinbarte Leistung vollständig geliefert ist','Er muss grundsätzlich gar nichts mehr prüfen','Der Auftragspreis wird mathematisch immer doppelt so hoch','Vorauszahlung verschiebt Leistungsrisiko und verlangt Vertrauen oder Absicherung.')],
'Zahlungsbedingungen verändern den Geldbedarf – und die Risikoverteilung zwischen den Beteiligten.','Prüfe beim Werkstattfall, welcher konkrete Meilenstein die verbleibende Lücke schliessen könnte.',C),
chapter(CASH,4,'Zu schnell gewachsen','Du erkennst, wie mehrere rentable Aufträge den Vorfinanzierungsbedarf vergrössern können.',[
 card('decision','Drei Kunden statt einem','Zurück zur ursprünglichen Zahlungsfolge ohne Anzahlung: Drei identische Aufträge starten gleichzeitig. Sie bringen zusammen 24’000 CHF, verursachen vorher 18’000 CHF Kosten und der Betrieb hat weiterhin nur 1’000 CHF Startguthaben.',probe=number('Wie gross ist die Lücke vor den Kundenzahlungen?',17000,'CHF','18’000 frühere Auszahlungen minus 1’000 vorhandenes Geld = 17’000 CHF.')),
 card('evidence','Wachstum bindet Geld','Der vereinfachte Auftragserfolg steigt auf 6’000 CHF. Der vorherige Finanzierungsbedarf steigt aber ebenfalls. Mehr Umsatz heilt eine zeitliche Lücke nicht zwangsläufig; parallele Aufträge können sie vergrössern.\n\nDie konkreten Zahlen hängen von Lagerdauer, Zahlungsfristen und Abläufen ab. Es ist der Mechanismus der Vorfinanzierung, nicht eine Behauptung, Wachstum sei grundsätzlich schlecht.'),
 card('lab','Welche Stellschraube wirkt wann?','Gestaffelte Auftragsstarts können Ausgaben entzerren. Vereinbarte Meilensteinzahlungen können Eingänge vorziehen. Kürzere Durchlaufzeiten können gebundenes Kapital früher freisetzen. Eine zugesagte Finanzierung kann verbleibende Lücken überbrücken.\n\nJede Variante hat Kosten, Risiken und Grenzen. Lieferanten einfach unvereinbart später zu bezahlen ist keine saubere Planungsstrategie.',visual=compare('Vier unterschiedliche Hebel',['Zeit: Auftragsstarts staffeln','Eingang: Zahlung an Leistungen koppeln','Ablauf: Durchlaufzeit prüfen','Puffer: Finanzierung vorab klären'],'Erst nachrechnen, dann über die passende Kombination entscheiden.')),
 card('transfer','Dein Urteil über die Werkstatt','Du bekommst nur die Meldung «Umsatz verdreifacht». Welche drei Rückfragen stellst du jetzt?',reveal='Zum Beispiel: Wie hoch sind die zugehörigen Kosten? Wann fliesst das Geld tatsächlich? Wie ist der höchste Zwischenbedarf gedeckt? Erst zusammen beschreiben Ergebnis und Liquiditätsplan ein belastbareres Bild.')
],[number('Wie hoch ist das vereinfachte Ergebnis von drei Aufträgen mit je 2’000 CHF Ergebnis?',6000,'CHF','3 × 2’000 = 6’000 CHF.'),number('Wie gross ist der Vorfinanzierungsbedarf bei 18’000 frühen Auszahlungen und 1’000 Guthaben?',17000,'CHF','18’000 − 1’000 = 17’000 CHF.'),sc('Warum kann schnelleres Wachstum die Lage verschärfen?','Mehr Auszahlungen fallen an, bevor die Kundenzahlungen eintreffen','Jeder Umsatzanstieg erzeugt zwangsläufig Verlust','Kunden dürfen bei Wachstum nicht mehr bezahlen','Die Zeitstruktur der Zahlungsströme ist entscheidend.'),multi('Welche Massnahmen sind grundsätzlich prüfbare Liquiditätshebel?',['Vereinbarte Meilensteinzahlungen','Gestaffelte Auftragsstarts','Fällige Rechnungen ohne Absprache ignorieren','Forderungen als bereits vorhandenes Bargeld zählen'],[0,1],'Die ersten beiden verändern Zeitpunkte nachvollziehbar.'),sc('Welche Aussage fasst den Fall am besten zusammen?','Ergebnis und zwischenzeitliche Zahlungsfähigkeit müssen zusammen geplant werden','Ein guter Auftrag braucht nie Vorfinanzierung','Mehr Umsatz ersetzt jede Liquiditätsplanung','Wirtschaftlichkeit und Zahlungszeitpunkte beantworten verschiedene notwendige Fragen.')],
'Ein Unternehmen wächst nicht nur in den Umsatz hinein, sondern oft auch in einen grösseren Geldbedarf.','Nimm einen fiktiven Auftrag und notiere Ergebnis, Einzahlungen, Auszahlungen und höchsten Zwischenbedarf.',C),
chapter(COMPOUND,1,'Wer verdient im zweiten Jahr mit?','Du berechnest Zinseszins und unterscheidest ihn von einer blossen linearen Fortschreibung.',[
 card('scene','Der Anfang ist unspektakulär','Ein reines Rechenmodell: 1’000 CHF bleiben zwei Jahre angelegt. Der jährliche Zins beträgt konstant 5 %, die Erträge bleiben im Konto. Kosten, Steuern, Inflation und Risiko sind vorerst ausgeschlossen. Dies ist keine Empfehlung und kein Renditeversprechen.\n\nNach dem ersten Jahr stehen 1’050 CHF da. Jetzt entscheidet sich, ob du das Modell wirklich verstanden hast.',image='compound-start',alt='Eine Person legt eine Münze in ein schlichtes Sparglas neben einem Notizbuch.',caption=FICTION),
 card('reveal','Sind es noch einmal genau 50?','Im zweiten Jahr werden nicht nur die ursprünglichen 1’000 verzinst, sondern auch die bereits gutgeschriebenen 50. Rechne 5 % von 1’050.',reveal='Das sind 52.50 CHF. Am Ende stehen 1’102.50 CHF da. Die zusätzlichen 2.50 gegenüber zweimal 50 entstehen durch die Verzinsung des ersten Ertrags.'),
 card('decision','Wenn der erste Ertrag ausgegeben wird','Du entnimmst die ersten 50 CHF sofort. Für das zweite Jahr bleiben nur 1’000 CHF im Modellkonto.',probe=sc('Wie viel Zins entsteht dann im zweiten Jahr bei gleichen 5 %?','50 CHF','52.50 CHF','100 CHF','Die Verzinsungsbasis ist wieder 1’000 CHF. Entnommene Erträge arbeiten dort nicht weiter.')),
 card('evidence','Der Mechanismus in drei Punkten','Zeit, Verzinsungsbasis und Wiederanlage wirken zusammen. Die Formel für konstante jährliche Verzinsung lautet: Endwert = Startwert × (1 + Zinssatz)^Jahre. Dabei wird 5 % als 0.05 eingesetzt.\n\nDie Formel beschreibt genau ihre Annahmen. Sie sagt nicht, dass ein reales Anlageprodukt jedes Jahr denselben positiven Ertrag liefert.',visual=bars('Konstantes 5-%-Modell',['Start','Jahr 1','Jahr 2'],[1000,1050,1102.5],'CHF; ohne Kosten, Steuern, Inflation und Schwankungen.'))
],[number('Wie hoch ist der Modellendwert nach zwei Jahren?',1102.5,'CHF','1’000 × 1.05 × 1.05 = 1’102.50.'),number('Wie viel Zins fällt im zweiten Jahr auf 1’050 CHF bei 5 % an?',52.5,'CHF','1’050 × 0.05 = 52.50.'),recall('Wie nennt man die Verzinsung bereits gutgeschriebener Zinsen?','Zinseszins','Der frühere Ertrag wird Teil der neuen Verzinsungsbasis.'),sc('Was passiert bei Entnahme des ersten Jahreszinses im Modell?','Der entnommene Betrag wird im Konto nicht weiter verzinst','Die Entnahme verdoppelt die Verzinsungsbasis','Der zweite Jahreszins bleibt zwingend 52.50 CHF','Für die neue Zinsrechnung zählt das tatsächlich verbleibende Kapital.'),multi('Welche Annahmen gelten ausdrücklich für diese Rechnung?',['Konstanter Jahreszins','Keine Kosten oder Steuern','Garantierte reale Börsenrendite','Automatische Verdopplung nach zwei Jahren'],[0,1],'Das Modell ist keine Zusage für ein reales Produkt.')],
'Zinseszins entsteht, wenn Erträge zur Basis künftiger Erträge werden.','Erkläre mit 1’000, 50 und 2.50 CHF, wo der Unterschied zur linearen Rechnung entsteht.',M),
chapter(COMPOUND,2,'Ein Prozentpunkt bleibt nicht klein','Du vergleichst zwei Netto-Wachstumsraten, ohne Gebühren und Rendite zu verwechseln.',[
 card('lab','Zwei vereinfachte Konten','Konto A wächst im Modell jährlich netto um 5 %, Konto B netto um 4 %. Beide starten mit 1’000 CHF. Nach einem Jahr sind es 1’050 und 1’040. Nach zwei Jahren 1’102.50 und 1’081.60.\n\nHier vergleichen wir direkt vorgegebene Nettoraten. In realen Produkten können Gebühren zu unterschiedlichen Zeitpunkten und nach unterschiedlichen Regeln abgezogen werden.'),
 card('reveal','Warum wächst der Abstand?','Nach einem Jahr beträgt die Differenz 10 CHF, nach zwei Jahren 20.90 CHF. Warum nicht genau 20?',reveal='Der erste Unterschied verändert bereits die Kapitalbasis für das nächste Jahr. A verzinst 1’050, B nur 1’040 und zudem mit einer anderen Rate. Die Pfade laufen dadurch zunehmend auseinander.'),
 card('decision','Eine schöne Bruttozahl','Ein Angebot nennt nur eine hohe Bruttorendite. Kosten und deren Berechnung stehen getrennt im Dokument.',probe=sc('Welche Information fehlt für einen sinnvollen Vergleich?','Welche Kosten wann anfallen und welcher Nettoverlauf daraus folgt','Nur die Farbe der Darstellung','Ausschliesslich die Zahl der Werbeanzeigen','Brutto und netto können unterschiedliche Ergebnisse beschreiben. Die tatsächliche Kostenregel muss bekannt sein.')),
 card('transfer','Rechne vor dem Urteil','Ein niedrigerer Kostensatz macht ein riskantes Produkt nicht automatisch passend. Vergleiche auch Risiko, Zeitraum und die tatsächliche Leistung. Diese Lektion lehrt den Rechenmechanismus eines dauerhaften Unterschieds, nicht die Auswahl eines bestimmten Produkts.',visual=bars('Nach zwei Jahren: Nettomodell',['5 % netto','4 % netto'],[1102.5,1081.6],'Gleicher Startbetrag; konstante Nettoraten ohne weitere Abzüge.'))
],[number('Wie viel ergibt 1’000 × 1.04 × 1.04?',1081.6,'CHF','Nach Jahr 1 sind es 1’040, nach Jahr 2 1’081.60.'),number('Wie gross ist die Differenz zwischen 1’102.50 und 1’081.60?',20.9,'CHF','1’102.50 − 1’081.60 = 20.90.'),sc('Warum kann ein dauerhafter Ratenunterschied wachsen?','Frühere Unterschiede verändern die nächste Kapitalbasis','Prozentpunkte und Franken sind immer identisch','Es gibt unabhängig vom Kapital jedes Jahr denselben festen Frankenbetrag','Beide Raten wirken auf die jeweils weiterentwickelte Basis.'),multi('Was gehört in einen brauchbaren Produktvergleich?',['Tatsächliche Kostenregeln','Risiko und Zeitraum','Nur die beworbene Bruttorendite','Nur der höchste mögliche Endwert'],[0,1],'Ein Nettovergleich braucht mehr als einen Werbewert.'),recall('Die Rendite nach den berücksichtigten Abzügen nennen wir hier ___rendite.','Netto|Nettorendite','Netto bezieht die jeweils berücksichtigten Kosten ein.',True)],
'Ein dauerhafter kleiner Unterschied wirkt auch auf alle späteren Berechnungsgrundlagen.','Prüfe bei einer Renditegrafik, ob die Zahlen brutto oder netto angegeben sind.',M),
chapter(COMPOUND,3,'Plus zwanzig, minus zwanzig','Du erkennst, warum entgegengesetzte Prozentsätze sich nicht zwingend aufheben.',[
 card('decision','Die vermeintliche Nullrunde','Neues Rechenmodell: 1’000 CHF steigen um 20 % auf 1’200 CHF. Danach fällt der Wert um 20 % des dann vorhandenen Betrags.',probe=number('Wie viele CHF bleiben?',960,'CHF','1’200 × 0.80 = 960. Der Verlust von 240 ist grösser als der vorherige Gewinn von 200.')),
 card('evidence','Dieselbe Prozentzahl, andere Basis','Das arithmetische Mittel von +20 % und −20 % ist null. Der tatsächlich zusammengesetzte Wertverlauf ist aber 1.20 × 0.80 = 0.96, also insgesamt −4 %.\n\nDie Reihenfolge dieser beiden reinen Faktoren ändert ohne Ein- oder Auszahlungen den Endwert nicht. Mit zwischenzeitlichen Einzahlungen oder Entnahmen können Zeitpunkte hingegen wichtig werden.'),
 card('scene','Wachstum ist kein glatter Fahrstuhl','Ein Bild von Wachstum kann verführerisch gleichmässig wirken. Reale Wertentwicklungen schwanken. Die Illustration mit den Pflanzen ist eine Metapher, kein Finanzmodell und keine Prognose.',image='compound-weather',alt='Zwei junge Pflanzen stehen am Fenster; eine ist abgestützt, die andere neigt sich im Luftzug.',caption='KI-Illustration · Wachstumsmetapher, kein Diagramm und keine Renditeprognose.'),
 card('reveal','Was bedeutet das für schöne Kurven?','Welche Frage stellst du, wenn eine Grafik jedes Jahr dieselbe positive Rendite zeigt?',reveal='Ist das eine Modellannahme oder ein nachgewiesener Verlauf? Welche Schwankungen, Einzahlungen, Kosten und Risiken fehlen? Eine Kurve kann mathematisch korrekt sein und für eine reale Entscheidung trotzdem zu wenig Information enthalten.')
],[number('Wie lautet der Endwert von 1’000 nach +20 % und danach −20 %?',960,'CHF','1’000 × 1.2 × 0.8 = 960.'),number('Wie hoch ist der Gesamtverlust in Prozent?',4,'%','40 CHF Verlust von ursprünglich 1’000 entsprechen 4 %.'),sc('Warum heben sich +20 % und −20 % nicht auf?','Sie beziehen sich auf unterschiedliche Kapitalbeträge','Negative Prozentwerte sind mathematisch unzulässig','Zwanzig Prozent bedeutet immer 200 CHF','Die zweite Veränderung wirkt auf 1’200 statt auf 1’000.'),multi('Welche Angaben helfen, eine Renditekurve einzuordnen?',['Ob sie Modell oder beobachteter Verlauf ist','Welche Einzahlungen und Kosten berücksichtigt sind','Ob die Linie besonders glatt ist','Ob das Bild Wachstum symbolisiert'],[0,1],'Die Modellannahmen sind wichtiger als die grafische Wirkung.'),sc('Ändert das Vertauschen dieser beiden Faktoren ohne Zwischenzahlungen den Endwert?','Nein, 1.2 × 0.8 und 0.8 × 1.2 ergeben beide 0.96','Ja, dann werden daraus automatisch 1’040 CHF','Ja, Verluste können dann nicht auftreten','Die reine Multiplikation ist vertauschbar; Geldflüsse würden die Fragestellung verändern.')],
'Prozentsätze brauchen eine Bezugsgrösse. Durchschnitt und zusammengesetzter Verlauf sind nicht dasselbe.','Rechne einen Verlust und eine gleich grosse prozentuale Erholung selbst durch, bevor du von Ausgleich sprichst.',M),
chapter(COMPOUND,4,'Was kannst du dir davon kaufen?','Du unterscheidest nominalen Geldbetrag, Kaufkraft und Sparbeitrag.',[
 card('lab','Mehr Franken, nicht gleich viel mehr Kaufkraft','Modell: Dein Geld wächst netto um 4 %, das betrachtete Preisniveau steigt um 2 %. Aus 1’000 werden 1’040 CHF. Was zuvor 1’000 gekostet hat, kostet nun 1’020.\n\nDer Kaufkraftfaktor ist 1.04 / 1.02, ungefähr 1.0196. Die reale Veränderung liegt bei rund 1.96 %. Einfach 4 minus 2 ergibt eine brauchbare Näherung, nicht den exakten Wert.'),
 card('decision','Die Einzahlung nicht als Rendite verkaufen','Ein Konto startet mit 1’000 CHF, du zahlst 100 CHF zusätzlich ein und am Ende liegen 1’100 CHF darin. Im Beispiel gibt es keinen Ertrag.',probe=sc('Welche Aussage stimmt?','Das Vermögen stieg durch die Einzahlung, nicht durch Rendite','Das Konto erzielte zwingend 10 % Rendite','Die Einzahlung zählt als Zinseszins','Ein selbst eingezahlter Franken ist kein erwirtschafteter Ertrag.')),
 card('evidence','Drei getrennte Beiträge','Eigenes Sparen verändert, wie viel du einzahlst. Rendite verändert den Wert des angelegten Kapitals. Preisänderungen beeinflussen, was du dir dafür kaufen kannst. Gebühren und Steuern können den verfügbaren Betrag zusätzlich verändern.\n\nEin ehrlicher Vergleich benennt diese Bestandteile. Er verwechselt eine disziplinierte Einzahlung nicht mit einer aussergewöhnlichen Anlageleistung.',visual=compare('Drei Fragen an den Endwert',['Sparen: Wie viel habe ich selbst eingezahlt?','Ertrag: Was entstand zusätzlich durch die Anlage?','Kaufkraft: Welche Preise stehen dem Geld gegenüber?'],'Bildungsmodell, keine individuelle Anlageempfehlung.')),
 card('transfer','Prüfe den Rechner wie einen Vertrag','Öffnest du einen Zinsrechner, kontrolliere Startbetrag, Einzahlungen, Rate, Verzinsungsintervall und Kostenannahmen. Das Ergebnis ist dann ein Wenn-dann-Szenario. Es wird nicht zur Prognose, nur weil es auf zwei Nachkommastellen genau angezeigt wird.',reveal='Die entscheidende Gewohnheit: Erst die Annahmen lesen, dann die grosse Endzahl. Präzision in der Darstellung ist keine Sicherheit über die Zukunft.')
],[number('Wie hoch ist die reale Veränderung bei 4 % Nettowachstum und 2 % Preissteigerung ungefähr? Antworte in Prozent auf zwei Dezimalstellen.',1.96,'%','(1.04 / 1.02 − 1) × 100 ≈ 1.96 %.',0.02),sc('1’000 Start, 100 Einzahlung, 1’100 Endwert ohne Ertrag: Was verursachte den Anstieg?','Die eigene Einzahlung','Eine Rendite von 10 %','Die Inflation','Der gesamte Zuwachs stammt hier aus zusätzlichem Kapital.'),recall('Was beschreibt, wie viel du dir für einen Geldbetrag kaufen kannst?','Kaufkraft','Nominaler Betrag und reale Kaufmöglichkeiten sind zu unterscheiden.'),multi('Welche Vorgehensweisen machen die Modellrechnung nachvollziehbarer?',['Einzahlungszeitpunkte ausdrücklich festlegen','Verzinsungsintervall und Kosten offenlegen','Den nominalen Endwert mit garantierter Kaufkraft gleichsetzen','Eine vergangene Jahresrendite stillschweigend für alle Folgejahre fortschreiben'],[0,1],'Die Eingaben bestimmen die Aussage des Modells.'),sc('Warum ist eine genaue Modellzahl keine sichere Zukunftsprognose?','Weil die eingesetzten Annahmen in der Realität anders ausfallen können','Weil korrekte Mathematik keine Bedeutung hat','Weil ein Endwert nie berechnet werden darf','Rechenpräzision ist etwas anderes als Vorhersagesicherheit.')],
'Ein guter Endwert trennt eigenes Geld, erwirtschafteten Ertrag und tatsächliche Kaufkraft.','Nimm eine Renditebehauptung und benenne mindestens zwei Annahmen, die du vor einer Entscheidung kennen müsstest.',M),
chapter(CHIP,1,'Ein Muster wird übertragen','Du erklärst die Rolle der Lithografie, ohne sie mit der gesamten Chipherstellung gleichzusetzen.',[
 card('scene','Der Wafer ist noch kein fertiger Rechner','Du betrittst gedanklich eine Halbleiterfertigung. Auf einem Siliziumwafer werden viele Chipstrukturen verarbeitet. Die dargestellte Reinraumszene ist illustrativ, keine Dokumentation einer konkreten Anlage.\n\nLithografie ist ein Teil dieses Prozesses: Ein Muster wird mithilfe von Licht auf eine lichtempfindliche Schicht übertragen.',image='chip-wafer',alt='Eine Reinraumtechnikerin hält einen strukturierten Siliziumwafer am Rand.',caption='KI-Szenenbild · vereinfachte Fertigungsszene, keine Aufnahme einer bestimmten Fabrik.'),
 card('evidence','Die Vorlage ist nicht das fertige Bauteil','Eine Maske oder ein Retikel enthält eine Mustervorlage. Optik und Belichtung übertragen ein verkleinertes Muster auf die vorbereitete Oberfläche. Diese Beschreibung ist bewusst vereinfacht; unterschiedliche Verfahren nutzen unterschiedliche optische Systeme.\n\nAus dem übertragenen Muster allein entsteht noch kein vollständig funktionierender Chip. Weitere Bearbeitungsschritte und zahlreiche Schichten folgen.'),
 card('decision','Was ist hier die Leistung der Lithografie?','Jemand sagt: Die Maschine druckt in einem einzigen Schritt ein fertiges Smartphone-Gehirn.',probe=sc('Welche Korrektur ist am präzisesten?','Sie überträgt Muster in einem mehrstufigen Fertigungsprozess','Sie produziert ausschliesslich die Verpackung','Jede Belichtung prüft bereits alle späteren Softwarefunktionen','Lithografie ist zentral, aber nicht mit sämtlichen Fertigungs- und Prüfschritten identisch.')),
 card('lab','Die Schablonen-Analogie','Eine Schablone hilft, ein Muster wiederholt zu übertragen. Sie ist hier nur eine grobe Analogie. Bei Halbleitern geht es um sehr kleine Strukturen, lichtempfindliche Materialien und hochpräzise Ausrichtung. Übernimm den Mechanismus der Musterübertragung, nicht die Vorstellung, eine Fabrik sei ein einfacher Papierdrucker.',visual=chain('Vereinfachte Musterübertragung',['Mustervorlage','Optische Belichtung','Muster in lichtempfindlicher Schicht','Weitere Bearbeitung'],'Keine technische Bauanleitung und kein vollständiger Prozessplan.'))
],[recall('Wie heisst das beschriebene Verfahren der lichtgestützten Musterübertragung?','Lithografie|Lithographie|Fotolithografie|Photolithographie','Lithografie überträgt Muster auf eine vorbereitete lichtempfindliche Schicht.'),sc('Was enthält eine Maske beziehungsweise ein Retikel?','Eine Mustervorlage','Alle fertigen Smartphones eines Auftrags','Nur die Versandetiketten','Die Vorlage wird bei der Belichtung optisch übertragen.'),multi('Welche Aussagen treffen auf die Erklärung zu?',['Lithografie ist ein Schritt in einem grösseren Prozess','Weitere Bearbeitung und Schichten sind nötig','Eine einzige Belichtung erzeugt das gesamte Endprodukt','Die Illustration dokumentiert eine bestimmte Fabrik'],[0,1],'Der Prozess ist komplexer als die vereinfachte Szene.'),order('Ordne die vereinfachte Übertragung.',['Mustervorlage bereitstellen','Vorbereitete Schicht belichten','Übertragenes Muster weiterbearbeiten'],'Die Vorlage wird nicht schon durch Bereitstellung zum fertigen Chip.'),sc('Welche Grenze hat die Schablonen-Analogie?','Sie zeigt das Prinzip, nicht die technische Präzision und alle Prozessschritte','Sie beweist, dass Reinräume unnötig sind','Sie macht jedes Lichtverfahren identisch','Analogien reduzieren Komplexität und müssen als solche begrenzt werden.')],
'Ein zentraler Fertigungsschritt ist noch nicht das gesamte Produkt.','Erkläre Lithografie in einem Satz und nenne ausdrücklich einen Schritt, den die Erklärung offenlässt.',A),
chapter(CHIP,2,'Schichten müssen zusammenpassen','Du verstehst, warum Ausrichtung und wiederholte Bearbeitung die Qualität beeinflussen.',[
 card('lab','Zwei Folien als Gedankenexperiment','Stell dir zwei transparente Folien mit zusammengehörenden Mustern vor. Verschiebst du eine, treffen die vorgesehenen Verbindungen nicht mehr aufeinander. Das ist eine grobe Anschauung für Ausrichtung zwischen Schichten, nicht das tatsächliche Herstellungsverfahren.\n\nIn einem Chip werden Strukturen schichtweise aufgebaut. Neue Arbeitsschritte müssen zu den bereits vorhandenen Strukturen passen.'),
 card('reveal','Reicht ein besonders scharfes Einzelbild?','Du kannst ein Muster sehr fein abbilden, richtest es aber falsch zu den vorherigen Strukturen aus. Warum ist die Schärfe allein dann nicht genug?',reveal='Die einzelnen Formen können präzise aussehen und trotzdem an der falschen Stelle liegen. Auflösung und Ausrichtung sind unterschiedliche Anforderungen. Das Zusammenspiel entscheidet, ob die beabsichtigte Struktur entsteht.'),
 card('evidence','Ein wiederholter Prozess','Belichten, Material gezielt bearbeiten und Eigenschaften kontrollieren gehören zu einem wiederkehrenden Ablauf mit weiteren spezialisierten Schritten. Welche Schritte genau folgen, hängt vom Prozess ab.\n\nDer Branchenblick fragt deshalb nicht nur nach der berühmtesten Maschine, sondern nach dem Zusammenspiel vieler Werkzeuge, Materialien und Kontrollen.'),
 card('decision','Wo würdest du nachsehen?','Im fiktiven Fall wirken einzelne Muster scharf, liegen aber systematisch verschoben zu einer früheren Schicht.',probe=sc('Welche Vermutung passt zuerst zu dieser Beschreibung?','Ein Problem der relativen Ausrichtung','Ein sicher bewiesener Mangel an Kundennachfrage','Ein Problem ausschliesslich mit der Versandverpackung','Das beobachtete Fehlerbild betrifft die Lage der Schichten zueinander. Die genaue Ursache müsste weiter geprüft werden.'))
],[sc('Was zeigt das Folienexperiment?','Passende Muster müssen auch richtig zueinander liegen','Zwei beliebige Muster bilden automatisch einen Chip','Fertigung benötigt keine Materialbearbeitung','Die räumliche Zuordnung zwischen Schichten ist wesentlich.'),recall('Wie nennen wir hier die passende Lage mehrerer Muster zueinander?','Ausrichtung|Ausrichten','Ausrichtung ist von der Feinheit eines einzelnen Musters zu unterscheiden.'),multi('Welche Anforderungen sind verschieden?',['Feinheit eines Musters','Relative Lage zu anderen Strukturen','Auflösung als alleinige Erfolgsgarantie','Verpackungsfarbe als Beweis der Schichtqualität'],[0,1],'Ein feines Muster kann trotzdem falsch positioniert sein.'),sc('Scharfe, aber verschobene Muster beweisen bereits die genaue technische Ursache. Stimmt das?','Nein, das Fehlerbild lenkt die Suche, ersetzt aber keine Ursachenprüfung','Ja, jede Verschiebung hat stets dieselbe Ursache','Ja, es beweist fehlende Nachfrage','Beobachtung und nachgewiesene Ursache bleiben getrennt.'),sc('Warum sollte man die Branche nicht nur über eine berühmte Maschine verstehen?','Weil viele spezialisierte Schritte zusammen ein brauchbares Produkt ergeben','Weil einzelne Maschinen keinen Einfluss haben','Weil alle Firmen dieselben Aufgaben ausführen','Bedeutung eines Schritts und Abhängigkeit vom Gesamtsystem bestehen gleichzeitig.')],
'Präzise Einzelteile ergeben nur dann ein funktionierendes Ganzes, wenn auch ihre Beziehungen stimmen.','Nenne am Folienbeispiel den Unterschied zwischen scharfem Muster und richtiger Ausrichtung.',A),
chapter(CHIP,3,'Hundert hergestellt, achtzig brauchbar','Du berechnest Ausbeute und Kosten je gutem Stück in einem vereinfachten Fertigungsmodell.',[
 card('scene','Die Kontrolle nach der Herstellung','Ein Teil der hergestellten Einheiten erfüllt die Anforderungen nicht. Die Ausbeute, englisch Yield, beschreibt in unserem Modell den Anteil brauchbarer Stücke. Reale Fehlerprüfungen sind erheblich komplexer als diese Rechnung.',image='chip-inspection',alt='Ein strukturierter Wafer liegt unter optischer Prüfausrüstung im Reinraum.',caption='KI-Szenenbild · illustrative Prüfung, keine Messung realer Produktionsdaten.'),
 card('lab','Die Rechnung der brauchbaren Stücke','Erfundenes Modell: Ein Fertigungslauf kostet insgesamt 1’000 CHF und erzeugt 100 mögliche Einheiten. Davon bestehen 80 die Prüfung. Die Ausbeute ist 80 %. Die Modellkosten je gutem Stück betragen 1’000 / 80 = 12.50 CHF.\n\nDurch 100 zu teilen ergäbe 10 CHF je hergestelltem Stück, aber nicht je brauchbarem Stück. Verpackung und weitere Kosten sind ausgeschlossen.'),
 card('decision','Mehr Ausschuss, gleiche Laufkosten','Nun bestehen nur 50 der 100 Einheiten. Die Laufkosten bleiben im Modell 1’000 CHF.',probe=number('Wie hoch sind die Kosten je gutem Stück?',20,'CHF','1’000 / 50 = 20 CHF je brauchbarer Einheit.')),
 card('evidence','Warum der Nenner zählt','Ein höherer Durchsatz kann wertlos sein, wenn zugleich die Zahl brauchbarer Stücke fällt. Umgekehrt kann bessere Qualität die Kosten je gutem Stück senken, auch ohne mehr Rohstücke zu fertigen.\n\nEine Qualitätsverbesserung ist selbst nicht kostenlos. Für eine reale Entscheidung müssen ihre zusätzlichen Kosten und die tatsächlich erreichbare Ausbeute mitgeprüft werden.',visual=bars('Kosten je gutem Stück',['80 gute Stücke','50 gute Stücke'],[12.5,20],'CHF bei gleichen fiktiven Laufkosten von 1’000 CHF.'))
],[number('Wie hoch ist die Ausbeute bei 80 brauchbaren von 100 hergestellten Einheiten?',80,'%','80 / 100 × 100 = 80 %.'),number('Wie hoch sind die Kosten je gutem Stück bei 1’000 CHF Laufkosten und 80 guten Stück?',12.5,'CHF','Die Kosten werden auf die tatsächlich brauchbaren Stücke verteilt.'),recall('Wie lautet der englische Begriff für die beschriebene Ausbeute?','Yield','Yield beschreibt hier den Anteil brauchbarer Einheiten.'),sc('Warum ist 1’000 / 100 nicht die gesuchte Kostenkennzahl bei nur 80 guten Stück?','Der Nenner enthält auch unbrauchbare Stücke','Division ist bei Fertigungskosten nie zulässig','Die Laufkosten betragen deshalb automatisch 800 CHF','Kosten pro hergestelltem und pro gutem Stück sind verschiedene Kennzahlen.'),multi('Was braucht die Bewertung einer Qualitätsverbesserung?',['Zusätzliche Kosten der Verbesserung','Tatsächlich erreichbare Zahl guter Stücke','Nur die Anzahl aller Rohstücke','Die Annahme, Qualitätsarbeit sei kostenlos'],[0,1],'Der Nutzen besserer Ausbeute muss gegen seinen Aufwand geprüft werden.')],
'Nicht die Zahl der Rohstücke bezahlt die Rechnung, sondern die Zahl brauchbarer Ergebnisse.','Suche bei einer Produktivitätskennzahl den Nenner: alle erzeugten Einheiten oder wirklich nutzbare Ergebnisse?',A),
chapter(CHIP,4,'Die schnellste Maschine wartet','Du erkennst den Engpass einer Prozesskette und unterscheidest Durchsatz von lokaler Auslastung.',[
 card('decision','Drei Stationen, ein Ausgang','Vereinfachtes Modell einer Fertigungslinie: Station A schafft 100 Einheiten pro Stunde, B schafft 60, C schafft 90. Alle Einheiten müssen nacheinander durch alle drei Stationen. Wir unterstellen keine Verluste oder Ausfälle.',probe=number('Wie viele fertige Einheiten pro Stunde kann die Kette langfristig höchstens liefern?',60,'Stück','Die langsamste erforderliche Station B begrenzt den Durchsatz auf 60.')),
 card('lab','Ein teures Missverständnis','Du beschleunigst A von 100 auf 150. B bleibt bei 60 und C bei 90. Ohne andere Änderung bleibt der mögliche Ausgang 60. Vor B kann sich mehr Arbeit aufstauen.\n\nBeschleunigst du stattdessen B auf 80, steigt die Modellgrenze auf 80. Bei B = 100 würde C mit 90 zum neuen Engpass. Der Engpass kann also wandern.',visual=bars('Kapazität der ursprünglichen Stationen',['A','B','C'],[100,60,90],'Einheiten pro Stunde; vereinfachtes verlustfreies Modell.')),
 card('evidence','Vom Modell zurück zur Chipbranche','Reale Fertigungen haben parallele Anlagen, Ausbeuteverluste, Wartung und wechselnde Aufträge. Das Modell ist keine Beschreibung einer bestimmten Fabrik. Es gibt dir eine gute Frage: Welche Stufe begrenzt derzeit die nutzbare Gesamtleistung?\n\nEin starkes Unternehmen an einer wichtigen Stufe ist ausserdem nicht automatisch eine attraktive Aktie. Bewertung, Wettbewerb und Unsicherheit wären eigene Fragen.'),
 card('transfer','Dein Blick hinter die Schlagzeile','Wenn du liest, eine Fabrik kaufe eine schnellere Maschine, frage nach drei Dingen: War diese Stufe wirklich der Engpass? Bleibt die Qualität erhalten? Können die folgenden Stufen mithalten?\n\nSo wird aus einer beeindruckenden Maschine ein verständliches Produktionssystem.',reveal='Die Lehre verbindet alle vier Kapitel: Muster übertragen, Schichten passend bearbeiten, brauchbare Stücke prüfen und die gesamte Kette betrachten. Jede Stufe zählt; nicht jede begrenzt gleichzeitig den Ausgang.')
],[number('Welche Grenze hat die Kette A=100, B=60, C=90?',60,'Stück pro Stunde','Die kleinste erforderliche Kapazität ist 60.'),number('Welche Grenze ergibt sich nach B=80 bei sonst gleichem Ablauf?',80,'Stück pro Stunde','B bleibt der Engpass, nun bei 80.'),sc('Was bewirkt A=150 allein im ursprünglichen Modell?','Keine höhere Endkapazität als 60','Automatisch 150 fertige Stück pro Stunde','Automatisch bessere Ausbeute','B bleibt unverändert bei 60.'),recall('Wie nennt man die Stufe, die den Gesamtdurchsatz begrenzt?','Engpass|Bottleneck','Der Engpass begrenzt die Kette unter den genannten Annahmen.'),multi('Welche Fragen gehören zur Prüfung einer neuen Maschine?',['War ihre Stufe der Engpass?','Können nachfolgende Stufen und Qualitätsprüfung mithalten?','Ist jede wichtige Maschine automatisch ein gutes Aktieninvestment?','Reicht allein die höhere lokale Geschwindigkeit?'],[0,1],'Die technische Verbesserung muss im Gesamtsystem beurteilt werden.')],
'Eine lokale Bestleistung ist noch keine höhere Leistung des gesamten Systems.','Zeichne eine dreistufige Prozesskette aus deinem Alltag und suche ihren begrenzenden Schritt.',A)
]
