from story_authoring import *

PRESS=topic('press','history','Gutenberg: Eine Seite verändert die Regeln','Du stehst in einer Druckwerkstatt. Was wird plötzlich möglich, wenn derselbe Text nicht jedes Mal neu abgeschrieben werden muss?','Historische Spurensuche')
STOIC=topic('stoic','philosophy','Die Absage: Was liegt wirklich bei dir?','Du hast dich vorbereitet. Trotzdem kommt ein Nein. Epiktets Unterscheidung wird an genau diesem Konflikt geprüft.','Entscheidungsfall')
SOCRATES=topic('socrates','philosophy','Sokrates und die teure Uhr','Ist erfolgreich, wer viel besitzt? Ein einziges Gespräch nimmt diese scheinbar einfache Definition auseinander.','Sokratischer Dialog')
TOPICS=[PRESS,STOIC,SOCRATES]
G=source('Library of Congress · The Gutenberg Bible','https://www.loc.gov/exhibits/bibles/the-gutenberg-bible.html')
E=source('Epiktet · Enchiridion, besonders 1, 5, 17 und 24','https://classics.mit.edu/Epictetus/epicench.html')
S=source('Platon · Menon: Begriffe durch Fragen untersuchen','https://classics.mit.edu/Plato/meno.html')
LESSONS=[
chapter(PRESS,1,'Die Werkstatt in Mainz','Du erklärst, warum wiederverwendbare Lettern die Herstellung vieler gleicher Texte verändern.',[
 card('scene','Eine Seite. Noch einmal. Und noch einmal.','Mainz, um die Mitte des 15. Jahrhunderts. Stell dir eine Werkstatt vor: Metalllettern, Druckfarbe, Papier und eine schwere Presse. Der historische Anker ist Gutenbergs Bibeldruck. Unsere Werkstattszene ist rekonstruiert, kein überlieferter Augenzeugenbericht.\n\nDie entscheidende Frage lautet nicht bloss: Wie druckt man eine Seite? Sondern: Wie stellt man die nächste gleiche Seite her?',image='press-workshop',alt='Ein Drucker färbt gesetzte Lettern neben einer hölzernen Presse ein.',caption=ILLUSTRATION),
 card('decision','Wo sitzt der Hebel?','Eine Handschrift muss erneut geschrieben werden. Beim Druck kostet das Setzen zunächst Arbeit. Eine eingerichtete Seite kann danach mehrfach abgezogen werden. Einzelne Lettern lassen sich später für andere Seiten neu zusammensetzen.',probe=sc('Was verändert das Verfahren besonders stark?','Die Herstellung weiterer gleicher Seiten nach dem Setzen','Die vollständige Abschaffung jeder Vorarbeit','Die automatische Richtigkeit des gedruckten Inhalts','Das Setzen bleibt aufwendig. Der Vorteil liegt in der Wiederholung eines vorbereiteten Textes.')),
 card('evidence','Keine Erfindung aus dem Nichts','Druckverfahren existierten zuvor in Ostasien; Gutenberg erfand nicht jede Form des Druckens. Sein europäisches System verband mehrere Elemente zu einer praktisch nutzbaren Herstellung. Auch nach einem Abzug bleiben Tätigkeiten wie Prüfen, Trocknen und Binden.\n\nTechnischer Wandel ist häufig eine neue Verbindung vorhandener Verfahren, nicht ein einzelner magischer Gegenstand.',visual=chain('Der wiederholbare Ablauf',['Lettern setzen','Farbe auftragen','Abzug herstellen','Seite erneut drucken'],'Vereinfachtes Prozessbild. Nach dem Druck folgen weitere Arbeitsschritte.')),
 card('transfer','Erklär es einem Schreiber','Erkläre ohne Fachwörter, warum sich viel Vorarbeit lohnen kann, wenn derselbe Text oft gebraucht wird. Nenne danach eine Arbeit, die trotzdem übrig bleibt.',reveal='Ein möglicher Satz: Die Seite wird einmal vorbereitet und danach wiederholt abgezogen; geprüft und gebunden werden muss weiterhin. Damit benennst du sowohl den Vorteil als auch seine Grenze.')
],[sc('Was ist der zentrale Vorteil wiederverwendbarer Lettern?','Texte können gesetzt, mehrfach gedruckt und später neu zusammengesetzt werden','Jede Seite benötigt keinerlei Vorbereitung','Ein einzelner Druck ersetzt das Binden eines Buchs','Wiederverwendung betrifft die Herstellung, nicht sämtliche Arbeitsschritte.'),order('Ordne den vereinfachten ersten Druckvorgang.',['Lettern setzen','Farbe auftragen','Abzug herstellen'],'Ohne gesetzte und eingefärbte Druckform entsteht noch kein Abzug.'),recall('Wie heissen die einzelnen wiederverwendbaren Druckzeichen?','Lettern|Metalllettern','Lettern lassen sich zu einer Druckform zusammenstellen.'),multi('Welche Aussagen sind mit dem Kapitel vereinbar?',['Druckverfahren gab es vor Gutenberg.','Setzen verursacht zunächst Aufwand.','Drucken garantiert wahre Aussagen.','Binden wird dadurch überflüssig.'],[0,1],'Frühere Druckgeschichte und verbleibende Arbeit gehören zur Einordnung.'),sc('Warum ist das Szenenbild kein Beweis für die genaue Ausstattung einer bestimmten Werkstatt?','Es ist eine illustrative Rekonstruktion','Weil historische Werkstätten nicht existierten','Weil nur ein handgeschriebener Text überhaupt eine Quelle sein kann','Plausible Darstellung und historische Quelle sind verschiedene Dinge.')],
'Wiederholbare Herstellung verändert die Kosten der nächsten Kopie – nicht automatisch ihren Wahrheitsgehalt.','Suche heute einen Ablauf, bei dem einmalige Vorbereitung viele spätere Wiederholungen erleichtert.',G),
chapter(PRESS,2,'Die hundertste Kopie','Du unterscheidest Einrichtungsaufwand und Aufwand je Kopie anhand eines transparenten Modells.',[
 card('lab','Zwei Angebote liegen auf dem Tisch','Ein bewusst erfundenes Rechenmodell: Abschreiben kostet 6 Arbeitseinheiten je Seite. Drucken kostet 40 Einheiten fürs Einrichten und dann 1 Einheit je Kopie. Es sind keine historischen Preise.\n\nFür eine einzige Kopie stehen damit 6 gegen 41 Einheiten. Die neue Technik gewinnt also nicht unter allen Bedingungen.',visual=bars('Eine Kopie: Modellkosten',['Abschreiben','Drucken'],[6,41],'Arbeitseinheiten, keine historischen Messwerte.')),
 card('reveal','Ab wann kippt der Vergleich?','Für zehn Kopien kostet Abschreiben 10 × 6 = 60. Drucken kostet 40 + 10 × 1 = 50. Suche den Punkt, an dem beide gleich teuer sind.',reveal='Bei acht Kopien: 8 × 6 = 48 und 40 + 8 = 48. Oberhalb von acht Kopien ist Drucken in diesem Modell günstiger. Der einmalige Einrichtungsaufwand verteilt sich auf mehr Exemplare.'),
 card('decision','Der Auftrag schrumpft','Der Kunde möchte am Ende nur vier Kopien. Die Einrichtung ist noch nicht begonnen. Das Modell ergibt 24 fürs Abschreiben und 44 fürs Drucken.',probe=sc('Welches Verfahren ist nach diesen Modellkosten günstiger?','Abschreiben','Drucken','Beide kosten gleich viel','24 ist kleiner als 44. Eine höhere Stückzahl war die Voraussetzung für den Druckvorteil.')),
 card('evidence','Was die Rechnung nicht weiss','Papierqualität, Fehler, Lesbarkeit, verfügbarer Platz und Nachfrage fehlen im Modell. Die Rechnung beantwortet eine eng begrenzte Kostenfrage; sie erklärt nicht allein die historische Verbreitung des Buchdrucks.\n\nDer übertragbare Gedanke bleibt: Ein hoher Startaufwand kann bei vielen Wiederholungen attraktiv werden. Ohne genügend Nachfrage bleibt er eine Belastung.')
],[number('Wie viele Arbeitseinheiten benötigt Drucken für zehn Kopien im Modell?',50,'Einheiten','40 Einrichtung + 10 für die Kopien = 50.'),number('Bei wie vielen Kopien sind beide Verfahren gleich teuer?',8,'Kopien','6n = 40 + n, also 5n = 40 und n = 8.'),sc('Warum kann Drucken bei einer Kopie teurer sein?','Der Einrichtungsaufwand verteilt sich auf nur ein Exemplar','Die Kosten je zusätzlicher Kopie steigen immer','Die Zahl der Leser verdoppelt die Einrichtungsarbeit','Der einmalige Aufwand fällt auch bei kleiner Auflage an.'),multi('Welche Annahmen fehlen in der einfachen Rechnung?',['Tatsächliche Nachfrage','Qualität und Fehlerkosten','Die angegebenen 40 Einrichtungseinheiten','Die angegebenen 6 Einheiten pro Abschrift'],[0,1],'Die letzten beiden Werte sind schon Teil des Modells; Nachfrage und Qualität nicht.'),sc('Der Modellvergleich beweist, dass jede Druckerei profitabel war. Was ist daran falsch?','Aus einem Modellvorteil folgen weder reale Nachfrage noch ein historischer Gewinn','Ein Kostenmodell darf grundsätzlich keine Zahlen enthalten','Gewinn hängt ausschliesslich von der Zahl der Lettern ab','Kosten, Nachfrage und historische Umstände müssen getrennt geprüft werden.')],
'Der Vorteil einer Technik hängt auch davon ab, wie oft ihre Vorarbeit genutzt wird.','Erkläre den Unterschied zwischen Startaufwand und zusätzlicher Kopie an der Druckwerkstatt.',G),
chapter(PRESS,3,'Der Fehler vervielfältigt sich','Du erkennst, warum skalierbare Herstellung zugleich eine stärkere Qualitätsprüfung verlangt.',[
 card('scene','Ein falsches Zeichen ist gesetzt','Du prüfst einen Probeabzug. In der erfundenen Werkstattsituation steht an einer Stelle ein falsches Wort. Die Druckform ist noch eingerichtet. Wenn niemand eingreift, erscheint derselbe Fehler auf jedem weiteren Abzug.',image='press-proof',alt='Ein Drucker vergleicht einen Probeabzug mit gesetzten Metalllettern.',caption=ILLUSTRATION),
 card('decision','Schneller werden – oder erst prüfen?','Der nächste Stapel Papier liegt bereit. Du kannst die fehlerhafte Stelle jetzt korrigieren oder erst alle Kopien drucken und später nachbessern.',probe=sc('Welche Handlung vermeidet die Wiederholung genau dieses Fehlers?','Druckform vor den weiteren Abzügen korrigieren und erneut prüfen','Mehr Kopien aus derselben unveränderten Form herstellen','Den Fehler nur auf dem ersten Probeabzug markieren','Eine Änderung am Papier allein ändert die Druckform nicht. Erst ihre Korrektur wirkt auf neue Abzüge.')),
 card('evidence','Gleiche Kopie heisst nicht wahre Aussage','Ein korrekt kopierter Satz kann sachlich falsch sein. Zwei Kontrollen sind deshalb verschieden: Stimmt der Abzug mit der Vorlage überein? Und stimmt die Behauptung in der Vorlage?\n\nDie erste prüft die Übertragung; die zweite braucht passende Quellen und Argumente. Eine schön gedruckte Seite kann beides leicht miteinander verwechseln lassen.',visual=compare('Zwei unterschiedliche Prüfungen',['Übertragung: Entspricht die Kopie ihrer Vorlage?','Inhalt: Ist die Behauptung begründet?'],'Eine bestandene Übertragungsprüfung ersetzt keine Inhaltsprüfung.')),
 card('transfer','Eine Analogie mit Grenze','Auch eine digitale Nachricht lässt sich schnell vervielfältigen. Der gemeinsame Mechanismus ist die Verbreitung derselben Vorlage. Digitale Netzwerke unterscheiden sich aber in Geschwindigkeit, Reichweite und Zugang erheblich vom frühen Buchdruck. Ein Vergleich erklärt einen Mechanismus; er macht die Epochen nicht identisch.',reveal='Prüfe zuerst die Vorlage, bevor du ihren Inhalt weiterverbreitest. Das folgt aus dem gemeinsamen Mechanismus, ohne Gutenberg zur Erklärung sämtlicher heutiger Medienprobleme zu machen.')
],[sc('Warum hilft die Korrektur nur des ersten Papierabzugs nicht gegen weitere falsche Kopien?','Die Druckform bleibt unverändert','Das Papier kann grundsätzlich nicht korrigiert werden','Alle Lettern verändern sich beim Lesen','Weitere Kopien stammen aus derselben Form.'),multi('Welche Prüfungen sind voneinander zu unterscheiden?',['Übereinstimmung mit der Vorlage','Sachliche Begründung der Aussage','Schöne Schrift als Beweis der Wahrheit','Hohe Auflage als Beweis der Wahrheit'],[0,1],'Genaues Kopieren und wahrer Inhalt sind unabhängig zu prüfen.'),order('Ordne einen sinnvollen Qualitätsablauf.',['Probeabzug prüfen','Fehler in der Druckform korrigieren','Neuen Probeabzug kontrollieren','Weitere Kopien herstellen'],'Die Korrektur wird vor der weiteren Vervielfältigung geprüft.'),sc('Eine Aussage steht in 500 identischen Drucken. Was belegt das zunächst?','Dass sie vervielfältigt wurde','Dass 500 unabhängige Untersuchungen sie bestätigt haben','Dass keine ursprüngliche Quelle nötig ist','Abhängige Kopien sind keine unabhängigen Bestätigungen.'),recall('Wie heisst der Abzug, an dem vor weiteren Kopien geprüft wird?','Probeabzug','Ein Probeabzug macht Fehler vor der grösseren Auflage sichtbar.')],
'Vervielfältigung vergrössert Reichweite und kann denselben Fehler gleich mitvergrössern.','Prüfe bei einer oft geteilten Behauptung, ob die verschiedenen Fundstellen wirklich unabhängige Quellen sind.',G),
chapter(PRESS,4,'Was beweist die erhaltene Seite?','Du trennst Objektbeobachtung, plausible Deutung und unbelegte historische Behauptung.',[
 card('evidence','Du wirst zum Quellenprüfer','Eine erhaltene Gutenberg-Bibel ist ein historisches Objekt. Ihr Druckbild und Material lassen sich untersuchen. Die Library of Congress zeigt und beschreibt ein Exemplar ihrer Sammlung. Das ist etwas anderes als unser generiertes Werkstattbild.\n\nEin Buch kann belegen, dass dieser Druck hergestellt wurde. Es erzählt nicht von selbst, was jeder damalige Leser dachte.'),
 card('dialogue','Zwei Behauptungen über dieselbe Seite','Person A: Die Gestaltung und Herstellung dieses Exemplars lassen sich am Objekt untersuchen. Person B: Dieses einzelne Exemplar beweist, dass sofort jeder Mensch in Europa lesen konnte.\n\nA bleibt nahe an untersuchbaren Eigenschaften. B springt von einem Objekt zu einer Aussage über eine gesamte Bevölkerung. Dafür wären ganz andere Belege nötig.',probe=sc('Welche Zusatzinformation würde eher zur Behauptung über allgemeine Lesefähigkeit passen?','Quellen zur Verbreitung von Leseunterricht und Lesefähigkeit','Ein zweites Foto desselben Buchdeckels','Eine hellere Ausleuchtung der Seite','Die Zusatzquelle muss zur Reichweite der Behauptung passen. Ein schöneres Bild erweitert sie nicht.')),
 card('reveal','Bau deine eigene Erklärung','Beantworte die Ausgangsfrage: Was änderte die wiederverwendbare Druckform? Nenne den Vorteil, eine Voraussetzung und ein Risiko.',reveal='Vorteil: Viele gleiche Kopien lassen sich nach dem Setzen herstellen. Voraussetzung: Genügend Nutzung rechtfertigt die Vorarbeit. Risiko: Auch ein Fehler der Vorlage wird vervielfältigt. Zur historischen Wirkung braucht es darüber hinaus Quellen über Verbreitung und Nutzung.'),
 card('transfer','Der Prüfstein für die nächste Geschichte','Eine gute historische Erklärung nennt ihren Mechanismus und die Grenzen ihrer Belege. Du musst keine grosse Personenerzählung erfinden, um eine bedeutsame Veränderung zu verstehen. Hier war es die Verbindung aus wiederverwendbarer Herstellung, Nachfrage und Verbreitung – nicht die Behauptung, ein einzelnes Buch habe über Nacht alle Verhältnisse geändert.')
],[sc('Welche Aussage liegt am nächsten an einem erhaltenen Buch als Quelle?','Sein Material und Druckbild lassen sich untersuchen','Es beweist allein die Gedanken aller damaligen Leser','Es beweist allein flächendeckende Alphabetisierung','Objekte tragen bestimmte Informationen, aber keine unbegrenzten Aussagen.'),multi('Welche Bestandteile gehören in die Erklärung des Lernfalls?',['Wiederverwendbare Herstellung','Genügend Nachfrage für den Startaufwand','Automatische Wahrheit gedruckter Texte','Sofortige Lesefähigkeit aller Menschen'],[0,1],'Die beiden anderen Aussagen überschreiten das Belegte.'),sc('Was unterscheidet unser Werkstattbild von einem Foto eines erhaltenen Exemplars?','Das Werkstattbild ist eine generierte Rekonstruktion','Das Werkstattbild ist automatisch genauer','Ein Foto eines Objekts kann keinerlei Quelle sein','Illustration und Dokumentation müssen gekennzeichnet bleiben.'),order('Ordne die Quellenprüfung.',['Behauptung genau formulieren','Passende Quelle suchen','Beobachtung und Deutung trennen','Reichweite des Schlusses begrenzen'],'Die Quelle muss zur konkreten Frage passen.'),sc('Welcher Satz vermeidet eine überzogene historische Erklärung?','Die Technik erleichterte Vervielfältigung; ihre Wirkung hing auch von Nutzung und Verbreitung ab','Nach Gutenberg spielte gesellschaftlicher Kontext keine Rolle mehr','Jeder technische Vorteil setzt sich sofort überall durch','Eine technische Möglichkeit ist noch keine vollständig erklärte gesellschaftliche Wirkung.')],
'Ein beeindruckendes Objekt ist eine Quelle für bestimmte Fragen, nicht für jede denkbare Behauptung.','Formuliere beim nächsten historischen Bild einen Satz: Das sehe ich – und das schliesse ich nur daraus.',G),
chapter(STOIC,1,'Das Nein auf dem Tisch','Du trennst ein Ereignis von deiner Deutung, ohne dein Gefühl abzuwerten.',[
 card('scene','Die Nachricht ist drei Zeilen lang','Ein fiktiver Fall: Du hast ein Angebot sorgfältig vorbereitet. Die Antwort lautet Nein. Dein erster Gedanke: Die nehmen mich nicht ernst. Ärger ist verständlich. Trotzdem enthält die Nachricht nicht automatisch diese Erklärung.',image='stoic-desk',alt='Eine Person hält nachdenklich einen Brief, daneben liegen Stift und Notizbuch.',caption=FICTION),
 card('dialogue','Ereignis, Deutung, Handlung','Ereignis: Das Angebot wurde abgelehnt. Deutung: Ich bin grundsätzlich ungeeignet. Handlung: Ich bitte respektvoll um einen konkreten Grund.\n\nEpiktet lenkt die Aufmerksamkeit auf eigene Urteile und Handlungen. Die Übersetzung in diesen modernen Fall ist unsere Anwendung: Eine Deutung prüfen, bevor sie die nächste Handlung bestimmt. Das ist kein Auftrag, Ärger zu verleugnen.'),
 card('decision','Welchen Satz weisst du wirklich?','Du hast nur die Absage, noch keine Begründung.',probe=sc('Welche Aussage bleibt am engsten bei den vorliegenden Informationen?','Dieses Angebot wurde abgelehnt','Meine gesamte berufliche Zukunft ist gescheitert','Die andere Person wollte mich sicher demütigen','Die Absage ist belegt; die Motive und ein Urteil über deine ganze Zukunft sind es nicht.')),
 card('reveal','Gib der Deutung eine Alternative','Finde eine zweite plausible Erklärung für das Nein. Nicht, um dich blind zu beruhigen, sondern um eine voreilige Gewissheit aufzulösen.',reveal='Vielleicht passt der Zeitpunkt nicht, das Budget fehlt oder das Angebot löst das Problem nicht gut genug. Keine dieser Möglichkeiten ist damit bewiesen. Eine Rückfrage kann Informationen liefern; du musst nicht vorab eine beruhigende Geschichte für wahr erklären.')
],[sc('Was ist im Fall das beobachtete Ereignis?','Das Angebot wurde abgelehnt','Du bist grundsätzlich unfähig','Die andere Person verachtet dich','Nur die Ablehnung steht fest.'),multi('Welche Schritte passen zur beschriebenen Unterscheidung?',['Die eigene Deutung als Deutung erkennen','Eine konkrete Rückfrage stellen','Das Gefühl als moralischen Fehler verurteilen','Ein unbekanntes Motiv als Tatsache behandeln'],[0,1],'Urteil prüfen und Handlung wählen lässt Gefühle bestehen.'),recall('Wie nennen wir die Bedeutung, die du dem Ereignis zunächst gibst?','Deutung|Interpretation','Eine Deutung ist von der beobachteten Nachricht zu unterscheiden.'),order('Ordne die bewusste Antwort.',['Die Absage wahrnehmen','Die erste Deutung prüfen','Eine angemessene Rückfrage formulieren'],'Zwischen Ereignis und Handlung liegt die Prüfung des eigenen Urteils.'),sc('Eine alternative Erklärung ist gefunden. Was folgt?','Sie ist eine Möglichkeit, noch kein Beweis','Sie ist automatisch die wahre Ursache','Die Absage hat nicht stattgefunden','Mehrere plausible Erklärungen lösen voreilige Gewissheit, ersetzen aber keine Belege.')],
'Ein Gefühl darf da sein; die erste Erklärung dafür muss nicht das letzte Wort behalten.','Notiere bei einem Ärgernis getrennt: beobachtetes Ereignis, erste Deutung, nächster vernünftiger Schritt.',E),
chapter(STOIC,2,'Das Schiff und der Sturm','Du unterscheidest eigenes Handeln, Einfluss und ein nicht garantierbares Ergebnis.',[
 card('scene','Der Wind fragt nicht nach deinem Plan','Stell dir ein antikes Schiff vor. Der Wind frischt auf. Der Steuermann kann die Richtung des Windes nicht bestimmen. Er kann aber Segel anpassen und Schutz suchen. Das Bild ist eine Analogie für die Unterscheidung, keine überlieferte Episode aus Epiktets Leben.',image='stoic-storm',alt='Ein Seemann arbeitet an einem Tau, während ein Schiff einen Hafen bei aufziehendem Sturm ansteuert.',caption=ILLUSTRATION),
 card('evidence','Nicht alles ist entweder Macht oder Ohnmacht','Epiktets Grundunterscheidung betrifft das Eigene und das nicht von uns Abhängige. Im heutigen Alltag hilft eine zusätzliche praktische Nuance: Manche Ergebnisse können wir beeinflussen, aber nicht garantieren.\n\nDu kannst ein Angebot überarbeiten. Das kann seine Chancen verbessern. Du kannst die Unterschrift des Kunden nicht erzwingen. Die moderne Drei-Felder-Hilfe ist eine Anwendung, kein wörtliches Schema des antiken Texts.',visual=compare('Der Spielraum in der Absage',['Eigenes Handeln: begründet nachfragen','Beeinflussbar: Verständlichkeit des Angebots','Nicht garantiert: endgültige Zusage'],'Einfluss ist real, aber keine Erfolgsgarantie.')),
 card('decision','Was wäre die falsche Schlussfolgerung?','Weil du eine Zusage nicht garantieren kannst, willst du gar keine Angebote mehr vorbereiten.',probe=sc('Was übersieht dieser Schluss?','Vorbereitung kann die Chance beeinflussen, auch ohne Erfolgsgarantie','Gute Vorbereitung garantiert grundsätzlich jeden Abschluss','Jeder äussere Einfluss ist bedeutungslos','Nicht garantierbar bedeutet nicht unbeeinflussbar.')),
 card('transfer','Eine bessere Messlatte','Bewerte die Qualität einer Vorbereitung mit prüfbaren Kriterien: Problem verstanden, Annahmen offengelegt, Angebot verständlich. Betrachte den Ausgang zusätzlich. Ein schlechtes Ergebnis kann zum Lernen anregen, ohne rückwirkend jede vorherige Entscheidung schlecht zu machen.')
],[sc('Was kann der Steuermann in der Analogie unmittelbar tun?','Segel anpassen','Den Wind nach Wunsch drehen','Jedes mögliche Unwetter verhindern','Handlungsfähigkeit bleibt trotz nicht kontrollierbarer Bedingungen.'),multi('Welche Aussagen passen zur Unterscheidung?',['Einfluss ist nicht dasselbe wie Garantie','Vorbereitung kann trotz Unsicherheit sinnvoll sein','Ohne Garantie lohnt keine Handlung','Jede Absage beweist schlechte Vorbereitung'],[0,1],'Die Qualität einer Handlung und ihr Ausgang sind nicht identisch.'),recall('Ein Ergebnis ist beeinflussbar, aber nicht sicher erzwingbar. Es gibt also keine ___.','Garantie|Erfolgsgarantie','Du kannst an Chancen arbeiten, ohne den Ausgang zu besitzen.',True),sc('Welche Messlatte beurteilt deine Vorbereitung am direktesten?','Ob du das Kundenproblem geprüft und Annahmen erklärt hast','Ob der Kunde unabhängig von allem anderen unterschreibt','Ob ein anderer Anbieter zufällig ausfällt','Die Kriterien beziehen sich auf den eigenen Prozess.'),sc('Ist das Drei-Felder-Schema ein wörtliches Zitat Epiktets?','Nein, es ist eine moderne Anwendung seiner Unterscheidung','Ja, er verwendete genau diese Projektbegriffe','Nein, daher kann es keinerlei Anwendung sein','Historischer Ausgangstext und heutiges Hilfsschema werden transparent getrennt.')],
'Nutze deinen Einfluss vollständig, ohne daraus einen Anspruch auf das Ergebnis abzuleiten.','Wähle beim aktuellen Problem eine beeinflussbare Handlung und ein Ergebnis, das du nicht garantieren kannst.',E),
chapter(STOIC,3,'Gelassenheit ist keine Kapitulation','Du erkennst, wann die Kontrollunterscheidung verantwortliches Handeln statt Rückzug verlangt.',[
 card('dialogue','Eine bequeme Ausrede','Im erfundenen Fall bemerkt eine Kollegin, dass dein Angebot einen wichtigen Nachteil verschweigt. Du sagst: Was sie darüber denkt, liegt nicht bei mir.\n\nDer Satz benutzt einen richtigen Teilgedanken, um die falsche Sache auszublenden. Die Reaktion der Kollegin ist nicht vollständig steuerbar. Ob du einen bekannten Nachteil offenlegst, betrifft sehr wohl dein Handeln.'),
 card('decision','Was gehört jetzt auf deine Seite?','Du kannst die Kritik nicht ungeschehen machen. Du kannst aber das Dokument prüfen und korrigieren.',probe=sc('Welche Reaktion nimmt die Unterscheidung ernst?','Den berechtigten Punkt prüfen und den Nachteil offenlegen','Jede Kritik ignorieren, weil sie von aussen kommt','Die Kollegin zur Zustimmung zwingen','Verantwortung liegt in der eigenen Korrektur, nicht im Erzwingen fremder Anerkennung.')),
 card('evidence','Rollen bringen Aufgaben mit sich','Epiktet spricht auch über Rollen und Verpflichtungen gegenüber anderen. Seine Unterscheidung ist daher nicht einfach ein Freibrief zum Rückzug. In unserer Anwendung heisst das: Unrecht benennen, Hilfe suchen oder eine Grenze setzen kann die angemessene eigene Handlung sein.\n\nOb andere sofort einlenken, bleibt offen. Du musst weder Schaden gutheissen noch jede fremde Reaktion zu deiner persönlichen Aufgabe machen.'),
 card('reveal','Der Unterschied in einem Satz','Formuliere eine Grenze, die deine eigene Handlung beschreibt, statt das Verhalten der anderen Person zu garantieren.',reveal='Zum Beispiel: Wenn das Gespräch beleidigend wird, unterbreche ich es und schlage einen sachlichen Termin vor. Das beschreibt, was du tun wirst. Es verspricht nicht, dass die andere Person nie wieder beleidigend wird.')
],[sc('Warum ist das Verschweigen eines bekannten Nachteils keine unveränderliche äussere Tatsache?','Du kannst entscheiden, ob du ihn offenlegst','Jeder Nachteil ist immer erfunden','Nur der Kunde kann den Text ändern','Die eigene Kommunikation gehört zum Handlungsspielraum.'),multi('Welche Handlungen können zur Kontrollunterscheidung passen?',['Eine begründete Grenze setzen','Einen Fehler korrigieren','Jeden Missstand automatisch gutheissen','Andere zur gewünschten Gefühlsreaktion zwingen'],[0,1],'Die Unterscheidung schützt Handlungsfähigkeit, nicht Verantwortungslosigkeit.'),sc('Welche Formulierung beschreibt eine umsetzbare eigene Grenze?','Bei Beleidigungen unterbreche ich das Gespräch','Du wirst mich ab jetzt immer respektieren','Niemand wird mich jemals kritisieren','Eine Grenze beschreibt das eigene Verhalten bei einer erkennbaren Situation.'),recall('Eine selbst übernommene Aufgabe gegenüber anderen nennen wir hier eine ___.','Verpflichtung|Pflicht','Rollen und Verpflichtungen bleiben trotz Unsicherheit des Ausgangs relevant.',True),sc('Eine sachliche Grenze führt nicht sofort zum Einlenken. Was folgt daraus?','Der Ausgang war nicht garantiert; die Grenze kann trotzdem angemessen sein','Jede Grenze war damit sinnlos','Du musst die Beleidigung künftig gutheissen','Eine angemessene Handlung garantiert keine fremde Reaktion.')],
'Gelassenheit entbindet nicht von Verantwortung für das eigene Handeln.','Prüfe, ob du bei einem Problem gerade fremde Reaktionen kontrollieren willst oder eine eigene Pflicht vermeidest.',E),
chapter(STOIC,4,'Die zweite Antwort','Du wendest die Unterscheidung in einer neuen Variante der Absage eigenständig an.',[
 card('decision','Eine neue Information','Der Kunde erklärt seine Absage: Dein Vorschlag war fachlich interessant, aber die Einführung hätte das Team überfordert. Das ist mehr Information als vorher. Nun kannst du sachlich nach dem gewünschten Umfang fragen oder die Absage einfach respektieren.',probe=sc('Welche Reaktion nutzt die neue Information am besten?','Den Umfang prüfen und eine kleinere erste Etappe erwägen','Behaupten, das Nein beweise weiterhin persönliche Verachtung','Versprechen, dass der Kunde diesmal sicher zustimmen wird','Neue Informationen können die eigene Handlung verbessern, ohne eine Zusage zu garantieren.')),
 card('lab','Drei Zeilen statt drei Stunden Grübeln','Schreibe gedanklich drei Zeilen: Was ist jetzt bekannt? Was bleibt eine Vermutung? Was werde ich als Nächstes tun?\n\nBekannt ist die Sorge um die Einführung. Unbekannt ist, ob eine kleinere Etappe genügt. Eine mögliche Handlung ist eine präzise Rückfrage. Du brauchst keine Gewissheit über die ganze Zukunft, um einen vernünftigen nächsten Schritt zu wählen.'),
 card('reveal','Was wäre eine gute Antwort?','Versuche erst selbst einen kurzen Antwortsatz. Er soll weder unterwürfig noch beleidigt sein.',reveal='Ein mögliches Muster: Danke für die Rückmeldung. Welche Belastung wäre in einer ersten Etappe tragbar? Dann kann ich prüfen, ob ein kleinerer Einstieg sinnvoll ist. Die Antwort nimmt den Grund ernst und lässt ein weiteres Nein zu.'),
 card('transfer','Und wenn es beim Nein bleibt?','Dann bleibt der Lerngewinn: eine geprüfte Deutung, eine konkrete Verbesserung und ein respektierter Entscheid. Das ist kein Trostpreis und kein Beweis, dass das Ergebnis unwichtig wäre. Du trennst nur, wofür du Verantwortung übernehmen kannst, von dem, was andere entscheiden.\n\nDiese Anwendung der Stoa ist eine Denkübung, keine psychologische Behandlung und keine Aufforderung, schwierige Gefühle wegzudrücken.')
],[sc('Welche Information ist nach der Rückmeldung neu belegt?','Der Kunde nennt eine Überforderung des Teams als Grund','Der Kunde wird jedes kleinere Angebot kaufen','Der Kunde hat dich grundsätzlich verachtet','Ein genannter Grund erweitert die Informationslage, garantiert aber keinen neuen Abschluss.'),multi('Was soll eine gute Rückfrage leisten?',['Den konkreten Hinderungsgrund klären','Eine umsetzbare Anpassung prüfen','Eine weitere Absage verbieten','Eigene Gefühle vollständig abschalten'],[0,1],'Die Rückfrage dient Verständnis und Handlungsmöglichkeiten.'),order('Ordne den Umgang mit neuer Information.',['Rückmeldung aufnehmen','Frühere Deutung überprüfen','Passende Handlung wählen'],'Ein neues Datum kann ein altes Urteil verändern.'),sc('Ein verbessertes Angebot wird erneut abgelehnt. Welcher Schluss ist angemessen?','Den Ausgang anerkennen und den eigenen Prozess weiterhin prüfen','Die Verbesserung war logisch unmöglich','Andere Menschen haben keine eigene Entscheidung','Prozessqualität und Ergebnis bleiben verschieden.'),recall('Wie heisst der Philosoph, dessen Unterscheidung diesen Lernfall trägt?','Epiktet','Der Fall ist eine moderne Anwendung der im Enchiridion behandelten Unterscheidung.')],
'Du besitzt nicht das letzte Wort anderer Menschen, aber du kannst dein nächstes Wort bewusst wählen.','Nutze bei einer echten Rückmeldung die drei Zeilen: bekannt, vermutet, nächste Handlung.',E),
chapter(SOCRATES,1,'Wer gilt als erfolgreich?','Du unterscheidest ein Beispiel von einer Definition.',[
 card('scene','Ein Gespräch unter dem Portikus','Ein erfundener Dialog nach dem Vorbild philosophischer Begriffsprüfung: Nikos zeigt auf einen reichen Händler und nennt ihn erfolgreich. Eine ältere Gesprächsperson fragt: Was genau macht ihn erfolgreich?\n\nDie Szene ist kein überlieferter Wortwechsel mit Sokrates. Sie macht eine Methode sichtbar, die Platons Dialoge auf unterschiedliche Begriffe anwenden.',image='socratic-agora',alt='Drei Menschen führen unter einem antiken Portikus ein aufmerksames Gespräch.',caption=ILLUSTRATION),
 card('dialogue','Ein Name ist noch keine Regel','Nikos: Schau ihn doch an. Er besitzt viel.\nAntwort: Das ist ein Beispiel. Welche Eigenschaft sollen alle erfolgreichen Menschen gemeinsam haben?\n\nEin Beispiel zeigt einen Fall. Eine Definition versucht, den Begriff so abzugrenzen, dass du auch neue Fälle beurteilen kannst. Die erste Arbeitsdefinition lautet: Erfolgreich ist, wer viel Geld besitzt.'),
 card('decision','Prüfbare Behauptung oder Ausweichen?','Du sollst die Arbeitsdefinition prüfen, nicht Nikos persönlich beurteilen.',probe=sc('Welche Frage hilft dabei unmittelbar?','Ist jeder Mensch mit viel Geld erfolgreich, unabhängig davon, wie er lebt?','Warum magst du den Händler nicht?','Wie teuer sind die Sandalen des Händlers?','Die Frage prüft, ob die genannte Eigenschaft als ausreichendes Kriterium gedacht ist.')),
 card('reveal','Was fehlt an «Du weisst schon»?','Warum genügt die Antwort «Erfolg ist halt Erfolg» nicht als Erklärung?',reveal='Sie wiederholt den Begriff, ohne ihn abzugrenzen. Eine brauchbare Arbeitsdefinition nennt Kriterien, an denen wir einen unbekannten Fall prüfen können. Sie muss noch nicht endgültig richtig sein.')
],[sc('Was unterscheidet eine Definition von einem einzelnen Beispiel?','Sie nennt Kriterien für weitere Fälle','Sie muss eine berühmte Person nennen','Sie ersetzt jede spätere Prüfung','Eine Definition macht den Begriff auf neue Fälle anwendbar.'),recall('Wie heisst die vorläufige begriffliche Abgrenzung, die wir prüfen?','Arbeitsdefinition|Definition','Sie ist ein Ausgangspunkt für die Prüfung, kein unangreifbares Endergebnis.'),sc('Was ist am Satz «Erfolg ist Erfolg» unzureichend?','Er liefert keine abgrenzenden Kriterien','Er enthält zu wenige historische Namen','Er ist bereits ein Gegenbeispiel','Die Wiederholung erklärt nicht, was unter den Begriff fällt.'),multi('Welche Handlungen dienen der Begriffsprüfung?',['Kriterien erfragen','Einen neuen Fall an den Kriterien prüfen','Die Person lächerlich machen','Beliebtheit mit Wahrheit gleichsetzen'],[0,1],'Geprüft wird die Behauptung, nicht der soziale Rang des Sprechers.'),sc('Ist unser Portikus-Dialog ein historisches Sokrates-Zitat?','Nein, eine ausdrücklich erfundene Anwendung','Ja, jedes antike Szenenbild beweist den Wortlaut','Ja, weil darin eine Frage vorkommt','Die Methode wird durch einen eigenen Dialog illustriert.')],
'Ein gutes Beispiel macht einen Begriff anschaulich; eine Definition macht ihn prüfbar.','Formuliere deine eigene Arbeitsdefinition von Erfolg in einem Satz.',S),
chapter(SOCRATES,2,'Die Uhr ohne Publikum','Du prüfst eine allgemeine Definition mit einem passenden Gegenbeispiel.',[
 card('scene','Der Besitz ist sichtbar, das Leben nicht','Stell dir eine Person mit einer kostbaren Uhr vor. Sie verdient gut, arbeitet gegen ihre Überzeugungen und hat keinerlei freie Zeit. Das ist ein gedachter Fall, keine Behauptung über Uhrenbesitzer.\n\nDie Frage bleibt eng: Reicht Geld allein aus, um dieses Leben erfolgreich zu nennen?',image='socratic-watch',alt='Eine unmarkierte mechanische Uhr liegt neben einer persönlichen Notiz auf einem Tisch.',caption=FICTION),
 card('dialogue','Was ein Gegenbeispiel leistet','Wenn Nikos selbst diesen reichen Menschen nicht erfolgreich nennt, verträgt sich sein Urteil nicht mit «Jeder Mensch mit viel Geld ist erfolgreich». Ein Gegenbeispiel widerlegt eine ausnahmslose Behauptung, sofern es die genannten Bedingungen erfüllt und trotzdem nicht zum behaupteten Ergebnis führt.\n\nEs beweist nicht das Gegenteil «Geld ist immer unwichtig». Das wäre ein neuer, ebenso grosser Sprung.'),
 card('decision','Welcher Einwand trifft die Definition?','Die Definition behauptet ausdrücklich, Geld allein genüge.',probe=sc('Welcher Einwand prüft genau dieses «allein»?','Ein reicher Mensch, den Nikos wegen seines unfreien Lebens nicht erfolgreich nennt','Eine arme Person, die Nikos ebenfalls nicht erfolgreich nennt','Eine Uhr, die Nikos optisch nicht gefällt','Nur der erste Fall erfüllt das Geldkriterium und widerspricht gleichzeitig dem Erfolgsurteil.')),
 card('transfer','Kein heimlicher Moralwechsel','Die Untersuchung entscheidet nicht, ob du eine Uhr kaufen sollst. Sie fragt, ob ein sichtbarer Besitz als vollständiges Kriterium für ein gutes Ergebnis taugt. Wer daraus pauschal «Luxus ist schlecht» macht, hat während der Diskussion den Begriff gewechselt.')
],[sc('Was muss ein Gegenbeispiel zur Behauptung «Geld allein genügt» erfüllen?','Viel Geld liegt vor, das Erfolgsurteil wird trotzdem verneint','Geld fehlt und Erfolg wird verneint','Die Person besitzt eine andere Uhrenmarke','Das Beispiel muss die behauptete ausreichende Bedingung erfüllen.'),multi('Welche Schlüsse sind nach einem passenden Gegenbeispiel zulässig?',['Die ausnahmslose Definition muss geprüft werden','Geld allein ist nach diesen Urteilen nicht ausreichend','Geld ist deshalb immer wertlos','Jeder reiche Mensch lebt schlecht'],[0,1],'Das Gegenbeispiel widerlegt die starke Regel, nicht jede Bedeutung von Geld.'),recall('Wie nennt man einen passenden Fall gegen eine allgemeine Behauptung?','Gegenbeispiel','Ein einziger passender Fall kann eine ausnahmslose Regel widerlegen.'),sc('Warum ist eine missfallende Uhrenfarbe kein Gegenbeispiel?','Sie prüft Geschmack statt des behaupteten Zusammenhangs von Geld und Erfolg','Farben existieren nicht in Definitionen','Uhren dürfen grundsätzlich nicht als Beispiele dienen','Der Einwand muss zur genauen Behauptung passen.'),sc('Was wäre ein unzulässiger neuer Schluss?','Weil Geld allein nicht genügt, ist Geld immer unwichtig','Die Definition braucht ein weiteres Kriterium','Wir sollten Erfolg genauer abgrenzen','Nicht ausreichend bedeutet nicht bedeutungslos.')],
'Ein Gegenbeispiel trifft eine genaue Behauptung. Es ist kein Freibrief für das entgegengesetzte Vorurteil.','Suche ein Gegenbeispiel zu deiner Erfolgsdefinition, das du selbst ernst nehmen würdest.',S),
chapter(SOCRATES,3,'Nötig oder schon genug?','Du unterscheidest notwendige und hinreichende Bedingungen.',[
 card('lab','Eine kleine logische Trennung','Eine notwendige Bedingung muss vorhanden sein, damit etwas gelten kann. Eine hinreichende Bedingung genügt bereits dafür. Als klares Übungsbeispiel: Ein Quadrat hat vier Seiten. Vier Seiten sind dafür notwendig, aber nicht hinreichend – auch ein nichtquadratisches Rechteck hat vier Seiten.\n\nDie Unterscheidung hilft uns, Nikos genauer zu verstehen. Meint er: Ohne Geld kein Erfolg? Oder: Mit Geld automatisch Erfolg?'),
 card('dialogue','Die Regel hat sich verändert','Nikos sagt nun: Geld garantiert kein gutes Leben, aber ein Mindestmass an Sicherheit ist für meine Definition notwendig. Damit zieht er sich nicht bloss sprachlich zurück. Er stellt eine andere Behauptung auf, die anders geprüft werden muss.\n\nEin reicher unglücklicher Mensch widerlegt «Geld genügt». Er widerlegt nicht automatisch «Ein Mindestmass an Sicherheit ist nötig».'),
 card('decision','Welchen Fall brauchst du jetzt?','Prüfe die neue Behauptung: Ohne das verlangte Mindestmass an Sicherheit könne niemand nach Nikos erfolgreich sein.',probe=sc('Welcher gedachte Fall würde dieser Notwendigkeitsbehauptung widersprechen?','Jemand ohne dieses Mindestmass, den Nikos dennoch erfolgreich nennt','Ein wohlhabender Mensch, den Nikos erfolgreich nennt','Ein wohlhabender Mensch mit einer teuren Uhr','Ein Gegenbeispiel gegen Notwendigkeit zeigt das Ergebnis trotz fehlender Bedingung.')),
 card('reveal','Übersetze statt auswendig lernen','Erkläre «notwendig» und «hinreichend» ohne die beiden Fachwörter.',reveal='Notwendig: Ohne das geht es nicht. Hinreichend: Wenn das vorliegt, reicht es schon. Etwas kann nötig sein, ohne allein zu genügen. Welche Bedingungen für Erfolg gelten sollen, bleibt eine begründungsbedürftige Wertfrage.')
],[recall('Eine Bedingung, ohne die etwas nicht möglich sein soll, heisst ___.','notwendig|notwendige Bedingung','Notwendig bedeutet erforderlich, nicht schon allein ausreichend.',True),recall('Eine Bedingung, die bereits genügt, heisst ___.','hinreichend|hinreichende Bedingung','Hinreichend bedeutet ausreichend.',True),sc('Vier Seiten sind für ein Quadrat …','notwendig, aber nicht hinreichend','hinreichend, aber nicht notwendig','weder notwendig noch hinreichend','Auch andere Vierecke haben vier Seiten.'),sc('Was widerlegt «Ohne Sicherheit kein Erfolg»?','Ein als erfolgreich anerkannter Fall ohne die geforderte Sicherheit','Ein erfolgloser Fall ohne Sicherheit','Ein erfolgreicher Fall mit Sicherheit','Das behauptete notwendige Merkmal fehlt trotz anerkanntem Ergebnis.'),multi('Welche Aussagen sind logisch vereinbar?',['Etwas kann notwendig sein, ohne allein zu genügen.','Eine neue Definition braucht eine neue Prüfung.','Jede notwendige Bedingung garantiert das Ergebnis.','Ein Gegenbeispiel passt automatisch zu jeder Version einer Definition.'],[0,1],'Der genaue Bedingungstyp bestimmt die passende Prüfung.')],
'«Ohne das nicht» ist etwas anderes als «Mit dem automatisch».','Prüfe in einem Werbespruch, ob eine Voraussetzung stillschweigend als Erfolgsgarantie verkauft wird.',S),
chapter(SOCRATES,4,'Eine Definition, die sich ändern darf','Du überarbeitest eine Position nachvollziehbar und erkennst offene Wertfragen.',[
 card('dialogue','Nikos formuliert neu','Seine neue Arbeitsdefinition: Erfolg bedeutet für mich, wichtige selbstgewählte Ziele zu erreichen, ohne grundlegende Verpflichtungen dauerhaft zu verletzen. Geld kann dabei Mittel oder Teilziel sein.\n\nDie Definition löst nicht jede Frage. Welche Ziele sind wichtig? Welche Verpflichtungen grundlegend? Aber sie legt mehr von den tatsächlichen Wertungen offen als eine einzige sichtbare Zahl.'),
 card('decision','Die nächste gute Frage','Du willst die neue Definition weiter untersuchen, ohne dem anderen deine Werte unterzuschieben.',probe=sc('Welche Rückfrage hilft?','Welche Verpflichtung dürfte für ein Ziel nicht dauerhaft verletzt werden?','Welche Uhr beweist die Definition endgültig?','Warum gibst du nicht einfach zu, dass ich gewonnen habe?','Die Rückfrage prüft einen unklaren Begriff innerhalb der überarbeiteten Definition.')),
 card('evidence','Nicht jede Differenz ist ein Denkfehler','Zwei Personen können den Begriff klar verwenden und Ziele trotzdem verschieden gewichten. Dann besteht ein Wertkonflikt, nicht zwingend ein logischer Widerspruch. Ein logischer Widerspruch entsteht etwa, wenn jemand gleichzeitig an «Geld genügt immer» festhält und einen reichen Gegenfall ausdrücklich ausschliesst.\n\nGute Gespräche unterscheiden unklare Wörter, widersprüchliche Regeln und unterschiedliche Werte.'),
 card('transfer','Dein eigener Satz, zweite Fassung','Kehre zu deiner ersten Erfolgsdefinition zurück. Ändere höchstens einen Satz und begründe die Änderung anhand eines Falles. Wenn du nichts änderst, nenne den stärksten Einwand und deine Antwort darauf.',reveal='Du musst nicht Nikos’ Definition übernehmen. Der Lerngewinn ist die Methode: Begriff klären, passenden Fall prüfen, Bedingung unterscheiden und die Position begründet weiterentwickeln. Revision kann ein Zeichen besseren Denkens sein, nicht einer Niederlage.')
],[order('Ordne den bearbeiteten Prüfweg.',['Arbeitsdefinition formulieren','Passendes Gegenbeispiel prüfen','Bedingungen präzisieren','Definition begründet überarbeiten'],'Die Schritte machen Änderungen nachvollziehbar.'),sc('Zwei Menschen gewichten Freiheit unterschiedlich, verwenden die Begriffe aber klar. Was kann vorliegen?','Ein Wertkonflikt','Zwingend ein Rechenfehler','Zwingend Unehrlichkeit einer Person','Eine andere Gewichtung ist nicht schon ein logischer Widerspruch.'),multi('Was kennzeichnet eine faire Begriffsprüfung?',['Die andere Position korrekt wiedergeben','Auch die eigene Definition prüfen','Jede Revision als Niederlage behandeln','Den Begriff bei Einwänden unbemerkt wechseln'],[0,1],'Die Methode gilt für beide Gesprächsseiten.'),sc('Warum ist die neue Definition nicht automatisch endgültig?','Auch ihre Begriffe und Wertungen brauchen weitere Prüfung','Weil Definitionen keine Wörter enthalten dürfen','Weil Geld ausnahmslos allein genügt','Eine präzisere Arbeitsdefinition kann weiterhin offene Fragen enthalten.'),recall('Eine begründete Überarbeitung der eigenen Position kann man auch ___ nennen.','Revision|Präzisierung|Ueberarbeitung|Überarbeitung','Überarbeitung aufgrund guter Gründe ist ein normaler Teil des Denkens.',True)],
'Das Ziel des Gesprächs ist eine besser begründete Position, nicht ein Siegerfoto.','Nutze bei der nächsten Meinungsverschiedenheit eine faire Rückfrage, die du auch dir selbst stellen würdest.',S)
]
