from story_authoring import *

SLEEP=topic('sleep','health','Morgen müde – gestern entschieden','Ein Abend, eine frühe Abfahrt und ein scheinbar harmloses «noch ein Video». Du untersuchst, wo die verlorene Erholung beginnt.','Alltagsbeobachtung')
HABIT=topic('habit','development','Der Moment an der Haustür','Du willst abends weniger scrollen. Statt eines neuen grossen Vorsatzes baust du einen Plan für genau einen wiederkehrenden Moment.','Verhaltensexperiment')
DEAL=topic('deal','communication','Zu teuer – oder falsch verstanden?','Eine Kundin verlangt einen niedrigeren Preis. In vier Schritten findest du heraus, was sie tatsächlich braucht und wo deine Grenze liegt.','Verhandlungsdialog')
TOPICS=[SLEEP,HABIT,DEAL]
N=source('NHLBI · Healthy Sleep Habits','https://www.nhlbi.nih.gov/health/sleep-deprivation/healthy-sleep-habits')
NC=source('NHLBI · Your Sleep/Wake Cycle','https://www.nhlbi.nih.gov/health/sleep/sleep-wake-cycle')
NI=source('NHLBI · Why Is Sleep Important?','https://www.nhlbi.nih.gov/health/sleep/why-sleep-important')
H=source('Gollwitzer & Sheeran · Implementation Intentions and Goal Achievement (2006)','https://doi.org/10.1016/S0065-2601(06)38002-1')
D=source('OpenStax · Negotiation Behavior','https://openstax.org/books/organizational-behavior/pages/14-4-negotiation-behavior')
LESSONS=[
chapter(SLEEP,1,'Der Abend leiht sich Zeit vom Morgen','Du unterscheidest verfügbare Schlafzeit von tatsächlich geschlafener Zeit.',[
 card('scene','Das Video dauert nur kurz','Fiktiver Alltag: Morgen musst du um 06:00 aufstehen. Um 22:30 könntest du das Licht ausschalten. Stattdessen schaust du bis 23:30 weiter. Die Abfahrt verschiebt sich nicht.\n\nDu hast damit nicht eine freie Stunde entdeckt. Du hast das mögliche Schlaffenster um eine Stunde verkürzt.',image='sleep-evening',alt='Eine Person legt ihr Telefon auf eine Ablage ausserhalb eines abendlich beleuchteten Schlafzimmers.',caption=FICTION),
 card('decision','Rechne die Gelegenheit, nicht das Wunschgefühl','Zwischen 22:30 und 06:00 liegen 7 Stunden 30 Minuten. Zwischen 23:30 und 06:00 liegen 6 Stunden 30 Minuten.',probe=number('Wie viele Minuten Schlafgelegenheit bleiben beim späteren Lichtausschalten?',390,'Minuten','6 × 60 + 30 = 390 Minuten. Das ist noch nicht automatisch die tatsächlich geschlafene Zeit.')),
 card('evidence','Zeit im Bett ist nicht identisch mit Schlaf','Einschlafzeit und nächtliche Wachphasen können die tatsächliche Schlafdauer verkürzen. Die Rechnung beschreibt deshalb nur die Gelegenheit zum Schlafen. Sie diagnostiziert weder Schlafqualität noch eine Erkrankung.\n\nAusreichender Schlaf unterstützt Denken, Lernen und Gesundheit. Eine bewusst geschützte Zeitspanne ist eine Voraussetzung, aber kein Knopf, der Schlaf erzwingt.'),
 card('transfer','Die Entscheidung früher verlegen','Wenn deine Aufstehzeit feststeht, liegt ein Teil des Spielraums am Vorabend. Ein klarer Zeitpunkt fürs Beenden der Unterhaltung macht den Konflikt sichtbar, bevor du müde im nächsten Video landest. Halte den Plan realistisch; die passende Schlafdauer ist nicht allein aus einem App-Timer abzulesen.')
],[number('Wie viele Minuten liegen zwischen 22:30 und 06:00?',450,'Minuten','7 Stunden 30 Minuten entsprechen 450 Minuten.'),number('Um wie viele Minuten verkürzt 23:30 statt 22:30 das Fenster bei gleicher Aufstehzeit?',60,'Minuten','Der spätere Beginn verschiebt sich um eine Stunde.'),sc('Was beschreibt das berechnete Zeitfenster zunächst?','Schlafgelegenheit','Garantierte Tiefschlafdauer','Eine ärztliche Diagnose','Einschlafen und Wachphasen sind in dieser einfachen Zeitspanne nicht abgezogen.'),multi('Was kann tatsächliche Schlafzeit gegenüber der Bettzeit verkürzen?',['Einschlafzeit','Nächtliche Wachphasen','Eine gleiche feste Aufstehzeit als automatische Verlängerung','Die reine Anzeige des Timers'],[0,1],'Bettzeit und Schlafdauer sind nicht identisch.'),sc('Wo liegt bei festem Aufstehen ein veränderbarer Teil des Plans?','Beim Ende der abendlichen Aktivitäten','Nur beim Design des Weckers','Ausschliesslich beim Wetter','Ein späteres Ende verkürzt das verfügbare Fenster.')],
'Wenn der Morgen feststeht, wird die Schlafgelegenheit oft schon am Abend verteilt.','Rechne dein nächstes mögliches Schlaffenster aus, ohne es mit garantiertem Schlaf gleichzusetzen.',N),
chapter(SLEEP,2,'Zwei Signale, nicht nur Müdigkeit','Du verstehst Schlafdruck und den Tagesrhythmus als unterschiedliche Einflüsse.',[
 card('lab','Warum bist du müde und trotzdem wach?','Zwei Einflüsse helfen, den Schlaf-Wach-Rhythmus zu verstehen. Schlafdruck baut sich während des Wachseins auf und sinkt im Schlaf. Daneben beeinflusst die innere Tagesrhythmik, wann der Körper eher Wachheit oder Schlafbereitschaft unterstützt.\n\nDiese Erklärung ist vereinfacht. Sie zeigt, warum lange wach sein und zur passenden Zeit schlafen können nicht dieselbe Frage sind.'),
 card('evidence','Licht ist ein Zeitzeichen','Licht und Dunkelheit sind wichtige Hinweise für die innere Uhr. Regelmässige Tagesabläufe und passende Lichtverhältnisse können sie unterstützen. Beim Bildschirm wirken ausserdem Inhalte: Ein aufwühlender Austausch oder ein endloser Feed kann das Beenden unabhängig von der Lichtfarbe erschweren.\n\nEin Nachtmodus ist daher kein Freipass für beliebig langes Scrollen.'),
 card('decision','Der Bildschirm ist warm gefärbt','Du aktivierst einen Farbfilter, bleibst aber eine Stunde länger am Feed.',probe=sc('Welche Aussage folgt daraus sicher für das feste Schlaffenster?','Die spätere Bettzeit verkürzt weiterhin die Schlafgelegenheit','Der Farbfilter stellt die verlorene Stunde automatisch wieder her','Schlafdruck und Tagesrhythmus sind jetzt ausgeschaltet','Eine geänderte Farbe verschiebt die feste Aufstehzeit nicht.')),
 card('reveal','Erklär den Unterschied ohne Biologieprüfung','Beschreibe die beiden Einflüsse mit «wie lange» und «wann».',reveal='Schlafdruck hängt vereinfacht damit zusammen, wie lange du schon wach bist. Die innere Tagesrhythmik beeinflusst, wann Wachheit und Schlafbereitschaft unterstützt werden. Beides wirkt zusammen; einzelne Gewohnheiten erklären nicht jede Schlafstörung.')
],[recall('Wie nennen wir den während des Wachseins wachsenden Schlafbedarf im vereinfachten Modell?','Schlafdruck','Schlafdruck und innere Tagesrhythmik sind unterschiedliche Einflüsse.'),sc('Welche Rolle spielt Licht für die innere Uhr?','Es dient als wichtiger Zeitgeber','Es garantiert unabhängig von allem anderen sofortigen Schlaf','Es ersetzt die benötigte Schlafgelegenheit','Licht unterstützt die zeitliche Abstimmung, nicht eine beliebige Schlafverkürzung.'),multi('Warum löst ein Nachtmodus das ganze Problem nicht?',['Die Nutzungsdauer kann weiterhin die Bettzeit verschieben','Inhalte können das Abschalten erschweren','Er erzeugt automatisch zusätzliche Nachtstunden','Er beseitigt jede Schlafstörung'],[0,1],'Lichtfarbe ist nur ein möglicher Einfluss unter mehreren.'),sc('Was beschreibt die Frage «Wie lange bin ich bereits wach?» am ehesten?','Schlafdruck','Ausschliesslich die Uhrzeit auf dem Display','Den Preis des Bettes','Sie betrifft den wachsenden Schlafdruck, nicht nur den Tageszeitpunkt.'),sc('Warum sollte das vereinfachte Modell nicht als Diagnose benutzt werden?','Weitere persönliche und medizinische Faktoren können beteiligt sein','Weil Schlaf keinerlei körperliche Grundlage hat','Weil Zeit grundsätzlich nicht messbar ist','Ein Lernmodell erklärt einen Zusammenhang, ersetzt aber keine Abklärung.')],
'Schlafdruck und innere Uhr arbeiten zusammen; ein einzelner Bildschirmfilter ersetzt keinen passenden Abend.', 'Prüfe getrennt: Wann endet der Feed, und welche Umgebung unterstützt danach das Ruhigerwerden?',NC),
chapter(SLEEP,3,'Wach fühlen ist nicht alles','Du unterscheidest subjektive Wachheit von verlässlicher Leistungsfähigkeit.',[
 card('scene','Am Morgen geht es irgendwie','Im Lernfall sitzt du mit einer Tasse am Tisch. Du fühlst dich nach einer kurzen Nacht etwas wacher. Trotzdem ist dieses Gefühl kein vollständiger Test von Aufmerksamkeit oder Reaktionsfähigkeit.',image='sleep-morning',alt='Eine müde Person sitzt bei frühem Tageslicht mit Tasse und Arbeitstasche am Tisch.',caption=FICTION),
 card('evidence','Was Schlaf für den Kopf bedeutet','Schlaf unterstützt unter anderem Lernen und die Bildung langfristiger Erinnerungen. Zu wenig oder schlechter Schlaf kann Konzentration und klares Denken beeinträchtigen. Es ist deshalb unpräzise, nur «Ich halte noch durch» als Qualitätsmassstab zu verwenden.\n\nEine einzelne müde Phase beweist umgekehrt keine bestimmte Erkrankung. Beobachtung und Diagnose sind verschiedene Schritte.'),
 card('decision','Eine riskante Selbstprüfung','Du merkst beim Fahren deutliche Schläfrigkeit und willst dich mit einem besonders spannenden Podcast wach halten.',probe=sc('Welche Reaktion ist sicherer?','Die Fahrt sicher unterbrechen und nicht schläfrig weiterfahren','Nur die Lautstärke erhöhen und weiterfahren','Den App-Timer als Beweis der Fahrtüchtigkeit ansehen','Bei Schläfrigkeit am Steuer ist eine sichere Unterbrechung nötig. Unterhaltung oder ein App-Wert belegen keine Fahrtüchtigkeit.')),
 card('transfer','Daten sammeln, ohne dich zu diagnostizieren','Ein einfaches Protokoll von Schlafgelegenheiten, längeren Wachphasen und Tagesmüdigkeit kann ein Gespräch erleichtern. Bei anhaltenden Beschwerden, ausgeprägter Tagesmüdigkeit oder beobachteten Atemaussetzern ist ärztliche Abklärung sinnvoll. Gate kann diese Ursachen nicht diagnostizieren.\n\nDas Ziel ist Erholung und Sicherheit, nicht eine möglichst perfekte Schlafzahl um jeden Preis.')
],[sc('Was beweist das Gefühl «Ich bin wieder etwas wacher» nicht?','Dass Aufmerksamkeit und Reaktionsfähigkeit vollständig unbeeinträchtigt sind','Dass überhaupt ein Gefühl vorhanden ist','Dass am Morgen Licht durch ein Fenster fällt','Subjektive Wachheit ist kein vollständiger Leistungstest.'),multi('Welche Bereiche kann zu wenig Schlaf beeinträchtigen?',['Konzentration','Klares Denken','Die mathematische Länge einer Minute','Die Existenz von Tageslicht'],[0,1],'Schlafmangel kann kognitive Leistungen beeinflussen.'),sc('Was ist bei deutlicher Schläfrigkeit am Steuer angemessen?','Sicher unterbrechen statt schläfrig weiterfahren','Nur ein aufregenderes Video wählen','Sich auf den Lernfortschritt in Gate verlassen','App-Werte ersetzen keine Fahrtüchtigkeit.'),sc('Was kann ein einfaches Schlafprotokoll leisten?','Beobachtungen für ein Gespräch strukturieren','Jede Schlafstörung selbst sicher diagnostizieren','Eine medizinische Abklärung grundsätzlich ersetzen','Ein Protokoll liefert Informationen, keine automatische Diagnose.'),sc('Wann sollte professionelle Abklärung erwogen werden?','Bei anhaltenden Beschwerden oder ausgeprägter Tagesmüdigkeit','Ausschliesslich bei einem roten App-Symbol','Nie, solange eine Tasse wach macht','Dauerhafte Beschwerden verdienen eine fachliche Bewertung.')],
'Erholung ist mehr als das Gefühl, gerade noch durchzuhalten.','Beobachte deine Tagesmüdigkeit ohne Selbstdiagnose und plane Sicherheit vor Leistung um jeden Preis.',NI),
chapter(SLEEP,4,'Ein kleiner Versuch am Abend','Du entwirfst eine überprüfbare Veränderung, ohne aus einer Nacht ein Naturgesetz abzuleiten.',[
 card('decision','Nicht alles gleichzeitig ändern','Du willst prüfen, ob ein früheres Ende des Feeds dir mehr Schlafgelegenheit lässt. Im Alltag ändern sich aber auch Stress, Bewegung und Termine.',probe=sc('Welcher Versuch ist am ehesten nachvollziehbar?','Einen klaren Schlusszeitpunkt wählen und Bettzeit sowie Tagesgefühl mehrere Tage notieren','Jeden Abend fünf neue Regeln ausprobieren und nur die beste Nacht behalten','Nach einer Nacht jede andere Ursache ausschliessen','Eine überschaubare Änderung und mehrere Beobachtungen machen den Vergleich verständlicher.')),
 card('lab','Was du tatsächlich erfassen kannst','Notiere vor dem Versuch, was du ändern willst: zum Beispiel den Feed eine halbe Stunde früher beenden und das Telefon ausserhalb des Betts laden. Notiere danach, wann du tatsächlich ins Bett gegangen bist.\n\nDie Zielgrösse ist zunächst ein früheres, verlässlicheres Schlaffenster – nicht die Behauptung, eine App habe deinen Tiefschlaf exakt gemessen.'),
 card('evidence','Ein besserer Morgen ist ein Hinweis','Wenn du dich nach mehreren früheren Abenden besser fühlst, ist das interessant. Ein persönlicher Alltagsversuch kontrolliert aber nicht alle anderen Einflüsse. Du darfst eine hilfreiche Gewohnheit behalten, ohne eine universelle medizinische Wirkung zu behaupten.\n\nWenn der Versuch zusätzlichen Druck erzeugt, vereinfache ihn. Schlaf lässt sich nicht durch die perfekte Erfüllung einer Checkliste erzwingen.'),
 card('reveal','Die Ausgangsfrage beantworten','Was hat das späte Video mit dem müden Morgen zu tun – und was wissen wir damit noch nicht?',reveal='Bei festem Aufstehen nimmt die spätere Bettzeit Schlafgelegenheit weg. Ob und wie stark das die konkrete Müdigkeit erklärt, hängt von tatsächlichem Schlaf und weiteren Einflüssen ab. Du hast einen veränderbaren Faktor gefunden, keine vollständige Diagnose.')
],[sc('Welche Zielgrösse passt zum Versuch mit früherem Feed-Ende?','Die tatsächliche Bettzeit und verfügbare Schlafgelegenheit','Eine erfundene exakte Tiefschlafmessung durch Gate','Die Bewertung anderer Menschen','Der Versuch verändert einen beobachtbaren Zeitpunkt.'),multi('Was macht die Auswertung ehrlicher?',['Mehrere Tage betrachten','Andere mögliche Einflüsse mitdenken','Nur die beste Nacht auswählen','Eine einzelne Nacht als Beweis für alle Menschen verwenden'],[0,1],'Alltagsbeobachtungen bleiben durch weitere Faktoren beeinflusst.'),order('Ordne einen überschaubaren Alltagsversuch.',['Eine konkrete Änderung wählen','Ihre Umsetzung beobachten','Mehrere Beobachtungen vergleichen','Plan bei Bedarf anpassen'],'Vorher festlegen hilft gegen nachträgliche Wunschdeutung.'),sc('Was folgt aus einem hilfreichen persönlichen Versuch nicht automatisch?','Ein universeller medizinischer Wirksamkeitsnachweis','Dass du deine Bettzeit beobachtet hast','Dass eine Gewohnheit für dich praktikabel sein kann','Persönlicher Nutzen und allgemeiner Nachweis sind verschieden.'),sc('Der Plan erzeugt Druck und du schläfst deshalb nicht wie gewünscht. Was passt?','Den Plan vereinfachen und bei anhaltenden Problemen Unterstützung suchen','Schlaf mit noch strengeren Strafen erzwingen','Jede Müdigkeit als persönliches Versagen behandeln','Ein hilfreicher Plan soll unterstützen, nicht Schlaf zur Prüfung machen.')],
'Schütze eine echte Schlafgelegenheit und prüfe Veränderungen nüchtern, ohne Perfektionsdruck.','Wähle für einige Abende genau eine umsetzbare Änderung und eine einfache Beobachtung.',N),
chapter(HABIT,1,'Der Vorsatz verpasst seinen Einsatz','Du übersetzt ein allgemeines Ziel in eine konkrete Wenn-dann-Verknüpfung.',[
 card('scene','Die Tür fällt ins Schloss','Fiktiver Fall: Du kommst heim, legst die Tasche ab und öffnest automatisch einen Feed. Du hattest morgens fest vor, weniger zu scrollen. Das Problem ist nicht, dass der Vorsatz grammatisch unklar wäre. Er sagt nur nicht, was genau in diesem Moment passieren soll.',image='habit-door',alt='Eine Hand greift im Eingangsbereich nach bereitgestellten Schuhen; ein Telefon liegt in einer Schale.',caption=FICTION),
 card('lab','Gib dem Plan einen Auslöser','Ein Wenn-dann-Plan verbindet eine erkennbare Situation mit einer konkreten Handlung. Beispiel: Wenn ich zuhause meine Tasche abstelle, lege ich das Telefon auf die Ablage und ziehe die Schuhe für einen kurzen Gang an.\n\nDie Handlung soll zu deinem Ziel passen und in der Situation ausführbar sein. Ein Plan ist eine Hilfe zum Beginnen, keine Garantie und kein Beweis mangelnden Charakters, wenn es nicht klappt.'),
 card('decision','Welche Formulierung hat einen Einsatz?','Vergleiche die drei Pläne.',probe=sc('Welcher nennt Situation und beobachtbare Handlung?','Wenn ich die Tasche abstelle, lege ich das Telefon in die Schale','Ich werde irgendwann disziplinierter','Ich werde nie wieder einen Impuls spüren','Der erste Plan sagt, wann welche Handlung beginnen soll.')),
 card('transfer','Klein genug für einen müden Abend','Der erste Schritt darf sehr klein sein. Er soll den Einstieg eindeutig machen. «Eine Stunde produktiv sein» ist noch ein Bündel unklarer Entscheidungen. «Das Buch aufschlagen und einen Absatz lesen» beschreibt einen Beginn. Welcher Schritt sinnvoll ist, hängt von deinem eigentlichen Ziel ab.')
],[recall('Wie heisst die hier verwendete Verbindung aus Situation und Handlung?','Wenn-dann-Plan|Wenn dann Plan|Implementierungsintention|Implementation Intention','Die Situation wird mit einer konkreten Reaktion verknüpft.'),sc('Was fehlt «Ich scrolle künftig weniger» für diesen Plan?','Ein konkreter Auslöser und eine ausführbare Handlung','Ein noch strengeres Adjektiv','Eine möglichst grosse öffentliche Ankündigung','Das Ziel nennt noch keinen eindeutigen Beginn.'),multi('Was sollte ein Auslöser im Plan sein?',['Erkennbar','In deinem Alltag tatsächlich vorkommend','Möglichst vage','Von der gewünschten Handlung unabhängig unerreichbar'],[0,1],'Ein nicht erkennbarer oder nie auftretender Auslöser hilft beim Beginnen kaum.'),sc('Warum kann ein kleiner erster Schritt sinnvoll sein?','Er reduziert offene Entscheidungen beim Einstieg','Er garantiert jede langfristige Veränderung','Er ersetzt das eigentliche Ziel dauerhaft','Ein leichter Einstieg ist eine Unterstützung, kein vollständiges Ergebnis.'),sc('Ein Plan klappt an einem Abend nicht. Was beweist das?','Allein noch keinen grundlegenden Charakterfehler','Dass die Handlung für immer unmöglich ist','Dass jeder Plan wissenschaftlich widerlegt ist','Die konkrete Situation und Passung des Plans müssen untersucht werden.')],
'Ein Ziel benennt die Richtung. Ein Wenn-dann-Plan benennt den Moment des Handelns.','Schreibe einen Plan mit genau einer erkennbaren Situation und einem kleinen sichtbaren ersten Schritt.',H),
chapter(HABIT,2,'Die Umgebung stimmt mit ab','Du unterscheidest Auslöser, Reibung und Handlung.',[
 card('lab','Zwei Versionen derselben Haustür','Version A: Das Telefon liegt griffbereit auf dem Sofa, die Schuhe sind im Keller. Version B: Die Schuhe stehen an der Tür, die Telefonablage liegt im Flur.\n\nBeide Versionen lassen dir eine Entscheidung. Sie unterscheiden sich aber darin, welche Handlung gerade einfach erreichbar ist. Umgebung ersetzt nicht jedes Motiv; sie kann die Ausführung erleichtern oder erschweren.'),
 card('evidence','Drei verschiedene Dinge','Auslöser: Du stellst die Tasche ab. Reibung: Wie viele Schritte brauchst du, um loszugehen? Handlung: Du ziehst die Schuhe an.\n\nWenn du diese Ebenen verwechselst, baust du vielleicht nur eine weitere Erinnerung, obwohl in Wahrheit die Ausführung umständlich ist. Oder du bereitest alles vor, erkennst aber den vorgesehenen Startmoment nicht.'),
 card('decision','Der Plan scheitert am Suchen','Du erinnerst dich an den Gang, findest aber jeden Abend erst Jacke und Schlüssel nicht.',probe=sc('Welche Änderung trifft dieses Hindernis am direktesten?','Jacke und Schlüssel vorher an einen festen erreichbaren Platz legen','Den Vorsatz mit mehr Ausrufezeichen schreiben','Einen völlig anderen Auslöser wählen, obwohl der bisherige erkannt wird','Hier ist der Start erinnert; die umständliche Ausführung ist das konkrete Hindernis.')),
 card('reveal','Kein perfektes Haus nötig','Nenne eine einzige Veränderung, die den ersten Schritt leichter macht, ohne dein ganzes Zuhause umzubauen.',reveal='Zum Beispiel die Schuhe bereitstellen oder einen festen Ladeplatz ausserhalb des Sofabereichs wählen. Prüfe die Wirkung im Alltag. Eine zusätzliche Hürde soll unterstützen und wichtige Kommunikation nicht unnötig behindern.')
],[sc('Was beschreibt die Reibung im Beispiel?','Den Aufwand zwischen Auslöser und gewünschter Handlung','Eine moralische Eigenschaft des Telefons','Ausschliesslich die Stärke eines Ziels','Suchen und zusätzliche Wege können einen einfachen Beginn erschweren.'),recall('Der erkennbare Startmoment eines Plans ist sein ___.','Auslöser|Trigger','Der Auslöser erinnert an die vorab gewählte Handlung.',True),multi('Welche Änderungen betreffen die Ausführbarkeit?',['Schuhe bereitlegen','Schlüssel an einen festen Platz legen','Den gleichen vagen Vorsatz lauter sagen','Einen nie auftretenden Auslöser wählen'],[0,1],'Vorbereitung reduziert hier konkrete Hindernisse.'),sc('Du erkennst den Auslöser, scheiterst aber an fehlendem Material. Was prüfst du zuerst?','Die Vorbereitung der Handlung','Ob du den Auslöser grundsätzlich nie bemerkst','Ob Ziele immer nutzlos sind','Die Beobachtung zeigt auf ein Hindernis in der Umsetzung.'),sc('Warum ist eine Umgebungsänderung keine Erfolgsgarantie?','Motive, Belastung und andere Bedingungen wirken weiterhin mit','Weil bereitgelegte Gegenstände nie auffindbar sind','Weil ein Plan nur mit perfekter Einrichtung erlaubt ist','Ein praktischer Hebel ist nicht die einzige Einflussgrösse.')],
'Gestalte nicht nur die Erinnerung, sondern auch den Weg von der Erinnerung zur Handlung.','Entferne eine konkrete Hürde vor deinem ersten Schritt und beobachte, ob das hilft.',H),
chapter(HABIT,3,'Es regnet. Der Plan lebt weiter.','Du baust eine begrenzte Ausweichhandlung statt eines Alles-oder-nichts-Plans.',[
 card('scene','Der erste echte Alltagstest','Der Plan sieht einen kurzen Gang vor. Heute regnet es stark und du kommst erschöpft heim. Ein starrer Plan kennt nur die volle Version oder das Scheitern. Ein robusterer Plan kann eine vorab gewählte kleine Alternative enthalten.',image='habit-rain',alt='Bei Regen draussen wird drinnen eine einfache Bewegungsmatte ausgerollt.',caption=FICTION),
 card('dialogue','Zwei Stimmen im Kopf','Stimme A: Wenn ich nicht die volle Runde schaffe, bringt gar nichts etwas.\nStimme B: Heute passt eine kleine Ersatzhandlung, danach prüfe ich den Plan.\n\nDie Ersatzhandlung soll das Ziel noch erkennbar unterstützen. Beliebig alles als Erfolg umzubenennen würde den Plan dagegen bedeutungslos machen.'),
 card('decision','Welche Alternative erhält den Sinn?','Das Ziel des Beispiels ist ein bewusster Übergang nach Hause statt sofortigem Scrollen, nicht eine festgelegte sportliche Leistung.',probe=sc('Welche Ersatzhandlung passt bei diesem Ziel?','Telefon ablegen und zwei Minuten ruhig strecken, sofern angenehm','Sofort den Feed öffnen und die gleiche Handlung anders benennen','Jede notwendige Pause verbieten','Der kleine Übergang erhält den konkreten Zweck, ohne die volle Aussenrunde zu erzwingen.')),
 card('evidence','Ein Ausrutscher ist ein Datenpunkt','Nach einem ausgelassenen Abend kannst du beim nächsten erkennbaren Auslöser wieder einsteigen. Du musst den Verlust nicht durch eine übergrosse Strafe kompensieren. Frage: War die Handlung zu gross, der Auslöser unklar oder die Situation anders?\n\nEine praktikable Anpassung ist etwas anderes als tägliches spontanes Neuverhandeln jedes Plans.')
],[sc('Was soll eine Ersatzhandlung erhalten?','Den erkennbaren Zweck des Plans','Exakt dieselbe Dauer unter allen Umständen','Die Möglichkeit, jede Handlung beliebig als Erfolg zu bezeichnen','Die Anpassung muss zum Ziel passen.'),multi('Welche Fragen helfen nach einem ausgelassenen Abend?',['War der erste Schritt zu gross?','War die Situation anders als erwartet?','Welche möglichst harte Strafe verdiene ich?','Warum beweist ein Abend meinen gesamten Charakter?'],[0,1],'Die Fragen suchen veränderbare Bedingungen statt pauschaler Selbstabwertung.'),recall('Eine vorab gewählte kleinere Alternative nennen wir hier ___.','Ersatzhandlung|Ausweichhandlung|Alternative','Sie hält den Zweck unter veränderten Bedingungen erreichbar.'),sc('Warum ist tägliches beliebiges Umdeuten problematisch?','Dann ist nicht mehr erkennbar, ob der Plan umgesetzt wurde','Weil Anpassung grundsätzlich verboten ist','Weil jedes Ziel die gleiche Handlung verlangt','Kriterien müssen klar genug bleiben, um die Umsetzung zu beurteilen.'),sc('Was ist nach einem einzelnen Auslassen ein vernünftiger nächster Schritt?','Beim nächsten passenden Auslöser wieder beginnen und das Hindernis prüfen','Die gesamte Idee endgültig aufgeben','Die nächste Nacht als Strafe auf Schlaf verzichten','Wiedereinstieg und Anpassung sind konkreter als Alles-oder-nichts-Reaktionen.')],
'Ein tragfähiger Plan hat Spielraum für den Alltag, ohne seinen Zweck zu verlieren.','Lege eine kleine Ersatzhandlung fest und beschreibe, wann sie statt der normalen Version gilt.',H),
chapter(HABIT,4,'Fünf Tage, eine ehrliche Auswertung','Du misst die Umsetzung eines Plans getrennt vom langfristigen Ziel.',[
 card('lab','Zähle die wirklichen Gelegenheiten','Im fiktiven Wochenprotokoll trat der geplante Auslöser an fünf Abenden auf. Dreimal hast du die normale Handlung begonnen, einmal die vorher definierte Ersatzhandlung, einmal den Plan ausgelassen.\n\nNach der vorab festgelegten Regel wurden vier von fünf Gelegenheiten genutzt. Das sind 80 %. Die Zahl belegt noch nicht, dass die gesamte Bildschirmzeit um 80 % fiel.'),
 card('decision','Was misst die Zahl?','Du willst den Versuch ehrlich beschreiben.',probe=sc('Welche Aussage passt zu den Daten?','Der geplante Einstieg gelang bei vier von fünf Gelegenheiten','Die gesamte Bildschirmzeit sank sicher um 80 %','Eine dauerhafte Gewohnheit ist damit garantiert','Die Kennzahl betrifft die Umsetzung, nicht automatisch die langfristige Wirkung.')),
 card('evidence','Ausführung und Wirkung getrennt prüfen','Ein Plan kann zuverlässig ausgeführt werden, aber wenig zum Ziel beitragen. Dann braucht es eine passendere Handlung. Ein sinnvoller Plan kann umgekehrt an einer unrealistischen Ausführung scheitern. Dann braucht es einen einfacheren Einstieg.\n\nUnterscheide deshalb: Habe ich den vorgesehenen Schritt getan? Und half dieser Schritt tatsächlich bei meinem Ziel?'),
 card('transfer','Dein nächster Versuch','Behalte den klaren Auslöser, wenn er funktioniert. Ändere gezielt nur das erkennbare Hindernis. Beobachte nicht nur die Quote, sondern auch den wirklichen Zweck: etwa einen bewussteren Übergang und weniger automatisches Öffnen.\n\nEs gibt hier keine wissenschaftlich garantierte Zahl von Tagen, nach der jeder Mensch eine Gewohnheit besitzen muss.',reveal='Der fertige Plan besteht aus Auslöser, kleiner Handlung, sinnvoller Ersatzhandlung und ehrlicher Auswertung. Das ist ein überprüfbares Experiment, kein Urteil über deinen Wert als Mensch.')
],[number('Vier genutzte von fünf Gelegenheiten: Wie hoch ist die Umsetzungsquote?',80,'%','4 / 5 × 100 = 80 %.'),sc('Warum bedeutet 80 % Umsetzung nicht 80 % weniger Bildschirmzeit?','Es sind unterschiedliche Messgrössen','Weil Prozentrechnung grundsätzlich unbrauchbar ist','Weil die Ersatzhandlung nicht existiert','Die Quote zählt Gelegenheiten, nicht Nutzungsminuten.'),multi('Welche Fragen gehören zur Auswertung?',['Wurde die Handlung ausgeführt?','Hat sie zum Ziel beigetragen?','Welche Quote sieht öffentlich am besten aus?','Wie ignoriere ich ausgelassene Gelegenheiten?'],[0,1],'Ausführung und Wirkung sind getrennt zu prüfen.'),sc('Der Schritt gelingt, aber hilft dem Ziel kaum. Was prüfst du?','Ob eine andere konkrete Handlung besser zum Ziel passt','Ob du die guten Daten als Erfolgsgarantie ausgibst','Ob du die gesamte Auswertung weglässt','Zuverlässige Ausführung ist kein Beweis für die passende Wirkung.'),order('Ordne die Entwicklung des Plans.',['Situation und Handlung festlegen','Umsetzung im Alltag beobachten','Ausführung und Wirkung unterscheiden','Gezielt anpassen'],'Die Rückmeldung verbessert den nächsten Versuch.')],
'Miss, ob der Plan ausgeführt wird – und getrennt davon, ob er wirklich hilft.','Notiere bei den nächsten passenden Gelegenheiten Umsetzung und Hindernis, ohne zusätzliche Selbstbestrafung.',H),
chapter(DEAL,1,'Hinter «zu teuer»','Du unterscheidest eine ausgesprochene Position vom dahinterliegenden Interesse.',[
 card('scene','Das Angebot liegt zwischen euch','Fiktiver Dialog: Eine Kundin sieht dein Projektangebot und sagt: Das muss günstiger werden. Du könntest sofort Rabatt geben. Dann hättest du aber noch nicht verstanden, ob das Problem der Gesamtpreis, der Zeitpunkt der Zahlung oder der Nutzen des Umfangs ist.',image='negotiation-table',alt='Zwei Geschäftspartner prüfen an einem kleinen Tisch unterschiedliche Projektunterlagen.',caption=FICTION),
 card('dialogue','Eine Forderung, mehrere mögliche Gründe','Die Position ist die ausgesprochene Forderung: niedrigerer Preis. Das Interesse ist das dahinterliegende Anliegen: beispielsweise ein begrenztes Budget oder geringeres Einführungsrisiko.\n\nInteressen sind zunächst Hypothesen. Du kennst sie nicht, nur weil du eine geschickte Vermutung formulierst. Frage offen und prüfe, ob die andere Seite sich korrekt verstanden fühlt.'),
 card('decision','Die erste Frage','Du willst genauer verstehen, ohne der Kundin bereits eine Antwort in den Mund zu legen.',probe=sc('Welche Frage öffnet die relevante Information?','Was genau passt am Angebot noch nicht zu Ihrer Situation?','Sie wollen also einfach die gleiche Leistung billiger, richtig?','Ist Ihnen Qualität grundsätzlich egal?','Die offene Frage lässt unterschiedliche Ursachen zu und greift die Person nicht an.')),
 card('evidence','Verstehen ist noch kein Nachgeben','Eine Nachfrage verpflichtet dich nicht zu einem Rabatt. Sie liefert Informationen für eine bessere Entscheidung. Erst wenn klarer ist, worüber verhandelt wird, kannst du Umfang, Preis, Termine oder Zahlungsablauf sinnvoll beurteilen.\n\nGute Kommunikation macht den Konflikt genauer; sie zaubert ihn nicht automatisch weg.')
],[recall('Die ausgesprochene Forderung nennen wir in der Verhandlung eine ___.','Position','Die Position ist von ihrem möglichen Hintergrund zu unterscheiden.',True),recall('Das dahinterliegende Anliegen nennen wir ein ___.','Interesse|Bedürfnis','Interessen müssen durch Gespräch geklärt werden.',True),sc('Warum ist sofortiger Rabatt möglicherweise voreilig?','Der eigentliche Hinderungsgrund ist noch nicht geklärt','Jeder Rabatt ist grundsätzlich unzulässig','Preis spielt in Verhandlungen nie eine Rolle','Vielleicht betrifft der Konflikt Umfang oder Zeitpunkt statt nur die Höhe.'),multi('Welche Gründe könnten hinter «zu teuer» stehen?',['Begrenztes Budget','Unsicherheit über den Nutzen','Zwingend mangelnder Respekt','Zwingend Ablehnung jeder Zusammenarbeit'],[0,1],'Mögliche Interessen sind Hypothesen, keine bewiesenen Motive.'),sc('Bedeutet eine offene Rückfrage bereits Zustimmung zur Forderung?','Nein, sie dient zunächst dem Verständnis','Ja, sie ist automatisch ein Rabatt','Ja, sie gibt jedes eigene Interesse auf','Information sammeln und zustimmen sind verschiedene Handlungen.')],
'Erst verstehen, worüber ihr wirklich uneinig seid; dann über Lösungen sprechen.','Übersetze bei einer Forderung getrennt: ausgesprochene Position und mögliche Interessen.',D),
chapter(DEAL,2,'Zwei Pakete statt eines Rabatts','Du nutzt unterschiedliche Prioritäten, um konkrete Angebotsvarianten zu prüfen.',[
 card('scene','Jetzt werden die Karten neu gelegt','Die Kundin erklärt: Das Team braucht zuerst einen einfachen Einstieg. Die grosse Ausbaustufe kann warten. Dir ist wichtig, dass zusätzlicher Aufwand bezahlt und der Start planbar bleibt.\n\nDer Konflikt enthält nun mehr als eine einzige Preiszahl.',image='negotiation-options',alt='Zwei Personen ordnen unbeschriftete Projektkarten auf einem Tisch neu.',caption=FICTION),
 card('lab','Formuliere vergleichbare Pakete','Erfundenes Beispiel: Paket A umfasst Einführung und Ausbau für 4’000 CHF. Paket B umfasst nur eine klar abgegrenzte Einführung für 2’500 CHF; ein späterer Ausbau wird separat vereinbart.\n\nB ist nicht dieselbe Leistung mit neuem Etikett. Umfang und offene spätere Kosten müssen transparent sein. Sonst verlagert ihr den Streit nur in die Zukunft.'),
 card('decision','Welche Variante nutzt die neue Information?','Das akute Interesse ist ein kleinerer, beherrschbarer Einstieg.',probe=sc('Welcher Vorschlag passt dazu?','Eine klar abgegrenzte erste Etappe mit eigenem Preis','Unverändert alles liefern und die fehlende Marge verschweigen','Den Ausbau stillschweigend weglassen, aber das Paket gleich benennen','Die erste Variante verändert Umfang und Preis nachvollziehbar.')),
 card('evidence','Wert schaffen und Wert verteilen','Wenn verschiedene Prioritäten sichtbar werden, lassen sich manchmal bessere Kombinationen finden. Das ist der integrative Teil einer Verhandlung. Wer welchen Anteil des Vorteils erhält, bleibt eine Verteilungsfrage.\n\nNicht jeder Konflikt bietet eine perfekte Lösung für beide. Neue Optionen sind prüfbare Vorschläge, keine Garantie auf Einigung.')
],[number('Wie gross ist der Preisunterschied zwischen 4’000 und 2’500 CHF?',1500,'CHF','4’000 − 2’500 = 1’500 CHF, bei ausdrücklich unterschiedlichem Umfang.'),sc('Warum ist Paket B kein reiner Rabatt?','Es enthält einen kleineren vereinbarten Umfang','Es enthält zwingend genau dieselbe Leistung','Der Preis ist deshalb irrelevant','Der Leistungsumfang wurde verändert.'),multi('Welche Angaben müssen bei Varianten klar sein?',['Enthaltener Umfang','Was später separat vereinbart werden muss','Nur die günstigere Endzahl','Unbemerkte Weglassungen'],[0,1],'Transparenz verhindert, dass scheinbare Einigung auf verschiedenen Erwartungen beruht.'),recall('Die Suche nach Kombinationen, die Interessen beider Seiten besser erfüllen, heisst hier ___ Verhandeln.','integratives|integrativ','Integratives Verhandeln sucht zusätzliche oder besser passende Lösungsmöglichkeiten.',True),sc('Was bleibt auch nach einer guten neuen Option offen?','Ob beide zustimmen und wie Vorteile verteilt werden','Ob Worte überhaupt eine Bedeutung haben','Ob das vereinbarte Paket irgendeinen Umfang hat','Wert schaffen ist nicht dasselbe wie jede Verteilungsfrage lösen.')],
'Eine bessere Kombination kann mehr helfen als dieselbe Leistung einfach billiger anzubieten.','Formuliere zwei transparente Varianten, die sich in einem für beide Seiten relevanten Punkt unterscheiden.',D),
chapter(DEAL,3,'Dein Nein braucht eine Grundlage','Du prüfst eine Alternative zur Einigung und eine begründete Grenze.',[
 card('lab','Die Alternative ausserhalb des Gesprächs','Bevor du zusagst, frage: Was kann ich realistisch tun, wenn diese Einigung nicht zustande kommt? Ein anderer Auftrag, ein späterer Termin oder kein Projekt können unterschiedlich gute Alternativen sein.\n\nEine echte Alternative ist etwas anderes als eine erfundene Drohung. Sie muss praktisch erreichbar und mit Kosten sowie Risiken bewertet sein.'),
 card('evidence','Nicht jede Unterschrift ist ein Gewinn','Im vereinfachten Beispiel würdest du für eine Etappe 2’200 CHF erhalten, aber 2’400 CHF zusätzliche Kosten verursachen. Andere Vorteile seien nicht vorhanden. Dann verschlechtert dieser Abschluss das Ergebnis um 200 CHF.\n\nZeit, Liquidität, Risiken und andere Verpflichtungen gehören in echten Fällen ebenfalls zur Prüfung. Der Wunsch nach einer Zusage allein ist kein guter Massstab.'),
 card('decision','Du sollst unter deiner Grenze zustimmen','Die Kundin hält am beschriebenen Preis von 2’200 fest, der Aufwand lässt sich nicht senken und es gibt im Modell keine weiteren Vorteile.',probe=sc('Welche Reaktion ist unter diesen Annahmen begründet?','Den Umfang nochmals prüfen oder diesen Abschluss ablehnen','Zustimmen, weil jeder Umsatz automatisch Gewinn ist','Eine nicht vorhandene Alternative erfinden','Die Kosten übersteigen den Erlös. Ein Nein kann sachlich richtig sein.')),
 card('reveal','Ein Nein ohne Angriff','Formuliere eine kurze Grenze, die die Sache erklärt und die andere Person respektiert.',reveal='Zum Beispiel: Für diesen Umfang kann ich zu diesem Preis nicht verlässlich liefern. Wir können die Etappe verkleinern oder es bei diesem Stand belassen. Die Grenze beschreibt die eigene Tragfähigkeit, nicht den angeblichen Charakter der Kundin.')
],[number('Welches zusätzliche Ergebnis entsteht bei 2’200 Erlös und 2’400 zusätzlichen Kosten? Gib den Verlust als positiven Betrag an.',200,'CHF Verlust','2’400 − 2’200 = 200 CHF Verlust im vereinfachten Modell.'),sc('Was kennzeichnet eine brauchbare Alternative zur Einigung?','Sie ist realistisch erreichbar und mit ihren Kosten geprüft','Sie muss nur überzeugend erfunden sein','Sie ist automatisch besser als jedes Angebot','Eine Alternative dient als reale Vergleichsgrundlage.'),multi('Was sollte eine begründete Grenze berücksichtigen?',['Aufwand und Kosten','Risiken und Verpflichtungen','Nur den Wunsch, eine Zusage zu hören','Eine beliebige Drohung'],[0,1],'Die Grenze soll zur eigenen Tragfähigkeit passen.'),sc('Warum ist jeder Umsatz nicht automatisch vorteilhaft?','Die damit verbundenen zusätzlichen Kosten können höher sein','Umsatz wird grundsätzlich nie bezahlt','Ein Auftrag kann keine Kosten haben','Erlös und Ergebnis sind nicht identisch.'),sc('Welche Formulierung setzt eine sachliche Grenze?','Zu diesem Preis kann ich diesen Umfang nicht verlässlich liefern','Sie sind grundsätzlich kein vernünftiger Kunde','Ich habe garantiert zehn bessere Angebote, obwohl das nicht stimmt','Eine sachliche Grenze braucht keine Abwertung oder erfundene Drohung.')],
'Eine Einigung ist nur dann ein guter Abschluss, wenn sie gegenüber realistischen Alternativen tragfähig ist.','Benenne vor einer Verhandlung eine echte Alternative und eine sachlich begründete Grenze.',D),
chapter(DEAL,4,'Einverstanden – womit genau?','Du machst eine Einigung konkret und unterscheidest Verständnisprüfung von Druck.',[
 card('dialogue','Das freundliche Ja ist noch ungenau','Ihr einigt euch auf einen kleineren Einstieg. Du denkst an eine Einführung ohne Ausbau. Die Kundin denkt an den ganzen ursprünglichen Umfang, nur später geliefert. Beide sagen Ja – zu unterschiedlichen Vorstellungen.\n\nJetzt hilft keine Siegerpose, sondern eine klare Zusammenfassung.'),
 card('lab','Fünf Punkte in einfachen Worten','Fasse zusammen: Was wird geliefert? Was nicht? Bis wann? Zu welchem Preis und Zahlungsablauf? Wer prüft welche offene Frage?\n\nDas ist eine Kommunikationshilfe, keine vollständige Vertragsvorlage. Je nach Geschäft können weitere rechtliche und fachliche Anforderungen nötig sein. Die Methode verhindert vor allem, dass unterschiedliche Erwartungen unbemerkt bleiben.'),
 card('decision','Die letzte Rückfrage','Du möchtest prüfen, ob die Vereinbarung wirklich gleich verstanden wird.',probe=sc('Welche Frage dient diesem Zweck?','Was haben Sie als enthaltenen Umfang verstanden, und fehlt Ihnen noch etwas?','Sie stimmen doch jetzt endlich allem zu, oder?','Darf ich offene Punkte einfach weglassen?','Die erste Frage erlaubt eine Korrektur, statt Zustimmung zu erzwingen.')),
 card('transfer','Der ganze Fall in einem Ablauf','Du hast hinter einer Preisforderung ein Interesse gesucht, Varianten entwickelt, eine eigene Grenze geprüft und die Einigung präzisiert. Jede Phase kann zu einem begründeten Nein führen.\n\nEine gute Verhandlung besteht nicht darin, jedes Gespräch abzuschliessen. Sie schafft möglichst klare, tragfähige Entscheidungen – auch wenn keine Einigung zustande kommt.',reveal='Der nächste praktische Schritt: Wiederhole die Vereinbarung so konkret, dass die andere Seite einen Unterschied bemerken und korrigieren könnte. Verständnis ist überprüfbar; ein freundlicher Ton allein ist noch kein Beleg.')
],[multi('Welche Punkte helfen, den beschriebenen Abschluss zu klären?',['Enthaltener und ausgeschlossener Umfang','Termin, Preis und Zahlungsablauf','Nur die Stimmung im Raum','Nur die Zahl freundlicher Zustimmungen'],[0,1],'Die Beteiligten müssen dieselbe konkrete Leistung meinen.'),sc('Warum können zwei freundliche Ja trotzdem problematisch sein?','Sie können sich auf unterschiedliche Erwartungen beziehen','Freundlichkeit macht jede Einigung unwirksam','Eine mündliche Aussage kann nie verständlich sein','Zustimmung setzt gemeinsames Verständnis voraus.'),order('Ordne den Lernfall.',['Interessen hinter der Forderung klären','Transparente Varianten prüfen','Eigene Tragfähigkeit und Alternative prüfen','Vereinbarung konkret zusammenfassen'],'Die Schritte unterstützen eine fundierte Entscheidung.'),sc('Welche Rückfrage prüft Verständnis ohne unnötigen Druck?','Welchen Umfang haben Sie als enthalten verstanden?','Sie müssen jetzt einfach zustimmen, richtig?','Kann ich die offenen Punkte ignorieren?','Eine offene Korrekturmöglichkeit macht Unterschiede sichtbar.'),sc('Ist die Fünf-Punkte-Hilfe eine vollständige Rechtsberatung?','Nein, eine Kommunikationshilfe mit möglichen weiteren Anforderungen','Ja, sie ersetzt jeden fachlichen oder rechtlichen Prüfbedarf','Ja, wenn das Gespräch freundlich war','Die Reichweite der Hilfe bleibt ausdrücklich begrenzt.')],
'Ein Abschluss ist erst verständlich, wenn beide dieselbe Vereinbarung meinen.','Fasse eine nächste Abmachung mit Umfang, Grenze, Zeitpunkt und offenen Punkten zusammen.',D)
]
